#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: descriptive_statistics_nulliparous_tp2
# Date: 2025.08.20
# Programmer: Barbara Nowak
# Purpose: Test if differences in descriptive statistics between Fp and Sp are significant at tp2
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [3]:
# Read file
fp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp2_nulliparous/2025-08-18_fp_tp2_filt.csv", header = TRUE)
sp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp2_nulliparous/2025-08-18_sp_tp2_filt.csv", header = TRUE)
combined_fp_sp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp2_nulliparous/2025-08-18_combined_fp_sp_tp2.csv", header = TRUE)

In [4]:
head(fp_tp2)
dim(fp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5301 S1f862a6     NA         0        0         0
4 5285 S3c0f6ee     NA         0        0         0
5 5275 S2b86cc0     NA         0        0         0
6 5243 S39fe1d7     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2019-05-23 P1a267fa        0                   32          ⋯ 0
3 2018-03-07 P1f862a6        0                   32          ⋯ 0
4 2019-03-25 P3c0f6ee        0                   31          ⋯ 0
5 2019-05-29 P3cac7b0        0                   31          ⋯ 0
6 2018-06-23 P3db7da6        0                   29          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     31
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  24 566

In [5]:
head(sp_tp2)
dim(sp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5332 Sb124b17     NA         0        0         2
3 5305 Sa79a719     NA         0        0         1
4 5310 S5097402     NA         0        0         1
5 5311 S3cac7b0     NA         0        0         0
6 5252 S3db7da6     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯ 0
2 2021-01-06 P1a267fa        0                   34          ⋯ 0
3 2019-01-17 P1f862a6        0                   32          ⋯ 0
4 2020-10-18 P3c0f6ee        0                   33          ⋯ 0
5 2020-10-20 P3cac7b0        0                   33          ⋯ 0
6 2019-09-24 P3db7da6        0                   30          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  24 566

In [6]:
head(combined_fp_sp_tp2)
dim(combined_fp_sp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5301 S1f862a6     NA         0        0         0
4 5285 S3c0f6ee     NA         0        0         0
5 5275 S2b86cc0     NA         0        0         0
6 5243 S39fe1d7     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-11-16 P159f9c8        0                   36          ⋯
2 2019-05-23 P1a267fa        0                   32          ⋯
3 2018-03-07 P1f862a6        0                   32          ⋯
4 2019-03-25 P3c0f6ee        0                   31          ⋯
5 2019-05-29 P3cac7b0        0                   31          ⋯
6 2018-06-23 P3db7da6        0                   29          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     31
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

[1]  48 567

# Categorical, Nominal data===============================================================================

## Diabetes----------------------------------------------------------------------

In [7]:
class(combined_fp_sp_tp2$Q2_X13.1.Pregproblem_gestational_diabetes)

[1] "character"

In [8]:
# Convert from char to fct
diabetes_category_fp <- ifelse(fp_tp2$Q2_X13.1.Pregproblem_gestational_diabetes == "Nej", 0, 
                            ifelse(fp_tp2$Q2_X13.1.Pregproblem_gestational_diabetes == "Ja", 1, NA))
diabetes_category_fp

diabetes_category_sp <- ifelse(sp_tp2$Q2_X13.1.Pregproblem_gestational_diabetes == "Nej", 0, 
                            ifelse(sp_tp2$Q2_X13.1.Pregproblem_gestational_diabetes == "Ja", 1, NA))
diabetes_category_sp

 [1]  0 NA NA  1  0 NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA  0  0 NA NA

 [1] NA NA NA  1 NA NA NA NA NA NA  0 NA  0 NA NA NA NA NA NA NA NA NA NA NA

In [9]:
# Add diabetes category column as factors
fp_tp2$Q2_Diabetes_category <- as.factor(diabetes_category_fp)
class(fp_tp2$Q2_Diabetes_category)

sp_tp2$Q2_Diabetes_category <- as.factor(diabetes_category_sp)
class(sp_tp2$Q2_Diabetes_category)

[1] "factor"

[1] "factor"

In [10]:
# Select variables of interest
fp_diabetes <- fp_tp2 |>
  select(Q1_Personnummer, Q2_Diabetes_category)
fp_diabetes

sp_diabetes <- sp_tp2 |>
  select(Q1_Personnummer, Q2_Diabetes_category)
sp_diabetes

   Q1_Personnummer Q2_Diabetes_category
1  P159f9c8        0
2  P1a267fa        NA
3  P1f862a6        NA
4  P3c0f6ee        1
5  P3cac7b0        0
6  P3db7da6        NA
7  P424fd61        NA
8  P4a05456        NA
9  P4de45e7        NA
10 P50f102c        NA
11 P5b98b6c        NA
12 P62ea0b2        NA
13 P719b21e        NA
14 P7ece52e        NA
15 P92b4604        NA
16 P97574f9        NA
17 P9cdfd5a        NA
18 Pa8f3b51        NA
19 Pbe289c8        NA
20 Pc44e366        NA
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        NA
24 Pe706703        NA

   Q1_Personnummer Q2_Diabetes_category
1  P159f9c8        NA
2  P1a267fa        NA
3  P1f862a6        NA
4  P3c0f6ee        1
5  P3cac7b0        NA
6  P3db7da6        NA
7  P424fd61        NA
8  P4a05456        NA
9  P4de45e7        NA
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        NA
13 P719b21e        0
14 P7ece52e        NA
15 P92b4604        NA
16 P97574f9        NA
17 P9cdfd5a        NA
18 Pa8f3b51        NA
19 Pbe289c8        NA
20 Pc44e366        NA
21 Pc77a35c        NA
22 Pcd2c0d1        NA
23 Pdab1897        NA
24 Pe706703        NA

In [11]:
combined_df_diabetes <-  merge(fp_diabetes, sp_diabetes, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
dim(combined_df_diabetes)

[1] 24  3

In [12]:
# Pull personal# where NA for EITHER pregnancy but NOT na for the other pregnancy
# This way get separate lists for fp and sp personal#
# NA ONLY for fp
missing_pn_diabetes_fp <- combined_df_diabetes |> filter(is.na(combined_df_diabetes$Q2_Diabetes_category_FP) & !is.na(combined_df_diabetes$Q2_Diabetes_category_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_diabetes_fp

[1] "P5b98b6c" "P719b21e"

In [13]:
# NA ONLY for sp
missing_pn_diabetes_sp <- combined_df_diabetes |> filter(is.na(combined_df_diabetes$Q2_Diabetes_category_SP) & !is.na(combined_df_diabetes$Q2_Diabetes_category_FP)) |> 
  pull(Q1_Personnummer)
missing_pn_diabetes_sp

[1] "P159f9c8" "P3cac7b0" "Pc77a35c" "Pcd2c0d1"

In [14]:
# Pull personal# where NA for BOTH fp AND sp
missing_pn_diabetes_both <- combined_df_diabetes |> filter(is.na(combined_df_diabetes$Q2_Diabetes_category_FP) & is.na(combined_df_diabetes$Q2_Diabetes_category_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_diabetes_both
length(missing_pn_diabetes_both)

 [1] "P1a267fa" "P1f862a6" "P3db7da6" "P424fd61" "P4a05456" "P4de45e7"
 [7] "P50f102c" "P62ea0b2" "P7ece52e" "P92b4604" "P97574f9" "P9cdfd5a"
[13] "Pa8f3b51" "Pbe289c8" "Pc44e366" "Pdab1897" "Pe706703"

[1] 17

## Depression--------------------------------------------------------------------

In [15]:
class(combined_fp_sp_tp2$Depression_score_sum_Q2)
sum(is.na(combined_fp_sp_tp2$Depression_score_sum_Q2))

[1] "integer"

[1] 9

In [16]:
# Convert to factors based on categories
depression_category_fp <- ifelse(fp_tp2$Depression_score_sum_Q2 >= 0 & fp_tp2$Depression_score_sum_Q2 < 13,  0, 
                              ifelse(fp_tp2$Depression_score_sum_Q2 >= 13 & fp_tp2$Depression_score_sum_Q2 <= 30, 1, NA))
depression_category_fp
sum(is.na(depression_category_fp))

depression_category_sp <- ifelse(sp_tp2$Depression_score_sum_Q2 >= 0 & sp_tp2$Depression_score_sum_Q2 < 13,  0, 
                                 ifelse(sp_tp2$Depression_score_sum_Q2 >= 13 & sp_tp2$Depression_score_sum_Q2 <= 30, 1, NA))
depression_category_sp
sum(is.na(depression_category_sp))

 [1]  0 NA  0  1  0  0  0  0  0 NA  0  0  0  1 NA  0 NA  0  0  0  0  0  0  0

[1] 4

 [1]  0  0  1 NA  0  1  0  0  0 NA  0  0  0  0 NA  0 NA  0  0  0  1 NA  0  0

[1] 5

In [17]:
# Add depression category column as factors
fp_tp2$Q2_Depression_category <- as.factor(depression_category_fp)
class(fp_tp2$Q2_Depression_category)

sp_tp2$Q2_Depression_category <- as.factor(depression_category_sp)
class(sp_tp2$Q2_Depression_category)

[1] "factor"

[1] "factor"

In [18]:
# Select variables of interest
fp_depression <- fp_tp2 |>
  select(Q1_Personnummer, Q2_Depression_category)
fp_depression

sp_depression <- sp_tp2 |>
  select(Q1_Personnummer, Q2_Depression_category)
sp_depression

   Q1_Personnummer Q2_Depression_category
1  P159f9c8        0
2  P1a267fa        NA
3  P1f862a6        0
4  P3c0f6ee        1
5  P3cac7b0        0
6  P3db7da6        0
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        1
15 P92b4604        NA
16 P97574f9        0
17 P9cdfd5a        NA
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        0
24 Pe706703        0

   Q1_Personnummer Q2_Depression_category
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        1
4  P3c0f6ee        NA
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        NA
16 P97574f9        0
17 P9cdfd5a        NA
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        1
22 Pcd2c0d1        NA
23 Pdab1897        0
24 Pe706703        0

In [19]:
# Combine both df so each personal# has two values
combined_df_depression <- merge(fp_depression, sp_depression, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_depression

   Q1_Personnummer Q2_Depression_category_FP Q2_Depression_category_SP
1  P159f9c8        0                         0
2  P1a267fa        NA                        0
3  P1f862a6        0                         1
4  P3c0f6ee        1                         NA
5  P3cac7b0        0                         0
6  P3db7da6        0                         1
7  P424fd61        0                         0
8  P4a05456        0                         0
9  P4de45e7        0                         0
10 P50f102c        NA                        NA
11 P5b98b6c        0                         0
12 P62ea0b2        0                         0
13 P719b21e        0                         0
14 P7ece52e        1                         0
15 P92b4604        NA                        NA
16 P97574f9        0                         0
17 P9cdfd5a        NA                        NA
18 Pa8f3b51        0                         0
19 Pbe289c8        0                         0
20 Pc44e366        0                         0
21 Pc77a35c        0                         1
22 Pcd2c0d1        0                         NA
23 Pdab1897        0                         0
24 Pe706703        0                         0

In [20]:
# NA ONLY for fp
missing_pn_depression_fp <- combined_df_depression|> filter(is.na(combined_df_depression$Q2_Depression_category_FP) & !is.na(combined_df_depression$Q2_Depression_category_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_depression_fp

[1] "P1a267fa"

In [21]:
# NA ONLY for sp
missing_pn_depression_sp <- combined_df_depression |> filter(is.na(combined_df_depression$Q2_Depression_category_SP) & !is.na(combined_df_depression$Q2_Depression_category_FP)) |> 
  pull(Q1_Personnummer)
missing_pn_depression_sp

[1] "P3c0f6ee" "Pcd2c0d1"

In [22]:
# Pull personal# where NA for BOTH fp AND sp
missing_pn_depression_both  <- combined_df_depression |> filter(is.na(combined_df_depression$Q2_Depression_category_FP) & is.na(combined_df_depression$Q2_Depression_category_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_depression_both
length(missing_pn_depression_both)

[1] "P50f102c" "P92b4604" "P9cdfd5a"

[1] 3

In [23]:
# P-value
# Make sure stress_FP and stress_SP are numeric (NOT factors)
combined_df_depression$Q2_Depression_category_FP <- as.numeric(as.character(combined_df_depression$Q2_Depression_category_FP))
combined_df_depression$Q2_Depression_category_SP <- as.numeric(as.character(combined_df_depression$Q2_Depression_category_SP))

In [24]:
# 2. Split into groups
m2 <- combined_df_depression[!is.na(combined_df_depression$Q2_Depression_category_FP) & !is.na(combined_df_depression$Q2_Depression_category_SP), ] # complete
m1 <- combined_df_depression[!is.na(combined_df_depression$Q2_Depression_category_FP) & is.na(combined_df_depression$Q2_Depression_category_SP), ]  # only FP 
m3 <- combined_df_depression[is.na(combined_df_depression$Q2_Depression_category_FP) & !is.na(combined_df_depression$Q2_Depression_category_SP), ]  # only SP

In [25]:
# 3. Sizes
n_total <- nrow(combined_df_depression)
m1_n <- nrow(m1)
m2_n <- nrow(m2)
m3_n <- nrow(m3)

Pms <- m1_n / n_total # missing depression SP
Pmt <- m3_n / n_total # missing depression SP

In [26]:
# 4. Paired estimator Δ̂(P)
delta_paired <- mean(m2$Q2_Depression_category_SP - m2$Q2_Depression_category_FP, na.rm = TRUE)

In [27]:
# 5. Unpaired estimator Δ̂(U)
P_s <- mean(m1$Q2_Depression_category_FP, na.rm = TRUE) # from m1
P_t <- mean(m3$Q2_Depression_category_SP, na.rm = TRUE) # from m3
delta_unpaired <- P_t - P_s

In [28]:
# 6. Calculate components for V_P
P01 <- sum(m2$Q2_Depression_category_FP == 0 & m2$Q2_Depression_category_SP == 1) / m2_n
P10 <- sum(m2$Q2_Depression_category_FP == 1 & m2$Q2_Depression_category_SP == 0) / m2_n

VP <- (P01 + P10 - (P01 - P10)^2) / (1 - Pms - Pmt)

In [29]:
# 7. Calculate VU
VU <- (P_s * (1 - P_s)) / Pms + (P_t * (1 - P_t)) / Pmt

In [30]:
# 8. Weight w and hybrid estimator
w <- VU / (VU + VP)
delta_D <- w * delta_unpaired + (1 - w) * delta_paired

In [31]:
# 9. Combined variance and SE
var_D <- (VU * VP) / (VU + VP)
se_D <- sqrt(var_D)

In [32]:
# 10. Z-test
z_value <- delta_D / se_D
p_value <- 2 * (1 - pnorm(abs(z_value)))
print(p_value)

[1] 0.3345707

## Stress------------------------------------------------------------------------

In [33]:
table(combined_fp_sp_tp2$stress_sum_score_Q2)

 0  1  2  3  4  5  6  7  8  9 11 13
 8  3  3  4  8  8  8  1  2  1  1  1

In [34]:
# There was no high stress column for Q2
# Convert stress score to categories
high_stress_Q2_fp <- ifelse(fp_tp2$stress_sum_score_Q2 >= 7, 1, ifelse(fp_tp2$stress_sum_score_Q2 < 7 , 0, NA))
table(high_stress_Q2_fp)
length(fp_tp2$stress_sum_score_Q2)

high_stress_Q2_sp <- ifelse(sp_tp2$stress_sum_score_Q2 >= 7, 1, ifelse(sp_tp2$stress_sum_score_Q2 < 7 , 0, NA))
table(high_stress_Q2_sp)
length(sp_tp2$stress_sum_score_Q2)

high_stress_Q2_fp
 0  1
22  2

[1] 24

high_stress_Q2_sp
 0  1
20  4

[1] 24

In [35]:
# Create new column with yes/no for high stress
fp_tp2$high_stress_Q2_fp <- high_stress_Q2_fp
table(fp_tp2$high_stress_Q2_fp)

sp_tp2$high_stress_Q2_sp <- high_stress_Q2_sp
table(sp_tp2$high_stress_Q2_sp)

 0  1
22  2

 0  1
20  4

In [36]:
# Select variables 
fp_stress <- fp_tp2 |>
  select(Q1_Personnummer, high_stress_Q2_fp)
fp_stress

sp_stress <- sp_tp2 |>
  select(Q1_Personnummer, high_stress_Q2_sp)
sp_stress

   Q1_Personnummer high_stress_Q2_fp
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        0
4  P3c0f6ee        0
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        1
16 P97574f9        0
17 P9cdfd5a        0
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        0
24 Pe706703        0

   Q1_Personnummer high_stress_Q2_sp
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        0
4  P3c0f6ee        0
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        0
8  P4a05456        1
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        0
16 P97574f9        0
17 P9cdfd5a        1
18 Pa8f3b51        0
19 Pbe289c8        1
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        0
24 Pe706703        0

In [37]:
combined_df_stress <- merge(fp_stress, sp_stress, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_stress

   Q1_Personnummer high_stress_Q2_fp high_stress_Q2_sp
1  P159f9c8        0                 0
2  P1a267fa        0                 0
3  P1f862a6        0                 0
4  P3c0f6ee        0                 0
5  P3cac7b0        0                 0
6  P3db7da6        1                 1
7  P424fd61        0                 0
8  P4a05456        0                 1
9  P4de45e7        0                 0
10 P50f102c        0                 0
11 P5b98b6c        0                 0
12 P62ea0b2        0                 0
13 P719b21e        0                 0
14 P7ece52e        0                 0
15 P92b4604        1                 0
16 P97574f9        0                 0
17 P9cdfd5a        0                 1
18 Pa8f3b51        0                 0
19 Pbe289c8        0                 1
20 Pc44e366        0                 0
21 Pc77a35c        0                 0
22 Pcd2c0d1        0                 0
23 Pdab1897        0                 0
24 Pe706703        0                 0

In [38]:
tab_stress <- table(combined_df_stress$high_stress_Q2_fp, combined_df_stress$high_stress_Q2_sp)
tab_stress

     0  1
  0 19  3
  1  1  1

In [39]:
mcnemar.test(tab_stress)

	McNemar's Chi-squared test with continuity correction

data:  tab_stress
McNemar's chi-squared = 0.25, df = 1, p-value = 0.6171

## Smoking-----------------------------------------------------------------------

In [40]:
combined_fp_sp_tp2$Q2_X25_Smoking_snus_now

 [1] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" NA    "Nej" "Nej"
[13] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej"
[25] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" NA    "Nej" "Nej"
[37] "Nej" "Nej" NA    "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" NA    "Nej" "Nej"

In [41]:
# Convert to categories 
smoking_category_fp <- ifelse(fp_tp2$Q2_X25_Smoking_snus_now == "Nej", 0, 
                           ifelse(fp_tp2$Q2_X25_Smoking_snus_now == "Ja", 1, NA))
table(smoking_category_fp)

smoking_category_sp <- ifelse(sp_tp2$Q2_X25_Smoking_snus_now == "Nej", 0, 
                              ifelse(sp_tp2$Q2_X25_Smoking_snus_now == "Ja", 1, NA))
table(smoking_category_sp)

smoking_category_fp
 0
23

smoking_category_sp
 0
21

In [42]:
# Check for NA
sum(is.na(smoking_category_fp))
sum(is.na(smoking_category_sp))

[1] 1

[1] 3

In [43]:
fp_tp2$smoking_category_Q2 <- smoking_category_fp
fp_tp2$smoking_category_Q2

sp_tp2$smoking_category_Q2 <- smoking_category_sp
sp_tp2$smoking_category_Q2

 [1]  0  0  0  0  0  0  0  0  0 NA  0  0  0  0  0  0  0  0  0  0  0  0  0  0

 [1]  0  0  0  0  0  0  0  0  0 NA  0  0  0  0 NA  0  0  0  0  0  0 NA  0  0

In [44]:
fp_smoking <- fp_tp2 |>
  select(Q1_Personnummer, smoking_category_Q2)
fp_smoking

sp_smoking <-  sp_tp2 |>
  select(Q1_Personnummer, smoking_category_Q2)
sp_smoking

   Q1_Personnummer smoking_category_Q2
1  P159f9c8         0
2  P1a267fa         0
3  P1f862a6         0
4  P3c0f6ee         0
5  P3cac7b0         0
6  P3db7da6         0
7  P424fd61         0
8  P4a05456         0
9  P4de45e7         0
10 P50f102c        NA
11 P5b98b6c         0
12 P62ea0b2         0
13 P719b21e         0
14 P7ece52e         0
15 P92b4604         0
16 P97574f9         0
17 P9cdfd5a         0
18 Pa8f3b51         0
19 Pbe289c8         0
20 Pc44e366         0
21 Pc77a35c         0
22 Pcd2c0d1         0
23 Pdab1897         0
24 Pe706703         0

   Q1_Personnummer smoking_category_Q2
1  P159f9c8         0
2  P1a267fa         0
3  P1f862a6         0
4  P3c0f6ee         0
5  P3cac7b0         0
6  P3db7da6         0
7  P424fd61         0
8  P4a05456         0
9  P4de45e7         0
10 P50f102c        NA
11 P5b98b6c         0
12 P62ea0b2         0
13 P719b21e         0
14 P7ece52e         0
15 P92b4604        NA
16 P97574f9         0
17 P9cdfd5a         0
18 Pa8f3b51         0
19 Pbe289c8         0
20 Pc44e366         0
21 Pc77a35c         0
22 Pcd2c0d1        NA
23 Pdab1897         0
24 Pe706703         0

In [45]:
combined_df_smoking <- merge(fp_smoking, sp_smoking, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_smoking

   Q1_Personnummer smoking_category_Q2_FP smoking_category_Q2_SP
1  P159f9c8         0                      0
2  P1a267fa         0                      0
3  P1f862a6         0                      0
4  P3c0f6ee         0                      0
5  P3cac7b0         0                      0
6  P3db7da6         0                      0
7  P424fd61         0                      0
8  P4a05456         0                      0
9  P4de45e7         0                      0
10 P50f102c        NA                     NA
11 P5b98b6c         0                      0
12 P62ea0b2         0                      0
13 P719b21e         0                      0
14 P7ece52e         0                      0
15 P92b4604         0                     NA
16 P97574f9         0                      0
17 P9cdfd5a         0                      0
18 Pa8f3b51         0                      0
19 Pbe289c8         0                      0
20 Pc44e366         0                      0
21 Pc77a35c         0                      0
22 Pcd2c0d1         0                     NA
23 Pdab1897         0                      0
24 Pe706703         0                      0

In [46]:
# NA ONLY for fp
missing_pn_smoking_fp <- combined_df_smoking |> filter(is.na(combined_df_smoking$smoking_category_Q2_FP) & !is.na(combined_df_smoking$smoking_category_Q2_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_smoking_fp

character(0)

In [47]:
# NA ONLY for sp
missing_pn_smoking_sp <- combined_df_smoking |> filter(is.na(combined_df_smoking$smoking_category_Q2_SP) & !is.na(combined_df_smoking$smoking_category_Q2_FP)) |> 
  pull(Q1_Personnummer)
missing_pn_smoking_sp

[1] "P92b4604" "Pcd2c0d1"

In [48]:
# Pull personal# where NA for BOTH fp AND sp
missing_pn_smoking_both <- combined_df_smoking |> filter(is.na(combined_df_smoking$smoking_category_Q2_FP) & is.na(combined_df_smoking$smoking_category_Q2_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_smoking_both
length(missing_pn_smoking_both)

[1] "P50f102c"

[1] 1

## Alcohol-----------------------------------------------------------------------

In [49]:
combined_fp_sp_tp2$Q2_X28_How_often_alcohol_since_pregnancy

 [1] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
 [9] "Aldrig" NA       "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[17] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[25] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[33] "Aldrig" NA       "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[41] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" NA       "Aldrig" "Aldrig"

In [50]:
alcohol_category_fp <- ifelse(fp_tp2$Q2_X28_How_often_alcohol_since_pregnancy == "Aldrig", 0, NA)
table(alcohol_category_fp)

alcohol_category_sp <- ifelse(sp_tp2$Q2_X28_How_often_alcohol_since_pregnancy == "Aldrig", 0, NA)
table(alcohol_category_sp)

alcohol_category_fp
 0
23

alcohol_category_sp
 0
22

In [51]:
# Check for NA
sum(is.na(alcohol_category_fp))
sum(is.na(alcohol_category_sp))

[1] 1

[1] 2

In [52]:
fp_tp2$alcohol_category_Q2 <- alcohol_category_fp
fp_tp2$alcohol_category_Q2

sp_tp2$alcohol_category_Q2 <- alcohol_category_sp
sp_tp2$alcohol_category_Q2

 [1]  0  0  0  0  0  0  0  0  0 NA  0  0  0  0  0  0  0  0  0  0  0  0  0  0

 [1]  0  0  0  0  0  0  0  0  0 NA  0  0  0  0  0  0  0  0  0  0  0 NA  0  0

In [53]:
fp_alcohol <- fp_tp2 |>
  select(Q1_Personnummer, alcohol_category_Q2)
fp_alcohol

sp_alcohol <- sp_tp2 |>
  select(Q1_Personnummer, alcohol_category_Q2)
sp_alcohol

   Q1_Personnummer alcohol_category_Q2
1  P159f9c8         0
2  P1a267fa         0
3  P1f862a6         0
4  P3c0f6ee         0
5  P3cac7b0         0
6  P3db7da6         0
7  P424fd61         0
8  P4a05456         0
9  P4de45e7         0
10 P50f102c        NA
11 P5b98b6c         0
12 P62ea0b2         0
13 P719b21e         0
14 P7ece52e         0
15 P92b4604         0
16 P97574f9         0
17 P9cdfd5a         0
18 Pa8f3b51         0
19 Pbe289c8         0
20 Pc44e366         0
21 Pc77a35c         0
22 Pcd2c0d1         0
23 Pdab1897         0
24 Pe706703         0

   Q1_Personnummer alcohol_category_Q2
1  P159f9c8         0
2  P1a267fa         0
3  P1f862a6         0
4  P3c0f6ee         0
5  P3cac7b0         0
6  P3db7da6         0
7  P424fd61         0
8  P4a05456         0
9  P4de45e7         0
10 P50f102c        NA
11 P5b98b6c         0
12 P62ea0b2         0
13 P719b21e         0
14 P7ece52e         0
15 P92b4604         0
16 P97574f9         0
17 P9cdfd5a         0
18 Pa8f3b51         0
19 Pbe289c8         0
20 Pc44e366         0
21 Pc77a35c         0
22 Pcd2c0d1        NA
23 Pdab1897         0
24 Pe706703         0

In [54]:
combined_df_alcohol <- merge(fp_alcohol, sp_alcohol, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_alcohol

   Q1_Personnummer alcohol_category_Q2_FP alcohol_category_Q2_SP
1  P159f9c8         0                      0
2  P1a267fa         0                      0
3  P1f862a6         0                      0
4  P3c0f6ee         0                      0
5  P3cac7b0         0                      0
6  P3db7da6         0                      0
7  P424fd61         0                      0
8  P4a05456         0                      0
9  P4de45e7         0                      0
10 P50f102c        NA                     NA
11 P5b98b6c         0                      0
12 P62ea0b2         0                      0
13 P719b21e         0                      0
14 P7ece52e         0                      0
15 P92b4604         0                      0
16 P97574f9         0                      0
17 P9cdfd5a         0                      0
18 Pa8f3b51         0                      0
19 Pbe289c8         0                      0
20 Pc44e366         0                      0
21 Pc77a35c         0                      0
22 Pcd2c0d1         0                     NA
23 Pdab1897         0                      0
24 Pe706703         0                      0

## Antibiotic--------------------------------------------------------------------

In [55]:
class(combined_fp_sp_tp2$Q2_X6.Antibiotics_during_pregnancy)

[1] "integer"

In [56]:
# Convert to factor
fp_tp2$Q2_X6.Antibiotics_during_pregnancy <- as.factor(fp_tp2$Q2_X6.Antibiotics_during_pregnancy)
class(fp_tp2$Q2_X6.Antibiotics_during_pregnancy)

[1] "factor"

In [57]:
sum(is.na(fp_tp2$Q2_X6.Antibiotics_during_pregnancy))

[1] 1

In [58]:
sp_tp2$Q2_X6.Antibiotics_during_pregnancy <- as.factor(sp_tp2$Q2_X6.Antibiotics_during_pregnancy)
class(sp_tp2$Q2_X6.Antibiotics_during_pregnancy)

[1] "factor"

In [59]:
sum(is.na(sp_tp2$Q2_X6.Antibiotics_during_pregnancy))

[1] 2

In [60]:
fp_antibiotic <- fp_tp2 |>
  select(Q1_Personnummer, Q2_X6.Antibiotics_during_pregnancy)
fp_antibiotic

sp_antibiotic <- sp_tp2 |>
  select(Q1_Personnummer, Q2_X6.Antibiotics_during_pregnancy)
sp_antibiotic

   Q1_Personnummer Q2_X6.Antibiotics_during_pregnancy
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        0
4  P3c0f6ee        0
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        0
16 P97574f9        0
17 P9cdfd5a        0
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        0
24 Pe706703        1

   Q1_Personnummer Q2_X6.Antibiotics_during_pregnancy
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        0
4  P3c0f6ee        1
5  P3cac7b0        1
6  P3db7da6        0
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        0
16 P97574f9        0
17 P9cdfd5a        0
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        NA
23 Pdab1897        0
24 Pe706703        0

In [61]:
combined_df_antibiotic <- merge(fp_antibiotic, sp_antibiotic, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_antibiotic

   Q1_Personnummer Q2_X6.Antibiotics_during_pregnancy_FP
1  P159f9c8        0
2  P1a267fa        0
3  P1f862a6        0
4  P3c0f6ee        0
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        0
8  P4a05456        0
9  P4de45e7        0
10 P50f102c        NA
11 P5b98b6c        0
12 P62ea0b2        0
13 P719b21e        0
14 P7ece52e        0
15 P92b4604        0
16 P97574f9        0
17 P9cdfd5a        0
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        0
21 Pc77a35c        0
22 Pcd2c0d1        0
23 Pdab1897        0
24 Pe706703        1
   Q2_X6.Antibiotics_during_pregnancy_SP
1  0
2  0
3  0
4  1
5  1
6  0
7  0
8  0
9  0
10 NA
11 0
12 0
13 0
14 0
15 0
16 0
17 0
18 0
19 0
20 0
21 0
22 NA
23 0
24 0

In [62]:
# NA ONLY for fp
missing_pn_antibiotic_fp <- combined_df_antibiotic |> filter(is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP) & !is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_antibiotic_fp

character(0)

In [63]:
# NA ONLY for sp
missing_pn_antibiotic_sp <- combined_df_antibiotic |> filter(is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP) & !is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP)) |> 
  pull(Q1_Personnummer)
missing_pn_antibiotic_sp

[1] "Pcd2c0d1"

In [64]:
# Pull personal# where NA for BOTH fp AND sp
missing_pn_antibiotic_both <- combined_df_antibiotic |> filter(is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP) & is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP)) |> 
  pull(Q1_Personnummer)
missing_pn_antibiotic_both
length(missing_pn_antibiotic_both)

[1] "P50f102c"

[1] 1

In [65]:
# Make sure stress_FP and stress_SP are numeric (NOT factors)
combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP <- as.numeric(as.character(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP))
combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP <- as.numeric(as.character(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP))

In [66]:
# 2. Split into groups
m2 <- combined_df_antibiotic[!is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP) & !is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP), ] # complete
m1 <- combined_df_antibiotic[!is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP) & is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_SP), ]  # only FP
m3 <- combined_df_antibiotic[is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP) & !is.na(combined_df_antibiotic$Q2_X6.Antibiotics_during_pregnancy_FP), ]  # only SP

In [67]:
# 3. Sizes
n_total <- nrow(combined_df_antibiotic)
m1_n <- nrow(m1)
m2_n <- nrow(m2)
m3_n <- nrow(m3)

Pms <- m1_n / n_total # missing smoking SP
Pmt <- m3_n / n_total # missing missing FP

In [68]:
# 4. Paired estimator Δ̂(P)
delta_paired <- mean(m2$Q2_X6.Antibiotics_during_pregnancy_SP - m2$Q2_X6.Antibiotics_during_pregnancy_FP, na.rm = TRUE)

In [69]:
# 5. Unpaired estimator Δ̂(U)
P_s <- mean(m1$Q2_X6.Antibiotics_during_pregnancy_FP, na.rm = TRUE) # from m1

In [70]:
P_t <- mean(m3$Q2_X6.Antibiotics_during_pregnancy_SP, na.rm = TRUE) # from m3
delta_unpaired <- P_t - P_s

In [71]:
# 6. Calculate components for V_P
P01 <- sum(m2$Q2_X6.Antibiotics_during_pregnancy_FP == 0 & m2$Q2_X6.Antibiotics_during_pregnancy_SP == 1) / m2_n
P10 <- sum(m2$Q2_X6.Antibiotics_during_pregnancy_FP == 1 & m2$Q2_X6.Antibiotics_during_pregnancy_SP == 0) / m2_n

VP <- (P01 + P10 - (P01 - P10)^2) / (1 - Pms - Pmt)

In [72]:
# 7. Calculate VU
VU <- (P_s * (1 - P_s)) / Pms + (P_t * (1 - P_t)) / Pmt

In [73]:
# 8. Weight w and hybrid estimator
w <- VU / (VU + VP)
delta_D <- w * delta_unpaired + (1 - w) * delta_paired

In [74]:
# 9. Combined variance and SE
var_D <- (VU * VP) / (VU + VP)
se_D <- sqrt(var_D)

In [75]:
# 10. Z-test
z_value <- delta_D / se_D
p_value <- 2 * (1 - pnorm(abs(z_value)))
print(p_value)

[1] NaN

## Diet--------------------------------------------------------------------------

In [76]:
class(combined_fp_sp_tp2$Q2_healthydiet)

[1] "integer"

In [77]:
fp_diet <- fp_tp2 |>
  select(Q1_Personnummer, Q2_healthydiet)
fp_diet

sp_diet <- sp_tp2 |>
  select(Q1_Personnummer, Q2_healthydiet)
sp_diet

   Q1_Personnummer Q2_healthydiet
1  P159f9c8        1
2  P1a267fa        1
3  P1f862a6        1
4  P3c0f6ee        1
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        1
8  P4a05456        1
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        1
12 P62ea0b2        1
13 P719b21e        0
14 P7ece52e        1
15 P92b4604        1
16 P97574f9        1
17 P9cdfd5a        0
18 Pa8f3b51        1
19 Pbe289c8        0
20 Pc44e366        1
21 Pc77a35c        1
22 Pcd2c0d1        1
23 Pdab1897        1
24 Pe706703        1

   Q1_Personnummer Q2_healthydiet
1  P159f9c8        1
2  P1a267fa        1
3  P1f862a6        1
4  P3c0f6ee        1
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        1
8  P4a05456        1
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        1
12 P62ea0b2        1
13 P719b21e        0
14 P7ece52e        1
15 P92b4604        0
16 P97574f9        1
17 P9cdfd5a        0
18 Pa8f3b51        0
19 Pbe289c8        0
20 Pc44e366        1
21 Pc77a35c        1
22 Pcd2c0d1        0
23 Pdab1897        1
24 Pe706703        1

In [78]:
combined_df_diet <- merge(fp_diet, sp_diet, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_diet

   Q1_Personnummer Q2_healthydiet_FP Q2_healthydiet_SP
1  P159f9c8        1                 1
2  P1a267fa        1                 1
3  P1f862a6        1                 1
4  P3c0f6ee        1                 1
5  P3cac7b0        0                 0
6  P3db7da6        1                 1
7  P424fd61        1                 1
8  P4a05456        1                 1
9  P4de45e7        0                 0
10 P50f102c        0                 0
11 P5b98b6c        1                 1
12 P62ea0b2        1                 1
13 P719b21e        0                 0
14 P7ece52e        1                 1
15 P92b4604        1                 0
16 P97574f9        1                 1
17 P9cdfd5a        0                 0
18 Pa8f3b51        1                 0
19 Pbe289c8        0                 0
20 Pc44e366        1                 1
21 Pc77a35c        1                 1
22 Pcd2c0d1        1                 0
23 Pdab1897        1                 1
24 Pe706703        1                 1

In [79]:
tab_diet <- table(combined_df_diet$Q2_healthydiet_FP, combined_df_diet$Q2_healthydiet_SP)
tab_diet

     0  1
  0  6  0
  1  3 15

In [80]:
mcnemar.test(tab_diet)

	McNemar's Chi-squared test with continuity correction

data:  tab_diet
McNemar's chi-squared = 1.3333, df = 1, p-value = 0.2482

## Daily Fiber-------------------------------------------------------------------

In [81]:
class(combined_fp_sp_tp2$Q2_dailyfiber)

[1] "integer"

In [82]:
fp_fiber <- fp_tp2 |>
  select(Q1_Personnummer, Q2_dailyfiber)
fp_fiber

   Q1_Personnummer Q2_dailyfiber
1  P159f9c8        1
2  P1a267fa        1
3  P1f862a6        1
4  P3c0f6ee        1
5  P3cac7b0        0
6  P3db7da6        1
7  P424fd61        1
8  P4a05456        1
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        1
12 P62ea0b2        1
13 P719b21e        1
14 P7ece52e        1
15 P92b4604        1
16 P97574f9        1
17 P9cdfd5a        0
18 Pa8f3b51        1
19 Pbe289c8        0
20 Pc44e366        1
21 Pc77a35c        1
22 Pcd2c0d1        1
23 Pdab1897        1
24 Pe706703        1

In [83]:
sp_fiber <- sp_tp2 |>
  select(Q1_Personnummer, Q2_dailyfiber)
sp_fiber

   Q1_Personnummer Q2_dailyfiber
1  P159f9c8        1
2  P1a267fa        1
3  P1f862a6        1
4  P3c0f6ee        1
5  P3cac7b0        1
6  P3db7da6        1
7  P424fd61        1
8  P4a05456        1
9  P4de45e7        0
10 P50f102c        0
11 P5b98b6c        1
12 P62ea0b2        1
13 P719b21e        1
14 P7ece52e        1
15 P92b4604        0
16 P97574f9        1
17 P9cdfd5a        1
18 Pa8f3b51        1
19 Pbe289c8        0
20 Pc44e366        1
21 Pc77a35c        1
22 Pcd2c0d1        0
23 Pdab1897        1
24 Pe706703        1

In [84]:
combined_df_fiber <- merge(fp_fiber, sp_fiber, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
combined_df_fiber

   Q1_Personnummer Q2_dailyfiber_FP Q2_dailyfiber_SP
1  P159f9c8        1                1
2  P1a267fa        1                1
3  P1f862a6        1                1
4  P3c0f6ee        1                1
5  P3cac7b0        0                1
6  P3db7da6        1                1
7  P424fd61        1                1
8  P4a05456        1                1
9  P4de45e7        0                0
10 P50f102c        0                0
11 P5b98b6c        1                1
12 P62ea0b2        1                1
13 P719b21e        1                1
14 P7ece52e        1                1
15 P92b4604        1                0
16 P97574f9        1                1
17 P9cdfd5a        0                1
18 Pa8f3b51        1                1
19 Pbe289c8        0                0
20 Pc44e366        1                1
21 Pc77a35c        1                1
22 Pcd2c0d1        1                0
23 Pdab1897        1                1
24 Pe706703        1                1

In [85]:
tab_fiber <- table(combined_df_fiber$Q2_dailyfiber_FP, combined_df_fiber$Q2_dailyfiber_SP)
tab_fiber

     0  1
  0  3  2
  1  2 17

In [86]:
mcnemar.test(tab_fiber)

	McNemar's Chi-squared test

data:  tab_fiber
McNemar's chi-squared = 0, df = 1, p-value = 1

## Hypertension---------------------------------------------------------------------------------------

In [87]:
class(combined_fp_sp_tp2$Q2_bloodpressure)

fp_tp2$Q2_bloodpressure <- as.factor(fp_tp2$Q2_bloodpressure)
sp_tp2$Q2_bloodpressure <- as.factor(sp_tp2$Q2_bloodpressure)
combined_fp_sp_tp2$Q2_bloodpressure <- as.factor(combined_fp_sp_tp2$Q2_bloodpressure)

[1] "integer"

In [88]:
class(fp_tp2$Q2_bloodpressure)

[1] "factor"

In [89]:
fp_BP <- fp_tp2 |>
  select(Q1_Personnummer, Q2_bloodpressure)
head(fp_BP)

sp_BP <- sp_tp2 |>
  select(Q1_Personnummer, Q2_bloodpressure)
head(sp_BP)

  Q1_Personnummer Q2_bloodpressure
1 P159f9c8        1
2 P1a267fa        0
3 P1f862a6        0
4 P3c0f6ee        1
5 P3cac7b0        0
6 P3db7da6        0

  Q1_Personnummer Q2_bloodpressure
1 P159f9c8        0
2 P1a267fa        0
3 P1f862a6        0
4 P3c0f6ee        1
5 P3cac7b0        0
6 P3db7da6        0

In [90]:
combined_df_BP <- merge(fp_BP, sp_BP, by = "Q1_Personnummer", suffixes = c("_FP", "_SP"))
head(combined_df_BP)

  Q1_Personnummer Q2_bloodpressure_FP Q2_bloodpressure_SP
1 P159f9c8        1                   0
2 P1a267fa        0                   0
3 P1f862a6        0                   0
4 P3c0f6ee        1                   1
5 P3cac7b0        0                   0
6 P3db7da6        0                   0

In [91]:
tab_BP <- table(combined_df_BP$Q2_bloodpressure_FP, combined_df_BP$Q2_bloodpressure_SP)
tab_BP

     0  1
  0 19  1
  1  2  2

In [92]:
mcnemar.test(tab_BP)

	McNemar's Chi-squared test with continuity correction

data:  tab_BP
McNemar's chi-squared = 0, df = 1, p-value = 1