#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name:drop_na_kit1
# Date: 2025.07.30
# Programmer: Barbara Nowak
# Purpose: (File 2, double_pregnancy_convert comes before ) Feacal, drop participants with missing values in kit1 & invalid samples (missing barcodes)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [16]:
library(tidyverse)
library(dplyr)

# Reading files~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [17]:
# Read cleaned first and second pregnancy
fp <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_fp_.csv", header = TRUE)
dim(fp)
head(fp)

[1]  59 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

In [18]:
sp <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_sp_.csv", header = TRUE)
dim(sp)
head(sp)

[1]  59 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

In [19]:
sample_id <- readLines("/ceph/projects/010_SweMaMi/bm.nowak/data/list_of_samples_after_filtration_process.txt")
length(sample_id)

[1] 3483

In [20]:
# Find participants in fp where fecal barcode is missing
pn_fp_tp1 <- fp |>
  filter(is.na(kit1.faecal_sample.barcode)) |>
  pull(Q1_Personnummer)
pn_fp_tp1

[1] "Pfb279f0"

In [21]:
# Find participants in sp where faecal barcode is missing
pn_sp_tp1 <- sp |>
  filter(is.na(kit1.faecal_sample.barcode)) |>
  pull(Q1_Personnummer)
pn_sp_tp1

[1] "Pa8747ea" "Pfb279f0"

In [22]:
# Combine both sets of participants to drop
drop_tp1_pn <- c(pn_fp_tp1, pn_sp_tp1)
drop_tp1_pn
length(unique(drop_tp1_pn))

[1] "Pfb279f0" "Pa8747ea" "Pfb279f0"

[1] 2

# ===============================================================================

# Remove participants with missing TP1 faecal samples
# Q1_Personnummer is used to track individuals.
# If the barcode is missing in either fp or sp, both entries are dropped.

In [23]:
# Keep only participants with valid TP1 faecal samples
fp_tp1 <- fp |>
  filter(!(Q1_Personnummer %in% drop_tp1_pn))
head(fp_tp1)
dim(fp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

[1]  57 566

In [24]:
sp_tp1 <- sp |> 
  filter(!(Q1_Personnummer %in% drop_tp1_pn))
head(sp_tp1)
dim(sp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

[1]  57 566

In [25]:
# Find barcodes in fp that are missing from the valid sample list
missing_fp_tp1_samples <- setdiff(fp_tp1$kit1.faecal_sample.barcode, sample_id)

In [26]:
# Same for sp
missing_sp_tp1_samples <- setdiff(sp_tp1$kit1.faecal_sample.barcode, sample_id)

In [27]:
# Combine all missing sample barcodes
all_missing_samples <-  c(missing_fp_tp1_samples, missing_sp_tp1_samples)
length(all_missing_samples)

[1] 12

# Some barcodes might be present, but not part of the filtered list of valid samples

In [28]:
# Get person num for those missing samples from fp and sp
pn_fp_to_drop <- fp_tp1 |>
  filter(kit1.faecal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)

In [29]:
pn_sp_to_drop <-  sp_tp1 |>
  filter(kit1.faecal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)

In [31]:
# Combine all personal num to drop
pn_drop_all <- c(pn_fp_to_drop, pn_sp_to_drop)
pn_drop_all
length(unique(pn_drop_all))

 [1] "P060d440" "P1d75300" "P1f95844" "P3399626" "P42f2c08" "P735d77f"
 [7] "P7b2ccf8" "Pb752955" "Pbbb08bd" "Pc75b32a" "Pca94a0f" "Pbdbd455"

[1] 12

In [17]:
# Ensure we only retain those whose samples are both present and valid
# Final cleaned dataset after filtering out bad samples
fp_tp1_filt <- fp_tp1 |>
  filter(!(Q1_Personnummer %in% pn_drop_all))
dim(fp_tp1_filt)

[1]  45 566

In [18]:
sp_tp1_filt <- sp_tp1 |>
  filter(!(Q1_Personnummer %in% pn_drop_all))
dim(sp_tp1_filt)

[1]  45 566

In [19]:
# These contain only participants with valid, non-missing faecal sample barcodes also found in sample_id.
# Final check: Make sure both fp and sp have the same participants
# intersect() confirms the alignment.
length(intersect(fp_tp1_filt$Q1_Personnummer, sp_tp1_filt$Q1_Personnummer))

[1] 45

In [ ]:
# Write to file
write.table(fp_tp1_filt, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/", Sys.Date(), "_fp_tp1_filt", ".csv"), sep = ",", row.names = FALSE)
write.table(sp_tp1_filt, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/", Sys.Date(), "_sp_tp1_filt", ".csv"), sep = ",", row.names = FALSE)