#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: drop_na_kit2_nulliparous
# Date: 2025.08.18
# Programmer: Barbara Nowak
# Purpose: Drop participants with missing kit2 & invalid samples (missing barcodes)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [ ]:
library(tidyverse)
library(dplyr)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [3]:
# Read in filtered data 
 fp_tp1 <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp1_nulliparous/2025-08-01fp_tp1_filt_nulliparous.csv", header = TRUE)
 head(fp_tp1)
 dim(fp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5208 Sa8397fa     NA         0        0         0
4 5301 S1f862a6     NA         0        0         0
5 5285 S3c0f6ee     NA         0        0         0
6 5275 S2b86cc0     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2019-05-23 P1a267fa        0                   32          ⋯ 0
3 2018-03-14 P1ef420d        0                   27          ⋯ 0
4 2018-03-07 P1f862a6        0                   32          ⋯ 0
5 2019-03-25 P3c0f6ee        0                   31          ⋯ 0
6 2019-05-29 P3cac7b0        0                   31          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     28
4 NA                 NA   NA       NA                     31
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  25 566

In [4]:
  sp_tp1 <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp1_nulliparous/2025-08-01sp_tp1_filt_nulliparous.csv", header = TRUE)
 head(sp_tp1)
 dim(sp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5332 Sb124b17     NA         0        0         2
3 5247 S1ef420d     NA         0        0         1
4 5305 Sa79a719     NA         0        0         1
5 5310 S5097402     NA         0        0         1
6 5311 S3cac7b0     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯ 0
2 2021-01-06 P1a267fa        0                   34          ⋯ 0
3 2020-09-17 P1ef420d        0                   30          ⋯ 0
4 2019-01-17 P1f862a6        0                   32          ⋯ 0
5 2020-10-18 P3c0f6ee        0                   33          ⋯ 0
6 2020-10-20 P3cac7b0        0                   33          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Induction            NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  25 566

In [5]:
# Read valid sample list
sample_id <- readLines("/ceph/projects/010_SweMaMi/bm.nowak/data/list_of_samples_after_filtration_process.txt")
length(sample_id)

[1] 3483

In [ ]:
# Find fp women where birth date of child is missing & keep only participants where birthdate exists- ALREADY DONE
# Find women where primipara = TRUE for fp and keep them in fp and sp - ALREADY DONE

In [6]:
# Make sure all fp are primiparous
fp_pn_check <- fp_tp1 |> 
  filter(fp_tp1$Primipara == 1) |>
  pull(Q1_Personnummer)
fp_pn_check
length(fp_pn_check)

 [1] "P159f9c8" "P1a267fa" "P1ef420d" "P1f862a6" "P3c0f6ee" "P3cac7b0"
 [7] "P3db7da6" "P424fd61" "P4a05456" "P4de45e7" "P50f102c" "P5b98b6c"
[13] "P62ea0b2" "P719b21e" "P7ece52e" "P92b4604" "P97574f9" "P9cdfd5a"
[19] "Pa8f3b51" "Pbe289c8" "Pc44e366" "Pc77a35c" "Pcd2c0d1" "Pdab1897"
[25] "Pe706703"

[1] 25

In [7]:
# Doubble check that all sp are not primiparous
pn_check <- sp_tp1 |> 
  filter(sp_tp1$Primipara == 1) |>
  pull(Q1_Personnummer)
pn_check
length(pn_check)

character(0)

[1] 0

# ==============================================================================

In [8]:
grep("kit", names(fp_tp1), value = TRUE)

 [1] "kit1.faecal_sample.barcode"
 [2] "kit2.faecal_sample.barcode"
 [3] "kit3.faecal_sample.barcode"
 [4] "kit3.infant_faecal_sample.barcode"
 [5] "kit3.infant_faecal_sample_2.barcode"
 [6] "kit3.salival_sample.barcode"
 [7] "kit1.salival_sample.barcode"
 [8] "kit1.vaginal_sample.barcode"
 [9] "kit1.faecal_sample.datetime_taken"
[10] "kit1.salival_sample.datetime_taken"
[11] "kit1.vaginal_sample.datetime_taken"
[12] "kit2.salival_sample.barcode"
[13] "kit2.vaginal_sample.barcode"
[14] "kit2.faecal_sample.datetime_taken"
[15] "kit2.salival_sample.datetime_taken"
[16] "kit2.vaginal_sample.datetime_taken"
[17] "kit3.vaginal_sample.barcode"
[18] "kit3.faecal_sample.datetime_taken"
[19] "kit3.infant_faecal_sample.datetime_taken"
[20] "kit3.infant_faecal_sample_2.datetime_taken"
[21] "kit3.salival_sample.datetime_taken"
[22] "kit3.vaginal_sample.datetime_taken"

In [9]:
# Find participants where kit2 is missing
fp_pn_kit2_missing <- fp_tp1 |>
  filter(is.na(kit2.faecal_sample.barcode)) |>
  pull(Q1_Personnummer)
fp_pn_kit2_missing

[1] "P1ef420d"

In [10]:
sp_pn_kit2_missing <-  sp_tp1 |>
  filter(is.na(kit2.faecal_sample.barcode)) |>
  pull(Q1_Personnummer)
sp_pn_kit2_missing

character(0)

In [11]:
# doubble check 
fp_tp1$kit2.faecal_sample.barcode
sp_tp1$kit2.faecal_sample.barcode

 [1] 100000144381 100000172865           NA 100000112243 100000162699
 [6] 100000168325 100000123362 100000106341 100000172728 100000129494
[11] 100000129227 100000106136 100000136430 100000126714 100000155653
[16] 100000133958 100000148082 100000126820 100000117408 100000140093
[21] 100000134894 100000108482 100000106303 100000148693 100000103470

 [1] 100000433799 100000426708 100000429457 100000157503 100000429624
 [6] 100000424926 100000189313 100000426753 100000422069 100000421192
[11] 100000406489 100000417232 100000420362 100000408391 100000427415
[16] 100000406809 100000421864 100000429761 100000419274 100000434772
[21] 100000433645 100000426050 100000185766 100000418123 100000186718

In [12]:
# combine both sets of participants to drop (just good practice here) 
combined_missing_kit2 <- c(fp_pn_kit2_missing, sp_pn_kit2_missing)
length(combined_missing_kit2)

[1] 1

# -------------------------------------------------------------------------------

# Drop all participants with missing tp2 faecal sample (kit2)
# If missing in either fp or sp, BOTH ARE DROPPED

In [13]:
# Keep only participants with valid tp2 faecal samples
fp_tp2 <- fp_tp1 |>
  filter(!(Q1_Personnummer %in% combined_missing_kit2))
head(fp_tp2)
dim(fp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5301 S1f862a6     NA         0        0         0
4 5285 S3c0f6ee     NA         0        0         0
5 5275 S2b86cc0     NA         0        0         0
6 5243 S39fe1d7     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2019-05-23 P1a267fa        0                   32          ⋯ 0
3 2018-03-07 P1f862a6        0                   32          ⋯ 0
4 2019-03-25 P3c0f6ee        0                   31          ⋯ 0
5 2019-05-29 P3cac7b0        0                   31          ⋯ 0
6 2018-06-23 P3db7da6        0                   29          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     31
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  24 566

In [14]:
sp_tp2 <- sp_tp1 |>
  filter(!(Q1_Personnummer %in% combined_missing_kit2))
head(sp_tp2)
dim(sp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5332 Sb124b17     NA         0        0         2
3 5305 Sa79a719     NA         0        0         1
4 5310 S5097402     NA         0        0         1
5 5311 S3cac7b0     NA         0        0         0
6 5252 S3db7da6     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯ 0
2 2021-01-06 P1a267fa        0                   34          ⋯ 0
3 2019-01-17 P1f862a6        0                   32          ⋯ 0
4 2020-10-18 P3c0f6ee        0                   33          ⋯ 0
5 2020-10-20 P3cac7b0        0                   33          ⋯ 0
6 2019-09-24 P3db7da6        0                   30          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  24 566

In [15]:
# Find barcodes that are missing from valid sample list
missing_fp_tp2_samples <- setdiff(fp_tp2$kit2.faecal_sample.barcode, sample_id)
length(missing_fp_tp2_samples)

[1] 1

In [16]:
missing_sp_tp2_samples <- setdiff(sp_tp2$kit2.faecal_sample.barcode, sample_id)
length(missing_sp_tp2_samples)

[1] 2

In [17]:
# This part is mostly good practice since no more samples were missing
# Combine all missing samples (good practice)
all_missing_samples <-c(missing_fp_tp2_samples, missing_sp_tp2_samples)
all_missing_samples

[1] 100000162699 100000406489 100000419274

In [18]:
# Get the personal numbers
fp_pn_to_drop <- fp_tp2 |>
  filter(kit2.faecal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(fp_pn_to_drop)

[1] 1

In [19]:
sp_pn_to_drop <- sp_tp2 |>
  filter(kit2.faecal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(sp_pn_to_drop)

[1] 2

In [20]:
# Combine all to drop
combined_pn_to_drop <- c(fp_pn_to_drop, sp_pn_to_drop)
length(combined_pn_to_drop)

[1] 3

In [21]:
# Keep only participants with valid sample
fp_tp2_filtered_nulliparous <- fp_tp2 |>
  filter(!(Q1_Personnummer %in% combined_pn_to_drop)) 
head(fp_tp2_filtered_nulliparous)
dim(fp_tp2_filtered_nulliparous)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5301 S1f862a6     NA         0        0         0
4 5275 S2b86cc0     NA         0        0         0
5 5243 S39fe1d7     NA         0        0         0
6 5383 S7e4a963     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2019-05-23 P1a267fa        0                   32          ⋯ 0
3 2018-03-07 P1f862a6        0                   32          ⋯ 0
4 2019-05-29 P3cac7b0        0                   31          ⋯ 0
5 2018-06-23 P3db7da6        0                   29          ⋯ 0
6 2018-02-18 P424fd61        0                   37          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     31
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0

[1]  21 566

In [22]:
sp_tp2_filtered_nulliparous <- sp_tp2 |>
  filter(!(Q1_Personnummer %in% combined_pn_to_drop))
head(sp_tp2_filtered_nulliparous)
dim(sp_tp2_filtered_nulliparous)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5332 Sb124b17     NA         0        0         2
3 5305 Sa79a719     NA         0        0         1
4 5311 S3cac7b0     NA         0        0         0
5 5252 S3db7da6     NA         0        0         1
6 5415 S424fd61     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2021-01-06 P1a267fa        0                   34          ⋯  0
3 2019-01-17 P1f862a6        0                   32          ⋯  0
4 2020-10-20 P3cac7b0        0                   33          ⋯  0
5 2019-09-24 P3db7da6        0                   30          ⋯  0
6 2020-11-03 P424fd61        0                   40          ⋯ 31
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  21 566

In [23]:
# Contain only participants with valid, non-missing faecal sample barcodes for kit2 (AND kit1)
# Final check: Make sure both fp and sp have the same participants with intersect
 length(intersect(fp_tp2_filtered_nulliparous$Q1_Personnummer, sp_tp2_filtered_nulliparous$Q1_Personnummer))

[1] 21

# ===============================================================================

In [ ]:
# Write to file
write.table(fp_tp2_filtered_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/tp2_nulliparous/", Sys.Date(), "_fp_tp2_filt", ".csv"), sep = ",", row.names = FALSE)
write.table(sp_tp2_filtered_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/tp2_nulliparous/", Sys.Date(), "_sp_tp2_filt", ".csv"), sep = ",", row.names = FALSE)

In [ ]:
# Write file with combined fp and sp 
fp_tp2_filtered_nulliparous$Group <- "First pregnancy "
sp_tp2_filtered_nulliparous$Group <- "Second pregnancy"

In [ ]:
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_tp2_filtered_nulliparous, sp_tp2_filtered_nulliparous)
head(combined_fp_sp)
dim(combined_fp_sp)

In [ ]:
# Write combined, filtered data to file
write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/tp2_nulliparous/", Sys.Date(), "_combined_fp_sp_tp2", ".csv"), sep = ",", row.names = FALSE)

In [ ]:
 # Test written file
test <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/tp2_nulliparous/2025-09-01_combined_fp_sp_tp2.csv", header = TRUE)
head(test)
dim(test)