#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_check_date
# Date: 2025.10.06
# Programmer: Barbara Nowak
# Purpose: Compare dates of kit1 and Q1 (and Q2 and Q3) in order to determine if samples correspond to correct pregnancy
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ──────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# First, read files for Fp and Sp and merge them together

In [3]:
fp_saliva <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_fp_.csv", header = TRUE, row.names = 1)
head(fp_saliva)
dim(fp_saliva)

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5265 Scf5931f     NA         0        0         0
5254 S14e664f     NA         0        0         1
5367 S194e21b     NA         0        0         0
5297 S1a267fa     NA         0        0         0
5300 S30bce16     NA         0        0         0
5208 Sa8397fa     NA         0        0         0
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5265 2018-12-13 P060d440        0                   30          3          ⋯
5254 2018-09-10 P14e664f        0                   30          3          ⋯
5367 2018-11-16 P159f9c8        0                   36          4          ⋯
5297 2019-05-23 P1a267fa        0                   32          3          ⋯
5300 2018-04-18 P1d75300        0                   32          3          ⋯
5208 2018-03-14 P1ef420d        0                   27          2          ⋯
     diffdays missfall.IUFD_week IUFD missfall missfall.IUFD_comments
5265 NA       NA                 NA    1       MISSED ABORTION
5254  0       NA                 NA   NA       NA
5367  0       NA                 NA   NA       NA
5297  0       NA                 NA   NA       NA
5300 NA       NA                 NA   NA       NA
5208  0       NA                 NA   NA       NA
     Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
5265 NA              NA                   NA          NA
5254 39              Induction            NA          NA
5367 41              Spontaneous          NA          NA
5297 38              Spontaneous          NA          NA
5300 NA              NA                   NA          NA
5208 28              Spontaneous          very_w28_31  1
     preeclampsia_epi_analysis
5265 0
5254 0
5367 0
5297 0
5300 0
5208 0

[1]  59 565

In [4]:
sp_saliva <- read.csv("/ceph/projects//010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_sp_.csv", header = TRUE, row.names = 1)
head(sp_saliva)
dim(sp_saliva)

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5253 S060d440     NA         0        0         1
5290 Sefe71fe     NA         0        0         1
5391 S159f9c8     NA         0        0         0
5332 Sb124b17     NA         0        0         2
5322 S1d75300     NA         0        0         0
5247 S1ef420d     NA         0        0         1
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5253 2019-06-03 P060d440        0                   30          3          ⋯
5290 2020-08-17 P14e664f        0                   32          3          ⋯
5391 2021-01-28 P159f9c8        0                   38          4          ⋯
5332 2021-01-06 P1a267fa        0                   34          3          ⋯
5322 2019-05-14 P1d75300        0                   33          3          ⋯
5247 2020-09-17 P1ef420d        0                   30          3          ⋯
     diffdays missfall.IUFD_week IUFD missfall missfall.IUFD_comments
5253  0       NA                 NA   NA       NA
5290  0       NA                 NA   NA       NA
5391  0       NA                 NA   NA       NA
5332  0       NA                 NA   NA       NA
5322 NA       NA                 NA   NA       NA
5247  0       NA                 NA   NA       NA
     Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
5253 38              Unlaboured c-section NA          NA
5290 39              Spontaneous          NA          NA
5391 40              Spontaneous          NA          NA
5332 41              Spontaneous          NA          NA
5322 41              Induction            NA          NA
5247 40              Spontaneous          NA          NA
     preeclampsia_epi_analysis
5253 0
5290 0
5391 0
5332 0
5322 0
5247 0

[1]  59 565

In [5]:
fp_saliva$Group <- "First_pregnancy"
fp_saliva$Group

 [1] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
 [5] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
 [9] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[13] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[17] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[21] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[25] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[29] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[33] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[37] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[41] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[45] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[49] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[53] "First_pregnancy" "First_pregnancy" "First_pregnancy" "First_pregnancy"
[57] "First_pregnancy" "First_pregnancy" "First_pregnancy"

In [6]:
sp_saliva$Group <- "Second_pregnancy"
sp_saliva$Group

 [1] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
 [5] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
 [9] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[13] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[17] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[21] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[25] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[29] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[33] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[37] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[41] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[45] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[49] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[53] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"
[57] "Second_pregnancy" "Second_pregnancy" "Second_pregnancy"

In [7]:
combined_fp_sp <- rbind(fp_saliva, sp_saliva)
dim(combined_fp_sp)
head(combined_fp_sp)

[1] 118 566

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5265 Scf5931f     NA         0        0         0
5254 S14e664f     NA         0        0         1
5367 S194e21b     NA         0        0         0
5297 S1a267fa     NA         0        0         0
5300 S30bce16     NA         0        0         0
5208 Sa8397fa     NA         0        0         0
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5265 2018-12-13 P060d440        0                   30          3          ⋯
5254 2018-09-10 P14e664f        0                   30          3          ⋯
5367 2018-11-16 P159f9c8        0                   36          4          ⋯
5297 2019-05-23 P1a267fa        0                   32          3          ⋯
5300 2018-04-18 P1d75300        0                   32          3          ⋯
5208 2018-03-14 P1ef420d        0                   27          2          ⋯
     missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
5265 NA                 NA    1       MISSED ABORTION        NA
5254 NA                 NA   NA       NA                     39
5367 NA                 NA   NA       NA                     41
5297 NA                 NA   NA       NA                     38
5300 NA                 NA   NA       NA                     NA
5208 NA                 NA   NA       NA                     28
     deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
5265 NA                   NA          NA    0
5254 Induction            NA          NA    0
5367 Spontaneous          NA          NA    0
5297 Spontaneous          NA          NA    0
5300 NA                   NA          NA    0
5208 Spontaneous          very_w28_31  1    0
     Group
5265 First_pregnancy
5254 First_pregnancy
5367 First_pregnancy
5297 First_pregnancy
5300 First_pregnancy
5208 First_pregnancy

In [8]:
#combined_fp_sp$Group

In [9]:
# Change the dates into date format
combined_fp_sp$Q1_Date <- as.Date(combined_fp_sp$Q1_Datum)
combined_fp_sp$Q1_Date
class(combined_fp_sp$Q1_Date)

  [1] "2018-12-13" "2018-09-10" "2018-11-16" "2019-05-23" "2018-04-18"
  [6] "2018-03-14" "2018-03-07" "2018-04-10" "2018-04-20" "2019-02-23"
 [11] "2019-03-25" "2019-05-29" "2018-06-23" "2018-02-18" "2018-11-13"
 [16] "2019-07-28" "2019-05-23" "2019-12-04" "2019-03-27" "2018-08-30"
 [21] "2019-01-08" "2018-08-05" "2018-04-03" "2018-08-05" "2019-02-26"
 [26] "2018-07-09" "2018-08-24" "2017-12-08" "2019-01-02" "2019-07-28"
 [31] "2018-08-21" "2019-01-01" "2018-08-14" "2019-04-02" "2018-07-02"
 [36] "2019-06-07" "2018-11-12" "2018-07-03" "2019-12-18" "2018-09-12"
 [41] "2018-11-12" "2018-10-16" "2020-06-02" "2018-08-30" "2018-04-05"
 [46] "2018-03-14" "2018-11-13" "2018-01-31" "2018-08-31" "2018-03-05"
 [51] "2019-01-04" "2019-09-10" "2018-11-13" "2019-06-28" "2017-12-24"
 [56] "2018-02-13" "2018-10-26" "2018-09-29" "2018-12-19" "2019-06-03"
 [61] "2020-08-17" "2021-01-28" "2021-01-06" "2019-05-14" "2020-09-17"
 [66] "2019-01-17" "2020-12-17" "2020-11-04" "2020-01-10" "2020-10-18"
 [71] "2020-10-20" "2019-09-24" "2020-11-03" "2019-07-21" "2020-10-22"
 [76] "2021-01-06" "2021-01-12" "2020-10-10" "2020-11-05" "2020-12-02"
 [81] "2020-07-11" "2020-06-05" "2020-09-26" "2020-04-07" "2020-06-01"
 [86] "2019-11-20" "2020-10-13" "2020-10-21" "2020-02-19" "2020-04-06"
 [91] "2020-10-06" "2020-10-20" "2020-10-22" "2020-06-21" "2020-07-24"
 [96] "2019-09-23" "2019-11-15" "2020-08-25" "2020-10-21" "2021-01-15"
[101] "2019-05-28" "2020-12-27" "2021-01-22" "2020-08-04" "2020-11-25"
[106] "2020-11-09" "2020-05-15" "2020-11-02" "2019-11-08" "2019-07-18"
[111] "2020-08-18" "2020-06-16" "2020-11-03" "2019-11-08" "2019-11-03"
[116] "2020-01-16" "2021-01-28" "2019-08-08"

[1] "Date"

In [10]:
grep("datum", names(combined_fp_sp), value = TRUE)
grep("date", names(combined_fp_sp), value = TRUE)
grep("Datum", names(combined_fp_sp), value = TRUE)

[1] "fodelsedatum_barn"

 [1] "Due_date_fromQ2"
 [2] "Q2_X21_When_is_due_date"
 [3] "Q3_X7_Birthdate"
 [4] "kit1.faecal_sample.datetime_taken"
 [5] "kit1.salival_sample.datetime_taken"
 [6] "kit1.vaginal_sample.datetime_taken"
 [7] "kit2.faecal_sample.datetime_taken"
 [8] "kit2.salival_sample.datetime_taken"
 [9] "kit2.vaginal_sample.datetime_taken"
[10] "kit3.faecal_sample.datetime_taken"
[11] "kit3.infant_faecal_sample.datetime_taken"
[12] "kit3.infant_faecal_sample_2.datetime_taken"
[13] "kit3.salival_sample.datetime_taken"
[14] "kit3.vaginal_sample.datetime_taken"

[1] "Q1_Datum" "Q2_Datum" "Q3_Datum"

In [11]:
combined_fp_sp$Q2_Datum

  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [26] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [51] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [76] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[101] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

In [12]:
combined_fp_sp$Q3_Datum

  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [26] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [51] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
 [76] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
[101] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA

#Since all the dates were missing from the metadata files, extract the dates from an older file and add them to the correct column

In [13]:
metadata_old <- read.csv("/ceph/projects/010_SweMaMi/anusha.antony/Anu_SweMaMi/swemami_04APRIL2024.csv", header = TRUE, row.names = 1)
head(metadata_old)
dim(metadata_old)

  Studienummer Correct_PN age_checked_latest preeclampsia_epi_analysis Prev_RPL
1 S000029d     NA         NA                 0                         0
2 S000751b     NA         NA                 0                         0
3 S0014842     P0014842   31                 0                         0
4 S001892d     NA         NA                 0                         0
5 S0023943     P0023943   30                 0                         0
6 S003b222     NA         NA                 0                         0
  Prev_IUFD Prev_miscarriage_numb Q1_Datum...5        Q1_Personnummer
1 0         0                     2019-11-16 20:39:29 P000029d
2 0         1                     2019-11-15 13:46:18 P000751b
3 0         1                     2018-07-09 09:04:22 P0014842
4 0         0                     2018-03-16 19:51:26 P001892d
5 0         0                     2018-10-02 22:46:06 P0023943
6 0         2                     2020-02-01 11:33:13 P003b222
  Avbruten_graviditet ⋯ fstart    GL_v GL_d diffdays missfall.IUFD_week IUFD
1 No                  ⋯ NA        NA   NA   NA       NA                 NA
2 No                  ⋯ Spontan   38    3    0       NA                 NA
3 NA                  ⋯ Spontan   41    4    0       NA                 NA
4 No                  ⋯ Induktion 41    2    0       NA                 NA
5 NA                  ⋯ Spontan   41    6    0       NA                 NA
6 No                  ⋯ Spontan   40    0    0       NA                 NA
  missfall missfall.IUFD_comments Gest_w_combined deliv_start_combined
1 NA       NA                     39              Induction
2 NA       NA                     38              Spontaneous
3 NA       NA                     41              Spontaneous
4 NA       NA                     41              Induction
5 NA       NA                     41              Spontaneous
6 NA       NA                     40              Spontaneous

[1] 5422  540

In [14]:
# Extract the studynumber that have to be fixed
sn_to_check <- combined_fp_sp |> pull(Studienummer)
length(sn_to_check)
class(sn_to_check)

[1] 118

[1] "character"

In [15]:
class(metadata_old$Q2_Datum)
head(metadata_old$Q2_Datum)

[1] "character"

[1] "2020-02-24 09:18:25" NA                    "2018-12-10 14:17:21"
[4] "2018-07-03 09:29:07" "2018-12-18 15:39:58" "2020-06-07 09:44:35"

In [16]:
# Extract the dates and study number for the studynumbers that have to be fixed
dates_old_Q2 <- metadata_old |> 
    filter(Studienummer %in% sn_to_check) |>
    select(Studienummer, Q2_Datum, kit2.salival_sample.datetime_taken)
head(dates_old_Q2)
dim(dates_old_Q2)

  Studienummer Q2_Datum            kit2.salival_sample.datetime_taken
1 S02c5e39     2020-08-10 09:33:29 2020-08-25
2 S0332ad6     2020-10-19 11:53:32 NA
3 S034bf15     2021-02-22 14:03:25 NA
4 S060d440     2019-09-24 22:47:15 2019-09-28
5 S08dfdeb     2019-08-02 08:37:37 2019-08-27
6 S0a8c1f9     2021-01-07 18:19:08 NA

[1] 118   3

In [17]:
# Extract the dates for the studynumbers that have to be fixed
dates_old_Q3 <- metadata_old |> 
    filter(Studienummer %in% sn_to_check) |>
    select(Studienummer, Q3_Datum, kit3.salival_sample.datetime_taken)
head(dates_old_Q3)
dim(dates_old_Q3)

  Studienummer Q3_Datum            kit3.salival_sample.datetime_taken
1 S02c5e39     2020-12-27 22:56:22 NA
2 S0332ad6     2021-02-15 19:58:39 NA
3 S034bf15     2021-06-14 11:34:01 NA
4 S060d440     2020-01-27 12:43:32 NA
5 S08dfdeb     2019-12-09 11:02:36 2020-01-14
6 S0a8c1f9     2021-05-20 19:07:55 NA

[1] 118   3

In [18]:
# Convert dates into date format and remove time
# This is where the dates missmatch so sort both df with old dates first so they are in the same order as combined_fp_sp
dates_old_Q2_sorted <- dates_old_Q2[
  match(combined_fp_sp$Studienummer, dates_old_Q2$Studienummer),
  ]

#(dates_old_Q2_sorted)

dates_old_Q3_sorted <- dates_old_Q3[
  match(combined_fp_sp$Studienummer, dates_old_Q3$Studienummer),
  ]
#head(dates_old_Q3_sorted)

In [19]:
combined_fp_sp$Q2_date_fixed <- as.Date(substr(dates_old_Q2_sorted$Q2_Datum, 1, nchar(dates_old_Q2_sorted$Q2_Datum) - 9), format = "%Y-%m-%d")
combined_fp_sp$Q2_date_fixed
class(combined_fp_sp$Q2_date_fixed)

  [1] NA           "2019-01-15" "2019-03-10" "2019-08-26" NA
  [6] NA           "2018-07-06" "2018-09-04" NA           NA
 [11] "2019-06-14" "2019-09-05" "2018-10-16" "2018-06-18" NA
 [16] "2019-11-11" "2019-08-02" NA           "2019-08-19" "2018-11-08"
 [21] "2019-05-22" NA           "2018-06-19" "2019-01-25" NA
 [26] "2018-11-15" "2018-12-10" "2018-04-13" "2019-06-11" NA
 [31] "2018-12-18" "2019-04-17" "2018-11-29" "2019-07-25" "2018-10-05"
 [36] NA           NA           "2018-10-16" NA           "2019-01-31"
 [41] "2019-03-25" NA           NA           "2018-12-13" NA
 [46] "2018-06-25" "2019-03-01" NA           "2018-12-18" "2018-06-13"
 [51] NA           NA           "2019-04-13" NA           "2018-04-17"
 [56] "2018-05-03" NA           "2018-12-18" NA           "2019-09-24"
 [61] "2021-01-07" "2021-05-21" "2021-04-12" NA           "2021-02-15"
 [66] "2019-06-07" "2021-04-06" "2021-01-19" "2020-04-28" "2021-02-08"
 [71] "2021-02-15" "2020-01-21" "2021-03-15" "2019-11-04" "2021-02-03"
 [76] "2021-03-15" "2021-06-02" "2021-03-12" "2021-01-26" "2021-05-17"
 [81] NA           "2020-10-19" "2021-01-25" "2020-07-03" "2020-08-10"
 [86] "2020-03-10" "2021-01-25" "2021-03-01" "2020-07-27" "2020-07-27"
 [91] "2021-01-07" "2021-01-25" "2021-02-08" "2020-10-12" "2020-11-16"
 [96] NA           "2020-02-24" "2021-01-07" "2021-02-16" "2021-05-03"
[101] "2019-08-19" "2021-04-12" "2021-05-27" "2021-01-07" "2021-03-15"
[106] "2021-03-22" "2020-09-01" "2021-02-22" NA           "2019-11-04"
[111] "2021-01-18" "2020-10-19" "2021-01-07" "2020-02-17" "2020-02-03"
[116] "2020-04-06" "2021-06-14" NA

[1] "Date"

In [20]:
combined_fp_sp$Studienummer

  [1] "Scf5931f" "S14e664f" "S194e21b" "S1a267fa" "S30bce16" "Sa8397fa"
  [7] "S1f862a6" "S1f95844" "S765e59d" "S3780ac4" "S3c0f6ee" "S2b86cc0"
 [13] "S39fe1d7" "S7e4a963" "S428e1c4" "S71d01ec" "S08dfdeb" "Se6c08fb"
 [19] "S77f6878" "S5fa4a39" "S4eaf499" "S50f102c" "S5b98b6c" "S2b3865e"
 [25] "S6d2ebc4" "S719b21e" "S735d77f" "S7b2ccf8" "S9026714" "S7f1746e"
 [31] "S92b4604" "S97574f9" "S9cdfd5a" "S3a65384" "S7bffefd" "S981aed3"
 [37] "Sb592f2a" "Se5be4e8" "S2703f30" "Sbe04f9f" "S257a907" "Sc10d0b0"
 [43] "Sc3a5016" "S5e8bd2b" "S962e207" "Scb66cdd" "Sc99e873" "Sc9a3575"
 [49] "Sca94a0f" "S445ffbb" "Sd01a0ba" "Sd3b97e6" "Sf92b278" "Se3450d3"
 [55] "S3a71006" "Sed8773b" "Sf573f67" "S7a993ee" "Sb44bd37" "S060d440"
 [61] "Sefe71fe" "S159f9c8" "Sb124b17" "S1d75300" "S1ef420d" "Sa79a719"
 [67] "S0e78496" "S3399626" "Scdb718f" "S5097402" "S3cac7b0" "S3db7da6"
 [73] "S424fd61" "S3e3cfdb" "S42f2c08" "S43d1efc" "S46f36c7" "S4a05456"
 [79] "S4de45e7" "Sb4ca488" "Sa957143" "S0332ad6" "S62ea0b2" "S61c0f74"
 [85] "S02c5e39" "S9deb4a6" "S557ff11" "S7ece52e" "Sa8a8898" "S5a2acf4"
 [91] "Sb242462" "Sc56fd3c" "Sa8747ea" "Sa8f3b51" "Sab443f9" "Sb752955"
 [97] "Sbbb08bd" "Sbdbd455" "Sae324ac" "Sbe289c8" "S7b1a87b" "S651cee0"
[103] "Sc44e366" "Sc75b32a" "Sc77a35c" "S30f0866" "S99e6192" "S034bf15"
[109] "Scd2c0d1" "S1bd074e" "S7b4c3a0" "Sdab1897" "S0a8c1f9" "Se706703"
[115] "Sa303488" "S9d07d7c" "Sfb279f0" "Sff3c644"

In [21]:
is.na(combined_fp_sp$Q2_date_fixed) |> sum()

[1] 27

In [22]:
# Convert dates into date format and remove time
combined_fp_sp$Q3_date_fixed <- as.Date(substr(dates_old_Q3_sorted$Q3_Datum, 1, nchar(dates_old_Q3_sorted$Q3_Datum) - 9), format = "%Y-%m-%d")
combined_fp_sp$Q3_date_fixed
class(combined_fp_sp$Q3_date_fixed)

  [1] NA           "2019-05-16" "2019-07-08" "2020-01-07" NA
  [6] "2018-06-20" "2018-08-22" "2019-01-08" "2018-12-10" "2020-08-31"
 [11] "2019-09-23" "2020-01-07" "2019-02-14" "2018-10-09" "2020-03-30"
 [16] "2020-03-16" "2019-12-09" NA           "2019-12-17" "2019-03-15"
 [21] "2019-09-10" "2019-03-21" "2018-10-25" "2019-05-27" "2020-11-02"
 [26] "2019-03-22" "2019-04-26" "2018-08-04" "2019-10-14" "2020-11-30"
 [31] "2019-04-17" "2019-09-02" "2019-04-12" "2019-12-02" "2019-02-07"
 [36] NA           NA           "2019-03-01" NA           "2019-06-07"
 [41] NA           "2020-01-07" "2021-08-11" "2019-04-12" "2018-11-22"
 [46] "2018-11-08" "2019-06-28" "2018-05-09" "2019-04-16" "2018-10-09"
 [51] "2020-03-16" "2020-01-07" "2019-08-12" NA           "2018-07-13"
 [56] "2018-09-04" "2019-01-25" NA           NA           "2020-01-27"
 [61] "2021-05-03" "2021-10-04" "2021-08-30" "2020-01-20" "2021-06-28"
 [66] "2019-09-23" "2021-08-09" "2021-06-01" NA           "2021-06-21"
 [71] "2021-06-15" "2020-07-22" "2021-08-02" NA           "2021-05-31"
 [76] "2021-07-07" "2021-10-04" "2021-08-23" "2021-05-31" "2021-10-05"
 [81] "2021-02-08" "2021-02-15" "2021-06-07" NA           "2020-12-27"
 [86] "2020-07-06" "2021-05-31" "2021-07-05" NA           "2020-12-07"
 [91] "2021-05-17" "2021-05-31" "2021-06-20" "2021-01-25" "2021-03-22"
 [96] "2020-05-25" "2020-06-30" "2021-04-26" "2021-06-21" "2021-09-13"
[101] NA           NA           "2021-10-01" "2021-06-04" "2021-08-03"
[106] "2021-08-16" "2020-10-19" "2021-06-14" "2020-07-15" NA
[111] "2021-05-17" "2021-02-15" "2021-05-20" "2020-06-30" "2020-06-30"
[116] "2020-08-10" "2021-10-18" "2020-02-24"

[1] "Date"

In [23]:
is.na(combined_fp_sp$Q3_date_fixed) |> sum()

[1] 17

# Check that dates are correct

In [24]:
# Check that dates seem correct manually

head(combined_fp_sp$Q2_date_fixed)
head(combined_fp_sp$Studienummer)

metadata_old |> filter(Studienummer == "Scf5931f") |> select(Q2_Datum) 
metadata_old |> filter(Studienummer == "S14e664f") |> select(Q2_Datum) 
metadata_old |> filter(Studienummer == "S194e21b") |> select(Q2_Datum)

[1] NA           "2019-01-15" "2019-03-10" "2019-08-26" NA
[6] NA

[1] "Scf5931f" "S14e664f" "S194e21b" "S1a267fa" "S30bce16" "Sa8397fa"

  Q2_Datum
1 NA

  Q2_Datum
1 2019-01-15 07:10:40

  Q2_Datum
1 2019-03-10 14:02:23

# Extract columns of intrest

In [25]:
# Check for missmatches

mismatches <- combined_fp_sp |>
  select(Studienummer, Q2_date_fixed) |>
  left_join(
    metadata_old |> select(Studienummer, Q2_Datum),
    by = "Studienummer",
    suffix = c("_fp_sp", "_old")
  ) |>
  filter(Q2_date_fixed != Q2_Datum)
mismatches

     Studienummer Q2_date_fixed Q2_Datum

In [26]:
# Df for manual check missmatches
date_check_old <- metadata_old |> filter(Studienummer %in% sn_to_check) |> select(Studienummer, Q2_Datum, kit2.salival_sample.datetime_taken, Q3_Datum, kit3.salival_sample.datetime_taken)
dim(date_check_old)
#date_check_old

[1] 118   5

In [27]:
date_check_combined <- combined_fp_sp |> filter(Studienummer %in% sn_to_check) |> select(Studienummer, Q2_date_fixed, Q3_date_fixed )
dim(date_check_combined)
#date_check_combined

[1] 118   3

In [28]:
# Sort date_check_combined based on studienummer order in date_check_combined
date_check_combined_sorted <- date_check_combined[
  match(date_check_old$Studienummer, date_check_combined$Studienummer),
  ]

In [29]:
# Create df for manual check of dates
merged_date_check <- cbind(date_check_old, date_check_combined_sorted)
head(merged_date_check)

    Studienummer Q2_Datum            kit2.salival_sample.datetime_taken
85  S02c5e39     2020-08-10 09:33:29 2020-08-25
82  S0332ad6     2020-10-19 11:53:32 NA
108 S034bf15     2021-02-22 14:03:25 NA
60  S060d440     2019-09-24 22:47:15 2019-09-28
17  S08dfdeb     2019-08-02 08:37:37 2019-08-27
113 S0a8c1f9     2021-01-07 18:19:08 NA
    Q3_Datum            kit3.salival_sample.datetime_taken Studienummer
85  2020-12-27 22:56:22 NA                                 S02c5e39
82  2021-02-15 19:58:39 NA                                 S0332ad6
108 2021-06-14 11:34:01 NA                                 S034bf15
60  2020-01-27 12:43:32 NA                                 S060d440
17  2019-12-09 11:02:36 2020-01-14                         S08dfdeb
113 2021-05-20 19:07:55 NA                                 S0a8c1f9
    Q2_date_fixed Q3_date_fixed
85  2020-08-10    2020-12-27
82  2020-10-19    2021-02-15
108 2021-02-22    2021-06-14
60  2019-09-24    2020-01-27
17  2019-08-02    2019-12-09
113 2021-01-07    2021-05-20

In [30]:
# Extract additional variables of interest and add them to a new data frame
combined_fixed_date <- date_check_combined_sorted

In [31]:
grep("kit2", names(combined_fp_sp), value = TRUE)

[1] "kit2.faecal_sample.barcode"         "kit2.salival_sample.barcode"
[3] "kit2.vaginal_sample.barcode"        "kit2.faecal_sample.datetime_taken"
[5] "kit2.salival_sample.datetime_taken" "kit2.vaginal_sample.datetime_taken"

In [32]:
combined_variables <- combined_fp_sp |> 
    filter(Studienummer %in% sn_to_check) |>
    select(Studienummer, Q1_Personnummer, Q1_Datum, kit1.salival_sample.datetime_taken )
head(combined_variables)
dim(combined_variables)

  Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
1 Scf5931f     P060d440        2018-12-13 2018-12-24
2 S14e664f     P14e664f        2018-09-10 2018-10-19
3 S194e21b     P159f9c8        2018-11-16 2018-11-25
4 S1a267fa     P1a267fa        2019-05-23 2019-06-17
5 S30bce16     P1d75300        2018-04-18 2018-06-08
6 Sa8397fa     P1ef420d        2018-03-14 2018-03-25

[1] 118   4

In [33]:
combined_variables_sorted <- combined_variables[
  match(date_check_combined_sorted$Studienummer, combined_variables$Studienummer),
  ]
head(combined_variables_sorted)

    Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
85  S02c5e39     P719b21e        2020-06-01 2020-06-05
82  S0332ad6     P5b98b6c        2020-06-05 2020-08-03
108 S034bf15     Pca94a0f        2020-11-02 2020-11-10
60  S060d440     P060d440        2019-06-03 2019-06-22
17  S08dfdeb     P43d1efc        2019-05-23 2019-06-04
113 S0a8c1f9     Pe3450d3        2020-11-03 2020-11-07

In [34]:
# Create new data frame with all variables of interest

combined_date <- left_join(date_check_combined_sorted, combined_variables_sorted, by = "Studienummer")
#combined_date <- cbind(combined_variables_sorted, date_check_combined_sorted) |> select(Studienummer, Q1_Personnummer, Q1_Datum,kit1.salival_sample.datetime_taken, Q2_date_fixed, 
 #                                                                            kit2.salival_sample.datetime_taken, Q3_date_fixed, kit3.salival_sample.datetime_taken)
head(combined_date)

  Studienummer Q2_date_fixed Q3_date_fixed Q1_Personnummer Q1_Datum
1 S02c5e39     2020-08-10    2020-12-27    P719b21e        2020-06-01
2 S0332ad6     2020-10-19    2021-02-15    P5b98b6c        2020-06-05
3 S034bf15     2021-02-22    2021-06-14    Pca94a0f        2020-11-02
4 S060d440     2019-09-24    2020-01-27    P060d440        2019-06-03
5 S08dfdeb     2019-08-02    2019-12-09    P43d1efc        2019-05-23
6 S0a8c1f9     2021-01-07    2021-05-20    Pe3450d3        2020-11-03
  kit1.salival_sample.datetime_taken
1 2020-06-05
2 2020-08-03
3 2020-11-10
4 2019-06-22
5 2019-06-04
6 2020-11-07

In [35]:
# Since dates were also missing from the kits add them aswell from the sorted merged data frame
combined_date$kit2.salival_sample.datetime_taken <- merged_date_check$kit2.salival_sample.datetime_taken
combined_date$kit3.salival_sample.datetime_taken <- merged_date_check$kit3.salival_sample.datetime_taken
head(combined_date)

  Studienummer Q2_date_fixed Q3_date_fixed Q1_Personnummer Q1_Datum
1 S02c5e39     2020-08-10    2020-12-27    P719b21e        2020-06-01
2 S0332ad6     2020-10-19    2021-02-15    P5b98b6c        2020-06-05
3 S034bf15     2021-02-22    2021-06-14    Pca94a0f        2020-11-02
4 S060d440     2019-09-24    2020-01-27    P060d440        2019-06-03
5 S08dfdeb     2019-08-02    2019-12-09    P43d1efc        2019-05-23
6 S0a8c1f9     2021-01-07    2021-05-20    Pe3450d3        2020-11-03
  kit1.salival_sample.datetime_taken kit2.salival_sample.datetime_taken
1 2020-06-05                         2020-08-25
2 2020-08-03                         NA
3 2020-11-10                         NA
4 2019-06-22                         2019-09-28
5 2019-06-04                         2019-08-27
6 2020-11-07                         NA
  kit3.salival_sample.datetime_taken
1 NA
2 NA
3 NA
4 NA
5 2020-01-14
6 NA

In [36]:
# Sort the columns
combined_date <- combined_date |> select(Studienummer, Q1_Personnummer, Q1_Datum, kit1.salival_sample.datetime_taken, Q2_date_fixed, kit2.salival_sample.datetime_taken, Q3_date_fixed, kit3.salival_sample.datetime_taken)
head(combined_date)

  Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
1 S02c5e39     P719b21e        2020-06-01 2020-06-05
2 S0332ad6     P5b98b6c        2020-06-05 2020-08-03
3 S034bf15     Pca94a0f        2020-11-02 2020-11-10
4 S060d440     P060d440        2019-06-03 2019-06-22
5 S08dfdeb     P43d1efc        2019-05-23 2019-06-04
6 S0a8c1f9     Pe3450d3        2020-11-03 2020-11-07
  Q2_date_fixed kit2.salival_sample.datetime_taken Q3_date_fixed
1 2020-08-10    2020-08-25                         2020-12-27
2 2020-10-19    NA                                 2021-02-15
3 2021-02-22    NA                                 2021-06-14
4 2019-09-24    2019-09-28                         2020-01-27
5 2019-08-02    2019-08-27                         2019-12-09
6 2021-01-07    NA                                 2021-05-20
  kit3.salival_sample.datetime_taken
1 NA
2 NA
3 NA
4 NA
5 2020-01-14
6 NA

## Calculating difference ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [37]:
# Calculate difference

In [38]:
combined_date$Q1_Datum <- as.Date(combined_date$Q1_Datum)
combined_date$kit1.salival_sample.datetime_taken <- as.Date(combined_date$kit1.salival_sample.datetime_taken)
combined_date$kit2.salival_sample.datetime_taken <- as.Date(combined_date$kit2.salival_sample.datetime_taken)
combined_date$kit3.salival_sample.datetime_taken <- as.Date(combined_date$kit3.salival_sample.datetime_taken)
head(combined_date)

  Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
1 S02c5e39     P719b21e        2020-06-01 2020-06-05
2 S0332ad6     P5b98b6c        2020-06-05 2020-08-03
3 S034bf15     Pca94a0f        2020-11-02 2020-11-10
4 S060d440     P060d440        2019-06-03 2019-06-22
5 S08dfdeb     P43d1efc        2019-05-23 2019-06-04
6 S0a8c1f9     Pe3450d3        2020-11-03 2020-11-07
  Q2_date_fixed kit2.salival_sample.datetime_taken Q3_date_fixed
1 2020-08-10    2020-08-25                         2020-12-27
2 2020-10-19    <NA>                               2021-02-15
3 2021-02-22    <NA>                               2021-06-14
4 2019-09-24    2019-09-28                         2020-01-27
5 2019-08-02    2019-08-27                         2019-12-09
6 2021-01-07    <NA>                               2021-05-20
  kit3.salival_sample.datetime_taken
1 <NA>
2 <NA>
3 <NA>
4 <NA>
5 2020-01-14
6 <NA>

In [39]:
combined_date$diff_q1_kit1 <- as.integer(difftime(combined_date$kit1.salival_sample.datetime_taken, combined_date$Q1_Datum, units ="days"))
combined_date$diff_q2_kit2 <- as.integer(difftime(combined_date$kit2.salival_sample.datetime_taken, combined_date$Q2_date_fixed, units ="days"))
combined_date$diff_q3_kit3 <- as.integer(difftime(combined_date$kit3.salival_sample.datetime_taken, combined_date$Q3_date_fixed, units ="days"))

head(combined_date)

  Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
1 S02c5e39     P719b21e        2020-06-01 2020-06-05
2 S0332ad6     P5b98b6c        2020-06-05 2020-08-03
3 S034bf15     Pca94a0f        2020-11-02 2020-11-10
4 S060d440     P060d440        2019-06-03 2019-06-22
5 S08dfdeb     P43d1efc        2019-05-23 2019-06-04
6 S0a8c1f9     Pe3450d3        2020-11-03 2020-11-07
  Q2_date_fixed kit2.salival_sample.datetime_taken Q3_date_fixed
1 2020-08-10    2020-08-25                         2020-12-27
2 2020-10-19    <NA>                               2021-02-15
3 2021-02-22    <NA>                               2021-06-14
4 2019-09-24    2019-09-28                         2020-01-27
5 2019-08-02    2019-08-27                         2019-12-09
6 2021-01-07    <NA>                               2021-05-20
  kit3.salival_sample.datetime_taken diff_q1_kit1 diff_q2_kit2 diff_q3_kit3
1 <NA>                                4           15           NA
2 <NA>                               59           NA           NA
3 <NA>                                8           NA           NA
4 <NA>                               19            4           NA
5 2020-01-14                         12           25           36
6 <NA>                                4           NA           NA

In [40]:
combined_date

    Studienummer Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken
1   S02c5e39     P719b21e        2020-06-01 2020-06-05
2   S0332ad6     P5b98b6c        2020-06-05 2020-08-03
3   S034bf15     Pca94a0f        2020-11-02 2020-11-10
4   S060d440     P060d440        2019-06-03 2019-06-22
5   S08dfdeb     P43d1efc        2019-05-23 2019-06-04
6   S0a8c1f9     Pe3450d3        2020-11-03 2020-11-07
7   S0e78496     P1f95844        2020-12-17 2021-02-06
8   S14e664f     P14e664f        2018-09-10 2018-10-19
9   S159f9c8     P159f9c8        2021-01-28 2021-02-18
10  S194e21b     P159f9c8        2018-11-16 2018-11-25
11  S1a267fa     P1a267fa        2019-05-23 2019-06-17
12  S1bd074e     Pd01a0ba        2019-07-18 2019-07-25
13  S1d75300     P1d75300        2019-05-14 2019-07-17
14  S1ef420d     P1ef420d        2020-09-17 2020-10-30
15  S1f862a6     P1f862a6        2018-03-07 2018-04-17
16  S1f95844     P1f95844        2018-04-10 2018-06-11
17  S257a907     Pbe289c8        2018-11-12 2018-11-17
18  S2703f30     Pbdbd455        2019-12-18 2020-02-04
19  S2b3865e     P62ea0b2        2018-08-05 2018-10-19
20  S2b86cc0     P3cac7b0        2019-05-29 2019-06-15
21  S30bce16     P1d75300        2018-04-18 2018-06-08
22  S30f0866     Pc99e873        2020-11-09 2020-12-03
23  S3399626     P3399626        2020-11-04 2020-11-15
24  S3780ac4     P3780ac4        2019-02-23 2019-03-18
25  S39fe1d7     P3db7da6        2018-06-23 2018-08-12
26  S3a65384     Pa8747ea        2019-04-02 2019-04-17
27  S3a71006     Pe706703        2017-12-24 2018-01-21
28  S3c0f6ee     P3c0f6ee        2019-03-25 2019-03-28
29  S3cac7b0     P3cac7b0        2020-10-20 2020-10-29
30  S3db7da6     P3db7da6        2019-09-24 2019-10-07
⋮   ⋮            ⋮               ⋮          ⋮
89  Sbbb08bd     Pbbb08bd        2019-11-15 2019-12-04
90  Sbdbd455     Pbdbd455        2020-08-25 2020-09-18
91  Sbe04f9f     Pbe04f9f        2018-09-12 2018-10-15
92  Sbe289c8     Pbe289c8        2021-01-15 2021-01-31
93  Sc10d0b0     Pc10d0b0        2018-10-16 2018-11-20
94  Sc3a5016     Pc3a5016        2020-06-02 2020-06-14
95  Sc44e366     Pc44e366        2021-01-22 2021-02-26
96  Sc56fd3c     P9cdfd5a        2020-10-20 2020-10-29
97  Sc75b32a     Pc75b32a        2020-08-04 2020-09-19
98  Sc77a35c     Pc77a35c        2020-11-25 2020-12-09
99  Sc99e873     Pc99e873        2018-11-13 2018-12-08
100 Sc9a3575     Pc9a3575        2018-01-31 2018-02-13
101 Sca94a0f     Pca94a0f        2018-08-31 2018-09-20
102 Scb66cdd     Pc77a35c        2018-03-14 2018-03-29
103 Scd2c0d1     Pcd2c0d1        2019-11-08 2019-11-22
104 Scdb718f     P3780ac4        2020-01-10 2020-02-04
105 Scf5931f     P060d440        2018-12-13 2018-12-24
106 Sd01a0ba     Pd01a0ba        2019-01-04 2019-01-18
107 Sd3b97e6     Pd3b97e6        2019-09-10 2019-09-17
108 Sdab1897     Pdab1897        2020-06-16 2020-08-07
109 Se3450d3     Pe3450d3        2019-06-28 2020-11-11
110 Se5be4e8     Pbbb08bd        2018-07-03 2018-08-13
111 Se6c08fb     P46f36c7        2019-12-04 2019-12-18
112 Se706703     Pe706703        2019-11-08 2019-12-01
113 Sed8773b     Ped8773b        2018-02-13 2018-02-20
114 Sefe71fe     P14e664f        2020-08-17 2020-09-07
115 Sf573f67     Pf573f67        2018-10-26 2018-12-01
116 Sf92b278     Pdab1897        2018-11-13 2018-12-12
117 Sfb279f0     Pfb279f0        2021-01-28 <NA>
118 Sff3c644     Pff3c644        2019-08-08 2019-08-13
    Q2_date_fixed kit2.salival_sample.datetime_taken Q3_date_fixed
1   2020-08-10    2020-08-25                         2020-12-27
2   2020-10-19    <NA>                               2021-02-15
3   2021-02-22    <NA>                               2021-06-14
4   2019-09-24    2019-09-28                         2020-01-27
5   2019-08-02    2019-08-27                         2019-12-09
6   2021-01-07    <NA>                               2021-05-20
7   2021-04-06    <NA>                               2021-08-09
8   2019-01-15    2019-01-21                         2019-05-16
9   2021-05-21    <NA>                               2021-10-04
10  2019-03-10    2019-03-17                         2019-07-08
11  2019-08-26    2019-09-01                         2020-01-07
12  2019-11-04    <NA>                               <NA>
13  <NA>          2019-09-22                         2020-01-20
14  2021-02-15    <NA>                               2021-06-28
15  2018-07-06    2018-08-01                         2018-08-22
16  2018-09-04    2018-09-21                         2019-01-08
17  2019-03-25    2019-04-08                         <NA>
18  <NA>          <NA>                               <NA>
19  2019-01-25    2019-02-14                         2019-05-27
20  2019-09-05    2019-09-10                         2020-01-07
21  <NA>          <NA>                               <NA>
22  2021-03-22    <NA>                               2021-08-16
23  2021-01-19    <NA>                               2021-06-01
24  <NA>          2020-05-07                         2020-08-31
25  2018-10-16    2018-11-01                         2019-02-14
26  2019-07-25    2019-08-12                         2019-12-02
27  2018-04-17    2018-04-25                         2018-07-13
28  2019-06-14    2019-07-17                         2019-09-23
29  2021-02-15    <NA>                               2021-06-15
30  2020-01-21    2020-02-07                         2020-07-22
⋮   ⋮             ⋮                                  ⋮
89  2020-02-24    2020-03-24                         2020-06-30
90  2021-01-07    <NA>                               2021-04-26
91  2019-01-31    2019-02-16                         2019-06-07
92  2021-05-03    <NA>                               2021-09-13
93  <NA>          2019-08-26                         2020-01-07
94  <NA>          <NA>                               2021-08-11
95  2021-05-27    <NA>                               2021-10-01
96  2021-01-25    <NA>                               2021-05-31
97  2021-01-07    <NA>                               2021-06-04
98  2021-03-15    <NA>                               2021-08-03
99  2019-03-01    2019-03-13                         2019-06-28
100 <NA>          <NA>                               2018-05-09
101 2018-12-18    2018-12-28                         2019-04-16
102 2018-06-25    2018-07-07                         2018-11-08
103 <NA>          2020-03-19                         2020-07-15
104 2020-04-28    <NA>                               <NA>
105 <NA>          <NA>                               <NA>
106 <NA>          2019-11-26                         2020-03-16
107 <NA>          <NA>                               2020-01-07
108 2020-10-19    <NA>                               2021-02-15
109 <NA>          <NA>                               <NA>
110 2018-10-16    2018-10-30                         2019-03-01
111 <NA>          <NA>                               <NA>
112 2020-02-17    2020-02-20                         2020-06-30
113 2018-05-03    2018-05-12                         2018-09-04
114 2021-01-07    <NA>                               2021-05-03
115 <NA>          <NA>                               2019-01-25
116 2019-04-13    2019-04-19                         2019-08-12
117 2021-06-14    <NA>                               2021-10-18
118 <NA>          2019-11-02                         2020-02-24
    kit3.salival_sample.datetime_taken diff_q1_kit1 diff_q2_kit2 diff_q3_kit3
1   <NA>                                4           15           NA
2   <NA>                               59           NA           NA
3   <NA>                                8           NA           NA
4   <NA>                               19            4           NA
5   2020-01-14                         12           25           36
6   <NA>                                4           NA           NA
7   <NA>                               51           NA           NA
8   2019-06-07                         39            6           22
9   <NA>                               21           NA           NA
10  2019-07-30                          9            7           22
11  2020-01-12                         25            6            5
12  <NA>                                7           NA           NA
13  <NA>                               64           NA           NA
14  <NA>                               43           NA           NA
15  2018-09-09                         41           26           18
16  2019-01-16                         62           17            8
17  <NA>                                5           14           NA
18  <NA>                               48           NA           NA
19  2019-06-11                         75           20           15
20  2020-01-15                         17            5            8
21  <NA>                               51           NA           NA
22  <NA>                               24           NA           NA
23  <NA>                               11           NA           NA
24  2020-09-07                         23           NA            7
25  2019-03-12                         50           16           26
26  2019-12-16                         15           18           14
27  2018-08-22                         28            8           40
28  2019-11-16                          3           33           54
29  <NA>                                9           NA           NA
30  <NA>                               13           17           NA
⋮   ⋮                                  ⋮            ⋮            ⋮
89  <NA>                                19          29            NA
90  <NA>                                24          NA            NA
91  2019-06-27                          33          16            20
92  <NA>                                16          NA            NA
93  <NA>                                35          NA            NA
94  <NA>                                12          NA            NA
95  <NA>                                35          NA            NA
96  <NA>                                 9          NA            NA
97  <NA>                                46          NA            NA
98  <NA>                                14          NA            NA
99  2019-07-15                          25          12            17
100 <NA>                                13          NA            NA
101 2019-05-09                          20          10            23
102 2018-11-19                          15          12            11
103 2020-07-31                          14          NA            16
104 <NA>                                25          NA            NA
105 <NA>                                11          NA            NA
106 2020-03-29                          14          NA            13
107 <NA>                                 7          NA            NA
108 <NA>                                52          NA            NA
109 <NA>                               502          NA            NA
110 2019-04-03                          41          14            33
111 <NA>                                14          NA            NA
112 <NA>                                23           3            NA
113 2018-09-28                           7           9            24
114 <NA>                                21          NA            NA
115 2019-06-02                          36          NA           128
116 2019-08-22                          29           6            10
117 <NA>                                NA          NA            NA
118 2020-02-25                           5          NA             1

In [45]:
grep("Datum", names(metadata_old), value = TRUE)

[1] "Q1_Datum...5"  "Q1_Datum...23" "Q2_Datum"      "Q3_Datum"

In [51]:
metadata_old |> filter(Studienummer == "Se3450d3") |> select(Q1_Personnummer, Q1_Datum...5, kit1.salival_sample.datetime_taken, Q2_Datum, kit2.salival_sample.datetime_taken, Q3_Datum, kit3.salival_sample.datetime_taken, Q1_Personnummer)
combined_fp_sp |> filter(Studienummer == "Se3450d3") |> select(Q1_Personnummer, Q1_Datum, kit1.salival_sample.datetime_taken, Q2_Datum, kit2.salival_sample.datetime_taken, Q3_Datum, kit3.salival_sample.datetime_taken)

  Q1_Personnummer Q1_Datum...5        kit1.salival_sample.datetime_taken
1 Pe3450d3        2019-06-28 15:53:16 2020-11-11
  Q2_Datum kit2.salival_sample.datetime_taken Q3_Datum
1 NA       NA                                 NA
  kit3.salival_sample.datetime_taken
1 NA

  Q1_Personnummer Q1_Datum   kit1.salival_sample.datetime_taken Q2_Datum
1 Pe3450d3        2019-06-28 2020-11-11                         NA
  kit2.salival_sample.datetime_taken Q3_Datum
1 NA                                 NA
  kit3.salival_sample.datetime_taken
1 NA

In [55]:
metadata_old |> filter(Q1_Personnummer == "Pe3450d3") |> select(Studienummer, Q1_Datum...5, kit1.salival_sample.datetime_taken, Q2_Datum, kit2.salival_sample.datetime_taken, Q3_Datum, kit3.salival_sample.datetime_taken, Q1_Personnummer)
combined_fp_sp |> filter(Q1_Personnummer == "Pe3450d3") |> select(Studienummer, Q1_Datum, kit1.salival_sample.datetime_taken, Q2_Datum, kit2.salival_sample.datetime_taken, Q3_Datum, kit3.salival_sample.datetime_taken, Q1_Personnummer)

  Studienummer Q1_Datum...5        kit1.salival_sample.datetime_taken
1 S0a8c1f9     2020-11-03 14:50:05 2020-11-07
2 Se3450d3     2019-06-28 15:53:16 2020-11-11
  Q2_Datum            kit2.salival_sample.datetime_taken Q3_Datum
1 2021-01-07 18:19:08 NA                                 2021-05-20 19:07:55
2 NA                  NA                                 NA
  kit3.salival_sample.datetime_taken Q1_Personnummer
1 NA                                 Pe3450d3
2 NA                                 Pe3450d3

  Studienummer Q1_Datum   kit1.salival_sample.datetime_taken Q2_Datum
1 Se3450d3     2019-06-28 2020-11-11                         NA
2 S0a8c1f9     2020-11-03 2020-11-07                         NA
  kit2.salival_sample.datetime_taken Q3_Datum
1 NA                                 NA
2 NA                                 NA
  kit3.salival_sample.datetime_taken Q1_Personnummer
1 NA                                 Pe3450d3
2 NA                                 Pe3450d3

# Here I don't understand what I'm supposed to do further
date_2p <- combined_date %>%
 filter((Q1_Q2_time_diff <= 175 & Q1_Q2_time_diff > 0 | is.na(Q1_Q2_time_diff)) &
     (Q2_Q3_time_diff <= 180 & Q2_Q3_time_diff > 0 | is.na(Q2_Q3_time_diff)) &
     (Q1_kit1_days <= 140 & Q1_kit1_days > 0 | is.na(Q1_kit1_days)))
dim(date_2p)
head(date_2p)