#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_drop_na_kit1
# Date: 2025.10.02
# Programmer: Barbara Nowak
# Purpose: Drop missing saliva samples in kit1, check that Primiparous = TRUE (nulliparous), and write to separate files
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## File reading============================================================================================================================================================

saliva_samples <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/data/saliva_samples_250923.csv", header = TRUE)
dim(saliva_samples)
head(saliva_samples)

In [3]:
fp_saliva <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_fp_.csv", header = TRUE, row.names = 1)
head(fp_saliva)
dim(fp_saliva)

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5265 Scf5931f     NA         0        0         0
5254 S14e664f     NA         0        0         1
5367 S194e21b     NA         0        0         0
5297 S1a267fa     NA         0        0         0
5300 S30bce16     NA         0        0         0
5208 Sa8397fa     NA         0        0         0
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5265 2018-12-13 P060d440        0                   30          3          ⋯
5254 2018-09-10 P14e664f        0                   30          3          ⋯
5367 2018-11-16 P159f9c8        0                   36          4          ⋯
5297 2019-05-23 P1a267fa        0                   32          3          ⋯
5300 2018-04-18 P1d75300        0                   32          3          ⋯
5208 2018-03-14 P1ef420d        0                   27          2          ⋯
     diffdays missfall.IUFD_week IUFD missfall missfall.IUFD_comments
5265 NA       NA                 NA    1       MISSED ABORTION
5254  0       NA                 NA   NA       NA
5367  0       NA                 NA   NA       NA
5297  0       NA                 NA   NA       NA
5300 NA       NA                 NA   NA       NA
5208  0       NA                 NA   NA       NA
     Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
5265 NA              NA                   NA          NA
5254 39              Induction            NA          NA
5367 41              Spontaneous          NA          NA
5297 38              Spontaneous          NA          NA
5300 NA              NA                   NA          NA
5208 28              Spontaneous          very_w28_31  1
     preeclampsia_epi_analysis
5265 0
5254 0
5367 0
5297 0
5300 0
5208 0

[1]  59 565

In [4]:
sp_saliva <- read.csv("/ceph/projects//010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_sp_.csv", header = TRUE, row.names = 1)
head(sp_saliva)
dim(sp_saliva)

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5253 S060d440     NA         0        0         1
5290 Sefe71fe     NA         0        0         1
5391 S159f9c8     NA         0        0         0
5332 Sb124b17     NA         0        0         2
5322 S1d75300     NA         0        0         0
5247 S1ef420d     NA         0        0         1
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5253 2019-06-03 P060d440        0                   30          3          ⋯
5290 2020-08-17 P14e664f        0                   32          3          ⋯
5391 2021-01-28 P159f9c8        0                   38          4          ⋯
5332 2021-01-06 P1a267fa        0                   34          3          ⋯
5322 2019-05-14 P1d75300        0                   33          3          ⋯
5247 2020-09-17 P1ef420d        0                   30          3          ⋯
     diffdays missfall.IUFD_week IUFD missfall missfall.IUFD_comments
5253  0       NA                 NA   NA       NA
5290  0       NA                 NA   NA       NA
5391  0       NA                 NA   NA       NA
5332  0       NA                 NA   NA       NA
5322 NA       NA                 NA   NA       NA
5247  0       NA                 NA   NA       NA
     Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
5253 38              Unlaboured c-section NA          NA
5290 39              Spontaneous          NA          NA
5391 40              Spontaneous          NA          NA
5332 41              Spontaneous          NA          NA
5322 41              Induction            NA          NA
5247 40              Spontaneous          NA          NA
     preeclampsia_epi_analysis
5253 0
5290 0
5391 0
5332 0
5322 0
5247 0

[1]  59 565

In [5]:
#sp_saliva |> filter(is.na(kit1.salival_sample.barcode))
sp_saliva$kit2.salival_sample.barcode

 [1] 17683    NA    NA    NA 16603    NA 15399    NA    NA 18117    NA    NA
[13] 17232    NA 17360    NA    NA    NA    NA    NA    NA    NA    NA    NA
[25] 17856 19335 18192    NA    NA 20042 20183    NA    NA    NA    NA 23815
[37] 21521 21481    NA    NA    NA 16762    NA    NA    NA    NA    NA    NA
[49]    NA 17263 17491    NA    NA    NA 19613 19539 19008    NA 19677

In [6]:
grep("kit", names(fp_saliva), value = TRUE)

 [1] "kit1.faecal_sample.barcode"
 [2] "kit2.faecal_sample.barcode"
 [3] "kit3.faecal_sample.barcode"
 [4] "kit3.infant_faecal_sample.barcode"
 [5] "kit3.infant_faecal_sample_2.barcode"
 [6] "kit3.salival_sample.barcode"
 [7] "kit1.salival_sample.barcode"
 [8] "kit1.vaginal_sample.barcode"
 [9] "kit1.faecal_sample.datetime_taken"
[10] "kit1.salival_sample.datetime_taken"
[11] "kit1.vaginal_sample.datetime_taken"
[12] "kit2.salival_sample.barcode"
[13] "kit2.vaginal_sample.barcode"
[14] "kit2.faecal_sample.datetime_taken"
[15] "kit2.salival_sample.datetime_taken"
[16] "kit2.vaginal_sample.datetime_taken"
[17] "kit3.vaginal_sample.barcode"
[18] "kit3.faecal_sample.datetime_taken"
[19] "kit3.infant_faecal_sample.datetime_taken"
[20] "kit3.infant_faecal_sample_2.datetime_taken"
[21] "kit3.salival_sample.datetime_taken"
[22] "kit3.vaginal_sample.datetime_taken"

## Kit1-------------------------------------------------------------------------------------------------------------------------------------------------------------

In [7]:
# Find pn where kit1_saiva is missing
pn_fp_tp1 <- fp_saliva |>
  filter(is.na(kit1.salival_sample.barcode)) |>
  pull(Q1_Personnummer)
pn_fp_tp1
length(pn_fp_tp1)

[1] "P159f9c8" "P428e1c4" "Pc10d0b0" "Pc99e873"

[1] 4

In [8]:
pn_sp_tp1 <- sp_saliva |>
    filter(is.na(kit1.salival_sample.barcode)) |>
    pull(Q1_Personnummer)
pn_sp_tp1
length(pn_sp_tp1)

 [1] "P159f9c8" "P1a267fa" "P1ef420d" "P1f95844" "P3c0f6ee" "P3cac7b0"
 [7] "P42f2c08" "P43d1efc" "P46f36c7" "P4a05456" "P4eaf499" "P62ea0b2"
[13] "P7b2ccf8" "P97574f9" "P9cdfd5a" "Pa8747ea" "Pbdbd455" "Pbe04f9f"
[19] "Pbe289c8" "Pc3a5016" "Pc44e366" "Pc75b32a" "Pd3b97e6" "Pfb279f0"

[1] 24

In [10]:
# combine participants to drop
drop_pn_combined <- c(pn_fp_tp1, pn_sp_tp1)
unique(drop_pn_combined) |> length()

[1] 27

# Remove participants with missing TP1 faecal samples
# If the barcode is missing in either fp or sp, both entries are dropped.

In [38]:
fp_tp1_saliva <- fp_saliva |>
    filter(!(Q1_Personnummer %in% drop_pn_combined))
head(fp_tp1_saliva)
dim(fp_tp1_saliva)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Scf5931f     NA         0        0         0                     2018-12-13
2 S14e664f     NA         0        0         1                     2018-09-10
3 S30bce16     NA         0        0         0                     2018-04-18
4 S1f862a6     NA         0        0         0                     2018-03-07
5 S765e59d     NA         0        0         1                     2018-04-20
6 S3780ac4     NA         0        0         0                     2019-02-23
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P060d440        0                   30          3          ⋯ NA
2 P14e664f        0                   30          3          ⋯  0
3 P1d75300        0                   32          3          ⋯ NA
4 P1f862a6        0                   32          3          ⋯  0
5 P3399626        0                   36          4          ⋯  0
6 P3780ac4        0                   38          4          ⋯ NA
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     NA
4 NA                 NA   NA       NA                     31
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     NA
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 NA                   NA          NA    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          NA          NA    0
6 NA                   NA          NA    0

[1]  32 565

In [39]:
sp_tp1_saliva <- sp_saliva |>
    filter(!(Q1_Personnummer %in% drop_pn_combined))
head(sp_tp1_saliva)
dim(sp_tp1_saliva)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S060d440     NA         0        0         1                     2019-06-03
2 Sefe71fe     NA         0        0         1                     2020-08-17
3 S1d75300     NA         0        0         0                     2019-05-14
4 Sa79a719     NA         0        0         1                     2019-01-17
5 S3399626     NA         0        0         1                     2020-11-04
6 Scdb718f     NA         0        0         1                     2020-01-10
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P060d440        0                   30          3          ⋯  0
2 P14e664f        0                   32          3          ⋯  0
3 P1d75300        0                   33          3          ⋯ NA
4 P1f862a6        0                   32          3          ⋯  0
5 P3399626        0                   38          4          ⋯  0
6 P3780ac4        1                   38          4          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0

[1]  32 565

In [40]:
# Write to file
#write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_filtered/", Sys.Date(), "_combined_fp_sp_tp2", ".csv"), sep = ",", row.names = FALSE)

## Missing birthweight drop ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [41]:
# Find fp women where birth date of child is missing
# Why did we do this? oR why would the weight be missing?
pn_fp_missing_birthdate <- fp_tp1_saliva |>
  filter(is.na(fodelsedatum_barn)) |>
  pull(Q1_Personnummer)
pn_fp_missing_birthdate

 [1] "P060d440" "P1d75300" "P3780ac4" "P6d2ebc4" "P7f1746e" "Pab443f9"
 [7] "Pb752955" "Pc9a3575" "Pd01a0ba" "Pe3450d3" "Pf573f67" "Pff3c644"

In [42]:
# Find women where birth weight is missing
grep("weight", names(fp_tp1_saliva), value = TRUE)
pn_fp_missing_birthweight <- fp_tp1_saliva |>
    filter(is.na(Birthweight_checked)) |>
    pull(Q1_Personnummer)
pn_fp_missing_birthweight

[1] "Birthweight_checked" "excess_weight"

 [1] "P060d440" "P1d75300" "P3780ac4" "P6d2ebc4" "P7f1746e" "Pab443f9"
 [7] "Pb752955" "Pd01a0ba" "Pe3450d3" "Pff3c644"

In [43]:
setdiff(pn_fp_missing_birthdate,pn_fp_missing_birthweight)

[1] "Pc9a3575" "Pf573f67"

In [44]:
intersect(pn_fp_missing_birthdate, drop_pn_combined)

character(0)

# Drop participants with missing birthdate
fp_tp1_saliva_adjusted <- fp_tp1_saliva |>
    filter(!(Q1_Personnummer %in% pn_fp_missing_birthdate))
head(fp_tp1_saliva_adjusted)
dim(fp_tp1_saliva_adjusted)

In [45]:
# Drop participants with missing birthweight
fp_tp1_saliva_adjusted <- fp_tp1_saliva |>
    filter(!(Q1_Personnummer %in% pn_fp_missing_birthweight))
head(fp_tp1_saliva_adjusted)
dim(fp_tp1_saliva_adjusted)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S14e664f     NA         0        0         1                     2018-09-10
2 S1f862a6     NA         0        0         0                     2018-03-07
3 S765e59d     NA         0        0         1                     2018-04-20
4 S39fe1d7     NA         0        0         0                     2018-06-23
5 S7e4a963     NA         0        0         0                     2018-02-18
6 S5fa4a39     NA         0        0         0                     2018-08-30
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P14e664f        0                   30          3          ⋯ 0
2 P1f862a6        0                   32          3          ⋯ 0
3 P3399626        0                   36          4          ⋯ 0
4 P3db7da6        0                   29          2          ⋯ 0
5 P424fd61        0                   37          4          ⋯ 0
6 P4de45e7        0                   29          2          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     39
2 NA                 NA   NA       NA                     31
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          very_w28_31  1    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    1

[1]  22 565

## Nulliparous selection--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# FInd women where primipara = True for fp

In [46]:
# Find all primipara personal# from fp
pn_primipara_fp <- fp_tp1_saliva_adjusted |>
    filter(fp_tp1_saliva_adjusted$Primipara == 1) |>
    pull(Q1_Personnummer)
pn_primipara_fp
pn_fp_missing_birthdate

 [1] "P1f862a6" "P3db7da6" "P424fd61" "P4de45e7" "P50f102c" "P5b98b6c"
 [7] "P719b21e" "P735d77f" "P7ece52e" "P92b4604" "Pa8f3b51" "Pbbb08bd"
[13] "Pc77a35c" "Pc9a3575" "Pca94a0f" "Pcd2c0d1" "Pdab1897" "Pe706703"
[19] "Pf573f67"

 [1] "P060d440" "P1d75300" "P3780ac4" "P6d2ebc4" "P7f1746e" "Pab443f9"
 [7] "Pb752955" "Pc9a3575" "Pd01a0ba" "Pe3450d3" "Pf573f67" "Pff3c644"

In [47]:
intersect(pn_primipara_fp, pn_fp_missing_birthdate)

[1] "Pc9a3575" "Pf573f67"

In [48]:
# Keep only participants that are primiparous
fp_nulliparous <- fp_tp1_saliva_adjusted |>
  filter(Q1_Personnummer %in% pn_primipara_fp) 
head(fp_nulliparous)
dim(fp_nulliparous)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P1f862a6        0                   32          3          ⋯ 0
2 P3db7da6        0                   29          2          ⋯ 0
3 P424fd61        0                   37          4          ⋯ 0
4 P4de45e7        0                   29          2          ⋯ 0
5 P50f102c        0                   32          3          ⋯ 0
6 P5b98b6c        0                   28          2          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  19 565

In [49]:
pn_filtered <- fp_nulliparous |>
  pull(Q1_Personnummer)
pn_filtered
length(pn_filtered)

 [1] "P1f862a6" "P3db7da6" "P424fd61" "P4de45e7" "P50f102c" "P5b98b6c"
 [7] "P719b21e" "P735d77f" "P7ece52e" "P92b4604" "Pa8f3b51" "Pbbb08bd"
[13] "Pc77a35c" "Pc9a3575" "Pca94a0f" "Pcd2c0d1" "Pdab1897" "Pe706703"
[19] "Pf573f67"

[1] 19

In [50]:
# Keep sp participants primiparous in fp
sp_nulliparous <- sp_tp1_saliva |>
  filter(Q1_Personnummer %in% pn_filtered)
head(sp_nulliparous)
dim(sp_nulliparous)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Sa79a719     NA         0        0         1                     2019-01-17
2 S3db7da6     NA         0        0         1                     2019-09-24
3 S424fd61     NA         0        0         0                     2020-11-03
4 S4de45e7     NA         0        0         0                     2020-11-05
5 Sa957143     NA         0        0         1                     2020-07-11
6 S0332ad6     NA         0        0         0                     2020-06-05
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P1f862a6        0                   32          3          ⋯  0
2 P3db7da6        0                   30          3          ⋯  0
3 P424fd61        0                   40          4          ⋯ 31
4 P4de45e7        0                   31          3          ⋯  0
5 P50f102c        0                   34          3          ⋯  0
6 P5b98b6c        0                   30          3          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  19 565

# This I should maybe do in kit 2 check since it will make things less confusing
pn_check2 <- sp_nulliparous |>
  filter(is.na(fodelsedatum_barn)) |>
  pull(Q1_Personnummer)
pn_check2

In [51]:
# Doubble check that all are no longer primiparous in sp
pn_check <- sp_nulliparous |> 
  filter(sp_nulliparous$Primipara == 1) |>
  pull(Q1_Personnummer)
pn_check
length(pn_check)
#sp_nulliparous |> 
 # filter(sp_nulliparous$Primipara == 1) |> pull(Primipara)

[1] "Pc9a3575"

[1] 1

In [52]:
# One participant was marked as nulliparous twice, crossed week 24 but the baby did not make it
fp_saliva |> filter(fp_saliva$Q1_Personnummer == "Pc9a3575") 
sp_saliva |> filter(sp_saliva$Q1_Personnummer == "Pc9a3575")

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Sc9a3575     NA         0        0         0                     2018-01-31
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 Pc9a3575        0                   30          3          ⋯ NA
  missfall.IUFD_week IUFD missfall
1 24                 0    0
  missfall.IUFD_comments
1 IUFD Jag fick havandeskapsförgiftning i v.22 och var tvungen att bli igångsatt. Flickan föddes i v. 24 +0 och överlevde tyvärr inte.
  Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
1 24              Induction            NA          NA
  preeclampsia_epi_analysis
1 1

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S99e6192     NA         0        0         1                     2020-05-15
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 Pc9a3575        0                   32          3          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31 1     1

In [53]:
fp_saliva |> filter(fp_saliva$Q1_Personnummer == "Pc9a3575")  |> pull(Primipara)
sp_saliva |> filter(sp_saliva$Q1_Personnummer == "Pc9a3575")  |> pull(Primipara)

[1] 1

[1] 1

In [54]:
fp_saliva |> filter(fp_saliva$Q1_Personnummer == "Pc9a3575")  |> pull(Studienummer)
sp_saliva |> filter(sp_saliva$Q1_Personnummer == "Pc9a3575")  |> pull(Studienummer)

[1] "Sc9a3575"

[1] "S99e6192"

In [55]:
# The participant needs to be marked as multiparous for sp since 
sp_nulliparous$Primipara[sp_nulliparous$Q1_Personnummer == "Pc9a3575"] <- 0
sp_nulliparous |> filter(sp_nulliparous$Q1_Personnummer == "Pc9a3575")  |> pull(Primipara)

[1] 0

In [56]:
dim(sp_nulliparous)

[1]  19 565

## Write to file------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [57]:
# Ad column with group
fp_nulliparous$Group <- "First pregnancy "
sp_nulliparous$Group <- "Second pregnancy"

In [58]:
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_nulliparous, sp_nulliparous)
dim(combined_fp_sp)
head(combined_fp_sp)

[1]  38 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   29          2          ⋯
3 P424fd61        0                   37          4          ⋯
4 P4de45e7        0                   29          2          ⋯
5 P50f102c        0                   32          3          ⋯
6 P5b98b6c        0                   28          2          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [59]:
# Write to file
write.table(fp_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", Sys.Date(), "fp_tp1_nulliparous_saliva", ".csv"), sep = ",", row.names = FALSE)
write.table(sp_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", Sys.Date(), "sp_tp1_nulliparous_saliva", ".csv"), sep = ",", row.names = FALSE)

write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", Sys.Date(), "_combined_nulliparous_fp_sp_tp1_saliva", ".csv"), sep = ",", row.names = FALSE)

In [60]:
#grep("Q2_X2.4_Any", names(sp_nulliparous), value = TRUE)
#p_saliva$Q2_X2.4_Anything_gone_wrong

# Create files fp_tp1_saliva and sp_tp1_saliva
# This is just for flow cell filtration as Primiparity is not important, neither is missing any other condition

In [61]:
# Merge the two df vertically:
combined_for_flowcells <- rbind(fp_tp1_saliva, sp_tp1_saliva)
dim(combined_for_flowcells)
head(combined_for_flowcells)

[1]  64 565

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Scf5931f     NA         0        0         0                     2018-12-13
2 S14e664f     NA         0        0         1                     2018-09-10
3 S30bce16     NA         0        0         0                     2018-04-18
4 S1f862a6     NA         0        0         0                     2018-03-07
5 S765e59d     NA         0        0         1                     2018-04-20
6 S3780ac4     NA         0        0         0                     2019-02-23
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯ diffdays
1 P060d440        0                   30          3          ⋯ NA
2 P14e664f        0                   30          3          ⋯  0
3 P1d75300        0                   32          3          ⋯ NA
4 P1f862a6        0                   32          3          ⋯  0
5 P3399626        0                   36          4          ⋯  0
6 P3780ac4        0                   38          4          ⋯ NA
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     NA
4 NA                 NA   NA       NA                     31
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     NA
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 NA                   NA          NA    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          NA          NA    0
6 NA                   NA          NA    0

In [62]:
write.table(combined_for_flowcells, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", Sys.Date(), "combined_for_flowcells_saliva", ".csv"), sep = ",", row.names = FALSE)