#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_taxa_other_taxa
# Date: 2025.12.05
# Programmer: Barbara Nowak
# Purpose: Add other taxa row, keep only samples from participants 
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
taxa_tab <- read.table("/ceph/projects/010_SweMaMi/bm.nowak/data/2025-12-09_no_minimum_prev_abundance_no_other_taxa_saliva_taxa_cleaned_both_tp.tsv", header = TRUE, sep = "\t", check.names = FALSE )
dim(taxa_tab)
colSums(taxa_tab) |> sort ()

[1]  845 1673

    11437     19881     20420     13095     18901     12988      7349      1295
 99.99985  99.99987  99.99988  99.99988  99.99988  99.99988  99.99988  99.99988
    21331     16674     18954     20185     20308     11005     17801     19497
 99.99988  99.99989  99.99989  99.99989  99.99990  99.99990  99.99990  99.99990
    20706     15347     11223     15546     18251     19015     13205     19056
 99.99990  99.99990  99.99990  99.99990  99.99990  99.99990  99.99990  99.99990
    19931     22142     11371     16568     17668     15560     16091     15401
 99.99991  99.99991  99.99991  99.99991  99.99991  99.99991  99.99991  99.99991
    20737     21221     18272      7547      1358     20238     20541     11384
 99.99991  99.99991  99.99991  99.99992  99.99992  99.99992  99.99992  99.99992
    11228     17623     19766     16078     16138     19361     19071     16426
 99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992
    15000     11856     13627      1163      9691     21654     19566     19623
 99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992
    21298     17733     21426     19703     13776     17247     21080      1052
 99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992  99.99992
     1097      7551     10586     16951     16643     13593     14076     12971
 99.99992  99.99992  99.99992  99.99993  99.99993  99.99993  99.99993  99.99993
    18154     21481      7852      9290     20046     20248     20520     11344
 99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993
    10392     21123     19576     19723     19774     16219     17664     19506
 99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993
    17670     19221     20087     17837     12950     14865     16208      1178
 99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993
    17293     21294     17711     18025     19973      1289      8011     11497
 99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99993  99.99994
    10614     11099      1060      1077      7774     10741     19517     17830
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    18962     22196     22327     11419     22191     12898     10523     11375
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    11240     20521     19041     20957     20617     20848     15395     15792
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    16320     16832     17418     18914     22081     14533     20506     20241
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    17897     23278     13264     11673      1318     15431       953     18185
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    18693     21918     21450     19632     17286     17287      1151     12471
 99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994  99.99994
    18830     19446     17762     21441     10681      7776     10026      9418
 99.99994  99.99994  99.99994  99.99994  99.99995  99.99995  99.99995  99.99995
    11103      1123     18855     19803     18172     19905     19964     11432
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    23329     11416     13118     10388     10098     19364     20309     19321
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    21911     17360     17761     18241     19777     20765     17079     14564
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    16833     16974     16432     16612     19671     20760     17600     17633
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    20767     16705     17083     18456     17299     18076     16828     21269
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    17012     14560     16283     17058     17687     21106     19090      9246
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    23270     10721     22139     20036     20170     22180     12470     14513
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
     1131     14374     14820     13432     14877     12905     13033     12912
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    18409     17639     18016     17392     21303     18194     17714     18003
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
    20444     20347     20443      7870      7988      1387      7352     12436
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995
     7238     12751     12631     12405     12375     12381     19257     10656
 99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99995  99.99996
    11727     10304      1673     11766     10654     11482     18596     20407
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    19310     20380     18956     20632     19283     10445     11247      9251
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    11410     10240     11765     10132     11381      7764     20187     20485
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    20376     19868     19673     18800     18248     17192     21567     17471
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    15537     14569     19505     16988     18424     16071     16606     16975
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    20531     19074      9760     23342     20042     20628     20964     18654
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    19871     23292     11337     12457     12956     14609     12639      9661
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    16017     15377     15064     15986     13563      1232      1010     11469
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    13004     12647      1687     20538     17487     20554     17469     19714
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    21208     18211     19546     19556     19725     17279     17935     18124
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    21457     20246     18223      1217      9238      7350      7221      7552
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996
    10573     10242     21255     18100     21318     17703     20293     10048
 99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99996  99.99997
     1049     11011     11700     10020     18594     18587     20895     20665
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    17826     20338     20550     18988      7231     10488      9483      7880
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    11212     10469     10340     20850      9776     12941     12528     10984
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    12660     11843     12448     12953     11446      1632     11260     12935
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    11168     11458     10578      9698     10517      9766     11013      9410
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    12932     10065     20620     20615     19238     20140     20588     20622
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    19950     18597     19826     19912     17809     19621     21233     17542
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    21706     20846     17421     16442     14217     14278     16125     16224
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    16126     15449     19542     19393     16593     19543     18499     18393
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    16497     17768     16730     17021     16946     16716     17005     16967
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    15374     20529     21213     19065     19968     19488     17983     22130
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    23251     19921     20065     23161     22137     22239     19887     23253
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    12888      1140     13437     14876     12897     16413     15877     15335
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    15872     14937     14920     15465     12847     10258      7563      9748
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    11318     12710     18106     18513     19753     21262     20715     17367
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    21838     17348     21231     21124     19781     18351     21522     19728
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
     1320     13614      1166      1066      1177     13515     13551      7854
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
     1304     13572     12521     10527     10592     20003     21079     19692
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997  99.99997
    17767     21496     17199     17282     21528     13611      1392     21667
 99.99997  99.99997  99.99997  99.99997  99.99997  99.99998  99.99998  99.99998
    21666     17812     20811     18931     20818     19794     20707     10432
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    11390     11439     10771     23760     13449     10976     11229     11236
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    10287     11264     10827     18618     18032     17797     19329     19307
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    16739     15342     16962     16507     13804     17458     16443     16647
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    17764     19286     19025     17732     19003     21103     18874     19316
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    20565     17858     23277     10036     10076     20555     19867     20587
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    23815     22150     10200      9262     13375     11457     13076     11461
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    11699     15063     14726      9598     14740     16491     10221     13281
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
     1192      1009     11153     10311      9218      1316     19541     18292
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    18220     21045     18747     21721     17450     21475     18742     18283
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    21477     21248     21376     19452     19415     20001     17995     18346
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
     7179      7991     13525     13032     13473     10872     13153     21258
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    21929     21361     20007     17584     19763     21225     18891       921
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    19115     17374     14392     15369     21018     16550     21066     23302
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    11308     19328     19894     22325       972     16689     21427     17263
 99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998  99.99998
    19635     10298     18173     11601     12972     11003     11667      7211
 99.99998  99.99998  99.99998  99.99999  99.99999  99.99999  99.99999  99.99999
     9288     18147     19254     17815     20703     20524     19911     20281
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    21973     21634     22256     23353      1693     23349     19916     10508
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    11054     20523      9921     22176      9756     10478     10686      9393
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
     9273     10972      9885     13050     12383      7762     10280     11058
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
     9878     10421      1694     10456     20952     19513     20977     21909
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    19140     20179     19335     17889     20242     21892     20881     21852
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    17522     19598     18163     19747     17384     17459     17940     17491
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    16122     14270     16803     21011     18439     18299     16566     17401
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    16626     17523     16757     12385     19294     20603     17882     18054
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    13753     21062     19970     19902     11023     10548     12973     13491
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    13494     22177     19925     19520     20873     17893     23265     22286
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    22173     22282      9664     14826      1150     13250     12604     13573
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    13230     14220     15532     15783     13038     14999     14287     13126
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    12532     11251     10281     11355     11606     11629     17964     18281
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    21534     17949     22063     18402     18367     18203     18337     21148
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    18743     20772     21330     21238     19216     21387     17730     19147
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    20728     17731      1081      1247       964      1068      7301      7368
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
     9565      7562       980      1073      7881      7779     12797     12546
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    12911     12873     11713     10856     12773     20395     17521     20553
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999  99.99999
    21408     18846     17388     20385     21930     17260     12715      7772
 99.99999  99.99999  99.99999  99.99999  99.99999  99.99999 100.00000 100.00000
    11602     10064     19422     19351     20050     20701     20088     20854
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    20451     21132     20068     10506     23298     10989     22308     12952
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    10794     11014     12960     11422     23554     19273     12431     13247
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    12556     12675     11015     12653     12737      9263     12387     13442
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    10119     10318     10074     11433      9221     13509     10349     11595
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
     7848      9227     10545     17903     17856     18791     19538     19039
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    21151     19670     18113     18360     19399     20168     17230     21523
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    18217     18786     16118     12783     16711     13790     14561     14567
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    16779     16199     15461     13782     16499     21271     18358     18276
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    18530     19575     17575     16804     20900     17947     16852     16152
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    21879     19672     16056     16558     16969     16903     16328     17651
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    16957     17425     16561     16519     18117     20396      9333     23279
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    23291     22291     20708     20677     23931     22234     20121     14854
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
     1816     14821     11197     16511     15784     14208     14457     15477
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    13262     14803     15466     14060     16013     15761     15454     15430
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
     1347     12665     10881     12910     12632       963     11714     17617
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    18735     22053     21938     18498     18294     21322     21823     18233
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    19639     21246     21546     17994     19600     21404     21308     19767
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    21464      7197      1258      9602     13532     13372      9312     10582
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    13066      8005     10914      9439     12803     10368     18174     19055
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00000
    21850     13734     21716     17463     20397     17589      9482     10343
100.00000 100.00000 100.00000 100.00000 100.00000 100.00000 100.00001 100.00001
    10351     10357     10873      7701      1379     10443     10028     11660
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001
     9429     10704      1079      1094     10677     19797     18708     19493
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001
    18144      9574     23603     10434     22269     10520     22183     10459
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001
    11060     11435     12961     10148     12624      9253     11404     10256
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001
    10842     12659     11789     12735     10734     11584     11017     10629
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001
    11362     10501     10360     11347     11780     19156     20646     18622
100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001 100.00001

In [3]:
head(taxa_tab)
dim(taxa_tab)

                             11601   921     7766    11497   10644   7547
Prevotella_melaninogenica    7.46856 4.43305 2.01303 3.09323 2.18746  2.89516
TM7_phylum_sp_oral_taxon_352 3.14409 2.21632 0.27918 0.81149 0.10544  1.92240
Veillonella_dispar           3.16098 1.97065 5.15186 5.76151 3.67418  3.17602
Streptococcus_salivarius     6.66179 2.07087 9.56769 4.59215 7.84402 12.85163
Prevotella_pallens           1.09428 4.69337 0.48324 3.19061 0.00000  0.86855
Streptococcus_parasanguinis  5.05936 5.04811 4.55327 3.91857 2.32197  3.38418
                             10048   10681   13611   1054     ⋯ 19612   17589
Prevotella_melaninogenica    5.46348 7.60818 2.66597  7.05540 ⋯ 2.27635 3.91719
TM7_phylum_sp_oral_taxon_352 1.88095 0.70932 2.10826  1.12378 ⋯ 2.03540 1.91947
Veillonella_dispar           4.86584 7.54436 0.60527 13.37827 ⋯ 2.17340 6.97362
Streptococcus_salivarius     7.59421 8.05424 0.36229 23.52221 ⋯ 3.08711 3.59449
Prevotella_pallens           4.79881 1.50316 1.29621  0.03604 ⋯ 0.62355 1.68677
Streptococcus_parasanguinis  3.75756 4.71644 1.78240 11.06978 ⋯ 1.56545 3.28812
                             18881    21225   20293   21180   21386   21930
Prevotella_melaninogenica     0.01522 1.55264 4.93655 6.53807 3.30094 8.66169
TM7_phylum_sp_oral_taxon_352  0.99134 2.07174 0.46493 1.60654 3.36108 1.29958
Veillonella_dispar            9.72087 7.87567 7.26205 7.27621 5.88949 0.93840
Streptococcus_salivarius     18.06276 6.99764 9.51983 2.35358 6.62331 1.23692
Prevotella_pallens            0.52037 2.04457 2.32954 3.84069 0.71656 1.85049
Streptococcus_parasanguinis   9.99736 7.00401 2.73461 3.21385 7.10522 3.96688
                             17260    18891
Prevotella_melaninogenica     3.93085 3.41636
TM7_phylum_sp_oral_taxon_352  1.20771 1.13150
Veillonella_dispar           12.13797 1.20559
Streptococcus_salivarius     12.70253 6.49664
Prevotella_pallens            1.24524 0.92643
Streptococcus_parasanguinis   9.57804 1.01967

[1]  845 1673

In [4]:
# Adding other taxa row
new_row <- c()
tot <- colSums(taxa_tab)
for(i in tot){
    if(i < 100){
        new_row <- c(new_row, 100 - i)
    } else if (i >= 100){
        new_row <- c(new_row, 0)
    }
}
head(tot)
head(new_row)

# add this vector as row to the taxa table
new_row <- setNames(new_row, names(taxa_tab))
#new_row
new_row2 <- as.data.frame(t(new_row))
#new_row2
rownames(new_row2) <- "Other_taxa"
best_filt_new <- rbind(taxa_tab ,new_row2) 
#colSums(best_filt_new )
#now the colSums == 100

filt_new_arrange <- as.data.frame(best_filt_new)
head(filt_new_arrange)
dim(filt_new_arrange)

    11601       921      7766     11497     10644      7547
 99.99999  99.99998 100.00002  99.99994 100.00003  99.99992

[1] 1e-05 2e-05 0e+00 6e-05 0e+00 8e-05

                             11601   921     7766    11497   10644   7547
Prevotella_melaninogenica    7.46856 4.43305 2.01303 3.09323 2.18746  2.89516
TM7_phylum_sp_oral_taxon_352 3.14409 2.21632 0.27918 0.81149 0.10544  1.92240
Veillonella_dispar           3.16098 1.97065 5.15186 5.76151 3.67418  3.17602
Streptococcus_salivarius     6.66179 2.07087 9.56769 4.59215 7.84402 12.85163
Prevotella_pallens           1.09428 4.69337 0.48324 3.19061 0.00000  0.86855
Streptococcus_parasanguinis  5.05936 5.04811 4.55327 3.91857 2.32197  3.38418
                             10048   10681   13611   1054     ⋯ 19612   17589
Prevotella_melaninogenica    5.46348 7.60818 2.66597  7.05540 ⋯ 2.27635 3.91719
TM7_phylum_sp_oral_taxon_352 1.88095 0.70932 2.10826  1.12378 ⋯ 2.03540 1.91947
Veillonella_dispar           4.86584 7.54436 0.60527 13.37827 ⋯ 2.17340 6.97362
Streptococcus_salivarius     7.59421 8.05424 0.36229 23.52221 ⋯ 3.08711 3.59449
Prevotella_pallens           4.79881 1.50316 1.29621  0.03604 ⋯ 0.62355 1.68677
Streptococcus_parasanguinis  3.75756 4.71644 1.78240 11.06978 ⋯ 1.56545 3.28812
                             18881    21225   20293   21180   21386   21930
Prevotella_melaninogenica     0.01522 1.55264 4.93655 6.53807 3.30094 8.66169
TM7_phylum_sp_oral_taxon_352  0.99134 2.07174 0.46493 1.60654 3.36108 1.29958
Veillonella_dispar            9.72087 7.87567 7.26205 7.27621 5.88949 0.93840
Streptococcus_salivarius     18.06276 6.99764 9.51983 2.35358 6.62331 1.23692
Prevotella_pallens            0.52037 2.04457 2.32954 3.84069 0.71656 1.85049
Streptococcus_parasanguinis   9.99736 7.00401 2.73461 3.21385 7.10522 3.96688
                             17260    18891
Prevotella_melaninogenica     3.93085 3.41636
TM7_phylum_sp_oral_taxon_352  1.20771 1.13150
Veillonella_dispar           12.13797 1.20559
Streptococcus_salivarius     12.70253 6.49664
Prevotella_pallens            1.24524 0.92643
Streptococcus_parasanguinis   9.57804 1.01967

[1]  846 1673

In [5]:
tail(filt_new_arrange)

                                 11601 921   7766 11497 10644 7547  10048 10681
Brachybacterium_nesterenkovii    0e+00 0e+00 0    0e+00 0     0e+00 0e+00 0e+00
GGB6673_SGB99879                 0e+00 0e+00 0    0e+00 0     0e+00 0e+00 0e+00
Streptococcus_dysgalactiae       0e+00 0e+00 0    0e+00 0     0e+00 0e+00 0e+00
Cutibacterium_granulosum         0e+00 0e+00 0    0e+00 0     0e+00 0e+00 0e+00
Corynebacterium_pseudogenitalium 0e+00 0e+00 0    0e+00 0     0e+00 0e+00 0e+00
Other_taxa                       1e-05 2e-05 0    6e-05 0     8e-05 3e-05 5e-05
                                 13611 1054 ⋯ 19612 17589 18881 21225 20293
Brachybacterium_nesterenkovii    0e+00 0    ⋯ 0     0     0     0e+00 0e+00
GGB6673_SGB99879                 0e+00 0    ⋯ 0     0     0     0e+00 0e+00
Streptococcus_dysgalactiae       0e+00 0    ⋯ 0     0     0     0e+00 0e+00
Cutibacterium_granulosum         0e+00 0    ⋯ 0     0     0     0e+00 0e+00
Corynebacterium_pseudogenitalium 0e+00 0    ⋯ 0     0     0     0e+00 0e+00
Other_taxa                       2e-05 0    ⋯ 0     0     0     2e-05 4e-05
                                 21180 21386 21930 17260 18891
Brachybacterium_nesterenkovii    0     0     0e+00 0e+00 0e+00
GGB6673_SGB99879                 0     0     0e+00 0e+00 0e+00
Streptococcus_dysgalactiae       0     0     0e+00 0e+00 0e+00
Cutibacterium_granulosum         0     0     0e+00 0e+00 0e+00
Corynebacterium_pseudogenitalium 0     0     0e+00 0e+00 0e+00
Other_taxa                       0     0     1e-05 1e-05 2e-05

In [6]:
colSums(filt_new_arrange) |> sort()

   11601      921    11497     7547    10048    10681    13611     7776
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12972    10026    10656     1392    10614    11727     1049    11003
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11099    11667     9418    12715     1060     9290     7772     1077
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    1358    10304    11103     7211    11602     1673    11766     7774
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11011     1123    11700    10654    10741    10064    11482     9288
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10020    21667    21666    18147    18596    17812    19517    20238
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20541    18594    18855    20407    19422    19351    19254    20046
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19310    20380    20050    19803    18956    20811    18172    17815
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18587    18931    20703    20895    20665    20701    20818    19931
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20524    17826    19794    19911    20338    20632    19905    20088
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20854    20281    21973    17830    19283    20451    20420    19964
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21132    20308    20068    20248    21634    19881    20550    18962
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19115    20707    18988    11432    23329    10506    22256    10432
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   23353     7231    10488    23298    11390    10445    10989    22196
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    9483     7880    11439    20520     1693    23349    22327    22308
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   22142    11212    12952    19916    11247    10794    10508    11014
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12960    11419    11054    10469    10771    20523    10340    22191
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    9921    20850    22176    11384     9756    11416    13118    23760
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10478    11422    23554    10686    19273     9251    11410     9393
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    9776    13449    10240    12941    12431     9273    12528    13247
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10972    10984    11371    12660    12556    12675    11843    11015
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12448    10388     9885    13050    12653    12737     9263    12898
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12383    12953    12387    13442    11446     7762    10119    11005
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10280     1632    11765    11344    10976    11058    10318    11260
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10098    10132    11381     9878    10421    11229    10074    11236
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12935    11433    11168    10523    11375    11458    10578    10287
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    1694     9698     9221    10517    11228     9766    11264    13509
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11013     9410     7764    11240    12932    10349    10827    11595
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10456    10065     7848    10392     9227    10545    18618    20952
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17903    19364    17856    20620    20309    20615    18791    19513
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18032    19538    20521    19041    20977    17797    19238    20187
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17801    21909    20140    19140    20588    20179    19335    17889
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19329    20485    20957    20242    19497    20617    21892    20706
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19321    19307    20376    20622    19950    18597    19039    21911
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19826    19912    17809    19868    19621    21151    19670    18113
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20848    18360    21233    17360    19399    21123    20881    17761
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21852    17542    21706    17522    19598    19673    18800    18241
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18248    17762    20168    17230    19576    18163    20846    21523
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19747    17192    19777    18217    17384    18786    17374    21441
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19723    17459    19774    20765    17940    17491    21567    17421
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17471    17079    16442    14564    14392    16118    16833    14217
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16974    15395    15347    12783    16711    14278    13790    16125
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16432    16219    16122    14270    16568    16739    15537    16803
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15342    16962    15792    14561    14569    14567    16779    16199
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16224    16126    15461    13782    16320    16507    16832    16499
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15449    15369    19505    16612    17623    21271    21011    18358
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19671    20760    18276    19542    18530    17664    19575    19506
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19766    17418    17600    19393    18439    17575    16804    20900
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   13804    17458    17633    16593    16988    18299    18424    16078
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20767    19543    17670    16705    17947    18914    17083    18456
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   22081    16852    16152    21879    17299    19672    21018    16056
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16558    18499    18393    16443    18076    16497    16071    17768
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16566    16730    16647    14533    16828    16969    16951    17401
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16903    17021    21269    16946    17012    16716    14560    16328
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17651    16138    16957    17005    16283    17425    16626    16561
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17058    16606    16975    16967    17523    17687    16643    15374
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16550    16519    16757    17668    12385    16674    17764    19221
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20529    21213    18117    20396    19286    20506    19294    19361
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19065    19025    20603    19968    21106    17882    17732    19003
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19090    18954    20531    21103    18874    21066    19316    19074
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20565    19488    19071    18054    13753    20241    20087    17983
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21062    17858    19970    19902     9333    23277     9246    23302
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   23270    11023    10721    23279    23291    10548    22130    10036
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12973    11223    13491    11308    13494    10076    22177    13095
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   23251     9760    22291    23342    22139    19925    17837    20036
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19520    20555    19921    20042    19867    20708    17897    20185
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19328    20170    20628    20677    20873    20964    18654    20065
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17893    18901    20587    19894    19871    23815    23931    22150
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   23265    23292    22286    23278    23161    22234    22137    22239
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20121    22173    22282    19887    22325    23253    22180    13593
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12950    14854    12888     1140    10200     9664     1816    14826
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11337     1150     9262    13437    13375    14821    14865    13264
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11673    12457    12470    11457    13076    13250    12956    12604
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11461    14609    14876    12639    14513    12988    11699    11197
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    9661     1318     1131      972    13573    14374    14820    13432
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   13230    16511    14220    15063    15532    16017    12897    14877
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   14726    15560    15784    16413    14208    15783    15877    16208
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15546    14457    15335    15477    16426    15377    15872    16091
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   14937    13262    14803    13038    15431    15064    15466     9598
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   14920    15465    14060    16013    15761    15000    14076    14740
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15454    14999    12847    15430    14287    15401    15986    16491
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10221     1347    12971    10258    11437    13126    13563     1232
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12905     1010    12532    13281     1192     7563     1009     7349
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12665    11251     1178    10281    11469    11153    11856    13033
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10311    13627    10881    12910     9218    12632      963    13004
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11355    11606    12647     9748     1163    11714    11629    11318
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
     953    12710    12912     1687     9691     1316    21654    17964
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20538    17617    18281    18735    19541    17487    18185    18409
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21534    18693    22053    18292    18106    17639    20554    21938
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17949    17469    20737    22063    18154    19714    18402    18016
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16689    18498    18294    21322    19566    18220    21045    17392
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19623    18513    18367    18747    21918    21721    21298    17450
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21823    18203    19753    21262    18337    21450    21221    21475
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20715    21303    18742    17293    18233    21148    17367    18194
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18743    21838    17733    18283    17348    18251    21481    21477
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20772    21208    17714    21231    19632    18211    19546    19639
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21246    19556    21124    18272    21330    21248    19725    19781
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17279    17935    21426    21546    17994    21427    19703    18003
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   13776    18124    17286    21238    19216    17247    21376    19452
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19600    17263    21457    19415    17287    21080    18351    20001
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21294    21404    21387    21308    17711    18025    19015    20246
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20444    21522    18223    20347    19728    17995    19635    17730
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19767    20443    21464    19147    20728    17731    18346    19973
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    1081     1052     1247     1295     7870      964     1320     1097
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    7551     7988    13614     1217     7179     1387     7991     1068
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    1289     7301     8011     7368     1166     9238     7352    13525
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    7350     1066     1177     7197     9565    13032     1258    13515
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12436     7562     7852    13551     7238     7221     7854      980
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12751     1304     9602     1073    13532     7881    13372     7779
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    1151     7552     9312    12797    10582    12546    13066    10573
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   13572    12911    12521    13473    10527    10872    12873    12471
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    8005    10914    10586    12631    11713     9439    12803    10856
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10242    12405    10592    10368    12773    12375    12381    13153
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10298    13205    18174    19055    21255    21850    20395    21258
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17521    21929    21331    18830    20003    18100    21318    17703
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21079    19446    19692    17767    21496    21361    18173    20553
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   13734    20007    21716    17199    17463    21408    19257    17584
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19056    18846    17388    17282    19763    20397    21528    20385
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17589    21225    20293    21930    17260    18891     9482    10343
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10351    10357    10873     7701     1379    10443    10028    11660
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
    9429    10704     1079     1094    10677    19797    18708    19493
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18144     9574    23603    10434    22269    10520    22183    10459
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11060    11435    12961    10148    12624     9253    11404    10256
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   10842    12659    11789    12735    10734    11584    11017    10629
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   11362    10501    10360    11347    11780    19156    20646    18622
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   18607    20040    20840    17928    19954    21824    17580    18356
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21859    17232    19645    18701    17494    18942    16220    21950
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19405    15569    16984    16398    16652    14256    16874    16630
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15346    18411    18469    21454    15950    21673    17747    19772
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17390    16847    16456    14578    16792    15340    17043    16728
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   16047    16987    19001    19013    19448    18066    19431    20391
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   20307    21961    20526    19278    22214    22322    10861    19334
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   19809    20897    17851    17822    23583     9267    12810     1118
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   12414    13474    13584    12627    13382    10190    12661    13271
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   14681    15467    16425    15504    12589    13566    15769    16119
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   15954    10834     1141    12406     1197     9737    19712    20149
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   17220    17413    18344    21459    18343    17357    21442    21470
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21383    17527    17587    17201    21883    21007    21957    19293
100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000 100.0000
   21147    20373    21010     7573     7856     1014     1053     1207

In [10]:
# Export as .tsv
write.table(filt_new_arrange, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/data/", Sys.Date(),
                                       "no_minimum_abundance_other_taxa_saliva_taxa_table_cleaned_both_tp", ".tsv"), sep = "\t")

In [8]:
taxa_nulliparous <- taxa_tab [, colnames(taxa_tab) %in% fp$kit1.salival_sample.barcode]
head(taxa_nulliparous)
dim(taxa_nulliparous)

ERROR: Error: object 'fp' not found