#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_filtering_valid_barcodes_tp1
# Date: 2025.12.08
# Programmer: Barbara Nowak
# Purpose: Saliva, after Super StaG some samples failed, so matching of FP and SP valid samples had to be done again.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Read files --------------------------------------------------------------------------

In [3]:
# Taxa table where minimum abundance and prev species not removed
taxa_tab <- read.table("/ceph/projects/010_SweMaMi/bm.nowak/data/2025-12-09_no_minimum_prev_abundance_no_other_taxa_saliva_taxa_cleaned_both_tp.tsv", header = TRUE, sep ="\t", check.names = FALSE, quote='"') 
head(taxa_tab)
dim(taxa_tab)

                             11601   921     7766    11497   10644   7547
Prevotella_melaninogenica    7.46856 4.43305 2.01303 3.09323 2.18746  2.89516
TM7_phylum_sp_oral_taxon_352 3.14409 2.21632 0.27918 0.81149 0.10544  1.92240
Veillonella_dispar           3.16098 1.97065 5.15186 5.76151 3.67418  3.17602
Streptococcus_salivarius     6.66179 2.07087 9.56769 4.59215 7.84402 12.85163
Prevotella_pallens           1.09428 4.69337 0.48324 3.19061 0.00000  0.86855
Streptococcus_parasanguinis  5.05936 5.04811 4.55327 3.91857 2.32197  3.38418
                             10048   10681   13611   1054     ⋯ 19612   17589
Prevotella_melaninogenica    5.46348 7.60818 2.66597  7.05540 ⋯ 2.27635 3.91719
TM7_phylum_sp_oral_taxon_352 1.88095 0.70932 2.10826  1.12378 ⋯ 2.03540 1.91947
Veillonella_dispar           4.86584 7.54436 0.60527 13.37827 ⋯ 2.17340 6.97362
Streptococcus_salivarius     7.59421 8.05424 0.36229 23.52221 ⋯ 3.08711 3.59449
Prevotella_pallens           4.79881 1.50316 1.29621  0.03604 ⋯ 0.62355 1.68677
Streptococcus_parasanguinis  3.75756 4.71644 1.78240 11.06978 ⋯ 1.56545 3.28812
                             18881    21225   20293   21180   21386   21930
Prevotella_melaninogenica     0.01522 1.55264 4.93655 6.53807 3.30094 8.66169
TM7_phylum_sp_oral_taxon_352  0.99134 2.07174 0.46493 1.60654 3.36108 1.29958
Veillonella_dispar            9.72087 7.87567 7.26205 7.27621 5.88949 0.93840
Streptococcus_salivarius     18.06276 6.99764 9.51983 2.35358 6.62331 1.23692
Prevotella_pallens            0.52037 2.04457 2.32954 3.84069 0.71656 1.85049
Streptococcus_parasanguinis   9.99736 7.00401 2.73461 3.21385 7.10522 3.96688
                             17260    18891
Prevotella_melaninogenica     3.93085 3.41636
TM7_phylum_sp_oral_taxon_352  1.20771 1.13150
Veillonella_dispar           12.13797 1.20559
Streptococcus_salivarius     12.70253 6.49664
Prevotella_pallens            1.24524 0.92643
Streptococcus_parasanguinis   9.57804 1.01967

[1]  845 1673

In [4]:
fp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22fp_tp1_nulliparous_saliva.csv", header = TRUE)
dim(fp_tp1)
head(fp_tp1)

[1]  19 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   29          2          ⋯
3 P424fd61        0                   37          4          ⋯
4 P4de45e7        0                   29          2          ⋯
5 P50f102c        0                   32          3          ⋯
6 P5b98b6c        0                   28          2          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [5]:
sp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous//2025-10-22sp_tp1_nulliparous_saliva.csv", header = TRUE)
dim(sp_tp1)
head(sp_tp1)

[1]  19 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Sa79a719     NA         0        0         1                     2019-01-17
2 S3db7da6     NA         0        0         1                     2019-09-24
3 S424fd61     NA         0        0         0                     2020-11-03
4 S4de45e7     NA         0        0         0                     2020-11-05
5 Sa957143     NA         0        0         1                     2020-07-11
6 S0332ad6     NA         0        0         0                     2020-06-05
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   30          3          ⋯
3 P424fd61        0                   40          4          ⋯
4 P4de45e7        0                   31          3          ⋯
5 P50f102c        0                   34          3          ⋯
6 P5b98b6c        0                   30          3          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 Second pregnancy
2 Second pregnancy
3 Second pregnancy
4 Second pregnancy
5 Second pregnancy
6 Second pregnancy

In [6]:
    combined_fp_sp_tp1 <- read.csv("/ceph/projects//010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22_combined_nulliparous_fp_sp_tp1_saliva.csv", header = TRUE)
dim(combined_fp_sp_tp1)
head(combined_fp_sp_tp1)

[1]  38 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   29          2          ⋯
3 P424fd61        0                   37          4          ⋯
4 P4de45e7        0                   29          2          ⋯
5 P50f102c        0                   32          3          ⋯
6 P5b98b6c        0                   28          2          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

# Find valid barcodes ------------------------------------------------------------------------------

In [7]:
# Read fp and sp metadata files to obtain barcodes, OBS $Group for FP has a SPACE at the end!!
combined_fp_sp_tp1$Group
fp_bc <- combined_fp_sp_tp1 |>
  filter(Group == "First pregnancy ") |>
  pull(kit1.salival_sample.barcode)
print(fp_bc) |> length()

 [1] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [5] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [9] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[13] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[17] "First pregnancy " "First pregnancy " "First pregnancy " "Second pregnancy"
[21] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[25] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[29] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[33] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[37] "Second pregnancy" "Second pregnancy"

 [1]  1220 10368  1048 10700 10861  1372 10417 11161 13593 10656  9482 10856
[13]  1381  1115 10654   956  9864   961 11747

[1] 19

In [8]:
sp_bc <- combined_fp_sp_tp1 |>
  filter(Group == "Second pregnancy") |>
  pull(kit1.salival_sample.barcode)
print(sp_bc) |> length()

 [1] 13551 17523 23562 23353 19961 19835 18855 19676 23292 21844 17839 21011
[13] 23298 21973 22236 21819 20818 22000 21837

[1] 19

FP is the one that has less barcodes extract those since participants will be removed form SP if they are missing int FP.  
Then check what pn numbers correspont to those barcodes <-- this is what the filtering will then be based on.

In [35]:
valid_barcodes_fp <- taxa_tab[, colnames(taxa_tab) %in% fp_bc] |> colnames()

valid_barcodes_fp
length(valid_barcodes_fp)

 [1] "9482"  "10656" "11161" "10654" "10861" "13593" "11747" "9864"  "1115"
[10] "961"   "10856" "10368"

[1] 12

In [43]:
invalid_pn_fp <- fp_tp1 |> filter(!fp_tp1$kit1.salival_sample.barcode %in% valid_barcodes_fp) |> pull(Q1_Personnummer)
length(invalid_pn_fp)
    head(invalid_pn_fp)

[1] 7

[1] "P1f862a6" "P424fd61" "P4de45e7" "P5b98b6c" "P719b21e" "Pc77a35c"

In [44]:
valid_barcodes_sp <- taxa_tab[, colnames(taxa_tab) %in% sp_bc] |> colnames()

valid_barcodes_sp
length(valid_barcodes_sp)

 [1] "18855" "20818" "21973" "23353" "23562" "23298" "21011" "17523" "19961"
[10] "22236" "23292" "21819" "19676" "22000" "13551"

[1] 15

In [45]:
invalid_pn_sp <- sp_tp1 |> filter(!sp_tp1$kit1.salival_sample.barcode %in% valid_barcodes_sp) |> pull(Q1_Personnummer)
length(invalid_pn_sp)
    head(invalid_pn_sp)

[1] 4

[1] "P5b98b6c" "P92b4604" "Pa8f3b51" "Pf573f67"

In [46]:
class(valid_barcodes_fp)
class(valid_barcodes_sp)

[1] "character"

[1] "character"

In [52]:
intersect(invalid_pn_sp, invalid_pn_sp) |> length()
unique(invalid_pn_fp, invalid_pn_sp) |> length()

[1] 4

[1] 7

In [48]:
unique(invalid_pn_fp, invalid_pn_sp) |> length()

[1] 7

In [49]:
# combine both personal number to drop
pn_to_drop <- c(invalid_pn_fp, invalid_pn_sp)
pn_to_drop |> length()
pn_to_drop |> unique() |> length()

[1] 11

[1] 10

In [53]:
fp_tp1_saliva <- fp_tp1 |>
    filter(!(Q1_Personnummer %in% pn_to_drop))
head(fp_tp1_saliva)
dim(fp_tp1_saliva)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S39fe1d7     NA         0        0         0                     2018-06-23
2 S50f102c     NA         0        0         0                     2018-08-05
3 S735d77f     NA         0        0         0                     2018-08-24
4 S9026714     NA         0        0         2                     2019-01-02
5 Se5be4e8     NA         0        0         0                     2018-07-03
6 Sc9a3575     NA         0        0         0                     2018-01-31
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P3db7da6        0                   29          2          ⋯
2 P50f102c        0                   32          3          ⋯
3 P735d77f        0                   25          2          ⋯
4 P7ece52e        0                   25          2          ⋯
5 Pbbb08bd        0                   33          3          ⋯
6 Pc9a3575        0                   30          3          ⋯
  missfall.IUFD_week IUFD missfall
1 NA                 NA   NA
2 NA                 NA   NA
3 NA                 NA   NA
4 NA                 NA   NA
5 NA                 NA   NA
6 24                  0    0
  missfall.IUFD_comments
1 NA
2 NA
3 NA
4 NA
5 NA
6 IUFD Jag fick havandeskapsförgiftning i v.22 och var tvungen att bli igångsatt. Flickan föddes i v. 24 +0 och överlevde tyvärr inte.
  Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
1 41              Spontaneous          NA          NA
2 41              Spontaneous          NA          NA
3 39              Spontaneous          NA          NA
4 41              Induction            NA          NA
5 40              Spontaneous          NA          NA
6 24              Induction            NA          NA
  preeclampsia_epi_analysis Group
1 0                         First pregnancy
2 0                         First pregnancy
3 0                         First pregnancy
4 0                         First pregnancy
5 0                         First pregnancy
6 1                         First pregnancy

[1]   9 566

In [54]:
sp_tp1_saliva <- sp_tp1 |>
    filter(!(Q1_Personnummer %in% pn_to_drop))
head(sp_tp1_saliva)
dim(sp_tp1_saliva)

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S3db7da6     NA         0        0         1                     2019-09-24
2 Sa957143     NA         0        0         1                     2020-07-11
3 S9deb4a6     NA         0        0         0                     2019-11-20
4 S7ece52e     NA         0        0         2                     2020-10-21
5 Sbbb08bd     NA         0        0         1                     2019-11-15
6 S99e6192     NA         0        0         1                     2020-05-15
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P3db7da6        0                   30          3          ⋯
2 P50f102c        0                   34          3          ⋯
3 P735d77f        0                   26          2          ⋯
4 P7ece52e        0                   27          2          ⋯
5 Pbbb08bd        0                   34          3          ⋯
6 Pc9a3575        0                   32          3          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     39
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Unlaboured c-section NA          NA    0
6 Spontaneous          very_w28_31  1    1
  Group
1 Second pregnancy
2 Second pregnancy
3 Second pregnancy
4 Second pregnancy
5 Second pregnancy
6 Second pregnancy

[1]   9 566

# Export data --------------------------------------------------------------------------

In [ ]:
# Export metadata tables
# Write to file
#write.table(fp_tp1_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", 
 #                                         Sys.Date(), "_no_min_abundance_fp_tp1_nulliparous_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)

#write.table(sp_tp1_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/",
 #                                         Sys.Date(), "_no_min_abundance_sp_tp1_nulliparous_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)

In [56]:
# Combine both df
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_tp1_saliva, sp_tp1_saliva)
dim(combined_fp_sp)
head(combined_fp_sp)

[1]  18 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S39fe1d7     NA         0        0         0                     2018-06-23
2 S50f102c     NA         0        0         0                     2018-08-05
3 S735d77f     NA         0        0         0                     2018-08-24
4 S9026714     NA         0        0         2                     2019-01-02
5 Se5be4e8     NA         0        0         0                     2018-07-03
6 Sc9a3575     NA         0        0         0                     2018-01-31
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P3db7da6        0                   29          2          ⋯
2 P50f102c        0                   32          3          ⋯
3 P735d77f        0                   25          2          ⋯
4 P7ece52e        0                   25          2          ⋯
5 Pbbb08bd        0                   33          3          ⋯
6 Pc9a3575        0                   30          3          ⋯
  missfall.IUFD_week IUFD missfall
1 NA                 NA   NA
2 NA                 NA   NA
3 NA                 NA   NA
4 NA                 NA   NA
5 NA                 NA   NA
6 24                  0    0
  missfall.IUFD_comments
1 NA
2 NA
3 NA
4 NA
5 NA
6 IUFD Jag fick havandeskapsförgiftning i v.22 och var tvungen att bli igångsatt. Flickan föddes i v. 24 +0 och överlevde tyvärr inte.
  Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
1 41              Spontaneous          NA          NA
2 41              Spontaneous          NA          NA
3 39              Spontaneous          NA          NA
4 41              Induction            NA          NA
5 40              Spontaneous          NA          NA
6 24              Induction            NA          NA
  preeclampsia_epi_analysis Group
1 0                         First pregnancy
2 0                         First pregnancy
3 0                         First pregnancy
4 0                         First pregnancy
5 0                         First pregnancy
6 1                         First pregnancy

In [57]:
#write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/", 
 #                                         Sys.Date(), "_no_min_abundance_combined_nulliparous_fp_sp_tp1_saliva", ".csv"), sep = ",", 
  #          row.names = FALSE)