#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_super_stag_results_taxa_filtering
# Date: 2025.11.19
# Programmer: Barbara Nowak
# Purpose: Compile Super StaG metaphlan results for saliva into taxa table.
# Pick best reads, exclude duplicate or unsequenced samples, exclude minimum abundance and prevalence taxa
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [3]:
library(tidyverse)
library(dplyr)
library(stringr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Load Files  ----------------------------------------------------------------------------------------------

In [4]:
#installed.packages()

In [5]:
# Set working directory to where all metaphlan (and reads) files are
#help("setwd")
setwd("/ceph/projects/010_SweMaMi/bm.nowak/sstag_results/Samples_metaphlan_and_reads/metaphlan_files/")

In [6]:
list.files()

 [1] "E100073476_metaphlan.txt" "E100073508_metaphlan.txt"
 [3] "E100073527_metaphlan.txt" "E100073553_metaphlan.txt"
 [5] "E100074733_metaphlan.txt" "E100074741_metaphlan.txt"
 [7] "E100074769_metaphlan.txt" "E100074852_metaphlan.txt"
 [9] "E100074986_metaphlan.txt" "E111174961_metaphlan.txt"
[11] "E200005523_metaphlan.txt" "E200005561_metaphlan.txt"
[13] "E200005566_metaphlan.txt" "E200005569_metaphlan.txt"
[15] "E200005573_metaphlan.txt" "E200005574_metaphlan.txt"
[17] "E200005579_metaphlan.txt" "E200005581_metaphlan.txt"
[19] "E200005587_metaphlan.txt" "E200005591_metaphlan.txt"
[21] "E200005592_metaphlan.txt" "E200005599_metaphlan.txt"
[23] "E200005600_metaphlan.txt" "E200005601_metaphlan.txt"
[25] "E200005604_metaphlan.txt" "E200005606_metaphlan.txt"
[27] "E200005617_metaphlan.txt" "E200005618_metaphlan.txt"
[29] "E200013379_metaphlan.txt" "E200013398_metaphlan.txt"
[31] "E200013400_metaphlan.txt" "E200013437_metaphlan.txt"

In [7]:
file_list <- list.files() 
length(file_list)
head(file_list)

[1] 32

[1] "E100073476_metaphlan.txt" "E100073508_metaphlan.txt"
[3] "E100073527_metaphlan.txt" "E100073553_metaphlan.txt"
[5] "E100074733_metaphlan.txt" "E100074741_metaphlan.txt"

In [8]:
# read first files so that each flowcell? == one column
files_tabled <- read.table(file_list[1], header = TRUE) 
dim(files_tabled)
head(files_tabled)

[1] 1535   85

  clade_name
1 k__Bacteria
2 k__Bacteria|p__Firmicutes
3 k__Bacteria|p__Bacteroidota
4 k__Bacteria|p__Actinobacteria
5 k__Bacteria|p__Candidatus_Saccharibacteria
6 k__Bacteria|p__Proteobacteria
  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 100.00000                             100.00000
2  40.57446                              44.27937
3  31.89552                              16.48167
4  11.85675                              26.69077
5   7.56801                               1.42516
6   5.72420                              10.40903
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 100.00000                               100.00000
2  36.73116                                66.68932
3  22.02445                                13.95539
4  16.66630                                13.99746
5   1.94253                                 0.23176
6  19.52049                                 5.12607
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 100.00000                              100.00000
2  39.60400                               43.95355
3  15.16283                               20.84680
4  33.08312                               23.18805
5   2.54584                                2.30792
6   6.60701                                5.07465
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1 100.00000                              100.00000
2  62.06284                               58.86059
3   7.60091                               17.94967
4  25.56223                               17.48565
5   0.84112                                1.76397
6   3.77856                                1.83564
  X010_SweMaMi__11551__E100073476_L1_85_ ⋯
1 100.00000                              ⋯
2  45.42766                              ⋯
3  26.17817                              ⋯
4  18.97531                              ⋯
5   3.62014                              ⋯
6   3.53859                              ⋯
  X010_SweMaMi__10535__E100073476_L1_104_
1 100.00000
2  31.56497
3  30.23535
4  21.70559
5   5.79001
6   9.12536
  X010_SweMaMi__10814__E100073476_L1_124_
1 100.00000
2  44.10678
3  27.67272
4  22.74530
5   1.62158
6   1.85656
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 99.24139
2 69.66271
3  0.00750
4  0.03098
5  0.00000
6 29.54020
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 100.00000                               100.00000
2  32.74916                                42.76061
3  40.10263                                19.14150
4  13.12116                                25.57041
5   6.29651                                 3.54489
6   5.71770                                 7.68137
  X010_SweMaMi__10366__E100073476_L1_101_
1 100.00000
2  51.97740
3   9.17092
4  21.58565
5   6.31645
6   8.84412
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1 100.00000                              100.00000
2  54.41398                               38.85777
3   6.68187                               21.89859
4  27.49088                               18.45141
5   0.20516                                6.43051
6  10.50615                               10.22369
  X010_SweMaMi__11258__E100073476_L1_66_
1 100.00000
2  48.74284
3  17.53755
4  16.58855
5   6.71605
6   7.60353
  X010_SweMaMi__10652__E100073476_L1_122_
1 100.00000
2  41.86587
3  18.65936
4  23.71947
5   1.28795
6   9.50498

In [9]:
#colSums(files_tabled[, ])
files_tabled %>%
  select(-1) %>%
  summarise(across(everything(), sum))

  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 788.8468                              795.1167
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 796.8118                                799.3755
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 794.6363                               787.1218
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1 799.4385                               795.09
  X010_SweMaMi__11551__E100073476_L1_85_ X010_SweMaMi__10877__E100073476_L1_91_
1 792.2438                               797.0531
  ⋯ X010_SweMaMi__10535__E100073476_L1_104_
1 ⋯ 790.9308
  X010_SweMaMi__10814__E100073476_L1_124_
1 784.8229
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 800.0001
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 774.9185                                798.046
  X010_SweMaMi__10366__E100073476_L1_101_
1 795.7489
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1 798.9574                               793.7375
  X010_SweMaMi__11258__E100073476_L1_66_
1 792.3754
  X010_SweMaMi__10652__E100073476_L1_122_
1 789.851

In [10]:
#tail(files_tabled)

In [11]:
#help(grepl)

# Join df -------------------------------------------------------------------------------------------------------------------------

 Files are merged horizontaly (each file added to the right).
- While adding, check that each row matches and if there are new rows then add new row.
- full_join merges by keeping rows from both and adding NA if no match.
- Join by using species name (clade)

In [12]:
# matches first "s__", then any char after it ("+"),  may end "([...])?" with "_unclassified", 
# match goes to end of str "$"
match_pattern <- "s__.+(_unclassified)?$"

In [13]:
# Reads each file in setwd if file name present in input list
# Also only keeps rows that match pattern
f_join_tables <- function(input_list_of_files){
    lapply(input_list_of_files, function(a_file){
        
        files_tabled <- read.table(a_file, header = TRUE)
        
        #cat("\nProcessing:", a_file, "\n") # debug line
        print(dim(files_tabled)) # Dim for each df
        
        # finds rows where pattern TRUE (excludes unnecessary taxa info etc since pattern match)
        filtered_tab <- files_tabled |> filter(grepl(match_pattern, clade_name)) 
                
        return(filtered_tab)
    })
    }

all_df_list <- f_join_tables(file_list)
head(all_df_list[[1]]) # check first data frame

[1] 1535   85
[1] 1392   79
[1] 1651   85
[1] 1573   86
[1] 1643   85
[1] 1670   84
[1] 1711   88
[1] 1648   82
[1] 1537   88
[1] 1600   85
[1] 1631   87
[1] 1701   79
[1] 1650   85
[1] 1644   87
[1] 1685   78
[1] 1698   85
[1] 1644   86
[1] 1734   88
[1] 1644   61
[1] 1667   49
[1] 1634   36
[1] 1597   88
[1] 1680   83
[1] 1535   85
[1] 1694   87
[1] 1684   88
[1] 1692   80
[1] 1687   79
[1] 1673   75
[1] 1602   59
[1] 1574   88
[1] 1635   87

  clade_name
1 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_melaninogenica
2 k__Bacteria|p__Candidatus_Saccharibacteria|c__Candidatus_Saccharibacteria_unclassified|o__Candidatus_Saccharibacteria_unclassified|f__Candidatus_Saccharibacteria_unclassified|g__Candidatus_Saccharibacteria_unclassified|s__TM7_phylum_sp_oral_taxon_352
3 k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Veillonella|s__Veillonella_dispar
4 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_salivarius
5 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_pallens
6 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_parasanguinis
  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 15.88133                              7.52610
2  6.15194                              1.35811
3  5.16047                              6.61030
4  3.85011                              6.90766
5  3.54669                              0.70011
6  3.46334                              3.74551
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 1.55257                                  0.00000
2 1.65527                                  0.00000
3 1.56429                                  4.00127
4 2.19696                                 20.62685
5 0.16427                                  0.01262
6 0.97495                                  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 0.90646                                3.41822
2 2.17797                                1.62005
3 3.16944                                4.76538
4 6.61362                                6.85844
5 0.59646                                2.39482
6 6.31109                                3.36495
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1  1.04933                                2.36183
2  0.36381                                0.98670
3  9.36236                                8.23126
4 16.24347                               16.59799
5  0.20566                                1.46584
6  5.77425                                4.84807
  X010_SweMaMi__11551__E100073476_L1_85_ ⋯
1 7.99986                                ⋯
2 1.88438                                ⋯
3 7.87458                                ⋯
4 8.31708                                ⋯
5 3.19061                                ⋯
6 5.41943                                ⋯
  X010_SweMaMi__10535__E100073476_L1_104_
1 8.25667
2 5.31892
3 3.96571
4 3.72460
5 3.44876
6 2.30555
  X010_SweMaMi__10814__E100073476_L1_124_
1 3.40731
2 1.60921
3 6.66593
4 6.32084
5 1.00825
6 6.79054
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 0.00000
2 0.00000
3 0.00516
4 0.00819
5 0.00000
6 0.01544
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 7.37118                                 7.61837
2 5.04779                                 2.07931
3 3.82269                                 7.44099
4 0.92237                                 4.85763
5 7.22204                                 0.60944
6 1.42509                                 2.04594
  X010_SweMaMi__10366__E100073476_L1_101_
1 3.13746
2 5.77997
3 6.83962
4 7.91267
5 1.18837
6 5.41130
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1  0.00000                               3.65614
2  0.00000                               5.50514
3  3.55393                               2.99991
4 19.04877                               6.97655
5  0.00000                               1.52993
6  9.55598                               2.63567
  X010_SweMaMi__11258__E100073476_L1_66_
1 4.35311
2 6.30136
3 4.77804
4 5.10630
5 0.94249
6 3.39435
  X010_SweMaMi__10652__E100073476_L1_122_
1 2.79302
2 0.56413
3 4.07839
4 9.15081
5 1.27910
6 1.96370

In [14]:
head(all_df_list[[32]]) # check last data frame

  clade_name
1 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_mitis
2 k__Bacteria|p__Proteobacteria|c__Betaproteobacteria|o__Neisseriales|f__Neisseriaceae|g__Neisseria|s__Neisseria_subflava
3 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_melaninogenica
4 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Micrococcales|f__Micrococcaceae|g__Rothia|s__Rothia_mucilaginosa
5 k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Veillonella|s__Veillonella_dispar
6 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_parasanguinis
  X010_SweMaMi__18245__E200013437_L1_83_ X010_SweMaMi__21222__E200013437_L1_65_
1 14.96168                               0.85820
2 11.14989                               0.11463
3 10.38855                               1.09584
4  8.58245                               1.77437
5  4.31194                               4.37724
6  4.20654                               5.91425
  X010_SweMaMi__18174__E200013437_L1_80_ X010_SweMaMi__19055__E200013437_L1_33_
1 5.02498                                 9.74931
2 7.78873                                 1.30214
3 1.24644                                12.03281
4 3.01298                                 1.17626
5 0.33371                                 0.00000
6 0.19705                                 0.61701
  X010_SweMaMi__17473__E200013437_L1_69_ X010_SweMaMi__21030__E200013437_L1_35_
1 0.98299                                1.67879
2 0.88839                                1.21240
3 3.84415                                6.61754
4 0.70255                                1.95009
5 3.41613                                5.61947
6 1.57490                                1.72658
  X010_SweMaMi__17569__E200013437_L1_98_ X010_SweMaMi__17716__E200013437_L1_47_
1 14.76020                               1.74674
2  4.29994                               1.84816
3  9.70059                               2.32720
4  3.52260                               5.61698
5  6.50718                               6.34084
6  1.22887                               7.13178
  X010_SweMaMi__21255__E200013437_L1_74_ ⋯
1 1.31933                                ⋯
2 3.08502                                ⋯
3 3.78335                                ⋯
4 5.86515                                ⋯
5 3.76430                                ⋯
6 7.82372                                ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 2.79270
2 0.37906
3 3.91719
4 3.87062
5 6.97362
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1 1.00091                                 2.82163
2 0.10253                                 0.00843
3 0.01522                                 1.55264
4 8.29410                                 4.89969
5 9.72087                                 7.87567
6 9.99736                                 7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 0.96993
2 0.13410
3 4.93655
4 3.63325
5 7.26205
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02544
2 0.08256
3 0.02837
4 0.02951
5 0.01116
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 5.19815                                 1.24325
2 2.86634                                 3.62078
3 6.53807                                 3.30094
4 4.33091                                12.41749
5 7.27621                                 5.88949
6 3.21385                                 7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1  3.93306                               0.78210
2 10.71866                               0.00000
3  8.66169                               3.93085
4  4.25430                               6.32510
5  0.93840                              12.13797
6  3.96688                               9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1  1.50154
2  8.42377
3  3.41636
4 10.89671
5  1.20559
6  1.01967

In [15]:
# full_join merges by keeping rows from both and adding NA if no match and join by using species name (clade) 

joined_table <- reduce(all_df_list, full_join, by = "clade_name") 
# reduce takes each df and joins them together with the previous ones, 
# I.e instead of looping: append this_df with that_df, then append this_df with that_df_2 etc, it takes resulting df and full joins the next df in the list to it

#head(joined_table)
dim(joined_table)
tail(joined_table)
#colnames(joined_table)

[1] 1738 2536

     clade_name
1733 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae
1734 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae|t__SGB8219
1735 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum
1736 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum|t__SGB16958
1737 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium
1738 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium|t__SGB17071
     X010_SweMaMi__1646__E100073476_L1_58_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__9379__E100073476_L1_29_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__10919__E100073476_L1_117_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__9344__E100073476_L1_13_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__12913__E100073476_L1_76_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__13117__E100073476_L1_79_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__12889__E100073476_L1_81_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__10106__E100073476_L1_46_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1733 NA                                       ⋯
1734 NA                                       ⋯
1735 NA                                       ⋯
1736 NA                                       ⋯
1737 NA                                       ⋯
1738 NA                                       ⋯
     X010_SweMaMi__17589__E200013437_L1_91_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__18881__E200013437_L1_102_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21225__E200013437_L1_4_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__20293__E200013437_L1_122_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21180__E200013437_L1_89_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21386__E200013437_L1_62_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21930__E200013437_L1_3_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__17260__E200013437_L1_90_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__18891__E200013437_L1_30_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0

In [16]:
#sorted_names <- joined_table |> sort_by(colnames(joined_table))
#colnames(sorted_names) |> print()

In [17]:
# (colSums(cleaned_ids_filt_new_arrange)) |> sort_by(colnames(cleaned_ids_filt_new_arrange))
#joined_table$clade_name # shows the species names

# Minimum abundance and Prevalence Filtering --------------------------------------------------------------------------------------------------------

Left to do:
- Replace NA with 0
- Clean up strains
- Remove Samples with colSums < 80
- Add other taxa

In [18]:
min_filtered_joined_table <- joined_table %>% {replace(., is.na(.), 0)}
tail(min_filtered_joined_table)

     clade_name
1733 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae
1734 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae|t__SGB8219
1735 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum
1736 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum|t__SGB16958
1737 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium
1738 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium|t__SGB17071
     X010_SweMaMi__1646__E100073476_L1_58_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__9379__E100073476_L1_29_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__10919__E100073476_L1_117_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__9344__E100073476_L1_13_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__12913__E100073476_L1_76_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__13117__E100073476_L1_79_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__12889__E100073476_L1_81_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__10106__E100073476_L1_46_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1733 0                                        ⋯
1734 0                                        ⋯
1735 0                                        ⋯
1736 0                                        ⋯
1737 0                                        ⋯
1738 0                                        ⋯
     X010_SweMaMi__17589__E200013437_L1_91_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__18881__E200013437_L1_102_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21225__E200013437_L1_4_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__20293__E200013437_L1_122_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21180__E200013437_L1_89_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21386__E200013437_L1_62_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21930__E200013437_L1_3_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__17260__E200013437_L1_90_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__18891__E200013437_L1_30_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0

In [19]:
# Rearrange to keep only the species name
sp <- min_filtered_joined_table$clade_name # Extracts clade names
aa <- sub('.*s__', '', sp) # Remove all characters before s__ ("sub()" replaces ".*s__" any char (including s__) with empty string "''" ) 
# eg s__Corynebacterium_pseudogenitalium --> becomes Corynebacterium_pseudogenitalium

#head(min_filtered_joined_table)

t_strain <- grep("t__", aa, value = TRUE) # finds clade-name containing t__ 
#t_strain # list of clades containing "t__"

min_filtered_joined_table$clade_name <- aa # replaces clade name with cleaned species name
new_filtered_tab <- min_filtered_joined_table[!min_filtered_joined_table$clade_name %in% t_strain,] # If a row name (clade_name) appears in list containing "t__" then remove it

In [20]:
head(new_filtered_tab)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 3.91719
2 1.91947
3 6.97362
4 3.59449
5 1.68677
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02837
2 0.05275
3 0.01116
4 0.00792
5 0.02500
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

# Function for removing minimum abundance and prevalence taxa
is_here <- function(invector, min_abund, min_pres){
  min_count <- length(invector) * min_pres
  these <- length(which(invector > min_abund))
  if(these > min_count){
    return(TRUE)
  }
  else{
    return(FALSE)
  }
}

keep <- apply(new_filtered_tab , MARGIN = 1, is_here, min_abund = 0.001, min_pres = 0.05)
filt_taxa <- new_filtered_tab [keep,]
head(filt_taxa)
dim(filt_taxa)

In [21]:
#filt_taxa$clade_name |> sort_by(filt_taxa$clade_name) # Show species alphabetically

In [69]:
# Temporary fix for checking 
filt_taxa <- new_filtered_tab
head(filt_taxa)
dim(filt_taxa)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 3.91719
2 1.91947
3 6.97362
4 3.59449
5 1.68677
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02837
2 0.05275
3 0.01116
4 0.00792
5 0.02500
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

[1]  845 2536

In [23]:
# Select all samples where colSums < 80
col_names_to_drop <- names(filt_taxa)[-1][colSums(filt_taxa[, -1]) < 80] # skip clade_name
length(col_names_to_drop)
head(col_names_to_drop)

[1] 7

[1] "X010_SweMaMi__18253__E200005569_L1_26_"
[2] "X010_SweMaMi__21435__E200005569_L1_114_"
[3] "X010_SweMaMi__21945__E200005569_L1_28_"
[4] "X010_SweMaMi__19694__E200005569_L1_123_"
[5] "X010_SweMaMi__19690__E200005569_L1_122_"
[6] "X010_SweMaMi__17449__E200005569_L1_58_"

In [24]:
#  Remove all samples where colSums < 80
colsum_filt_taxa <- filt_taxa |> 
    select(!all_of(col_names_to_drop))
length(colsum_filt_taxa)
dim(colsum_filt_taxa)

[1] 2529

[1]  845 2529

In [25]:
#colSums(colsum_filt_taxa[, -1]) # Don't count first column (clade_name)

In [26]:
#rownames(colsum_filt_taxa)

In [68]:
# remove rownames and replace with species
rownames(colsum_filt_taxa) <- NULL
head(colsum_filt_taxa)

colsum_filt_taxa_2 <- colsum_filt_taxa |> 
    column_to_rownames(var = names(colsum_filt_taxa)[1])
head(colsum_filt_taxa_2)
dim(colsum_filt_taxa_2)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 3.91719
2 1.91947
3 6.97362
4 3.59449
5 1.68677
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02837
2 0.05275
3 0.01116
4 0.00792
5 0.02500
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

                             X010_SweMaMi__1646__E100073476_L1_58_.x
Prevotella_melaninogenica    15.88133
TM7_phylum_sp_oral_taxon_352  6.15194
Veillonella_dispar            5.16047
Streptococcus_salivarius      3.85011
Prevotella_pallens            3.54669
Streptococcus_parasanguinis   3.46334
                             X010_SweMaMi__9379__E100073476_L1_29_.x
Prevotella_melaninogenica    7.52610
TM7_phylum_sp_oral_taxon_352 1.35811
Veillonella_dispar           6.61030
Streptococcus_salivarius     6.90766
Prevotella_pallens           0.70011
Streptococcus_parasanguinis  3.74551
                             X010_SweMaMi__10919__E100073476_L1_117_.x
Prevotella_melaninogenica    1.55257
TM7_phylum_sp_oral_taxon_352 1.65527
Veillonella_dispar           1.56429
Streptococcus_salivarius     2.19696
Prevotella_pallens           0.16427
Streptococcus_parasanguinis  0.97495
                             X010_SweMaMi__9344__E100073476_L1_13_.x
Prevotella_melaninogenica     0.00000
TM7_phylum_sp_oral_taxon_352  0.00000
Veillonella_dispar            4.00127
Streptococcus_salivarius     20.62685
Prevotella_pallens            0.01262
Streptococcus_parasanguinis   5.04926
                             X010_SweMaMi__12913__E100073476_L1_76_.x
Prevotella_melaninogenica    0.90646
TM7_phylum_sp_oral_taxon_352 2.17797
Veillonella_dispar           3.16944
Streptococcus_salivarius     6.61362
Prevotella_pallens           0.59646
Streptococcus_parasanguinis  6.31109
                             X010_SweMaMi__13117__E100073476_L1_79_.x
Prevotella_melaninogenica    3.41822
TM7_phylum_sp_oral_taxon_352 1.62005
Veillonella_dispar           4.76538
Streptococcus_salivarius     6.85844
Prevotella_pallens           2.39482
Streptococcus_parasanguinis  3.36495
                             X010_SweMaMi__12889__E100073476_L1_81_.x
Prevotella_melaninogenica     1.04933
TM7_phylum_sp_oral_taxon_352  0.36381
Veillonella_dispar            9.36236
Streptococcus_salivarius     16.24347
Prevotella_pallens            0.20566
Streptococcus_parasanguinis   5.77425
                             X010_SweMaMi__10106__E100073476_L1_46_.x
Prevotella_melaninogenica     2.36183
TM7_phylum_sp_oral_taxon_352  0.98670
Veillonella_dispar            8.23126
Streptococcus_salivarius     16.59799
Prevotella_pallens            1.46584
Streptococcus_parasanguinis   4.84807
                             X010_SweMaMi__11551__E100073476_L1_85_.x
Prevotella_melaninogenica    7.99986
TM7_phylum_sp_oral_taxon_352 1.88438
Veillonella_dispar           7.87458
Streptococcus_salivarius     8.31708
Prevotella_pallens           3.19061
Streptococcus_parasanguinis  5.41943
                             X010_SweMaMi__10877__E100073476_L1_91_.x ⋯
Prevotella_melaninogenica     0.98840                                 ⋯
TM7_phylum_sp_oral_taxon_352  0.11358                                 ⋯
Veillonella_dispar           13.58697                                 ⋯
Streptococcus_salivarius     18.72063                                 ⋯
Prevotella_pallens            0.67060                                 ⋯
Streptococcus_parasanguinis  11.27242                                 ⋯
                             X010_SweMaMi__17589__E200013437_L1_91_
Prevotella_melaninogenica    3.91719
TM7_phylum_sp_oral_taxon_352 1.91947
Veillonella_dispar           6.97362
Streptococcus_salivarius     3.59449
Prevotella_pallens           1.68677
Streptococcus_parasanguinis  3.28812
                             X010_SweMaMi__18881__E200013437_L1_102_
Prevotella_melaninogenica     0.01522
TM7_phylum_sp_oral_taxon_352  0.99134
Veillonella_dispar            9.72087
Streptococcus_salivarius     18.06276
Prevotella_pallens            0.52037
Streptococcus_parasanguinis   9.99736
                             X010_SweMaMi__21225__E200013437_L1_4_
Prevotella_melaninogenica    1.55264
TM7_phylum_sp_oral_taxon_352 2.07174
Veillonella_dispar           7.87567
Streptococcus_salivarius     6.99764
Prevotella_pallens           2.04457
Streptococcus_parasanguinis  7.00401
                             X010_SweMaMi__20293__E200013437_L1_122_
Prevotella_melaninogenica    4.93655
TM7_phylum_sp_oral_taxon_352 0.46493
Veillonella_dispar           7.26205
Streptococcus_salivarius     9.51983
Prevotella_pallens           2.32954
Streptococcus_parasanguinis  2.73461
                             X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
Prevotella_melaninogenica    0.02837
TM7_phylum_sp_oral_taxon_352 0.05275
Veillonella_dispar           0.01116
Streptococcus_salivarius     0.00792
Prevotella_pallens           0.02500
Streptococcus_parasanguinis  0.00335
                             X010_SweMaMi__21180__E200013437_L1_89_
Prevotella_melaninogenica    6.53807
TM7_phylum_sp_oral_taxon_352 1.60654
Veillonella_dispar           7.27621
Streptococcus_salivarius     2.35358
Prevotella_pallens           3.84069
Streptococcus_parasanguinis  3.21385
                             X010_SweMaMi__21386__E200013437_L1_62_
Prevotella_melaninogenica    3.30094
TM7_phylum_sp_oral_taxon_352 3.36108
Veillonella_dispar           5.88949
Streptococcus_salivarius     6.62331
Prevotella_pallens           0.71656
Streptococcus_parasanguinis  7.10522
                             X010_SweMaMi__21930__E200013437_L1_3_
Prevotella_melaninogenica    8.66169
TM7_phylum_sp_oral_taxon_352 1.29958
Veillonella_dispar           0.93840
Streptococcus_salivarius     1.23692
Prevotella_pallens           1.85049
Streptococcus_parasanguinis  3.96688
                             X010_SweMaMi__17260__E200013437_L1_90_
Prevotella_melaninogenica     3.93085
TM7_phylum_sp_oral_taxon_352  1.20771
Veillonella_dispar           12.13797
Streptococcus_salivarius     12.70253
Prevotella_pallens            1.24524
Streptococcus_parasanguinis   9.57804
                             X010_SweMaMi__18891__E200013437_L1_30_
Prevotella_melaninogenica    3.41636
TM7_phylum_sp_oral_taxon_352 1.13150
Veillonella_dispar           1.20559
Streptococcus_salivarius     6.49664
Prevotella_pallens           0.92643
Streptococcus_parasanguinis  1.01967

[1]  845 2528

In [28]:
#sort(colnames(colsum_filt_taxa_2))  
#X010_SweMaMi__10334__E100073476_L1_127_.x''X010_SweMaMi__10334__E100073476_L1_127_.y''X010_SweMaMi__10334__E100074733_L1_127_'

In [29]:
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_"]]), na.rm = TRUE)
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_.x"]]), na.rm = TRUE)
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_.y"]]), na.rm = TRUE)

[1] 0

[1] 100

[1] 100

In [30]:
#colSums(filt_new_arrange) # Don't count first column (clade_name)

In [31]:
tail(colsum_filt_taxa_2)

                                 X010_SweMaMi__1646__E100073476_L1_58_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__9379__E100073476_L1_29_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__10919__E100073476_L1_117_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__9344__E100073476_L1_13_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__12913__E100073476_L1_76_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__13117__E100073476_L1_79_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__12889__E100073476_L1_81_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__10106__E100073476_L1_46_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__11551__E100073476_L1_85_.x
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__10877__E100073476_L1_91_.x ⋯
Acinetobacter_lwoffii            0                                        ⋯
Brachybacterium_nesterenkovii    0                                        ⋯
GGB6673_SGB99879                 0                                        ⋯
Streptococcus_dysgalactiae       0                                        ⋯
Cutibacterium_granulosum         0                                        ⋯
Corynebacterium_pseudogenitalium 0                                        ⋯
                                 X010_SweMaMi__17589__E200013437_L1_91_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__18881__E200013437_L1_102_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__21225__E200013437_L1_4_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__20293__E200013437_L1_122_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__21180__E200013437_L1_89_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__21386__E200013437_L1_62_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__21930__E200013437_L1_3_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__17260__E200013437_L1_90_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0
                                 X010_SweMaMi__18891__E200013437_L1_30_
Acinetobacter_lwoffii            0
Brachybacterium_nesterenkovii    0
GGB6673_SGB99879                 0
Streptococcus_dysgalactiae       0
Cutibacterium_granulosum         0
Corynebacterium_pseudogenitalium 0

# Clean up IDs ----------------------------------------------------------------------------------------------------------------------------

In [32]:
#sort(colnames(colsum_filt_taxa_2))

Same flowcell: check one 
Different flowcell: check after host removal reads

# keep sample ID and flowcell num
ids <- colnames(colsum_filt_taxa_2) # Extract names 
ids_nsmm <- sub( 'X010_SweMaMi__','', ids) # remove all char before X010_SweMaMi__ and replace with blank space
head(ids_nsmm)
#ids_nsmm_ne <- sub('__E.*', '', ids_nsmm) # also removes .x which I want to keep
ids_nsmm_ne <- sub('__E.*?([\\a-zA-Z]*)$', '\\1', ids_nsmm) # Matches E and everything after (not greedy), captures any trailing letters (at the end == $), then replaces match with captured letter
#head(ids_nsmm_ne)
length(ids_nsmm_ne)

In [33]:
#colnames(colsum_filt_taxa_2)

In [34]:
ids <- colnames(colsum_filt_taxa_2) # Extract names 
ids_nsmm <- sub( 'X010_SweMaMi__','', ids) # remove all char before X010_SweMaMi__ and replace with blank space
#flowcell will end in a number and then _

core <- sub('^(\\d+__E[0-9]+).*', "\\1", ids_nsmm) # extract sampleID and flowcellID and keep
head(core)

suffix <- sub('.*?([a-zA-Z]*)$', '\\1', ids_nsmm) # extract trailing letters
head(suffix)
length(suffix)
#head(ids_nsmm_ne)
#length(ids_nsmm_ne)
#ids_nsmm_ne

[1] "1646__E100073476"  "9379__E100073476"  "10919__E100073476"
[4] "9344__E100073476"  "12913__E100073476" "13117__E100073476"

[1] "x" "x" "x" "x" "x" "x"

[1] 2528

In [35]:
ids_nsmm_ne <- paste0(core, suffix)
head(ids_nsmm_ne)
length(ids_nsmm_ne)
#sort(ids_nsmm_ne) |> print()

[1] "1646__E100073476x"  "9379__E100073476x"  "10919__E100073476x"
[4] "9344__E100073476x"  "12913__E100073476x" "13117__E100073476x"

[1] 2528

Additional columns that need to be droped
- Those that contain something like "zymock"--> those are not sequenced
- Also some samples contain no sample id, instead have what looks like 2 flowcell ids
those don't have sample IDs
- Save any cols starting with a letter 
-  --> exclude any that start with a letter

In [36]:
#valid_cols <- grepl('^\\d+', core)  # TRUE for columns starting with digits
#ids_nsmm_ne <- ids_nsmm_ne[valid_cols]

#core <- core[valid_cols]
#suffix <- suffix[valid_cols]


# Replaces any columns NOT starting with didgit with NULL 
# This makes it easier to exclude invalid columns but keep the correct ID for columns
ids_nsmm_ne_NULL <- ifelse(grepl('^\\d+', core), ids_nsmm_ne, "NULL")
# Check
head(ids_nsmm_ne_NULL)
length(ids_nsmm_ne_NULL)

#sort(ids_nsmm_ne_NULL) |> print()

[1] "1646__E100073476x"  "9379__E100073476x"  "10919__E100073476x"
[4] "9344__E100073476x"  "12913__E100073476x" "13117__E100073476x"

[1] 2528

In [37]:
cleaned_ids_filt_new_arrange <- colsum_filt_taxa_2 |> set_names(ids_nsmm_ne_NULL)
head(cleaned_ids_filt_new_arrange)
dim(cleaned_ids_filt_new_arrange)

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             17589__E200013437 18881__E200013437
Prevotella_melaninogenica    3.91719            0.01522
TM7_phylum_sp_oral_taxon_352 1.91947            0.99134
Veillonella_dispar           6.97362            9.72087
Streptococcus_salivarius     3.59449           18.06276
Prevotella_pallens           1.68677            0.52037
Streptococcus_parasanguinis  3.28812            9.99736
                             21225__E200013437 20293__E200013437 NULL
Prevotella_melaninogenica    1.55264           4.93655           0.02837
TM7_phylum_sp_oral_taxon_352 2.07174           0.46493           0.05275
Veillonella_dispar           7.87567           7.26205           0.01116
Streptococcus_salivarius     6.99764           9.51983           0.00792
Prevotella_pallens           2.04457           2.32954           0.02500
Streptococcus_parasanguinis  7.00401           2.73461           0.00335
                             21180__E200013437 21386__E200013437
Prevotella_melaninogenica    6.53807           3.30094
TM7_phylum_sp_oral_taxon_352 1.60654           3.36108
Veillonella_dispar           7.27621           5.88949
Streptococcus_salivarius     2.35358           6.62331
Prevotella_pallens           3.84069           0.71656
Streptococcus_parasanguinis  3.21385           7.10522
                             21930__E200013437 17260__E200013437
Prevotella_melaninogenica    8.66169            3.93085
TM7_phylum_sp_oral_taxon_352 1.29958            1.20771
Veillonella_dispar           0.93840           12.13797
Streptococcus_salivarius     1.23692           12.70253
Prevotella_pallens           1.85049            1.24524
Streptococcus_parasanguinis  3.96688            9.57804
                             18891__E200013437
Prevotella_melaninogenica    3.41636
TM7_phylum_sp_oral_taxon_352 1.13150
Veillonella_dispar           1.20559
Streptococcus_salivarius     6.49664
Prevotella_pallens           0.92643
Streptococcus_parasanguinis  1.01967

[1]  845 2528

In [38]:
# Exclude invalid (NULL) colnames
all_valid_ids_filt_new_arrange <- cleaned_ids_filt_new_arrange |> select((!matches("^Null$")))
dim(all_valid_ids_filt_new_arrange)
head(all_valid_ids_filt_new_arrange)

[1]  845 2396

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             19612__E200013437 17589__E200013437
Prevotella_melaninogenica    2.27635           3.91719
TM7_phylum_sp_oral_taxon_352 2.03540           1.91947
Veillonella_dispar           2.17340           6.97362
Streptococcus_salivarius     3.08711           3.59449
Prevotella_pallens           0.62355           1.68677
Streptococcus_parasanguinis  1.56545           3.28812
                             18881__E200013437 21225__E200013437
Prevotella_melaninogenica     0.01522          1.55264
TM7_phylum_sp_oral_taxon_352  0.99134          2.07174
Veillonella_dispar            9.72087          7.87567
Streptococcus_salivarius     18.06276          6.99764
Prevotella_pallens            0.52037          2.04457
Streptococcus_parasanguinis   9.99736          7.00401
                             20293__E200013437 21180__E200013437
Prevotella_melaninogenica    4.93655           6.53807
TM7_phylum_sp_oral_taxon_352 0.46493           1.60654
Veillonella_dispar           7.26205           7.27621
Streptococcus_salivarius     9.51983           2.35358
Prevotella_pallens           2.32954           3.84069
Streptococcus_parasanguinis  2.73461           3.21385
                             21386__E200013437 21930__E200013437
Prevotella_melaninogenica    3.30094           8.66169
TM7_phylum_sp_oral_taxon_352 3.36108           1.29958
Veillonella_dispar           5.88949           0.93840
Streptococcus_salivarius     6.62331           1.23692
Prevotella_pallens           0.71656           1.85049
Streptococcus_parasanguinis  7.10522           3.96688
                             17260__E200013437 18891__E200013437
Prevotella_melaninogenica     3.93085          3.41636
TM7_phylum_sp_oral_taxon_352  1.20771          1.13150
Veillonella_dispar           12.13797          1.20559
Streptococcus_salivarius     12.70253          6.49664
Prevotella_pallens            1.24524          0.92643
Streptococcus_parasanguinis   9.57804          1.01967

In [39]:
((colnames(all_valid_ids_filt_new_arrange))) |> sort() |> head()

[1] "10009__E200005523" "10020__E100073553" "10021__E100073527"
[4] "10021__E111174961" "10026__E100073553" "10028__E100073553"

In [40]:
#colSums(all_valid_ids_filt_new_arrange) |> sort_by(colnames(all_valid_ids_filt_new_arrange)) |> head() |> print()

# Exclude y columns ---------------------------------------------------------------------------------------

Check all colnames that end in x or y.   
Duplicates that can be excluded randomly, for example all ending in y.  
If a column starts with the same sampleID more than once AND one of them ends in x or y then exclude the one that ends in a digit 
- This way only one sample ID of the same flowcell is keept (later easier to check reads if sampleIDs appear only once in any one flowcell)

In [41]:
# Check all colnames that end in x or y

#pattern for end
end_pattern <- '[a-zA-Z]$'

pulled_prefix <- grep(end_pattern, colnames(all_valid_ids_filt_new_arrange), value = TRUE) |> sub('[a-zA-Z]$', "", x = _)
head(pulled_prefix)

[1] "1646__E100073476"  "9379__E100073476"  "10919__E100073476"
[4] "9344__E100073476"  "12913__E100073476" "13117__E100073476"

In [42]:
# Double check that x and y are the same
colSums(all_valid_ids_filt_new_arrange |> select(matches(end_pattern))) %>% .[order(names(.))] %>% head()

10106__E100073476x 10106__E100073476y 10273__E100073476x 10273__E100073476y
          100.0001           100.0001           100.0000           100.0000
10300__E100073476x 10300__E100073476y
          100.0001           100.0001

In [43]:
# Check that no column exists also without suffix if one with suffix does exists
matching_cols <- colnames(all_valid_ids_filt_new_arrange)[colnames(all_valid_ids_filt_new_arrange) %in% pulled_prefix] 
matching_cols

character(0)

Now exclude all cols ending in y

In [44]:
y_exclude_filt_new_arrange <- all_valid_ids_filt_new_arrange |> select(-matches('y$'))
colnames(y_exclude_filt_new_arrange) |> sort() |> head() 
colnames(y_exclude_filt_new_arrange) |> sort() |> tail() 
dim(y_exclude_filt_new_arrange)

[1] "10009__E200005523" "10020__E100073553" "10021__E100073527"
[4] "10021__E111174961" "10026__E100073553" "10028__E100073553"

[1] "9893__E200005561" "9900__E100074852" "9901__E200005523" "9909__E200013398"
[5] "9919__E100074769" "9921__E100074769"

[1]  845 2315

In [45]:
# Check that all is correct as before
#colSums(y_exclude_filt_new_arrange) |> sort_by(colnames(y_exclude_filt_new_arrange))  |> head(n = 30)

In [46]:
head(y_exclude_filt_new_arrange)
dim(y_exclude_filt_new_arrange)

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             19612__E200013437 17589__E200013437
Prevotella_melaninogenica    2.27635           3.91719
TM7_phylum_sp_oral_taxon_352 2.03540           1.91947
Veillonella_dispar           2.17340           6.97362
Streptococcus_salivarius     3.08711           3.59449
Prevotella_pallens           0.62355           1.68677
Streptococcus_parasanguinis  1.56545           3.28812
                             18881__E200013437 21225__E200013437
Prevotella_melaninogenica     0.01522          1.55264
TM7_phylum_sp_oral_taxon_352  0.99134          2.07174
Veillonella_dispar            9.72087          7.87567
Streptococcus_salivarius     18.06276          6.99764
Prevotella_pallens            0.52037          2.04457
Streptococcus_parasanguinis   9.99736          7.00401
                             20293__E200013437 21180__E200013437
Prevotella_melaninogenica    4.93655           6.53807
TM7_phylum_sp_oral_taxon_352 0.46493           1.60654
Veillonella_dispar           7.26205           7.27621
Streptococcus_salivarius     9.51983           2.35358
Prevotella_pallens           2.32954           3.84069
Streptococcus_parasanguinis  2.73461           3.21385
                             21386__E200013437 21930__E200013437
Prevotella_melaninogenica    3.30094           8.66169
TM7_phylum_sp_oral_taxon_352 3.36108           1.29958
Veillonella_dispar           5.88949           0.93840
Streptococcus_salivarius     6.62331           1.23692
Prevotella_pallens           0.71656           1.85049
Streptococcus_parasanguinis  7.10522           3.96688
                             17260__E200013437 18891__E200013437
Prevotella_melaninogenica     3.93085          3.41636
TM7_phylum_sp_oral_taxon_352  1.20771          1.13150
Veillonella_dispar           12.13797          1.20559
Streptococcus_salivarius     12.70253          6.49664
Prevotella_pallens            1.24524          0.92643
Streptococcus_parasanguinis   9.57804          1.01967

[1]  845 2315

# Check reads -----------------------------------------------------------------------------------------------------------

Now check reads:
- Any flowcells that have a duplicate ending in x or y --> just pick one --> those are accidental duplicates
- Any col, ending in x or y are duplicates of same flowcell and sample --> just pick either
- Any samples that exist in two different flowcells: check reads and pick highest one

In [47]:
setwd("/ceph/projects/010_SweMaMi/bm.nowak/sstag_results/Samples_metaphlan_and_reads/reads_files")

In [48]:
file_list_reads <- list.files()

In [49]:
file_list_reads[1]

[1] "E100073476_preprocessing_read_counts.txt"

In [50]:
reads_tabled <- read.table(file_list_reads[1], header = TRUE) 
dim(reads_tabled)
head(reads_tabled)

[1] 84  5

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

In [51]:
# Reads each file in setwd if file name present in input list
f_join_tables_reads_vertical <- function(input_list_of_files){
    lapply(input_list_of_files, function(a_file){
        
        files_tabled <- read.table(a_file, header = TRUE)
        
        #cat("\nProcessing:", a_file, "\n") # debug line
        #print(dim(files_tabled)) # Dim for each df
                
        return(files_tabled)
    })
    }

all_reads_df <- f_join_tables_reads_vertical(file_list_reads)
head(all_reads_df[[1]]) # check first data frame

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

In [52]:
joined_table_reads <- bind_rows(all_reads_df)
head (joined_table_reads)
dim(joined_table_reads)

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

[1] 2534    5

Run same code as before to remove unwanted char from sample IDs
But split so flowcell and sample ID is separate

In [53]:
joined_table_id_cols <- joined_table_reads |> 
# Extracts col into two new columns: __(\\d+)  and __([E][0-9]+).*  " .*?" skips everything before
    extract( 
    col = Sample,
    into = c("SampleID", "EID"),
    regex = ".*?__(\\d+)__([E][0-9]+).*"
  )

head(joined_table_id_cols)
tail(joined_table_id_cols)

  SampleID EID        duplication before_fastp after_fastp
1 10106    E100073476 0.00356886  29921360     26989691
2 10273    E100073476 0.00285863  24215813     22036296
3 10300    E100073476 0.00445974  37433144     33674569
4 10334    E100073476 0.00372570  31416878     28389354
5 10346    E100073476 0.00316506  26756212     24218990
6 10366    E100073476 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

     SampleID EID        duplication before_fastp after_fastp
2529 21929    E200013437 0.00788660  66739419     66605012
2530 21930    E200013437 0.00788477  65871386     65735842
2531 NA       NA         0.01167810  59986372     59869294
2532 NA       NA         0.01046340  79858743     79701108
2533 NA       NA         0.01117510  85380498     85208710
2534 NA       NA         0.00847576  61283009     61162317
     after_kraken2_host_removal
2529 17960155
2530 15497124
2531 59817026
2532 78882409
2533 85187521
2534 60587883

Some samples have more than one flowcell:

In [54]:
joined_table_id_cols$SampleID |> sort() |> head() |> print()

[1] "10009" "10020" "10021" "10021" "10026" "10028"

In [55]:
joined_table_id_cols |> filter(!is.na(SampleID)) |> 
    group_by(SampleID) |> 
    filter(n() > 1 ) |> 
    summarise(EID_list = paste(EID, collapse = ", "), n = n ()) |>
    head()

  SampleID EID_list               n
1 10021    E100073527, E111174961 2
2 10056    E100073527, E111174961 2
3 10058    E100073527, E111174961 2
4 10066    E100073527, E111174961 2
5 10077    E100074986, E200013400 2
6 10104    E100073508, E200005561 2

## Find and Extract highest reads

If the prefix of colnames in 'y_exclude_filt_new_arrange' appears more than once, then check reads for that prefix in 'joined_table_id_cols' --> see which flowcell has more reads (after_kraken2_host_removal)
The flowcell coresponding to higher reads is keept

In [56]:
# Extract flowcells and sampleids
colnames_info <- colnames(y_exclude_filt_new_arrange)
prefix_info <- str_extract(colnames_info, '^[^_]+')
sort(prefix_info) |> head(prefix_info, n = 20) 

flowcell_ids <- str_extract(colnames_info, '(?<=__)[^x]+')
head(flowcell_ids, n = 20)

 [1] "10009" "10020" "10021" "10021" "10026" "10028" "10036" "10048" "1005"
[10] "10056" "10056" "10058" "10058" "10064" "10065" "10066" "10066" "10074"
[19] "10075" "10076"

 [1] "E100073476" "E100073476" "E100073476" "E100073476" "E100073476"
 [6] "E100073476" "E100073476" "E100073476" "E100073476" "E100073476"
[11] "E100073476" "E100073476" "E100073476" "E100073476" "E100073476"
[16] "E100073476" "E100073476" "E100073476" "E100073476" "E100073476"

In [57]:
# Extract duplicate samples
duplicate_ids <- prefix_info[duplicated(prefix_info) | duplicated(prefix_info, fromLast = TRUE)] |> unique()
sort(duplicate_ids) |> head(duplicate_ids, n = 20) 
length(duplicate_ids)

 [1] "10021" "10056" "10058" "10066" "10077" "10104" "10106" "1012"  "10131"
[10] "10134" "1015"  "10167" "1017"  "10193" "10213" "10273" "1028"  "10300"
[19] "10334" "10346"

[1] 321

In [58]:
# For each duplicate sampleID, find flowcell with the highest reads
duplicate_rows <- joined_table_id_cols |> filter(SampleID %in% duplicate_ids)

dim(duplicate_rows)
#duplicate_rows |> sort_by(duplicate_rows$SampleID) |> head()

[1] 642   6

In [59]:
# Find and extract flowcell with highest reads
highest_reads_flowcell <- duplicate_rows |>
    group_by(SampleID) |>
    slice_max(after_kraken2_host_removal, n = 1, with_ties = FALSE) |> # Inside each sampleID group: selects highest reads
    ungroup() |>
    select(SampleID, EID)

dim(highest_reads_flowcell)
head(highest_reads_flowcell)

[1] 321   2

  SampleID EID
1 10021    E100073527
2 10056    E100073527
3 10058    E100073527
4 10066    E100073527
5 10077    E200013400
6 10104    E200005561

Maybe this function is what causes issues with the reads?:

In [60]:
# Which columns to keep 
# sapply: collects all (TRUE/FALSE) into logical vector keep_cols 
keep_cols <- sapply(seq_along(colnames_info), function(i){ # loop over all columns 1-n, and for each column do
    
    # If sample (prefix) is not duplicate then keep it
    if (!(prefix_info[i] %in% duplicate_ids)) return(TRUE)

    # otherwise the sample is duplicate; then keep only if flowcell matches best flowcell for that sample  
    best_flowcell <- highest_reads_flowcell$EID[highest_reads_flowcell$SampleID == prefix_info[i]]
    prefix_info[i] %in% best_flowcell
})

best_reads_filt_new_arrange <- y_exclude_filt_new_arrange[, keep_cols]
dim(best_reads_filt_new_arrange)
head(best_reads_filt_new_arrange)

[1]  845 1673

                             11601__E100073553 921__E100073553 7766__E100073553
Prevotella_melaninogenica    7.46856           4.43305         2.01303
TM7_phylum_sp_oral_taxon_352 3.14409           2.21632         0.27918
Veillonella_dispar           3.16098           1.97065         5.15186
Streptococcus_salivarius     6.66179           2.07087         9.56769
Prevotella_pallens           1.09428           4.69337         0.48324
Streptococcus_parasanguinis  5.05936           5.04811         4.55327
                             11497__E100073553 10644__E100073553
Prevotella_melaninogenica    3.09323           2.18746
TM7_phylum_sp_oral_taxon_352 0.81149           0.10544
Veillonella_dispar           5.76151           3.67418
Streptococcus_salivarius     4.59215           7.84402
Prevotella_pallens           3.19061           0.00000
Streptococcus_parasanguinis  3.91857           2.32197
                             7547__E100073553 10048__E100073553
Prevotella_melaninogenica     2.89516         5.46348
TM7_phylum_sp_oral_taxon_352  1.92240         1.88095
Veillonella_dispar            3.17602         4.86584
Streptococcus_salivarius     12.85163         7.59421
Prevotella_pallens            0.86855         4.79881
Streptococcus_parasanguinis   3.38418         3.75756
                             10681__E100073553 13611__E100073553
Prevotella_melaninogenica    7.60818           2.66597
TM7_phylum_sp_oral_taxon_352 0.70932           2.10826
Veillonella_dispar           7.54436           0.60527
Streptococcus_salivarius     8.05424           0.36229
Prevotella_pallens           1.50316           1.29621
Streptococcus_parasanguinis  4.71644           1.78240
                             1054__E100073553 ⋯ 19612__E200013437
Prevotella_melaninogenica     7.05540         ⋯ 2.27635
TM7_phylum_sp_oral_taxon_352  1.12378         ⋯ 2.03540
Veillonella_dispar           13.37827         ⋯ 2.17340
Streptococcus_salivarius     23.52221         ⋯ 3.08711
Prevotella_pallens            0.03604         ⋯ 0.62355
Streptococcus_parasanguinis  11.06978         ⋯ 1.56545
                             17589__E200013437 18881__E200013437
Prevotella_melaninogenica    3.91719            0.01522
TM7_phylum_sp_oral_taxon_352 1.91947            0.99134
Veillonella_dispar           6.97362            9.72087
Streptococcus_salivarius     3.59449           18.06276
Prevotella_pallens           1.68677            0.52037
Streptococcus_parasanguinis  3.28812            9.99736
                             21225__E200013437 20293__E200013437
Prevotella_melaninogenica    1.55264           4.93655
TM7_phylum_sp_oral_taxon_352 2.07174           0.46493
Veillonella_dispar           7.87567           7.26205
Streptococcus_salivarius     6.99764           9.51983
Prevotella_pallens           2.04457           2.32954
Streptococcus_parasanguinis  7.00401           2.73461
                             21180__E200013437 21386__E200013437
Prevotella_melaninogenica    6.53807           3.30094
TM7_phylum_sp_oral_taxon_352 1.60654           3.36108
Veillonella_dispar           7.27621           5.88949
Streptococcus_salivarius     2.35358           6.62331
Prevotella_pallens           3.84069           0.71656
Streptococcus_parasanguinis  3.21385           7.10522
                             21930__E200013437 17260__E200013437
Prevotella_melaninogenica    8.66169            3.93085
TM7_phylum_sp_oral_taxon_352 1.29958            1.20771
Veillonella_dispar           0.93840           12.13797
Streptococcus_salivarius     1.23692           12.70253
Prevotella_pallens           1.85049            1.24524
Streptococcus_parasanguinis  3.96688            9.57804
                             18891__E200013437
Prevotella_melaninogenica    3.41636
TM7_phylum_sp_oral_taxon_352 1.13150
Veillonella_dispar           1.20559
Streptococcus_salivarius     6.49664
Prevotella_pallens           0.92643
Streptococcus_parasanguinis  1.01967

In [61]:
colnames(best_reads_filt_new_arrange) |> sort() |> head(, n = 20)

 [1] "10009__E200005523" "10020__E100073553" "10026__E100073553"
 [4] "10028__E100073553" "10036__E200005587" "10048__E100073553"
 [7] "1005__E200013379"  "10064__E100073553" "10065__E200005523"
[10] "10074__E200005523" "10075__E200005587" "10076__E200005587"
[13] "1009__E200005604"  "10098__E200005523" "1010__E200005604"
[16] "10119__E100074852" "10132__E200005523" "1014__E200013379"
[19] "10146__E200005599" "10148__E100074852"

# y_exclude_filt_new_arrange had 2309 columns, 321 were duplicates --> 2309 - 321 = 1988

In [62]:
# colSums(best_reads_filt_new_arrange) |> sort_by(colnames(best_reads_filt_new_arrange)) |> head (, n = 20) |> print()

In [63]:
#colSums(y_exclude_filt_new_arrange) |> sort_by(colnames(y_exclude_filt_new_arrange)) |> head (, n = 20) |> print()

# Clean away flowcell-IDs from taxa table ----------------------------------------------------------------

In [64]:
# Clean flowcell id and export as csv
dirty_colnames <- colnames(best_reads_filt_new_arrange)
head(dirty_colnames)

cleaned_colnames <- sub( "^([0-9]+)__.*$", '\\1', dirty_colnames) # capture one or more digits at the start of string, discard everything else
head(cleaned_colnames)

[1] "11601__E100073553" "921__E100073553"   "7766__E100073553"
[4] "11497__E100073553" "10644__E100073553" "7547__E100073553"

[1] "11601" "921"   "7766"  "11497" "10644" "7547"

In [65]:
# Assign clean IDs
cleaned_taxa_tab <- best_reads_filt_new_arrange |> set_names(cleaned_colnames)
dim(cleaned_taxa_tab)
head(cleaned_taxa_tab)

[1]  845 1673

                             11601   921     7766    11497   10644   7547
Prevotella_melaninogenica    7.46856 4.43305 2.01303 3.09323 2.18746  2.89516
TM7_phylum_sp_oral_taxon_352 3.14409 2.21632 0.27918 0.81149 0.10544  1.92240
Veillonella_dispar           3.16098 1.97065 5.15186 5.76151 3.67418  3.17602
Streptococcus_salivarius     6.66179 2.07087 9.56769 4.59215 7.84402 12.85163
Prevotella_pallens           1.09428 4.69337 0.48324 3.19061 0.00000  0.86855
Streptococcus_parasanguinis  5.05936 5.04811 4.55327 3.91857 2.32197  3.38418
                             10048   10681   13611   1054     ⋯ 19612   17589
Prevotella_melaninogenica    5.46348 7.60818 2.66597  7.05540 ⋯ 2.27635 3.91719
TM7_phylum_sp_oral_taxon_352 1.88095 0.70932 2.10826  1.12378 ⋯ 2.03540 1.91947
Veillonella_dispar           4.86584 7.54436 0.60527 13.37827 ⋯ 2.17340 6.97362
Streptococcus_salivarius     7.59421 8.05424 0.36229 23.52221 ⋯ 3.08711 3.59449
Prevotella_pallens           4.79881 1.50316 1.29621  0.03604 ⋯ 0.62355 1.68677
Streptococcus_parasanguinis  3.75756 4.71644 1.78240 11.06978 ⋯ 1.56545 3.28812
                             18881    21225   20293   21180   21386   21930
Prevotella_melaninogenica     0.01522 1.55264 4.93655 6.53807 3.30094 8.66169
TM7_phylum_sp_oral_taxon_352  0.99134 2.07174 0.46493 1.60654 3.36108 1.29958
Veillonella_dispar            9.72087 7.87567 7.26205 7.27621 5.88949 0.93840
Streptococcus_salivarius     18.06276 6.99764 9.51983 2.35358 6.62331 1.23692
Prevotella_pallens            0.52037 2.04457 2.32954 3.84069 0.71656 1.85049
Streptococcus_parasanguinis   9.99736 7.00401 2.73461 3.21385 7.10522 3.96688
                             17260    18891
Prevotella_melaninogenica     3.93085 3.41636
TM7_phylum_sp_oral_taxon_352  1.20771 1.13150
Veillonella_dispar           12.13797 1.20559
Streptococcus_salivarius     12.70253 6.49664
Prevotella_pallens            1.24524 0.92643
Streptococcus_parasanguinis   9.57804 1.01967

In [66]:
colnames(cleaned_taxa_tab) |> sort() |> head(, n = 70) |> print()

 [1] "10009" "10020" "10026" "10028" "10036" "10048" "1005"  "10064" "10065"
[10] "10074" "10075" "10076" "1009"  "10098" "1010"  "10119" "10132" "1014"
[19] "10146" "10148" "10154" "10190" "10194" "10200" "10202" "10221" "10227"
[28] "10228" "10240" "10242" "10256" "10257" "10258" "1026"  "10264" "1027"
[37] "10270" "10280" "10281" "10287" "10298" "10304" "10311" "10312" "10318"
[46] "10321" "10323" "10335" "10340" "10343" "10349" "10351" "10357" "10360"
[55] "10368" "10388" "10392" "10416" "10421" "10432" "10433" "10434" "10436"
[64] "10438" "10443" "10445" "10449" "10454" "10456" "10459"

In [67]:
#Export as .tsv
#write.table(cleaned_taxa_tab, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/data/", Sys.Date(),
 #                                          "_no_minimum_prev_abundance_no_other_taxa_saliva_taxa_cleaned_both_tp", ".tsv"), sep = "\t")

# Checking the missing samples samples

When comparing the taxa table and my filtered TP1 barcodes 9 samples were missing.  
Here checking what happend with them.   
- 2 were filtered out during minimum abundance / prev filtering <-- ended up including these  
- 6 were failed QC reads
- 1 Was filtered out based on reads (duplicate samples)

In [243]:
fp_tp1 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22fp_tp1_nulliparous_saliva.csv", header = TRUE)
dim(fp_tp1)
head(fp_tp1)

[1]  19 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   29          2          ⋯
3 P424fd61        0                   37          4          ⋯
4 P4de45e7        0                   29          2          ⋯
5 P50f102c        0                   32          3          ⋯
6 P5b98b6c        0                   28          2          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [244]:
sp_tp1 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22sp_tp1_nulliparous_saliva.csv", header = TRUE)
dim(sp_tp1)
head(sp_tp1)

[1]  19 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 Sa79a719     NA         0        0         1                     2019-01-17
2 S3db7da6     NA         0        0         1                     2019-09-24
3 S424fd61     NA         0        0         0                     2020-11-03
4 S4de45e7     NA         0        0         0                     2020-11-05
5 Sa957143     NA         0        0         1                     2020-07-11
6 S0332ad6     NA         0        0         0                     2020-06-05
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   30          3          ⋯
3 P424fd61        0                   40          4          ⋯
4 P4de45e7        0                   31          3          ⋯
5 P50f102c        0                   34          3          ⋯
6 P5b98b6c        0                   30          3          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     40
6 NA                 NA   NA       NA                     41
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 Second pregnancy
2 Second pregnancy
3 Second pregnancy
4 Second pregnancy
5 Second pregnancy
6 Second pregnancy

In [245]:
    combined_fp_sp_tp1 <- read.csv("/ceph/projects//010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22_combined_nulliparous_fp_sp_tp1_saliva.csv", header = TRUE)
dim(combined_fp_sp_tp1)
head(combined_fp_sp_tp1)

[1]  38 566

  Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
1 S1f862a6     NA         0        0         0                     2018-03-07
2 S39fe1d7     NA         0        0         0                     2018-06-23
3 S7e4a963     NA         0        0         0                     2018-02-18
4 S5fa4a39     NA         0        0         0                     2018-08-30
5 S50f102c     NA         0        0         0                     2018-08-05
6 S5b98b6c     NA         0        0         0                     2018-04-03
  Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
1 P1f862a6        0                   32          3          ⋯
2 P3db7da6        0                   29          2          ⋯
3 P424fd61        0                   37          4          ⋯
4 P4de45e7        0                   29          2          ⋯
5 P50f102c        0                   32          3          ⋯
6 P5b98b6c        0                   28          2          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     31
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          very_w28_31  1    0
2 Spontaneous          NA          NA    0
3 Induction            NA          NA    0
4 Induction            NA          NA    1
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [246]:
# Read fp and sp metadata files to obtain barcodes, OBS $Group for FP has a SPACE at the end!!
combined_fp_sp_tp1$Group
fp_bc <- combined_fp_sp_tp1 |>
  filter(Group == "First pregnancy ") |>
  pull(kit1.salival_sample.barcode)
print(fp_bc) |> length()

 [1] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [5] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [9] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[13] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[17] "First pregnancy " "First pregnancy " "First pregnancy " "Second pregnancy"
[21] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[25] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[29] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[33] "Second pregnancy" "Second pregnancy" "Second pregnancy" "Second pregnancy"
[37] "Second pregnancy" "Second pregnancy"

 [1]  1220 10368  1048 10700 10861  1372 10417 11161 13593 10656  9482 10856
[13]  1381  1115 10654   956  9864   961 11747

[1] 19

In [247]:
sp_bc <- combined_fp_sp_tp1 |>
  filter(Group == "Second pregnancy") |>
  pull(kit1.salival_sample.barcode)
print(sp_bc) |> length()

 [1] 13551 17523 23562 23353 19961 19835 18855 19676 23292 21844 17839 21011
[13] 23298 21973 22236 21819 20818 22000 21837

[1] 19

In [251]:
valid_barcodes_fp <- cleaned_taxa_tab[, colnames(cleaned_taxa_tab) %in% fp_bc] |> colnames()

valid_barcodes_fp
length(valid_barcodes_fp)

 [1] "9482"  "10656" "11161" "10654" "10861" "13593" "11747" "9864"  "1115"
[10] "961"   "10856" "10368"

[1] 12

In [252]:
valid_pn_fp <- fp_tp1 |> filter(fp_tp1$kit1.salival_sample.barcode %in% valid_barcodes_fp) |> pull(Q1_Personnummer)
length(valid_pn_fp)
    head(valid_pn_fp)

[1] 12

[1] "P3db7da6" "P50f102c" "P735d77f" "P7ece52e" "P92b4604" "Pa8f3b51"

In [290]:
# extract barcodes of the samples that got removed 
#missing_barcodes <- cleaned_taxa_tab[,!( colnames(cleaned_taxa_tab) %in% fp_bc)] |> colnames()

#missing_barcodes
#missing_barcodes <- fp_bc[,!(fp_tp1$kit1.salival_sample.barcode %in% cleaned_taxa_tab())

missing_bc <- sort(setdiff(fp_bc, valid_barcodes_fp))
missing_bc |> length()
missing_bc

[1] 7

[1]   956  1048  1220  1372  1381 10417 10700

In [289]:
dim(y_exclude_filt_new_arrange)
head(y_exclude_filt_new_arrange)

[1]  845 2315

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             19612__E200013437 17589__E200013437
Prevotella_melaninogenica    2.27635           3.91719
TM7_phylum_sp_oral_taxon_352 2.03540           1.91947
Veillonella_dispar           2.17340           6.97362
Streptococcus_salivarius     3.08711           3.59449
Prevotella_pallens           0.62355           1.68677
Streptococcus_parasanguinis  1.56545           3.28812
                             18881__E200013437 21225__E200013437
Prevotella_melaninogenica     0.01522          1.55264
TM7_phylum_sp_oral_taxon_352  0.99134          2.07174
Veillonella_dispar            9.72087          7.87567
Streptococcus_salivarius     18.06276          6.99764
Prevotella_pallens            0.52037          2.04457
Streptococcus_parasanguinis   9.99736          7.00401
                             20293__E200013437 21180__E200013437
Prevotella_melaninogenica    4.93655           6.53807
TM7_phylum_sp_oral_taxon_352 0.46493           1.60654
Veillonella_dispar           7.26205           7.27621
Streptococcus_salivarius     9.51983           2.35358
Prevotella_pallens           2.32954           3.84069
Streptococcus_parasanguinis  2.73461           3.21385
                             21386__E200013437 21930__E200013437
Prevotella_melaninogenica    3.30094           8.66169
TM7_phylum_sp_oral_taxon_352 3.36108           1.29958
Veillonella_dispar           5.88949           0.93840
Streptococcus_salivarius     6.62331           1.23692
Prevotella_pallens           0.71656           1.85049
Streptococcus_parasanguinis  7.10522           3.96688
                             17260__E200013437 18891__E200013437
Prevotella_melaninogenica     3.93085          3.41636
TM7_phylum_sp_oral_taxon_352  1.20771          1.13150
Veillonella_dispar           12.13797          1.20559
Streptococcus_salivarius     12.70253          6.49664
Prevotella_pallens            1.24524          0.92643
Streptococcus_parasanguinis   9.57804          1.01967

In [317]:
# Create vector of regular expressions, to extract all colnames that start with missing barcodes 
df_missing_bc <-c (  '^956__', '^1048__', '^1220__', '^1372__', '^1381__', '^10417__', '^10700__')

In [318]:
missing_bc_colnames <- colnames(y_exclude_filt_new_arrange)[sapply(colnames(y_exclude_filt_new_arrange), function(x) any(str_detect(x, df_missing_bc)))]
missing_bc_colnames |> sort() |> print()
                                                                   
length(missing_bc_colnames)

[1] "10417__E100073476x" "10417__E100074733"

[1] 2

In [ ]:
# Only 1 of the missing barcodes seems to have been excluded based on reads th rest are QC fails?