#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_super_stag_results_taxa_filtering
# Date: 2025.11.19
# Programmer: Barbara Nowak
# Purpose: Compile Super StaG metaphlan results for saliva into taxa table.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [377]:
library(tidyverse)
library(dplyr)

# Load Files  ----------------------------------------------------------------------------------------------

In [378]:
#installed.packages()

In [379]:
# Set working directory to where all metaphlan (and reads) files are
#help("setwd")
setwd("/ceph/projects/010_SweMaMi/bm.nowak/sstag_results/Samples_metaphlan_and_reads/metaphlan_files/")

In [380]:
list.files()

 [1] "E100073476_metaphlan.txt" "E100073508_metaphlan.txt"
 [3] "E100073527_metaphlan.txt" "E100073553_metaphlan.txt"
 [5] "E100074733_metaphlan.txt" "E100074741_metaphlan.txt"
 [7] "E100074769_metaphlan.txt" "E100074852_metaphlan.txt"
 [9] "E100074986_metaphlan.txt" "E111174961_metaphlan.txt"
[11] "E200005523_metaphlan.txt" "E200005561_metaphlan.txt"
[13] "E200005566_metaphlan.txt" "E200005569_metaphlan.txt"
[15] "E200005573_metaphlan.txt" "E200005574_metaphlan.txt"
[17] "E200005579_metaphlan.txt" "E200005581_metaphlan.txt"
[19] "E200005587_metaphlan.txt" "E200005591_metaphlan.txt"
[21] "E200005592_metaphlan.txt" "E200005599_metaphlan.txt"
[23] "E200005600_metaphlan.txt" "E200005601_metaphlan.txt"
[25] "E200005604_metaphlan.txt" "E200005606_metaphlan.txt"
[27] "E200005617_metaphlan.txt" "E200005618_metaphlan.txt"
[29] "E200013379_metaphlan.txt" "E200013398_metaphlan.txt"
[31] "E200013400_metaphlan.txt" "E200013437_metaphlan.txt"

In [381]:
file_list <- list.files() 
length(file_list)
head(file_list)

[1] 32

[1] "E100073476_metaphlan.txt" "E100073508_metaphlan.txt"
[3] "E100073527_metaphlan.txt" "E100073553_metaphlan.txt"
[5] "E100074733_metaphlan.txt" "E100074741_metaphlan.txt"

In [382]:
# read first files so that each flowcell? == one column
files_tabled <- read.table(file_list[1], header = TRUE) 
dim(files_tabled)
head(files_tabled)

[1] 1535   85

  clade_name
1 k__Bacteria
2 k__Bacteria|p__Firmicutes
3 k__Bacteria|p__Bacteroidota
4 k__Bacteria|p__Actinobacteria
5 k__Bacteria|p__Candidatus_Saccharibacteria
6 k__Bacteria|p__Proteobacteria
  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 100.00000                             100.00000
2  40.57446                              44.27937
3  31.89552                              16.48167
4  11.85675                              26.69077
5   7.56801                               1.42516
6   5.72420                              10.40903
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 100.00000                               100.00000
2  36.73116                                66.68932
3  22.02445                                13.95539
4  16.66630                                13.99746
5   1.94253                                 0.23176
6  19.52049                                 5.12607
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 100.00000                              100.00000
2  39.60400                               43.95355
3  15.16283                               20.84680
4  33.08312                               23.18805
5   2.54584                                2.30792
6   6.60701                                5.07465
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1 100.00000                              100.00000
2  62.06284                               58.86059
3   7.60091                               17.94967
4  25.56223                               17.48565
5   0.84112                                1.76397
6   3.77856                                1.83564
  X010_SweMaMi__11551__E100073476_L1_85_ ⋯
1 100.00000                              ⋯
2  45.42766                              ⋯
3  26.17817                              ⋯
4  18.97531                              ⋯
5   3.62014                              ⋯
6   3.53859                              ⋯
  X010_SweMaMi__10535__E100073476_L1_104_
1 100.00000
2  31.56497
3  30.23535
4  21.70559
5   5.79001
6   9.12536
  X010_SweMaMi__10814__E100073476_L1_124_
1 100.00000
2  44.10678
3  27.67272
4  22.74530
5   1.62158
6   1.85656
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 99.24139
2 69.66271
3  0.00750
4  0.03098
5  0.00000
6 29.54020
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 100.00000                               100.00000
2  32.74916                                42.76061
3  40.10263                                19.14150
4  13.12116                                25.57041
5   6.29651                                 3.54489
6   5.71770                                 7.68137
  X010_SweMaMi__10366__E100073476_L1_101_
1 100.00000
2  51.97740
3   9.17092
4  21.58565
5   6.31645
6   8.84412
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1 100.00000                              100.00000
2  54.41398                               38.85777
3   6.68187                               21.89859
4  27.49088                               18.45141
5   0.20516                                6.43051
6  10.50615                               10.22369
  X010_SweMaMi__11258__E100073476_L1_66_
1 100.00000
2  48.74284
3  17.53755
4  16.58855
5   6.71605
6   7.60353
  X010_SweMaMi__10652__E100073476_L1_122_
1 100.00000
2  41.86587
3  18.65936
4  23.71947
5   1.28795
6   9.50498

In [383]:
#colSums(files_tabled[, ])
files_tabled %>%
  select(-1) %>%
  summarise(across(everything(), sum))

  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 788.8468                              795.1167
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 796.8118                                799.3755
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 794.6363                               787.1218
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1 799.4385                               795.09
  X010_SweMaMi__11551__E100073476_L1_85_ X010_SweMaMi__10877__E100073476_L1_91_
1 792.2438                               797.0531
  ⋯ X010_SweMaMi__10535__E100073476_L1_104_
1 ⋯ 790.9308
  X010_SweMaMi__10814__E100073476_L1_124_
1 784.8229
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 800.0001
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 774.9185                                798.046
  X010_SweMaMi__10366__E100073476_L1_101_
1 795.7489
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1 798.9574                               793.7375
  X010_SweMaMi__11258__E100073476_L1_66_
1 792.3754
  X010_SweMaMi__10652__E100073476_L1_122_
1 789.851

In [384]:
#tail(files_tabled)

In [385]:
#help(grepl)

# Joining df -------------------------------------------------------------------------------------------------------------------------

 Files are merged horizontaly (each file added to the right).
- While adding, check that each row matches and if there are new rows then add new row.
- full_join merges by keeping rows from both and adding NA if no match.
- Join by using species name (clade)

In [386]:
# matches first "s__", then any char after it ("+"),  may end "([...])?" with "_unclassified", 
# match goes to end of str "$"
match_pattern <- "s__.+(_unclassified)?$"

In [387]:
# Reads each file in setwd if file name present in input list
# Also only keeps rows that match pattern
f_join_tables <- function(input_list_of_files){
    lapply(input_list_of_files, function(a_file){
        
        files_tabled <- read.table(a_file, header = TRUE)
        
        #cat("\nProcessing:", a_file, "\n") # debug line
        print(dim(files_tabled)) # Dim for each df
        
        # finds rows where pattern TRUE (excludes unnecessary taxa info etc since pattern match)
        filtered_tab <- files_tabled |> filter(grepl(match_pattern, clade_name)) 
                
        return(filtered_tab)
    })
    }

all_df_list <- f_join_tables(file_list)
head(all_df_list[[1]]) # check first data frame

[1] 1535   85
[1] 1392   79
[1] 1651   85
[1] 1573   86
[1] 1643   85
[1] 1670   84
[1] 1711   88
[1] 1648   82
[1] 1537   88
[1] 1600   85
[1] 1631   87
[1] 1701   79
[1] 1650   85
[1] 1644   87
[1] 1685   78
[1] 1698   85
[1] 1644   86
[1] 1734   88
[1] 1644   61
[1] 1667   49
[1] 1634   36
[1] 1597   88
[1] 1680   83
[1] 1535   85
[1] 1694   87
[1] 1684   88
[1] 1692   80
[1] 1687   79
[1] 1673   75
[1] 1602   59
[1] 1574   88
[1] 1635   87

  clade_name
1 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_melaninogenica
2 k__Bacteria|p__Candidatus_Saccharibacteria|c__Candidatus_Saccharibacteria_unclassified|o__Candidatus_Saccharibacteria_unclassified|f__Candidatus_Saccharibacteria_unclassified|g__Candidatus_Saccharibacteria_unclassified|s__TM7_phylum_sp_oral_taxon_352
3 k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Veillonella|s__Veillonella_dispar
4 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_salivarius
5 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_pallens
6 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_parasanguinis
  X010_SweMaMi__1646__E100073476_L1_58_ X010_SweMaMi__9379__E100073476_L1_29_
1 15.88133                              7.52610
2  6.15194                              1.35811
3  5.16047                              6.61030
4  3.85011                              6.90766
5  3.54669                              0.70011
6  3.46334                              3.74551
  X010_SweMaMi__10919__E100073476_L1_117_ X010_SweMaMi__9344__E100073476_L1_13_
1 1.55257                                  0.00000
2 1.65527                                  0.00000
3 1.56429                                  4.00127
4 2.19696                                 20.62685
5 0.16427                                  0.01262
6 0.97495                                  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_ X010_SweMaMi__13117__E100073476_L1_79_
1 0.90646                                3.41822
2 2.17797                                1.62005
3 3.16944                                4.76538
4 6.61362                                6.85844
5 0.59646                                2.39482
6 6.31109                                3.36495
  X010_SweMaMi__12889__E100073476_L1_81_ X010_SweMaMi__10106__E100073476_L1_46_
1  1.04933                                2.36183
2  0.36381                                0.98670
3  9.36236                                8.23126
4 16.24347                               16.59799
5  0.20566                                1.46584
6  5.77425                                4.84807
  X010_SweMaMi__11551__E100073476_L1_85_ ⋯
1 7.99986                                ⋯
2 1.88438                                ⋯
3 7.87458                                ⋯
4 8.31708                                ⋯
5 3.19061                                ⋯
6 5.41943                                ⋯
  X010_SweMaMi__10535__E100073476_L1_104_
1 8.25667
2 5.31892
3 3.96571
4 3.72460
5 3.44876
6 2.30555
  X010_SweMaMi__10814__E100073476_L1_124_
1 3.40731
2 1.60921
3 6.66593
4 6.32084
5 1.00825
6 6.79054
  X010_SweMaMi__zymomock_seq__E100073476_L1_115_
1 0.00000
2 0.00000
3 0.00516
4 0.00819
5 0.00000
6 0.01544
  X010_SweMaMi__10463__E100073476_L1_123_ X010_SweMaMi__1672__E100073476_L1_68_
1 7.37118                                 7.61837
2 5.04779                                 2.07931
3 3.82269                                 7.44099
4 0.92237                                 4.85763
5 7.22204                                 0.60944
6 1.42509                                 2.04594
  X010_SweMaMi__10366__E100073476_L1_101_
1 3.13746
2 5.77997
3 6.83962
4 7.91267
5 1.18837
6 5.41130
  X010_SweMaMi__9674__E100073476_L1_100_ X010_SweMaMi__9733__E100073476_L1_57_
1  0.00000                               3.65614
2  0.00000                               5.50514
3  3.55393                               2.99991
4 19.04877                               6.97655
5  0.00000                               1.52993
6  9.55598                               2.63567
  X010_SweMaMi__11258__E100073476_L1_66_
1 4.35311
2 6.30136
3 4.77804
4 5.10630
5 0.94249
6 3.39435
  X010_SweMaMi__10652__E100073476_L1_122_
1 2.79302
2 0.56413
3 4.07839
4 9.15081
5 1.27910
6 1.96370

In [388]:
head(all_df_list[[32]]) # check last data frame

  clade_name
1 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_mitis
2 k__Bacteria|p__Proteobacteria|c__Betaproteobacteria|o__Neisseriales|f__Neisseriaceae|g__Neisseria|s__Neisseria_subflava
3 k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Prevotellaceae|g__Prevotella|s__Prevotella_melaninogenica
4 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Micrococcales|f__Micrococcaceae|g__Rothia|s__Rothia_mucilaginosa
5 k__Bacteria|p__Firmicutes|c__Negativicutes|o__Veillonellales|f__Veillonellaceae|g__Veillonella|s__Veillonella_dispar
6 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_parasanguinis
  X010_SweMaMi__18245__E200013437_L1_83_ X010_SweMaMi__21222__E200013437_L1_65_
1 14.96168                               0.85820
2 11.14989                               0.11463
3 10.38855                               1.09584
4  8.58245                               1.77437
5  4.31194                               4.37724
6  4.20654                               5.91425
  X010_SweMaMi__18174__E200013437_L1_80_ X010_SweMaMi__19055__E200013437_L1_33_
1 5.02498                                 9.74931
2 7.78873                                 1.30214
3 1.24644                                12.03281
4 3.01298                                 1.17626
5 0.33371                                 0.00000
6 0.19705                                 0.61701
  X010_SweMaMi__17473__E200013437_L1_69_ X010_SweMaMi__21030__E200013437_L1_35_
1 0.98299                                1.67879
2 0.88839                                1.21240
3 3.84415                                6.61754
4 0.70255                                1.95009
5 3.41613                                5.61947
6 1.57490                                1.72658
  X010_SweMaMi__17569__E200013437_L1_98_ X010_SweMaMi__17716__E200013437_L1_47_
1 14.76020                               1.74674
2  4.29994                               1.84816
3  9.70059                               2.32720
4  3.52260                               5.61698
5  6.50718                               6.34084
6  1.22887                               7.13178
  X010_SweMaMi__21255__E200013437_L1_74_ ⋯
1 1.31933                                ⋯
2 3.08502                                ⋯
3 3.78335                                ⋯
4 5.86515                                ⋯
5 3.76430                                ⋯
6 7.82372                                ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 2.79270
2 0.37906
3 3.91719
4 3.87062
5 6.97362
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1 1.00091                                 2.82163
2 0.10253                                 0.00843
3 0.01522                                 1.55264
4 8.29410                                 4.89969
5 9.72087                                 7.87567
6 9.99736                                 7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 0.96993
2 0.13410
3 4.93655
4 3.63325
5 7.26205
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02544
2 0.08256
3 0.02837
4 0.02951
5 0.01116
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 5.19815                                 1.24325
2 2.86634                                 3.62078
3 6.53807                                 3.30094
4 4.33091                                12.41749
5 7.27621                                 5.88949
6 3.21385                                 7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1  3.93306                               0.78210
2 10.71866                               0.00000
3  8.66169                               3.93085
4  4.25430                               6.32510
5  0.93840                              12.13797
6  3.96688                               9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1  1.50154
2  8.42377
3  3.41636
4 10.89671
5  1.20559
6  1.01967

In [536]:
# full_join merges by keeping rows from both and adding NA if no match and join by using species name (clade) 

joined_table <- reduce(all_df_list, full_join, by = "clade_name") 
# reduce takes each df and joins them together with the previous ones, 
# I.e instead of looping: append this_df with that_df, then append this_df with that_df_2 etc, it takes resulting df and full joins the next df in the list to it

#head(joined_table)
dim(joined_table)
tail(joined_table)
#colnames(joined_table)

[1] 1738 2536

     clade_name
1733 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae
1734 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae|t__SGB8219
1735 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum
1736 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum|t__SGB16958
1737 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium
1738 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium|t__SGB17071
     X010_SweMaMi__1646__E100073476_L1_58_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__9379__E100073476_L1_29_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__10919__E100073476_L1_117_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__9344__E100073476_L1_13_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__12913__E100073476_L1_76_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__13117__E100073476_L1_79_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__12889__E100073476_L1_81_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__10106__E100073476_L1_46_.x
1733 NA
1734 NA
1735 NA
1736 NA
1737 NA
1738 NA
     X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1733 NA                                       ⋯
1734 NA                                       ⋯
1735 NA                                       ⋯
1736 NA                                       ⋯
1737 NA                                       ⋯
1738 NA                                       ⋯
     X010_SweMaMi__17589__E200013437_L1_91_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__18881__E200013437_L1_102_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21225__E200013437_L1_4_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__20293__E200013437_L1_122_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21180__E200013437_L1_89_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21386__E200013437_L1_62_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__21930__E200013437_L1_3_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__17260__E200013437_L1_90_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0
     X010_SweMaMi__18891__E200013437_L1_30_
1733 NA
1734 NA
1735  0
1736  0
1737  0
1738  0

In [463]:
#sorted_names <- joined_table |> sort_by(colnames(joined_table))
#colnames(sorted_names) |> print()

In [390]:
# (colSums(cleaned_ids_filt_new_arrange)) |> sort_by(colnames(cleaned_ids_filt_new_arrange))
#joined_table$clade_name # shows the species names

# Minimum abundance and Prevalence Filtering --------------------------------------------------------------------------------------------------------

Left to do:
- Replace NA with 0
- Clean up strains
- Remove Samples with colSums < 80
- Add other taxa

In [391]:
min_filtered_joined_table <- joined_table %>% {replace(., is.na(.), 0)}
tail(min_filtered_joined_table)

     clade_name
1733 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae
1734 k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Streptococcaceae|g__Streptococcus|s__Streptococcus_dysgalactiae|t__SGB8219
1735 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum
1736 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Propionibacteriales|f__Propionibacteriaceae|g__Cutibacterium|s__Cutibacterium_granulosum|t__SGB16958
1737 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium
1738 k__Bacteria|p__Actinobacteria|c__Actinomycetia|o__Corynebacteriales|f__Corynebacteriaceae|g__Corynebacterium|s__Corynebacterium_pseudogenitalium|t__SGB17071
     X010_SweMaMi__1646__E100073476_L1_58_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__9379__E100073476_L1_29_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__10919__E100073476_L1_117_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__9344__E100073476_L1_13_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__12913__E100073476_L1_76_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__13117__E100073476_L1_79_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__12889__E100073476_L1_81_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__10106__E100073476_L1_46_.x
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1733 0                                        ⋯
1734 0                                        ⋯
1735 0                                        ⋯
1736 0                                        ⋯
1737 0                                        ⋯
1738 0                                        ⋯
     X010_SweMaMi__17589__E200013437_L1_91_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__18881__E200013437_L1_102_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21225__E200013437_L1_4_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__20293__E200013437_L1_122_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21180__E200013437_L1_89_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21386__E200013437_L1_62_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__21930__E200013437_L1_3_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__17260__E200013437_L1_90_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0
     X010_SweMaMi__18891__E200013437_L1_30_
1733 0
1734 0
1735 0
1736 0
1737 0
1738 0

In [392]:
# Rearrange to keep only the species name
sp <- min_filtered_joined_table$clade_name # Extracts clade names
aa <- sub('.*s__', '', sp) # Remove all characters before s__ ("sub()" replaces ".*s__" any char (including s__) with empty string "''" ) 
# eg s__Corynebacterium_pseudogenitalium --> becomes Corynebacterium_pseudogenitalium

#head(min_filtered_joined_table)

t_strain <- grep("t__", aa, value = TRUE) # finds clade-name containing t__ 
#t_strain # list of clades containing "t__"

min_filtered_joined_table$clade_name <- aa # replaces clade name with cleaned species name
new_filtered_tab <- min_filtered_joined_table[!min_filtered_joined_table$clade_name %in% t_strain,] # If a row name (clade_name) appears in list containing "t__" then remove it

In [393]:
head(new_filtered_tab)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 3.91719
2 1.91947
3 6.97362
4 3.59449
5 1.68677
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02837
2 0.05275
3 0.01116
4 0.00792
5 0.02500
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

In [394]:
# Function for removing minimum abundance and prevalence taxa
is_here <- function(invector, min_abund, min_pres){
  min_count <- length(invector) * min_pres
  these <- length(which(invector > min_abund))
  if(these > min_count){
    return(TRUE)
  }
  else{
    return(FALSE)
  }
}

keep <- apply(new_filtered_tab , MARGIN = 1, is_here, min_abund = 0.001, min_pres = 0.05)
filt_taxa <- new_filtered_tab [keep,]
head(filt_taxa)
dim(filt_taxa)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__17589__E200013437_L1_91_
1 3.91719
2 1.91947
3 6.97362
4 3.59449
5 1.68677
6 3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__zymomock2_ex__E200013437_L1_67_
1 0.02837
2 0.05275
3 0.01116
4 0.00792
5 0.02500
6 0.00335
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

[1]  362 2536

In [395]:
#filt_taxa$clade_name |> sort_by(filt_taxa$clade_name) # Show species alphabetically

In [396]:
# Select all samples where colSums < 80
col_names_to_drop <- names(filt_taxa)[-1][colSums(filt_taxa[, -1]) < 80] # skip clade_name
length(col_names_to_drop)
head(col_names_to_drop)

[1] 119

[1] "X010_SweMaMi__zymomock_ex__E100073476_L1_84_.x"
[2] "X010_SweMaMi__neg_seq__E100073476_L1_39_.x"
[3] "X010_SweMaMi__zymomock_seq__E100073476_L1_115_.x"
[4] "X010_SweMaMi__neg_seq__E100073508_L1_39_"
[5] "X010_SweMaMi__zymomock_ex__E100073508_L1_61_"
[6] "X010_SweMaMi__zymomock_ex__E100073527_L1_74_"

In [397]:
#  Remove all samples where colSums < 80
colsum_filt_taxa <- filt_taxa |> 
    select(!all_of(col_names_to_drop))
length(colsum_filt_taxa)
dim(colsum_filt_taxa)

[1] 2417

[1]  362 2417

In [398]:
#colSums(colsum_filt_taxa[, -1]) # Don't count first column (clade_name)

In [399]:
#rownames(colsum_filt_taxa)

In [400]:
# remove rownames and replace with species
rownames(colsum_filt_taxa) <- NULL
head(colsum_filt_taxa)

colsum_filt_taxa_2 <- colsum_filt_taxa |> 
    column_to_rownames(var = names(colsum_filt_taxa)[1])
head(colsum_filt_taxa_2)

  clade_name                   X010_SweMaMi__1646__E100073476_L1_58_.x
1 Prevotella_melaninogenica    15.88133
2 TM7_phylum_sp_oral_taxon_352  6.15194
3 Veillonella_dispar            5.16047
4 Streptococcus_salivarius      3.85011
5 Prevotella_pallens            3.54669
6 Streptococcus_parasanguinis   3.46334
  X010_SweMaMi__9379__E100073476_L1_29_.x
1 7.52610
2 1.35811
3 6.61030
4 6.90766
5 0.70011
6 3.74551
  X010_SweMaMi__10919__E100073476_L1_117_.x
1 1.55257
2 1.65527
3 1.56429
4 2.19696
5 0.16427
6 0.97495
  X010_SweMaMi__9344__E100073476_L1_13_.x
1  0.00000
2  0.00000
3  4.00127
4 20.62685
5  0.01262
6  5.04926
  X010_SweMaMi__12913__E100073476_L1_76_.x
1 0.90646
2 2.17797
3 3.16944
4 6.61362
5 0.59646
6 6.31109
  X010_SweMaMi__13117__E100073476_L1_79_.x
1 3.41822
2 1.62005
3 4.76538
4 6.85844
5 2.39482
6 3.36495
  X010_SweMaMi__12889__E100073476_L1_81_.x
1  1.04933
2  0.36381
3  9.36236
4 16.24347
5  0.20566
6  5.77425
  X010_SweMaMi__10106__E100073476_L1_46_.x
1  2.36183
2  0.98670
3  8.23126
4 16.59799
5  1.46584
6  4.84807
  X010_SweMaMi__11551__E100073476_L1_85_.x ⋯
1 7.99986                                  ⋯
2 1.88438                                  ⋯
3 7.87458                                  ⋯
4 8.31708                                  ⋯
5 3.19061                                  ⋯
6 5.41943                                  ⋯
  X010_SweMaMi__19612__E200013437_L1_75_ X010_SweMaMi__17589__E200013437_L1_91_
1 2.27635                                3.91719
2 2.03540                                1.91947
3 2.17340                                6.97362
4 3.08711                                3.59449
5 0.62355                                1.68677
6 1.56545                                3.28812
  X010_SweMaMi__18881__E200013437_L1_102_ X010_SweMaMi__21225__E200013437_L1_4_
1  0.01522                                1.55264
2  0.99134                                2.07174
3  9.72087                                7.87567
4 18.06276                                6.99764
5  0.52037                                2.04457
6  9.99736                                7.00401
  X010_SweMaMi__20293__E200013437_L1_122_
1 4.93655
2 0.46493
3 7.26205
4 9.51983
5 2.32954
6 2.73461
  X010_SweMaMi__21180__E200013437_L1_89_ X010_SweMaMi__21386__E200013437_L1_62_
1 6.53807                                3.30094
2 1.60654                                3.36108
3 7.27621                                5.88949
4 2.35358                                6.62331
5 3.84069                                0.71656
6 3.21385                                7.10522
  X010_SweMaMi__21930__E200013437_L1_3_ X010_SweMaMi__17260__E200013437_L1_90_
1 8.66169                                3.93085
2 1.29958                                1.20771
3 0.93840                               12.13797
4 1.23692                               12.70253
5 1.85049                                1.24524
6 3.96688                                9.57804
  X010_SweMaMi__18891__E200013437_L1_30_
1 3.41636
2 1.13150
3 1.20559
4 6.49664
5 0.92643
6 1.01967

                             X010_SweMaMi__1646__E100073476_L1_58_.x
Prevotella_melaninogenica    15.88133
TM7_phylum_sp_oral_taxon_352  6.15194
Veillonella_dispar            5.16047
Streptococcus_salivarius      3.85011
Prevotella_pallens            3.54669
Streptococcus_parasanguinis   3.46334
                             X010_SweMaMi__9379__E100073476_L1_29_.x
Prevotella_melaninogenica    7.52610
TM7_phylum_sp_oral_taxon_352 1.35811
Veillonella_dispar           6.61030
Streptococcus_salivarius     6.90766
Prevotella_pallens           0.70011
Streptococcus_parasanguinis  3.74551
                             X010_SweMaMi__10919__E100073476_L1_117_.x
Prevotella_melaninogenica    1.55257
TM7_phylum_sp_oral_taxon_352 1.65527
Veillonella_dispar           1.56429
Streptococcus_salivarius     2.19696
Prevotella_pallens           0.16427
Streptococcus_parasanguinis  0.97495
                             X010_SweMaMi__9344__E100073476_L1_13_.x
Prevotella_melaninogenica     0.00000
TM7_phylum_sp_oral_taxon_352  0.00000
Veillonella_dispar            4.00127
Streptococcus_salivarius     20.62685
Prevotella_pallens            0.01262
Streptococcus_parasanguinis   5.04926
                             X010_SweMaMi__12913__E100073476_L1_76_.x
Prevotella_melaninogenica    0.90646
TM7_phylum_sp_oral_taxon_352 2.17797
Veillonella_dispar           3.16944
Streptococcus_salivarius     6.61362
Prevotella_pallens           0.59646
Streptococcus_parasanguinis  6.31109
                             X010_SweMaMi__13117__E100073476_L1_79_.x
Prevotella_melaninogenica    3.41822
TM7_phylum_sp_oral_taxon_352 1.62005
Veillonella_dispar           4.76538
Streptococcus_salivarius     6.85844
Prevotella_pallens           2.39482
Streptococcus_parasanguinis  3.36495
                             X010_SweMaMi__12889__E100073476_L1_81_.x
Prevotella_melaninogenica     1.04933
TM7_phylum_sp_oral_taxon_352  0.36381
Veillonella_dispar            9.36236
Streptococcus_salivarius     16.24347
Prevotella_pallens            0.20566
Streptococcus_parasanguinis   5.77425
                             X010_SweMaMi__10106__E100073476_L1_46_.x
Prevotella_melaninogenica     2.36183
TM7_phylum_sp_oral_taxon_352  0.98670
Veillonella_dispar            8.23126
Streptococcus_salivarius     16.59799
Prevotella_pallens            1.46584
Streptococcus_parasanguinis   4.84807
                             X010_SweMaMi__11551__E100073476_L1_85_.x
Prevotella_melaninogenica    7.99986
TM7_phylum_sp_oral_taxon_352 1.88438
Veillonella_dispar           7.87458
Streptococcus_salivarius     8.31708
Prevotella_pallens           3.19061
Streptococcus_parasanguinis  5.41943
                             X010_SweMaMi__10877__E100073476_L1_91_.x ⋯
Prevotella_melaninogenica     0.98840                                 ⋯
TM7_phylum_sp_oral_taxon_352  0.11358                                 ⋯
Veillonella_dispar           13.58697                                 ⋯
Streptococcus_salivarius     18.72063                                 ⋯
Prevotella_pallens            0.67060                                 ⋯
Streptococcus_parasanguinis  11.27242                                 ⋯
                             X010_SweMaMi__19612__E200013437_L1_75_
Prevotella_melaninogenica    2.27635
TM7_phylum_sp_oral_taxon_352 2.03540
Veillonella_dispar           2.17340
Streptococcus_salivarius     3.08711
Prevotella_pallens           0.62355
Streptococcus_parasanguinis  1.56545
                             X010_SweMaMi__17589__E200013437_L1_91_
Prevotella_melaninogenica    3.91719
TM7_phylum_sp_oral_taxon_352 1.91947
Veillonella_dispar           6.97362
Streptococcus_salivarius     3.59449
Prevotella_pallens           1.68677
Streptococcus_parasanguinis  3.28812
                             X010_SweMaMi__18881__E200013437_L1_102_
Prevotella_melaninogenica     0.01522
TM7_phylum_sp_oral_taxon_352  0.99134
Veillonella_dispar            9.72087
Streptococcus_salivarius     18.06276
Prevotella_pallens            0.52037
Streptococcus_parasanguinis   9.99736
                             X010_SweMaMi__21225__E200013437_L1_4_
Prevotella_melaninogenica    1.55264
TM7_phylum_sp_oral_taxon_352 2.07174
Veillonella_dispar           7.87567
Streptococcus_salivarius     6.99764
Prevotella_pallens           2.04457
Streptococcus_parasanguinis  7.00401
                             X010_SweMaMi__20293__E200013437_L1_122_
Prevotella_melaninogenica    4.93655
TM7_phylum_sp_oral_taxon_352 0.46493
Veillonella_dispar           7.26205
Streptococcus_salivarius     9.51983
Prevotella_pallens           2.32954
Streptococcus_parasanguinis  2.73461
                             X010_SweMaMi__21180__E200013437_L1_89_
Prevotella_melaninogenica    6.53807
TM7_phylum_sp_oral_taxon_352 1.60654
Veillonella_dispar           7.27621
Streptococcus_salivarius     2.35358
Prevotella_pallens           3.84069
Streptococcus_parasanguinis  3.21385
                             X010_SweMaMi__21386__E200013437_L1_62_
Prevotella_melaninogenica    3.30094
TM7_phylum_sp_oral_taxon_352 3.36108
Veillonella_dispar           5.88949
Streptococcus_salivarius     6.62331
Prevotella_pallens           0.71656
Streptococcus_parasanguinis  7.10522
                             X010_SweMaMi__21930__E200013437_L1_3_
Prevotella_melaninogenica    8.66169
TM7_phylum_sp_oral_taxon_352 1.29958
Veillonella_dispar           0.93840
Streptococcus_salivarius     1.23692
Prevotella_pallens           1.85049
Streptococcus_parasanguinis  3.96688
                             X010_SweMaMi__17260__E200013437_L1_90_
Prevotella_melaninogenica     3.93085
TM7_phylum_sp_oral_taxon_352  1.20771
Veillonella_dispar           12.13797
Streptococcus_salivarius     12.70253
Prevotella_pallens            1.24524
Streptococcus_parasanguinis   9.57804
                             X010_SweMaMi__18891__E200013437_L1_30_
Prevotella_melaninogenica    3.41636
TM7_phylum_sp_oral_taxon_352 1.13150
Veillonella_dispar           1.20559
Streptococcus_salivarius     6.49664
Prevotella_pallens           0.92643
Streptococcus_parasanguinis  1.01967

In [401]:
#sort(colnames(colsum_filt_taxa_2))  
#X010_SweMaMi__10334__E100073476_L1_127_.x''X010_SweMaMi__10334__E100073476_L1_127_.y''X010_SweMaMi__10334__E100074733_L1_127_'

In [402]:
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_"]]), na.rm = TRUE)
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_.x"]]), na.rm = TRUE)
sum(as.numeric(colsum_filt_taxa_2[["X010_SweMaMi__10334__E100073476_L1_127_.y"]]), na.rm = TRUE)

[1] 0

[1] 99.40272

[1] 99.40272

In [403]:
#colSums(filt_new_arrange) # Don't count first column (clade_name)

In [404]:
tail(colsum_filt_taxa_2)

                                           X010_SweMaMi__1646__E100073476_L1_58_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__9379__E100073476_L1_29_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__10919__E100073476_L1_117_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__9344__E100073476_L1_13_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__12913__E100073476_L1_76_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__13117__E100073476_L1_79_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__12889__E100073476_L1_81_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__10106__E100073476_L1_46_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__11551__E100073476_L1_85_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__10877__E100073476_L1_91_.x
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           ⋯
Peptostreptococcaceae_unclassified_SGB6622 ⋯
Johnsonella_ignava                         ⋯
GGB3385_SGB4472                            ⋯
Ottowia_sp_Marseille_P4747                 ⋯
Bacteroidota_unclassified_SGB1343          ⋯
Prevotella_saccharolytica                  ⋯
                                           X010_SweMaMi__19612__E200013437_L1_75_
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__17589__E200013437_L1_91_
Peptostreptococcaceae_unclassified_SGB6622 0.00867
Johnsonella_ignava                         0.00000
GGB3385_SGB4472                            0.01808
Ottowia_sp_Marseille_P4747                 0.00000
Bacteroidota_unclassified_SGB1343          0.00000
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__18881__E200013437_L1_102_
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__21225__E200013437_L1_4_
Peptostreptococcaceae_unclassified_SGB6622 0.00000
Johnsonella_ignava                         0.00000
GGB3385_SGB4472                            0.00000
Ottowia_sp_Marseille_P4747                 0.00000
Bacteroidota_unclassified_SGB1343          0.00229
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__20293__E200013437_L1_122_
Peptostreptococcaceae_unclassified_SGB6622 0.02978
Johnsonella_ignava                         0.00000
GGB3385_SGB4472                            0.01459
Ottowia_sp_Marseille_P4747                 0.00000
Bacteroidota_unclassified_SGB1343          0.00341
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__21180__E200013437_L1_89_
Peptostreptococcaceae_unclassified_SGB6622 0.00000
Johnsonella_ignava                         0.00000
GGB3385_SGB4472                            0.01543
Ottowia_sp_Marseille_P4747                 0.00492
Bacteroidota_unclassified_SGB1343          0.00000
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__21386__E200013437_L1_62_
Peptostreptococcaceae_unclassified_SGB6622 0.00000
Johnsonella_ignava                         0.00000
GGB3385_SGB4472                            0.00000
Ottowia_sp_Marseille_P4747                 0.00000
Bacteroidota_unclassified_SGB1343          0.00033
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__21930__E200013437_L1_3_
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0
                                           X010_SweMaMi__17260__E200013437_L1_90_
Peptostreptococcaceae_unclassified_SGB6622 0.00233
Johnsonella_ignava                         0.02817
GGB3385_SGB4472                            0.00000
Ottowia_sp_Marseille_P4747                 0.00000
Bacteroidota_unclassified_SGB1343          0.00000
Prevotella_saccharolytica                  0.00000
                                           X010_SweMaMi__18891__E200013437_L1_30_
Peptostreptococcaceae_unclassified_SGB6622 0
Johnsonella_ignava                         0
GGB3385_SGB4472                            0
Ottowia_sp_Marseille_P4747                 0
Bacteroidota_unclassified_SGB1343          0
Prevotella_saccharolytica                  0

# Cleaning up IDs ----------------------------------------------------------------------------------------------------------------------------

In [405]:
#sort(colnames(colsum_filt_taxa_2))

Same flowcell: check one 
Different flowcell: check after host removal reads

# keep sample ID and flowcell num
ids <- colnames(colsum_filt_taxa_2) # Extract names 
ids_nsmm <- sub( 'X010_SweMaMi__','', ids) # remove all char before X010_SweMaMi__ and replace with blank space
head(ids_nsmm)
#ids_nsmm_ne <- sub('__E.*', '', ids_nsmm) # also removes .x which I want to keep
ids_nsmm_ne <- sub('__E.*?([\\a-zA-Z]*)$', '\\1', ids_nsmm) # Matches E and everything after (not greedy), captures any trailing letters (at the end == $), then replaces match with captured letter
#head(ids_nsmm_ne)
length(ids_nsmm_ne)

In [469]:
#colnames(colsum_filt_taxa_2)

In [496]:
ids <- colnames(colsum_filt_taxa_2) # Extract names 
ids_nsmm <- sub( 'X010_SweMaMi__','', ids) # remove all char before X010_SweMaMi__ and replace with blank space
#flowcell will end in a number and then _

core <- sub('^(\\d+__E[0-9]+).*', "\\1", ids_nsmm)
head(core)

suffix <- sub('.*?([a-zA-Z]*)$', '\\1', ids_nsmm) 
head(suffix)
length(suffix)
#head(ids_nsmm_ne)
#length(ids_nsmm_ne)
#ids_nsmm_ne

[1] "1646__E100073476"  "9379__E100073476"  "10919__E100073476"
[4] "9344__E100073476"  "12913__E100073476" "13117__E100073476"

[1] "x" "x" "x" "x" "x" "x"

[1] 2416

In [497]:
ids_nsmm_ne <- paste0(core, suffix)
head(ids_nsmm_ne)
length(ids_nsmm_ne)
#sort(ids_nsmm_ne) |> print()

[1] "1646__E100073476x"  "9379__E100073476x"  "10919__E100073476x"
[4] "9344__E100073476x"  "12913__E100073476x" "13117__E100073476x"

[1] 2416

Additional columns that need to be droped
- Those that contain something like "zymock"--> those are not sequenced
- Also some samples contain no sample id, instead have what looks like 2 flowcell ids
those don't have sample IDs
- Save any cols starting with a letter 
-  --> exclude any that start with a letter

In [500]:
#valid_cols <- grepl('^\\d+', core)  # TRUE for columns starting with digits
#ids_nsmm_ne <- ids_nsmm_ne[valid_cols]

#core <- core[valid_cols]
#suffix <- suffix[valid_cols]


# Replaces any columns NOT starting with didgit with NULL 
# This makes it easier to exclude invalid columns bu8t keep the correct ID for columns
ids_nsmm_ne_NULL <- ifelse(grepl('^\\d+', core), ids_nsmm_ne, "NULL")
# Check
head(ids_nsmm_ne_NULL)
length(ids_nsmm_ne_NULL)

#sort(ids_nsmm_ne_NULL) |> print()

[1] "1646__E100073476x"  "9379__E100073476x"  "10919__E100073476x"
[4] "9344__E100073476x"  "12913__E100073476x" "13117__E100073476x"

[1] 2416

In [502]:
cleaned_ids_filt_new_arrange <- colsum_filt_taxa_2 |> set_names(ids_nsmm_ne_NULL)
head(cleaned_ids_filt_new_arrange)
dim(cleaned_ids_filt_new_arrange)

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             19612__E200013437 17589__E200013437
Prevotella_melaninogenica    2.27635           3.91719
TM7_phylum_sp_oral_taxon_352 2.03540           1.91947
Veillonella_dispar           2.17340           6.97362
Streptococcus_salivarius     3.08711           3.59449
Prevotella_pallens           0.62355           1.68677
Streptococcus_parasanguinis  1.56545           3.28812
                             18881__E200013437 21225__E200013437
Prevotella_melaninogenica     0.01522          1.55264
TM7_phylum_sp_oral_taxon_352  0.99134          2.07174
Veillonella_dispar            9.72087          7.87567
Streptococcus_salivarius     18.06276          6.99764
Prevotella_pallens            0.52037          2.04457
Streptococcus_parasanguinis   9.99736          7.00401
                             20293__E200013437 21180__E200013437
Prevotella_melaninogenica    4.93655           6.53807
TM7_phylum_sp_oral_taxon_352 0.46493           1.60654
Veillonella_dispar           7.26205           7.27621
Streptococcus_salivarius     9.51983           2.35358
Prevotella_pallens           2.32954           3.84069
Streptococcus_parasanguinis  2.73461           3.21385
                             21386__E200013437 21930__E200013437
Prevotella_melaninogenica    3.30094           8.66169
TM7_phylum_sp_oral_taxon_352 3.36108           1.29958
Veillonella_dispar           5.88949           0.93840
Streptococcus_salivarius     6.62331           1.23692
Prevotella_pallens           0.71656           1.85049
Streptococcus_parasanguinis  7.10522           3.96688
                             17260__E200013437 18891__E200013437
Prevotella_melaninogenica     3.93085          3.41636
TM7_phylum_sp_oral_taxon_352  1.20771          1.13150
Veillonella_dispar           12.13797          1.20559
Streptococcus_salivarius     12.70253          6.49664
Prevotella_pallens            1.24524          0.92643
Streptococcus_parasanguinis   9.57804          1.01967

[1]  362 2416

In [507]:
# Eclude invalid (NULL) colnames
all_valid_ids_filt_new_arrange <- cleaned_ids_filt_new_arrange |> select((!matches("^Null$")))
dim(all_valid_ids_filt_new_arrange)
head(all_valid_ids_filt_new_arrange)

[1]  362 2390

                             1646__E100073476x 9379__E100073476x
Prevotella_melaninogenica    15.88133          7.52610
TM7_phylum_sp_oral_taxon_352  6.15194          1.35811
Veillonella_dispar            5.16047          6.61030
Streptococcus_salivarius      3.85011          6.90766
Prevotella_pallens            3.54669          0.70011
Streptococcus_parasanguinis   3.46334          3.74551
                             10919__E100073476x 9344__E100073476x
Prevotella_melaninogenica    1.55257             0.00000
TM7_phylum_sp_oral_taxon_352 1.65527             0.00000
Veillonella_dispar           1.56429             4.00127
Streptococcus_salivarius     2.19696            20.62685
Prevotella_pallens           0.16427             0.01262
Streptococcus_parasanguinis  0.97495             5.04926
                             12913__E100073476x 13117__E100073476x
Prevotella_melaninogenica    0.90646            3.41822
TM7_phylum_sp_oral_taxon_352 2.17797            1.62005
Veillonella_dispar           3.16944            4.76538
Streptococcus_salivarius     6.61362            6.85844
Prevotella_pallens           0.59646            2.39482
Streptococcus_parasanguinis  6.31109            3.36495
                             12889__E100073476x 10106__E100073476x
Prevotella_melaninogenica     1.04933            2.36183
TM7_phylum_sp_oral_taxon_352  0.36381            0.98670
Veillonella_dispar            9.36236            8.23126
Streptococcus_salivarius     16.24347           16.59799
Prevotella_pallens            0.20566            1.46584
Streptococcus_parasanguinis   5.77425            4.84807
                             11551__E100073476x 10877__E100073476x ⋯
Prevotella_melaninogenica    7.99986             0.98840           ⋯
TM7_phylum_sp_oral_taxon_352 1.88438             0.11358           ⋯
Veillonella_dispar           7.87458            13.58697           ⋯
Streptococcus_salivarius     8.31708            18.72063           ⋯
Prevotella_pallens           3.19061             0.67060           ⋯
Streptococcus_parasanguinis  5.41943            11.27242           ⋯
                             19612__E200013437 17589__E200013437
Prevotella_melaninogenica    2.27635           3.91719
TM7_phylum_sp_oral_taxon_352 2.03540           1.91947
Veillonella_dispar           2.17340           6.97362
Streptococcus_salivarius     3.08711           3.59449
Prevotella_pallens           0.62355           1.68677
Streptococcus_parasanguinis  1.56545           3.28812
                             18881__E200013437 21225__E200013437
Prevotella_melaninogenica     0.01522          1.55264
TM7_phylum_sp_oral_taxon_352  0.99134          2.07174
Veillonella_dispar            9.72087          7.87567
Streptococcus_salivarius     18.06276          6.99764
Prevotella_pallens            0.52037          2.04457
Streptococcus_parasanguinis   9.99736          7.00401
                             20293__E200013437 21180__E200013437
Prevotella_melaninogenica    4.93655           6.53807
TM7_phylum_sp_oral_taxon_352 0.46493           1.60654
Veillonella_dispar           7.26205           7.27621
Streptococcus_salivarius     9.51983           2.35358
Prevotella_pallens           2.32954           3.84069
Streptococcus_parasanguinis  2.73461           3.21385
                             21386__E200013437 21930__E200013437
Prevotella_melaninogenica    3.30094           8.66169
TM7_phylum_sp_oral_taxon_352 3.36108           1.29958
Veillonella_dispar           5.88949           0.93840
Streptococcus_salivarius     6.62331           1.23692
Prevotella_pallens           0.71656           1.85049
Streptococcus_parasanguinis  7.10522           3.96688
                             17260__E200013437 18891__E200013437
Prevotella_melaninogenica     3.93085          3.41636
TM7_phylum_sp_oral_taxon_352  1.20771          1.13150
Veillonella_dispar           12.13797          1.20559
Streptococcus_salivarius     12.70253          6.49664
Prevotella_pallens            1.24524          0.92643
Streptococcus_parasanguinis   9.57804          1.01967

In [ ]:
#((colnames(all_valid_ids_filt_new_arrange))) |> sort() |> print()

In [528]:
colSums(all_valid_ids_filt_new_arrange) |> sort_by(colnames(all_valid_ids_filt_new_arrange)) |> head() |> print()

10009__E200005523 10020__E100073553 10021__E100073527 10021__E111174961
         99.91824          99.77788          99.89552          99.97504
10026__E100073553 10028__E100073553
         99.45009          99.89778

# Checking reads -----------------------------------------------------------------------------------------------------------

Now check reads:
- Any flowcells that have a duplicate ending in x or y --> just pick one --> those are accidental duplicates
- Any col, ending in x or y are duplicates of same flowcell and sample --> just pick either
- Any samples that exist in two different flowcells: check reads and pick highest one

In [529]:
setwd("/ceph/projects/010_SweMaMi/bm.nowak/sstag_results/Samples_metaphlan_and_reads/reads_files")

In [532]:
file_list_reads <- list.files()

In [534]:
file_list_reads[1]

[1] "E100073476_preprocessing_read_counts.txt"

In [535]:
reads_tabled <- read.table(file_list_reads[1], header = TRUE) 
dim(reads_tabled)
head(reads_tabled)

[1] 84  5

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

In [546]:
# Reads each file in setwd if file name present in input list
f_join_tables_reads_vertical <- function(input_list_of_files){
    lapply(input_list_of_files, function(a_file){
        
        files_tabled <- read.table(a_file, header = TRUE)
        
        cat("\nProcessing:", a_file, "\n") # debug line
        print(dim(files_tabled)) # Dim for each df
        
        # finds rows where pattern TRUE (excludes unnecessary taxa info etc since pattern match)
        #filtered_tab <- files_tabled |> filter(grepl(match_pattern, clade_name)) 
                
        return(files_tabled)
    })
    }

all_reads_df <- f_join_tables_reads_vertical(file_list_reads)
head(all_reads_df[[1]]) # check first data frame

Processing: E100073476_preprocessing_read_counts.txt
[1] 84  5

Processing: E100073508_preprocessing_read_counts.txt
[1] 78  5

Processing: E100073527_preprocessing_read_counts.txt
[1] 84  5

Processing: E100073553_preprocessing_read_counts.txt
[1] 85  5

Processing: E100074733_preprocessing_read_counts.txt
[1] 84  5

Processing: E100074741_preprocessing_read_counts.txt
[1] 83  5

Processing: E100074769_preprocessing_read_counts.txt
[1] 87  5

Processing: E100074852_preprocessing_read_counts.txt
[1] 81  5

Processing: E100074986_preprocessing_read_counts.txt
[1] 87  5

Processing: E111174961_preprocessing_read_counts.txt
[1] 84  5

Processing: E200005523_preprocessing_read_counts.txt
[1] 86  5

Processing: E200005561_preprocessing_read_counts.txt
[1] 78  5

Processing: E200005566_preprocessing_read_counts.txt
[1] 84  5

Processing: E200005569_preprocessing_read_counts.txt
[1] 86  5

Processing: E200005573_preprocessing_read_counts.txt
[1] 77  5

Processing: E200005574_preprocessing_read_counts.txt
[1] 84  5

Processing: E200005579_preprocessing_read_counts.txt
[1] 85  5

Processing: E200005581_preprocessing_read_counts.txt
[1] 87  5

Processing: E200005587_preprocessing_read_counts.txt
[1] 60  5

Processing: E200005591_preprocessing_read_counts.txt
[1] 48  5

Processing: E200005592_preprocessing_read_counts.txt
[1] 35  5

Processing: E200005599_preprocessing_read_counts.txt
[1] 87  5

Processing: E200005600_preprocessing_read_counts.txt
[1] 82  5

Processing: E200005601_preprocessing_read_counts.txt
[1] 83  5

Processing: E200005604_preprocessing_read_counts.txt
[1] 86  5

Processing: E200005606_preprocessing_read_counts.txt
[1] 87  5

Processing: E200005617_preprocessing_read_counts.txt
[1] 79  5

Processing: E200005618_preprocessing_read_counts.txt
[1] 78  5

Processing: E200013379_preprocessing_read_counts.txt
[1] 74  5

Processing: E200013398_preprocessing_read_counts.txt
[1] 58  5

Processing: E200013400_preprocessing_read_counts.txt
[1] 87  5

Processing: E200013437_preprocessing_read_counts.txt
[1] 86  5

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

In [548]:
joined_table_reads <- bind_rows(all_reads_df)
head (joined_table_reads)
dim(joined_table_reads)

  Sample                                 duplication before_fastp after_fastp
1 010_SweMaMi__10106__E100073476_L1_46_  0.00356886  29921360     26989691
2 010_SweMaMi__10273__E100073476_L1_93_  0.00285863  24215813     22036296
3 010_SweMaMi__10300__E100073476_L1_97_  0.00445974  37433144     33674569
4 010_SweMaMi__10334__E100073476_L1_127_ 0.00372570  31416878     28389354
5 010_SweMaMi__10346__E100073476_L1_99_  0.00316506  26756212     24218990
6 010_SweMaMi__10366__E100073476_L1_101_ 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

[1] 2534    5

Run same code as before to remove unwanted char from sample IDs
But split so flowcell and sampkle ID is separate

In [555]:
joined_table_id_cols <- joined_table_reads |> 
# Extracts col into two new columns: __(\\d+)  and __([E][0-9]+).*  " .*?" skips everything before
    extract( 
    col = Sample,
    into = c("SampleID", "EID"),
    regex = ".*?__(\\d+)__([E][0-9]+).*"
  )

head(joined_table_id_cols)

  SampleID EID        duplication before_fastp after_fastp
1 10106    E100073476 0.00356886  29921360     26989691
2 10273    E100073476 0.00285863  24215813     22036296
3 10300    E100073476 0.00445974  37433144     33674569
4 10334    E100073476 0.00372570  31416878     28389354
5 10346    E100073476 0.00316506  26756212     24218990
6 10366    E100073476 0.00326113  27499712     24944865
  after_kraken2_host_removal
1  9107230
2  8632034
3 24797849
4  7707971
5  7707363
6  6172882

In [562]:
# See if any sample IDs appear more than once and show flowcell
duplicate_samplesid <- joined_table_id_cols |> pull(SampleID)  
duplicate_eid <- joined_table_id_cols |> pull(EID)  
table(duplicate_samplesid, duplicate_eid)

                   duplicate_eid
duplicate_samplesid E100073476 E100073508 E100073527 E100073553 E100074733
              10009          0          0          0          0          0
              10020          0          0          0          1          0
              10021          0          0          1          0          0
              10026          0          0          0          1          0
              10028          0          0          0          1          0
              10030          0          0          0          0          0
              10035          0          0          0          0          0
              10036          0          0          0          0          0
              10038          0          0          0          0          0
              10048          0          0          0          1          0
              1005           0          0          0          0          0
              10056          0          0          1          0          0
              10058          0          0          1          0          0
              10064          0          0          0          1          0
              10065          0          0          0          0          0
              10066          0          0          1          0          0
              10074          0          0          0          0          0
              10075          0          0          0          0          0
              10076          0          0          0          0          0
              10077          0          0          0          0          0
              1009           0          0          0          0          0
              10098          0          0          0          0          0
              1010           0          0          0          0          0
              10104          0          1          0          0          0
              10106          1          0          0          0          1
              10119          0          0          0          0          0
              1012           0          0          1          0          0
              10131          0          1          0          0          0
              10132          0          0          0          0          0
              10134          0          1          0          0          0
              1014           0          0          0          0          0
              10146          0          0          0          0          0
              10148          0          0          0          0          0
              1015           0          0          1          0          0
              10154          0          0          0          0          0
              1016           0          0          0          0          0
              10167          0          1          0          0          0
              1017           0          0          1          0          0
              10190          0          0          0          0          0
              10193          0          1          0          0          0
              10194          0          0          0          0          0
              10200          0          0          0          0          0
              10202          0          0          0          0          0
              10213          0          1          0          0          0
              10221          0          0          0          0          0
              10227          0          0          0          0          0
              10228          0          0          0          0          0
              1024           0          0          0          0          0
              10240          0          0          0          0          0
              10242          0          0          0          0          0
              10256          0          0          0          0          0
              10257          0          0          0          0          0
              10258          0          0          0          0          0
              1026           0          0          0          0          0
              10264          0          0          0          0          0
              1027           0          0          0          0          0
              10270          0          0          0          0          0
              10273          1          0          0          0          1
              1028           0          0          1          0          0
              10280          0          0          0          0          0
              10281          0          0          0          0          0
              10287          0          0          0          0          0
              10298          0          0          0          0          0
              10300          1          0          0          0          1
              10304          0          0          0          1          0
              10311          0          0          0          0          0
              10312          0          0          0          1          0
              10318          0          0          0          0          0
              10321          0          0          0          0          0
              10323          0          0          0          1          0
              10334          1          0          0          0          1
              10335          0          0          0          1          0
              10340          0          0          0          0          0
              10343          0          0          0          1          0
              10346          1          0          0          0          1
              10349          0          0          0          0          0
              10351          0          0          0          1          0
              10354          0          0          1          0          0
              10355          0          0          1          0          0
              10356          0          0          1          0          0
              10357          0          0          0          1          0
              10360          0          0          0          0          0
              10365          0          0          1          0          0
              10366          1          0          0          0          1
              10368          0          0          0          0          0
              1037           0          0          0          0          0
              10388          0          0          0          0          0
              1039           0          0          0          0          0
              10392          0          0          0          0          0
              10410          1          0          0          0          1
              10413          0          0          1          0          0
              10416          0          0          0          0          0
              10417          1          0          0          0          1
              10418          1          0          0          0          1
              10419          0          0          1          0          0
              10421          0          0          0          0          0
              10422          1          0          0          0          1
              10432          0          0          0          0          0
              10433          0          0          0          0          0
              10434          0          0          0          0          0
              10436          0          0          0          0          0
              10438          0          0          0          1          0
              10443          0          0          0          1          0
              10445          0          0          0          0          0
              10449          0          0          0          0          0
              1045           0          0          0          0          0
              10454          0          0          0          1          0
              10456          0          0          0          0          0
              10459          0          0          0          0          0
              1046           0          0          0          0          0
              10463          1          0          0          0          1
              10469          0          0          0          0          0
              10478          0          0          0          0          0
              10481          0          0          0          0          0
              10488          0          0          0          0          0
              1049           0          0          0          1          0
              10491          0          0          0          0          0
              10501          0          0          0          0          0
              10505          1          0          0          0          1
              10506          0          0          0          0          0
              10508          0          0          0          0          0
              10515          1          0          0          0          1
              10517          0          0          0          0          0
              1052           0          0          0          0          0
              10520          0          0          0          0          0
              10523          0          0          0          0          0
              10527          0          0          0          0          0
              10528          0          0          1          0          0
              1053           0          0          0          0          0
              10530          1          0          0          0          1
              10535          1          0          0          0          1
              1054           0          0          0          1          0
              10541          0          0          1          0          0
              10545          0          0          0          0          0
              10548          0          0          0          0          0
              10559          0          0          0          0          0
              10573          0          0          0          0          0
              10576          0          0          0          0          0
              10578          0          0          0          0          0
              10582          0          0          0          0          0
              10586          0          0          0          0          0
              10592          0          0          0          0          0
              10594          0          0          0          0          0
              1060           0          0          0          1          0
              10614          0          0          0          1          0
              1062           0          0          0          0          0
              10629          0          0          0          0          0
              10644          0          0          0          1          0
              10652          1          0          0          0          1
              10654          0          0          0          1          0
              10656          0          0          0          1          0
              1066           0          0          0          0          0
              10672          1          0          0          0          1
              10677          0          0          0          1          0
              1068           0          0          0          0          0
              10681          0          0          0          1          0
              10686          0          0          0          0          0
              10703          1          0          0          0          1
              10704          0          0          0          1          0
              10715          0          0          0          1          0
              10720          0          0          0          0          0
              10721          0          0          0          0          0
              10728          1          0          0          0          1
              1073           0          0          0          0          0
              10734          0          0          0          0          0
              10738          0          0          0          0          0
              10741          0          0          0          1          0
              10747          1          0          0          0          1
              10748          1          0          0          0          1
              1077           0          0          0          1          0
              10771          0          0          0          0          0
              1078           0          0          0          1          0
              1079           0          0          0          1          0
              10790          0          0          0          0          0
              10791          0          0          0          1          0
              10794          0          0          0          0          0
              1081           0          0          0          0          0
              10814          1          0          0          0          1
              10827          0          0          0          0          0
              10834          0          0          0          0          0
              10836          1          0          0          0          1
              10842          0          0          0          0          0
              10856          0          0          0          0          0
              10861          0          0          0          0          0
              10870          0          0          0          0          0
              10872          0          0          0          0          0
              10873          0          0          0          1          0
              10877          1          0          0          0          1
              10881          0          0          0          0          0
              10888          1          0          0          0          1
              1089           0          0          0          0          0
              10892          0          0          1          0          0
              1090           0          0          0          0          0
              10902          0          1          0          0          0
              10913          0          0          0          0          0
              10914          0          0          0          0          0
              10917          1          0          0          0          1
              10919          1          0          0          0          1
              1094           0          0          0          1          0
              1097           0          0          0          0          0
              10972          0          0          0          0          0
              10976          0          0          0          0          0
              10982          0          0          0          1          0
              10984          0          0          0          0          0
              10986          0          0          0          0          0
              10989          0          0          0          0          0
              10996          0          0          0          0          0
              11003          0          0          0          1          0
              11005          0          0          0          0          0
              11011          0          0          0          1          0
              11013          0          0          0          0          0
              11014          0          0          0          0          0
              11015          0          0          0          0          0
              11017          0          0          0          0          0
              1102           0          0          0          0          0
              11023          0          0          0          0          0
              11031          0          0          0          0          0
              1105           0          0          0          0          0
              11054          0          0          0          0          0
              11055          0          0          0          0          0
              11058          0          0          0          0          0
              11060          0          0          0          0          0
              11064          0          0          0          0          0
              11069          0          0          0          0          0
              11099          0          0          0          1          0
              11103          0          0          0          1          0
              1115           0          0          0          0          0
              11153          0          0          0          0          0
              11155          0          0          0          1          0
              11157          0          0          0          1          0
              11161          0          0          0          1          0
              11168          0          0          0          0          0
              11173          0          0          0          1          0
              1118           0          0          0          0          0
              11182          0          0          0          0          0
              11188          0          0          0          0          0
              11189          1          0          0          0          1
              11197          0          0          0          0          0
              11202          1          0          0          0          1
              11211          1          0          0          0          1
              11212          0          0          0          0          0
              11223          0          0          0          0          0
              11228          0          0          0          0          0
              11229          0          0          0          0          0
              1123           0          0          0          1          0
              11234          0          0          0          0          0
              11236          0          0          0          0          0
              11240          0          0          0          0          0
              11247          0          0          0          0          0
              1125           0          0          1          0          0
              11251          0          0          0          0          0
              11252          0          0          0          0          0
              11258          1          0          0          0          1
              1126           0          0          0          0          0
              11260          0          0          0          0          0
              11264          0          0          0          0          0
              1129           0          0          0          0          0
              11308          0          0          0          0          0
              1131           0          0          0          0          0
              11311          0          0          0          0          0
              11314          1          0          0          0          1
              11318          0          0          0          0          0
              11325          1          0          0          0          1
              11337          0          0          0          0          0
              11343          1          0          0          0          1

# OLD CODE NEEDS CLEANING -----------------------------------------------------------------------------------------------------------------

cleaned_ids_filt_new_arrange <- colsum_filt_taxa_2 |> set_names(ids_nsmm_ne)
head(cleaned_ids_filt_new_arrange)
dim(cleaned_ids_filt_new_arrange)

#id_match <- "0-9.*?+([a-zA-Z]*)$"
#cleaned_ids_filt_new_arrange |> filter(grepl(id_match, colnames))
# Check if some samples truly duplicate
id_match <- "1646+([a-zA-Z]*)$"
grep(id_match, colnames(cleaned_ids_filt_new_arrange), value = TRUE)

## Separating out x y samples
Keep samples ending in x y etc separate.

CHECK this!   
So here below is again the problem where for some reason the first col is 100 even though it was 0 before.

In [364]:
#filter(cleaned_ids_filt_new_arrange$1646x) |> colSums( )
sum(as.numeric(cleaned_ids_filt_new_arrange[["10334"]]), na.rm = TRUE)
sum(as.numeric(cleaned_ids_filt_new_arrange[["10334x"]]), na.rm = TRUE)
sum(as.numeric(cleaned_ids_filt_new_arrange[["10334y"]]), na.rm = TRUE)

[1] 99.32284

[1] 99.40272

[1] 99.40272

(colSums(colsum_filt_taxa_2)) |> sort_by(colnames(colsum_filt_taxa_2))

(colSums(cleaned_ids_filt_new_arrange)) |> sort_by(colnames(cleaned_ids_filt_new_arrange))

# THIS IS NOT TO BE USED FOR NOW!!
new_row <- c()
tot <- colSums(colsum_filt_taxa_2)
for(i in tot){
    if(i < 100){
        new_row <- c(new_row, 100 - i)
    } else if (i >= 100){
        new_row <- c(new_row, 0)
    }
}
head(tot)
head(new_row)

# add this vector as row to the taxa table
new_row <- setNames(new_row, names(colsum_filt_taxa_2))
#new_row
new_row2 <- as.data.frame(t(new_row))
#new_row2
rownames(new_row2) <- "Other_taxa"
best_filt_new <- rbind(colsum_filt_taxa_2 ,new_row2) 
#colSums(best_filt_new )
#now the colSums == 100

filt_new_arrange <- as.data.frame(best_filt_new)
head(filt_new_arrange)
dim(filt_new_arrange)

# Testing ======================================================================================================

# read second files so that each flowcell? == one column
files_tabled_2 <- read.table(file_list[2], header = TRUE) 
dim(files_tabled_2)
head(files_tabled_2)

filtered_tab_2 <- files_tabled_2 |> filter(grepl(match_pattern, clade_name)) # finds rows where pattern TRUE (excludes unnecessary taxa info etc since pattern match)

head(filtered_tab_2) 

#filtered_tab$clade_name # shows the species names
dim(filtered_tab_2)

test_join_tab <- full_join(filtered_tab, filtered_tab_2, by = "clade_name")
#head(test_join_tab)
dim(test_join_tab)
tail(test_join_tab)

# Test-function for joining 2 dataframes
f_join_tables <- function(table1, table2){
    joined_table_test <- full_join(table1, table2, by = "clade_name")
    #output <- do_something(inputs)
    return(joined_table_test)
}

test_output <- f_join_tables(filtered_tab, filtered_tab_2)
dim(test_output)
#full_join(filtered_tab, filtered_tab_2, by = "clade_name")

#help(lapply) #eturns a list of the same length as X

f_join_tables_2 <- function(in_list_of_files){
    lapply(in_list_of_files, function(a_file){
        cat("Reading file:", a_file, "\n")  # <-- debug line
        files_tabled_test <- read.table(a_file, header = TRUE)
        print(dim(files_tabled_test))        # <-- show rows/cols
        return(files_tabled_test)
    })
}

all_df_list <- f_join_tables_2(file_list)

# more C++ logic

f_join_tables_2 <- function(in_list_of_files){
    for(i in in_list_of_files){ 
        x = 1
        files_tabled_test <- read.table(file_list[x], header = TRUE) 
        print(x)
        print()
        x++

    }

    return("Done")



test_output <- f_join_tables_2(file_list)
test_output