#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: saliva_drop_na_kit2
# Date: 2025.10.02
# Programmer: Barbara Nowak
# Purpose: Drop missing saliva samples in kit1, check that Primiparous = TRUE (nulliparous), and write to separate files
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
fp_saliva <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-22fp_tp1_nulliparous_saliva.csv", header = TRUE, row.names = 1)
head(fp_saliva)
dim(fp_saliva)

         Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
S1f862a6 NA         0        0         0                     2018-03-07
S39fe1d7 NA         0        0         0                     2018-06-23
S7e4a963 NA         0        0         0                     2018-02-18
S5fa4a39 NA         0        0         0                     2018-08-30
S50f102c NA         0        0         0                     2018-08-05
S5b98b6c NA         0        0         0                     2018-04-03
         Q1_Personnummer Avbruten_graviditet age_checked Age_groups
S1f862a6 P1f862a6        0                   32          3
S39fe1d7 P3db7da6        0                   29          2
S7e4a963 P424fd61        0                   37          4
S5fa4a39 P4de45e7        0                   29          2
S50f102c P50f102c        0                   32          3
S5b98b6c P5b98b6c        0                   28          2
         Swedish_born ⋯ missfall.IUFD_week IUFD missfall missfall.IUFD_comments
S1f862a6 1            ⋯ NA                 NA   NA       NA
S39fe1d7 1            ⋯ NA                 NA   NA       NA
S7e4a963 1            ⋯ NA                 NA   NA       NA
S5fa4a39 1            ⋯ NA                 NA   NA       NA
S50f102c 1            ⋯ NA                 NA   NA       NA
S5b98b6c 1            ⋯ NA                 NA   NA       NA
         Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
S1f862a6 31              Spontaneous          very_w28_31  1
S39fe1d7 41              Spontaneous          NA          NA
S7e4a963 38              Induction            NA          NA
S5fa4a39 39              Induction            NA          NA
S50f102c 41              Spontaneous          NA          NA
S5b98b6c 40              Spontaneous          NA          NA
         preeclampsia_epi_analysis Group
S1f862a6 0                         First pregnancy
S39fe1d7 0                         First pregnancy
S7e4a963 0                         First pregnancy
S5fa4a39 1                         First pregnancy
S50f102c 0                         First pregnancy
S5b98b6c 0                         First pregnancy

[1]  19 565

In [3]:
sp_saliva <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp1_nulliparous/2025-10-06sp_tp1_nulliparous_saliva.csv", header = TRUE, row.names = 1)
head(sp_saliva)
dim(sp_saliva)

         Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
Sa79a719 NA         0        0         1                     2019-01-17
S3db7da6 NA         0        0         1                     2019-09-24
S424fd61 NA         0        0         0                     2020-11-03
S4de45e7 NA         0        0         0                     2020-11-05
Sa957143 NA         0        0         1                     2020-07-11
S0332ad6 NA         0        0         0                     2020-06-05
         Q1_Personnummer Avbruten_graviditet age_checked Age_groups
Sa79a719 P1f862a6        0                   32          3
S3db7da6 P3db7da6        0                   30          3
S424fd61 P424fd61        0                   40          4
S4de45e7 P4de45e7        0                   31          3
Sa957143 P50f102c        0                   34          3
S0332ad6 P5b98b6c        0                   30          3
         Swedish_born ⋯ missfall.IUFD_week IUFD missfall missfall.IUFD_comments
Sa79a719 1            ⋯ NA                 NA   NA       NA
S3db7da6 1            ⋯ NA                 NA   NA       NA
S424fd61 1            ⋯ NA                 NA   NA       NA
S4de45e7 1            ⋯ NA                 NA   NA       NA
Sa957143 1            ⋯ NA                 NA   NA       NA
S0332ad6 1            ⋯ NA                 NA   NA       NA
         Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
Sa79a719 41              Induction            NA          NA
S3db7da6 39              Spontaneous          NA          NA
S424fd61 38              Spontaneous          NA          NA
S4de45e7 40              Spontaneous          NA          NA
Sa957143 40              Spontaneous          NA          NA
S0332ad6 41              Spontaneous          NA          NA
         preeclampsia_epi_analysis Group
Sa79a719 0                         Second pregnancy
S3db7da6 0                         Second pregnancy
S424fd61 0                         Second pregnancy
S4de45e7 0                         Second pregnancy
Sa957143 0                         Second pregnancy
S0332ad6 0                         Second pregnancy

[1]  19 565

In [4]:
# Find missing samples in kit2

pn_fp_tp2 <- fp_saliva |>
    filter(is.na(kit2.salival_sample.barcode)) |>
    pull(Q1_Personnummer)
pn_fp_tp2
length(pn_fp_tp2)

[1] "Pf573f67"

[1] 1

In [5]:
pn_sp_tp2 <- sp_saliva |>
    filter(is.na(kit2.salival_sample.barcode)) |>
    pull(Q1_Personnummer)
pn_sp_tp2
length(pn_sp_tp2)

 [1] "P424fd61" "P4de45e7" "P50f102c" "P5b98b6c" "P7ece52e" "Pa8f3b51"
 [7] "Pc77a35c" "Pc9a3575" "Pca94a0f" "Pdab1897"

[1] 10

In [17]:
sp_saliva$kit2.salival_sample.barcode

 [1] 15399 17232    NA    NA    NA    NA 19335 18192    NA 20183    NA 21481
[13]    NA    NA    NA 17263    NA 19613 19008

In [6]:
drop_pn_combined_tp2 <- c(pn_fp_tp2, pn_sp_tp2)
length(drop_pn_combined_tp2)

[1] 11

In [7]:
fp_tp2_saliva <- fp_saliva |>
    filter(!(Q1_Personnummer %in% drop_pn_combined_tp2))
head(fp_tp2_saliva)
dim(fp_tp2_saliva)

         Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
S1f862a6 NA         0        0         0                     2018-03-07
S39fe1d7 NA         0        0         0                     2018-06-23
S719b21e NA         0        0         0                     2018-07-09
S735d77f NA         0        0         0                     2018-08-24
S92b4604 NA         0        0         2                     2018-08-21
Se5be4e8 NA         0        0         0                     2018-07-03
         Q1_Personnummer Avbruten_graviditet age_checked Age_groups
S1f862a6 P1f862a6        0                   32          3
S39fe1d7 P3db7da6        0                   29          2
S719b21e P719b21e        0                   29          2
S735d77f P735d77f        0                   25          2
S92b4604 P92b4604        0                   35          4
Se5be4e8 Pbbb08bd        0                   33          3
         Swedish_born ⋯ missfall.IUFD_week IUFD missfall missfall.IUFD_comments
S1f862a6 1            ⋯ NA                 NA   NA       NA
S39fe1d7 1            ⋯ NA                 NA   NA       NA
S719b21e 1            ⋯ NA                 NA   NA       NA
S735d77f 1            ⋯ NA                 NA   NA       NA
S92b4604 1            ⋯ NA                 NA   NA       NA
Se5be4e8 1            ⋯ NA                 NA   NA       NA
         Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
S1f862a6 31              Spontaneous          very_w28_31  1
S39fe1d7 41              Spontaneous          NA          NA
S719b21e 39              Spontaneous          NA          NA
S735d77f 39              Spontaneous          NA          NA
S92b4604 38              Spontaneous          NA          NA
Se5be4e8 40              Spontaneous          NA          NA
         preeclampsia_epi_analysis Group
S1f862a6 0                         First pregnancy
S39fe1d7 0                         First pregnancy
S719b21e 0                         First pregnancy
S735d77f 0                         First pregnancy
S92b4604 0                         First pregnancy
Se5be4e8 0                         First pregnancy

[1]   8 565

In [8]:
sp_tp2_saliva <- sp_saliva |>
    filter(!(Q1_Personnummer %in% drop_pn_combined_tp2))
head(sp_tp2_saliva)
dim(sp_tp2_saliva)

         Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb Q1_Datum
Sa79a719 NA         0        0         1                     2019-01-17
S3db7da6 NA         0        0         1                     2019-09-24
S02c5e39 NA         0        0         0                     2020-06-01
S9deb4a6 NA         0        0         0                     2019-11-20
S5a2acf4 NA         0        0         2                     2020-04-06
Sbbb08bd NA         0        0         1                     2019-11-15
         Q1_Personnummer Avbruten_graviditet age_checked Age_groups
Sa79a719 P1f862a6        0                   32          3
S3db7da6 P3db7da6        0                   30          3
S02c5e39 P719b21e        0                   31          3
S9deb4a6 P735d77f        0                   26          2
S5a2acf4 P92b4604        0                   37          4
Sbbb08bd Pbbb08bd        0                   34          3
         Swedish_born ⋯ missfall.IUFD_week IUFD missfall missfall.IUFD_comments
Sa79a719 1            ⋯ NA                 NA   NA       NA
S3db7da6 1            ⋯ NA                 NA   NA       NA
S02c5e39 1            ⋯ NA                 NA   NA       NA
S9deb4a6 1            ⋯ NA                 NA   NA       NA
S5a2acf4 1            ⋯ NA                 NA   NA       NA
Sbbb08bd 1            ⋯ NA                 NA   NA       NA
         Gest_w_combined deliv_start_combined Type_of_PTB s_PTB
Sa79a719 41              Induction            NA          NA
S3db7da6 39              Spontaneous          NA          NA
S02c5e39 39              Spontaneous          NA          NA
S9deb4a6 39              Spontaneous          NA          NA
S5a2acf4 38              Induction            NA          NA
Sbbb08bd 38              Unlaboured c-section NA          NA
         preeclampsia_epi_analysis Group
Sa79a719 0                         Second pregnancy
S3db7da6 0                         Second pregnancy
S02c5e39 0                         Second pregnancy
S9deb4a6 0                         Second pregnancy
S5a2acf4 0                         Second pregnancy
Sbbb08bd 0                         Second pregnancy

[1]   8 565

In [9]:
fp_tp2_saliva$Primipara

[1] 1 1 1 1 1 1 1 1

In [10]:
# The participants need to be marked as multiparous for sp  
sp_tp2_saliva$Primipara

[1] 0 0 0 0 0 0 0 0

In [11]:
dim(sp_tp2_saliva)

[1]   8 565

In [13]:
write.table(fp_tp2_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp2_nulliparous/", 
                                  Sys.Date(), "_fp_tp2_nulliparous", ".csv"), sep = ",", row.names = FALSE)

write.table(sp_tp2_saliva, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/saliva/tp2_nulliparous/", 
                                  Sys.Date(), "_sp_tp2_nulliparous", ".csv"), sep = ",", row.names = FALSE)