#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: select_nulliparous_tp1
# Date: 2025.07.29
# Programmer: Barbara Nowak
# Purpose: (File 3, drop_na_kit1 comes before) Extract Nulliparous women, copy fp and sp data to different files, 
# Here I used data which had already been filtered by kit_feacal == TRUE, meaning I first filtered on if samples were valid then on nulliparity
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ──────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
# Read in filtered data 
fp <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp1_filtered/2025-07-30_fp_tp1_filt.csv", header = TRUE)
dim(fp)
head(fp)

[1]  45 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5254 S14e664f     NA         0        0         1
2 5367 S194e21b     NA         0        0         0
3 5297 S1a267fa     NA         0        0         0
4 5208 Sa8397fa     NA         0        0         0
5 5301 S1f862a6     NA         0        0         0
6 5402 S3780ac4     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-09-10 P14e664f        0                   30          ⋯  0
2 2018-11-16 P159f9c8        0                   36          ⋯  0
3 2019-05-23 P1a267fa        0                   32          ⋯  0
4 2018-03-14 P1ef420d        0                   27          ⋯  0
5 2018-03-07 P1f862a6        0                   32          ⋯  0
6 2019-02-23 P3780ac4        0                   38          ⋯ NA
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     39
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     38
4 NA                 NA   NA       NA                     28
5 NA                 NA   NA       NA                     31
6 NA                 NA   NA       NA                     NA
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Induction            NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          very_w28_31  1    0
6 NA                   NA          NA    0

In [3]:
sp <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/feacal/tp1_filtered/2025-07-30_sp_tp1_filt.csv", header = TRUE)
head(sp)
dim(sp)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5290 Sefe71fe     NA         0        0         1
2 5391 S159f9c8     NA         0        0         0
3 5332 Sb124b17     NA         0        0         2
4 5247 S1ef420d     NA         0        0         1
5 5305 Sa79a719     NA         0        0         1
6 5400 Scdb718f     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2020-08-17 P14e664f        0                   32          ⋯ 0
2 2021-01-28 P159f9c8        0                   38          ⋯ 0
3 2021-01-06 P1a267fa        0                   34          ⋯ 0
4 2020-09-17 P1ef420d        0                   30          ⋯ 0
5 2019-01-17 P1f862a6        0                   32          ⋯ 0
6 2020-01-10 P3780ac4        1                   38          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     39
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    0

[1]  45 566

In [4]:
# Find fp women where birth date of child is missing
pn_fp_missing_birthdate <- fp |>
  filter(is.na(fodelsedatum_barn)) |>
  pull(Q1_Personnummer)
pn_fp_missing_birthdate
length(unique(pn_fp_missing_birthdate))

 [1] "P3780ac4" "P428e1c4" "P46f36c7" "P6d2ebc4" "P7f1746e" "Pab443f9"
 [7] "Pbe04f9f" "Pc10d0b0" "Pc3a5016" "Pc9a3575" "Pd01a0ba" "Pd3b97e6"
[13] "Pe3450d3" "Pf573f67" "Pff3c644"

[1] 15

In [27]:
# Keep only participants where birthdate exists
fp_filtered_birthdate <- fp |>
  filter(!(Q1_Personnummer %in% pn_fp_missing_birthdate)) 
dim(fp_filtered_birthdate)

[1]  30 566

In [28]:
# Find fp women with primipara = TRUE
pn_fp_primipara <- fp |>
  filter(fp$Primipara == 1) |>
  pull(Q1_Personnummer)

In [29]:
# Keep only participants that are primiparous

fp_filtered <- fp_filtered_birthdate |>
  filter(Q1_Personnummer %in% pn_fp_primipara) 
head(fp_filtered)
dim(fp_filtered)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5208 Sa8397fa     NA         0        0         0
4 5301 S1f862a6     NA         0        0         0
5 5285 S3c0f6ee     NA         0        0         0
6 5275 S2b86cc0     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2019-05-23 P1a267fa        0                   32          ⋯ 0
3 2018-03-14 P1ef420d        0                   27          ⋯ 0
4 2018-03-07 P1f862a6        0                   32          ⋯ 0
5 2019-03-25 P3c0f6ee        0                   31          ⋯ 0
6 2019-05-29 P3cac7b0        0                   31          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     28
4 NA                 NA   NA       NA                     31
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  25 566

In [30]:
# Find all primipara personal# from fp
pn_filtered <- fp_filtered |>
  pull(Q1_Personnummer)
pn_filtered
length(pn_filtered)

 [1] "P159f9c8" "P1a267fa" "P1ef420d" "P1f862a6" "P3c0f6ee" "P3cac7b0"
 [7] "P3db7da6" "P424fd61" "P4a05456" "P4de45e7" "P50f102c" "P5b98b6c"
[13] "P62ea0b2" "P719b21e" "P7ece52e" "P92b4604" "P97574f9" "P9cdfd5a"
[19] "Pa8f3b51" "Pbe289c8" "Pc44e366" "Pc77a35c" "Pcd2c0d1" "Pdab1897"
[25] "Pe706703"

[1] 25

In [31]:
# Keep sp participants primiparous in fp
sp_filtered <- sp |>
  filter(Q1_Personnummer %in% pn_filtered)
head(sp_filtered)
dim(sp_filtered)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5332 Sb124b17     NA         0        0         2
3 5247 S1ef420d     NA         0        0         1
4 5305 Sa79a719     NA         0        0         1
5 5310 S5097402     NA         0        0         1
6 5311 S3cac7b0     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯ 0
2 2021-01-06 P1a267fa        0                   34          ⋯ 0
3 2020-09-17 P1ef420d        0                   30          ⋯ 0
4 2019-01-17 P1f862a6        0                   32          ⋯ 0
5 2020-10-18 P3c0f6ee        0                   33          ⋯ 0
6 2020-10-20 P3cac7b0        0                   33          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Induction            NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  25 566

In [32]:
# Doubble check that all are no longer primiparous
pn_check <- sp_filtered |> 
  filter(sp_filtered$Primipara == 1) |>
  pull(Q1_Personnummer)
pn_check
length(pn_check)

character(0)

[1] 0

In [33]:
# Double check that birthdates present
pn_check2 <- sp_filtered |>
  filter(is.na(fodelsedatum_barn)) |>
  pull(Q1_Personnummer)
pn_check2

[1] "Pc77a35c"

In [34]:
filter(sp_filtered, Q1_Personnummer == "Pc77a35c") |>
  pull(fodelsedatum_barn)

[1] NA

In [35]:
# Check if weight present
grep("weight", names(sp_filtered), value = TRUE)

[1] "Birthweight_checked" "excess_weight"

In [36]:
filter(sp_filtered, Q1_Personnummer == "Pc77a35c") |>
  pull(Birthweight_checked)

[1] 4395

In [ ]:
# Write both filtered df to file
#write.table(fp_filtered, file = paste0("~/Programs/Programing_experiments/R/HT25_project/filtered_data/", Sys.Date(), "fp_tp1_filt_nulliparous", ".csv"), sep = ",", row.names = FALSE)
#write.table(sp_filtered, file = paste0("~/Programs/Programing_experiments/R/HT25_project/filtered_data/", Sys.Date(), "sp_tp1_filt_nulliparous", ".csv"), sep = ",", row.names = FALSE)

In [20]:
# Write file with combined fp and sp 
fp_filtered$Group <- "First pregnancy "
sp_filtered$Group <- "Second pregnancy"

In [21]:
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_filtered, sp_filtered)
dim(combined_fp_sp)
head(combined_fp_sp)

[1]  50 567

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5297 S1a267fa     NA         0        0         0
3 5208 Sa8397fa     NA         0        0         0
4 5301 S1f862a6     NA         0        0         0
5 5285 S3c0f6ee     NA         0        0         0
6 5275 S2b86cc0     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-11-16 P159f9c8        0                   36          ⋯
2 2019-05-23 P1a267fa        0                   32          ⋯
3 2018-03-14 P1ef420d        0                   27          ⋯
4 2018-03-07 P1f862a6        0                   32          ⋯
5 2019-03-25 P3c0f6ee        0                   31          ⋯
6 2019-05-29 P3cac7b0        0                   31          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     38
3 NA                 NA   NA       NA                     28
4 NA                 NA   NA       NA                     31
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          very_w28_31  1    0
4 Spontaneous          very_w28_31  1    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [ ]:
# Write combined, filtered data to file
write.table(combined_fp_sp, file = paste0("~/Programs/Programing_experiments/R/HT25_project/filtered_data/", Sys.Date(), "_combined_fp_sp_tp1", ".csv"), sep = ",", row.names = FALSE)