#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: taxa_filtering_minimum
# Date: 2025.11.06
# Programmer: Barbara Nowak
# Purpose: Remove minimum abundance and prevalence taxa from taxa data, find valid barcodes and filter taxa based on nulliparity
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [26]:
library(tidyverse)
library(dplyr)

# File reading -----------------------------------------------------------------------------------------------------------------------------------------

In [27]:
taxa_tab <- read.table("/ceph/projects/010_SweMaMi/bm.nowak/data/all_vaginal_data_24_10_28.tsv", header = TRUE, sep = "\t" )
dim(taxa_tab)
colSums(taxa_tab)

[1] 1336 6037

                                           FF01572457
                                             99.99999
                                           FB02825199
                                            100.00001
                                           FF00653393
                                            100.00000
                                           FB02846074
                                            100.00004
                                           FF00619375
                                            100.00000
                                           FF00531869
                                            100.00001
                                           FF03815895
                                            100.00000
                                           FF06039864
                                            100.00001
                                           FF00652166
                                             99.99999
            not_sequenced_010SweMaMi_tra16_FF00530583
                                              0.00000
                                           FF00941092
                                            100.00000
                                           FF00657963
                                            100.00000
                                           FF02013805
                                            100.00001
                                           FB03582940
                                            100.00001
                                           FF00619946
                                            100.00000
                                           FF00652980
                                             99.99999
                                           FF00652175
                                            100.00001
                                           FF00620188
                                            100.00000
                                           FF00620287
                                            100.00000
                                           FF00620181
                                             99.99996
                                           FF00530066
                                            100.00000
                                           FF01571920
                                            100.00000
                                           FF01570835
                                            100.00000
                                           FF03937632
                                            100.00001
                                           FF00531221
                                            100.00000
                                           FF01570372
                                             99.99999
                                           FF00652106
                                            100.00001
                                           FF00940839
                                             99.99997
                                           FF00652256
                                            100.00001
                                           FF02740640
                                             99.99999
                                           FF00653421
                                             99.99998
                                           FF00657463
                                            100.00001
                                           FF02015801
                                            100.00000
                                           FF00620189
                                            100.00000
                                           FB02825209
                                             99.99999
                                           FF04023597
                                            100.00001
                                           FB03582963
                                            100.00000
                                           FF00620031
                                            100.00000
                                           FF00653003
                                            100.00003
                                           FF02015163
                                            100.00000
                                           FF00940827
                                             99.99999
                                           FF00530255
                                            100.00000
                                           FF01572410
                                             99.99999
                                           FF00652240
                                            100.00002
                                           FF00652234
                                            100.00001
                                           FF00620196
                                            100.00002
                                           FF00940854
                                            100.00000
                                           FF05043895
                                             99.99999
                                           FF01571549
                                             99.99999
                                           FF00652207
                                            100.00001
                                           FF00620269
                                             99.99999
                                           FF00530249
                                            100.00000
                                           FF02739464
                                            100.00000
                                           FF02557391
                                             99.99999
                                           FB02846079
                                            100.00000
                                           FF02014428
                                            100.00000
                                           FF03815890
                                            100.00000
                                           FF00657311
                                            100.00001
                                           FF02557308
                                            100.00000
                                           FF01570284
                                            100.00001
                                           FF00531731
                                             99.99999
                                           FF01571457
                                            100.00001
                                           FF00657492
                                            100.00000
                                           FF00531073
                                            100.00001
                                           FF04024705
                                            100.00000
                                           FF00620299
                                            100.00000
            not_sequenced_010SweMaMi_tra41_FF00657579
                                            100.00000
            not_sequenced_010SweMaMi_tra46_FF02557387
                                            100.00000
                                           FF03815891
                                            100.00001
                                           FF00657949
                                            100.00000
                                           FF00940857
                                            100.00000
                                           FF01571283
                                             99.99999
                                           FF00653389
                                            100.00000
                                           FF03815360
                                            100.00000
                                           FF00651884
                                            100.00000
                                           FF06040480
                                            100.00000
                                           FF03815297
                                            100.00000
                                           FB03582939
                                            100.00000
                                           FF00619369
                                             99.99999
                                           FF02740655
                                            100.00001
                                           FF00653544
                                            100.00000
                                           FB02825181
                                            100.00000
                                           FF02015862
                                            100.00000
                                           FF06040493
                                             99.99998
                                           FF01572557
                                            100.00000
                                           FF02015764
                                            100.00001
                                           FB03582933
                                            100.00001
                                           FF02014319
                                             99.99999
                                           FF00531735
                                            100.00000
                                           FF06039204
                                            100.00001
                                           FF00652206
                                             99.99999
                                           FF05042910
                                            100.00000
                                           FF00620055
                                            100.00002
                                           FF00619964
                                             99.99998
                                           FB02826905
                                            100.00000
                                           FF00651964
                                            100.00000
                                           FF00653390
                                            100.00000
                                           FF00620290
                                            100.00001
                                           FF01571924
                                             99.99999
                                           FF00940908
                                             99.99999
                                           FF00653373
                                             99.99999
                                           FF05043985
                                            100.00000
                                           FF00657453
                                             99.99999
                                           FF00620302
                                            100.00000
                                           FF00657928
                                             99.99999
            not_sequenced_010SweMaMi_tra46_FF02557389
                                            100.00000
                                           FF00657547
                                            100.00000
                                           FF03815917
                                            100.00003
                                           FF03815751
                                            100.00001
                                           FB02825411
                                            100.00001
                                           FF04023675
                                            100.00000
                                           FF00619876
                                            100.00000
                                           FF05043811
                                            100.00000
                                           FF00652250
                                            100.00000
                                           FF05043808
                                             99.99999
                                           FF00619883
                                            100.00000
                                           FF00531217
                                            100.00001
            not_sequenced_010SweMaMi_tra40_FF00531135
                                              0.00000
                                           FF01571556
                                            100.00001
                                           FF00620194
                                            100.00001
                                           FF05042914
                                            100.00001
                                           FF06039246
                                             99.99999
                                           FF00530069
                                            100.00000
                                           FF02557846
                                            100.00000
                                           FF00657322
                                            100.00000
                                           FF00653388
                                            100.00000
                                           FF02014790
                                            100.00000
                                           FF03815369
                                            100.00003
                                           FB02846071
                                            100.00001
                                           FF00531464
                                             99.99999
                                           FF02556147
                                            100.00000
                                           FF03815350
                                            100.00000
                                           FF01571928
                                            100.00000
                                           FB02846884
                                            100.00000
                                           FB02826883
                                             99.99999
                                           FF00530113
                                            100.00000
                                           FF05044785
                                             99.99998
                                           FF00530215
                                            100.00000
                                           FF06039868
                                             99.99997
                                           FF00620285
                                            100.00001
                                           FF00653542
                                            100.00002
                                           FB02826918
                                             99.99999
                                           FF01570379
                                             99.99998
                                           FF01572487
                                             99.99999
                                           FF00530554
                                            100.00000
                                           FF00531145
                                             99.99999
                                           FF00652205
                                             99.99999
                                           FF01572445
                                            100.00000
            not_sequenced_010SweMaMi_tra46_FF02557383
                                            100.00000
                                           FF02739450
                                             99.99999
                                           FF01571290
                                            100.00000
                                           FF01572121
                                             99.99997
                                           FF00529960
                                            100.00000
                                           FF02014830
                                             99.99998
                                           FB02846877
                                             99.99999
                                           FF00651959
                                            100.00000
                                           FF02015778
                                            100.00002
                                           FF05024953
                                            100.00000
                                           FB02825192
                                            100.00001
                                           FF00653522
                                            100.00000
                                           FF01571335
                                             99.99999
                                           FF00651912
                                            100.00002
                                           FF00530111
                                             99.99999
                                           FB02825208
                                            100.00001
                                           FF00619950
                                            100.00001
                                           FB02825185
                                            100.00001
                                           FF06039962
                                            100.00000
                                           FF00620268
                                             99.99999
                                           FF02739452
                                            100.00000
                                           FF00940878
                                            100.00000
                                           FF03815228
                                            100.00001
                                           FF03815353
                                            100.00001
                                           FF00531134
                                            100.00000
                                           FF03815873
                                             99.99999
                                           FF05043972
                                            100.00000
                                           FF05043973
                                            100.00000
                                           FF00653452
                                            100.00000
                                           FF01571282
                                            100.00000
                                           FF00657481
                                            100.00000
                                           FF01570356
                                             99.99999
                                           FF00529967
                                            100.00000
                                           FF00653440
                                            100.00001
                                           FF00653269
                                            100.00000
                                           FF05043956
                                            100.00000
                                           FF03815380
                                            100.00000

In [28]:
colSums(taxa_tab > 2)

                                           FF01572457
                                                    1
                                           FB02825199
                                                    2
                                           FF00653393
                                                    4
                                           FB02846074
                                                    2
                                           FF00619375
                                                    1
                                           FF00531869
                                                    3
                                           FF03815895
                                                    2
                                           FF06039864
                                                    2
                                           FF00652166
                                                    2
            not_sequenced_010SweMaMi_tra16_FF00530583
                                                    0
                                           FF00941092
                                                    3
                                           FF00657963
                                                    1
                                           FF02013805
                                                    3
                                           FB03582940
                                                    2
                                           FF00619946
                                                    1
                                           FF00652980
                                                    1
                                           FF00652175
                                                    5
                                           FF00620188
                                                    8
                                           FF00620287
                                                    1
                                           FF00620181
                                                    2
                                           FF00530066
                                                    1
                                           FF01571920
                                                    1
                                           FF01570835
                                                    1
                                           FF03937632
                                                    1
                                           FF00531221
                                                    1
                                           FF01570372
                                                    1
                                           FF00652106
                                                    2
                                           FF00940839
                                                    1
                                           FF00652256
                                                    2
                                           FF02740640
                                                    1
                                           FF00653421
                                                    5
                                           FF00657463
                                                    1
                                           FF02015801
                                                    2
                                           FF00620189
                                                    1
                                           FB02825209
                                                    1
                                           FF04023597
                                                    1
                                           FB03582963
                                                    2
                                           FF00620031
                                                    1
                                           FF00653003
                                                    6
                                           FF02015163
                                                    1
                                           FF00940827
                                                    2
                                           FF00530255
                                                    2
                                           FF01572410
                                                    1
                                           FF00652240
                                                    2
                                           FF00652234
                                                    3
                                           FF00620196
                                                    1
                                           FF00940854
                                                    3
                                           FF05043895
                                                    1
                                           FF01571549
                                                    1
                                           FF00652207
                                                    1
                                           FF00620269
                                                    5
                                           FF00530249
                                                    1
                                           FF02739464
                                                    1
                                           FF02557391
                                                    3
                                           FB02846079
                                                    2
                                           FF02014428
                                                    3
                                           FF03815890
                                                    2
                                           FF00657311
                                                    4
                                           FF02557308
                                                    1
                                           FF01570284
                                                    3
                                           FF00531731
                                                    2
                                           FF01571457
                                                    1
                                           FF00657492
                                                    1
                                           FF00531073
                                                    5
                                           FF04024705
                                                    2
                                           FF00620299
                                                    5
            not_sequenced_010SweMaMi_tra41_FF00657579
                                                    1
            not_sequenced_010SweMaMi_tra46_FF02557387
                                                    1
                                           FF03815891
                                                    6
                                           FF00657949
                                                    1
                                           FF00940857
                                                    1
                                           FF01571283
                                                    2
                                           FF00653389
                                                    1
                                           FF03815360
                                                    1
                                           FF00651884
                                                    6
                                           FF06040480
                                                    1
                                           FF03815297
                                                    2
                                           FB03582939
                                                    2
                                           FF00619369
                                                    1
                                           FF02740655
                                                    3
                                           FF00653544
                                                    3
                                           FB02825181
                                                    1
                                           FF02015862
                                                    1
                                           FF06040493
                                                    5
                                           FF01572557
                                                    1
                                           FF02015764
                                                    6
                                           FB03582933
                                                    2
                                           FF02014319
                                                    1
                                           FF00531735
                                                    2
                                           FF06039204
                                                    1
                                           FF00652206
                                                    4
                                           FF05042910
                                                    2
                                           FF00620055
                                                    1
                                           FF00619964
                                                    2
                                           FB02826905
                                                    1
                                           FF00651964
                                                    1
                                           FF00653390
                                                    1
                                           FF00620290
                                                    3
                                           FF01571924
                                                    1
                                           FF00940908
                                                    2
                                           FF00653373
                                                    2
                                           FF05043985
                                                    1
                                           FF00657453
                                                    5
                                           FF00620302
                                                    1
                                           FF00657928
                                                    1
            not_sequenced_010SweMaMi_tra46_FF02557389
                                                    2
                                           FF00657547
                                                    2
                                           FF03815917
                                                    3
                                           FF03815751
                                                    1
                                           FB02825411
                                                    1
                                           FF04023675
                                                    8
                                           FF00619876
                                                    3
                                           FF05043811
                                                    2
                                           FF00652250
                                                    1
                                           FF05043808
                                                    2
                                           FF00619883
                                                    1
                                           FF00531217
                                                    1
            not_sequenced_010SweMaMi_tra40_FF00531135
                                                    0
                                           FF01571556
                                                    1
                                           FF00620194
                                                    7
                                           FF05042914
                                                    2
                                           FF06039246
                                                    7
                                           FF00530069
                                                    3
                                           FF02557846
                                                    1
                                           FF00657322
                                                    2
                                           FF00653388
                                                    3
                                           FF02014790
                                                    1
                                           FF03815369
                                                    9
                                           FB02846071
                                                    1
                                           FF00531464
                                                    2
                                           FF02556147
                                                    1
                                           FF03815350
                                                    1
                                           FF01571928
                                                    3
                                           FB02846884
                                                    2
                                           FB02826883
                                                    1
                                           FF00530113
                                                    2
                                           FF05044785
                                                   14
                                           FF00530215
                                                    2
                                           FF06039868
                                                    3
                                           FF00620285
                                                    2
                                           FF00653542
                                                    3
                                           FB02826918
                                                    3
                                           FF01570379
                                                    4
                                           FF01572487
                                                    1
                                           FF00530554
                                                    2
                                           FF00531145
                                                    1
                                           FF00652205
                                                    2
                                           FF01572445
                                                    1
            not_sequenced_010SweMaMi_tra46_FF02557383
                                                    2
                                           FF02739450
                                                    3
                                           FF01571290
                                                    1
                                           FF01572121
                                                    7
                                           FF00529960
                                                    2
                                           FF02014830
                                                    2
                                           FB02846877
                                                    3
                                           FF00651959
                                                    1
                                           FF02015778
                                                    1
                                           FF05024953
                                                    3
                                           FB02825192
                                                    2
                                           FF00653522
                                                    2
                                           FF01571335
                                                    1
                                           FF00651912
                                                    2
                                           FF00530111
                                                    3
                                           FB02825208
                                                    2
                                           FF00619950
                                                    4
                                           FB02825185
                                                    1
                                           FF06039962
                                                    1
                                           FF00620268
                                                    6
                                           FF02739452
                                                    1
                                           FF00940878
                                                    3
                                           FF03815228
                                                    2
                                           FF03815353
                                                    1
                                           FF00531134
                                                    2
                                           FF03815873
                                                    2
                                           FF05043972
                                                    2
                                           FF05043973
                                                    1
                                           FF00653452
                                                    1
                                           FF01571282
                                                    1
                                           FF00657481
                                                    1
                                           FF01570356
                                                    2
                                           FF00529967
                                                    1
                                           FF00653440
                                                    2
                                           FF00653269
                                                    1
                                           FF05043956
                                                    3
                                           FF03815380
                                                    5

In [29]:
which(colSums(taxa_tab) < 1)

      not_sequenced_010SweMaMi_tra16_FF00530583
                                             10
      not_sequenced_010SweMaMi_tra40_FF00531135
                                            118
      not_sequenced_010SweMaMi_tra42_FF02014791
                                            192
      not_sequenced_010SweMaMi_tra23_FF06039602
                                            474
      not_sequenced_010SweMaMi_tra46_FF02557844
                                            511
      not_sequenced_010SweMaMi_tra41_FF00657574
                                            546
      not_sequenced_010SweMaMi_tra23_FF06039253
                                            635
      not_sequenced_010SweMaMi_tra42_FF00652060
                                            810
      not_sequenced_010SweMaMi_tra23_FF06039280
                                            952
      not_sequenced_010SweMaMi_tra46_FF02557271
                                            954
      not_sequenced_010SweMaMi_tra16_FF00530584
                                           1026
      not_sequenced_010SweMaMi_tra16_FF00530589
                                           1087
    not_sequenced_010SweMaMi_extra23_FF06039280
                                           1167
    not_sequenced_010SweMaMi_extra23_FF06039602
                                           1168
    not_sequenced_010SweMaMi_extra23_FF06039253
                                           1170
    not_sequenced_010SweMaMi_extra46_FF02557844
                                           1175
    not_sequenced_010SweMaMi_extra46_FF02557271
                                           1176
    not_sequenced_010SweMaMi_extra16_FF00530584
                                           1182
    not_sequenced_010SweMaMi_extra16_FF00530583
                                           1183
    not_sequenced_010SweMaMi_extra16_FF00530589
                                           1185
    not_sequenced_010SweMaMi_extra42_FF00652060
                                           1186
    not_sequenced_010SweMaMi_extra42_FF02014791
                                           1187
    not_sequenced_010SweMaMi_extra40_FF00531135
                                           1190
    not_sequenced_010SweMaMi_extra41_FF00657574
                                           1197
    not_sequenced_010SweMaMi_extra43_FB02846068
                                           1390
    not_sequenced_010SweMaMi_extra43_FF02014435
                                           1392
    not_sequenced_010SweMaMi_extra43_FF02014331
                                           1393
    not_sequenced_010SweMaMi_extra43_FF00653038
                                           1394
    not_sequenced_010SweMaMi_extra17_FF00530064
                                           1398
    not_sequenced_010SweMaMi_extra17_FF00530089
                                           1401
                      X010_extraction17_pos_ext
                                           1402
                                     FF00531027
                                           1425
                                     FF00530112
                                           1435
                                     FF00653075
                                           1440
                                     FF00529961
                                           1443
    not_sequenced_010SweMaMi_extra17_FF00529959
                                           1448
       not_sequenced_010SweMaMi_extra17_neg_ext
                                           1452
                                     FF00620276
                                           1454
                                     FF00530071
                                           1456
                                     FF00620297
                                           1459
                                     FF00530061
                                           1462
                                     FF02014338
                                           1468
                                     FF00620303
                                           1475
    not_sequenced_010SweMaMi_extra20_FF02739962
                                           1491
    not_sequenced_010SweMaMi_extra20_FF03817625
                                           1508
                                     FF03817641
                                           1531
    not_sequenced_010SweMaMi_extra20_FF03817610
                                           1538
       not_sequenced_010SweMaMi_extra20_neg_ext
                                           1545
    not_sequenced_010SweMaMi_extra20_FF00530512
                                           1556
    not_sequenced_010SweMaMi_extra20_FF03817161
                                           1573
    not_sequenced_010SweMaMi_extra19_FF03816469
                                           1574
    not_sequenced_010SweMaMi_extra19_FF03818250
                                           1584
    not_sequenced_010SweMaMi_extra19_FF02014689
                                           1586
    not_sequenced_010SweMaMi_extra19_FF03816679
                                           1587
    not_sequenced_010SweMaMi_extra19_FF02015451
                                           1598
    not_sequenced_010SweMaMi_extra19_FF03816668
                                           1605
    not_sequenced_010SweMaMi_extra19_FF03817221
                                           1636
    not_sequenced_010SweMaMi_extra19_FF03817611
                                           1643
    not_sequenced_010SweMaMi_extra19_FF03816693
                                           1650
    not_sequenced_010SweMaMi_extra19_FF02015450
                                           1652
    not_sequenced_010SweMaMi_extra18_FF02015022
                                           1673
    not_sequenced_010SweMaMi_extra18_FF02014716
                                           1675
       not_sequenced_010SweMaMi_extra18_neg_ext
                                           1684
    not_sequenced_010SweMaMi_extra18_FF02014994
                                           1687
                                     FF00653214
                                           1698
    not_sequenced_010SweMaMi_extra18_FF02014718
                                           1704
    not_sequenced_010SweMaMi_extra18_FF02014712
                                           1712
    not_sequenced_010SweMaMi_extra18_FF02014422
                                           1745
    not_sequenced_010SweMaMi_extra21_FF01570624
                                           1751
    not_sequenced_010SweMaMi_extra21_FF01570651
                                           1828
   not_sequenced_010SweMaMi_extra24_pos_ext_log
                                           1860
       not_sequenced_010SweMaMi_extra24_neg_ext
                                           1907
        not_sequenced_010SweMaMi_extra5_neg_ext
                                           2171
     not_sequenced_010SweMaMi_extra5_FF05043016
                                           2174
     not_sequenced_010SweMaMi_extra8_FF03817123
                                           2275
    not_sequenced_010SweMaMi_extra36_FB03582972
                                           2322
    not_sequenced_010SweMaMi_extra36_FF00653525
                                           2343
    not_sequenced_010SweMaMi_extra36_FF00653394
                                           2354
       not_sequenced_010SweMaMi_extra36_neg_ext
                                           2364
       not_sequenced_010SweMaMi_extra45_neg_seq
                                           2599
       not_sequenced_010SweMaMi_extra45_neg_ext
                                           2615
not_sequenced_010SweMaMi_extra25_3rdRun_neg_ext
                                           2802
    not_sequenced_010SweMaMi_extra34_FF00652198
                                           2817
       not_sequenced_010SweMaMi_extra15_neg_ext
                                           2995
       not_sequenced_010SweMaMi_extra47_neg_ext
                                           3816
       not_sequenced_010SweMaMi_extra11_neg_seq
                                           3902
    not_sequenced_010SweMaMi_extra11_FF03817586
                                           3906
       not_sequenced_010SweMaMi_extra11_neg_ext
                                           3922
    not_sequenced_010SweMaMi_extra11_FF03817590
                                           3952
                      X010_extraction10_pos_ext
                                           3982
    not_sequenced_010SweMaMi_extra10_FF03817560
                                           3986
                                     FF03816847
                                           4023
                                     FF03816882
                                           4035
       not_sequenced_010SweMaMi_extra10_neg_seq
                                           4038
                                     FF03816808
                                           4045
     not_sequenced_010SweMaMi_extra3_FF05043865
                                           4227
     not_sequenced_010SweMaMi_extra3_FF06039242
                                           4233
       not_sequenced_010SweMaMi_extra14_neg_seq
                                           4258
       not_sequenced_010SweMaMi_extra49_neg_ext
                                           4421
                                     FF02015049
                                           4555
                                     FF01566730
                                           4976

In [30]:
head(taxa_tab)

                                       FF01572457 FB02825199 FF00653393
Abiotrophia sp_HMSC24B09               0          0          0
Abyssicoccus albus                     0          0          0
Acholeplasmatales unclassified_SGB6584 0          0          0
Acidaminococcus intestini              0          0          0
Acidovorax ebreus                      0          0          0
Acinetobacter johnsonii                0          0          0
                                       FB02846074 FF00619375 FF00531869
Abiotrophia sp_HMSC24B09               0          0          0
Abyssicoccus albus                     0          0          0
Acholeplasmatales unclassified_SGB6584 0          0          0
Acidaminococcus intestini              0          0          0
Acidovorax ebreus                      0          0          0
Acinetobacter johnsonii                0          0          0
                                       FF03815895 FF06039864 FF00652166
Abiotrophia sp_HMSC24B09               0          0          0
Abyssicoccus albus                     0          0          0
Acholeplasmatales unclassified_SGB6584 0          0          0
Acidaminococcus intestini              0          0          0
Acidovorax ebreus                      0          0          0
Acinetobacter johnsonii                0          0          0
                                       not_sequenced_010SweMaMi_tra16_FF00530583
Abiotrophia sp_HMSC24B09               0
Abyssicoccus albus                     0
Acholeplasmatales unclassified_SGB6584 0
Acidaminococcus intestini              0
Acidovorax ebreus                      0
Acinetobacter johnsonii                0
                                       ⋯ FF02014701 FF02014180 FF02014994
Abiotrophia sp_HMSC24B09               ⋯ 0          0          0
Abyssicoccus albus                     ⋯ 0          0          0
Acholeplasmatales unclassified_SGB6584 ⋯ 0          0          0
Acidaminococcus intestini              ⋯ 0          0          0
Acidovorax ebreus                      ⋯ 0          0          0
Acinetobacter johnsonii                ⋯ 0          0          0
                                       FF05044768 FF02015306 FF03815206
Abiotrophia sp_HMSC24B09               0          0          0
Abyssicoccus albus                     0          0          0
Acholeplasmatales unclassified_SGB6584 0          0          0
Acidaminococcus intestini              0          0          0
Acidovorax ebreus                      0          0          0
Acinetobacter johnsonii                0          0          0
                                       FF02014712 FF05044788 neg_seq
Abiotrophia sp_HMSC24B09               0          0          0
Abyssicoccus albus                     0          0          0
Acholeplasmatales unclassified_SGB6584 0          0          0
Acidaminococcus intestini              0          0          0
Acidovorax ebreus                      0          0          0
Acinetobacter johnsonii                0          0          0
                                       zymomock_seq
Abiotrophia sp_HMSC24B09               0
Abyssicoccus albus                     0
Acholeplasmatales unclassified_SGB6584 0
Acidaminococcus intestini              0
Acidovorax ebreus                      0
Acinetobacter johnsonii                0

In [31]:
fp <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_fp_.csv", header = TRUE)
head(fp)
dim(fp)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

[1]  59 566

In [32]:
sp <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_sp_.csv", header = TRUE)
head(sp)
dim(sp)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

[1]  59 566

# Filtering taxa ------------------------------------------------------------------------------------------------------------------------------------------------------------

In [33]:
# Function for removing minimum abundance and prevalence taxa
is_here <- function(invector, min_abund, min_pres){
  min_count <- length(invector) * min_pres
  these <- length(which(invector > min_abund))
  if(these > min_count){
    return(TRUE)
  }
  else{
    return(FALSE)
  }
}

keep <- apply(taxa_tab , MARGIN = 1, is_here, min_abund = 0.001, min_pres = 0.05)
filt_taxa <- taxa_tab [keep,]
head(filt_taxa)
dim(filt_taxa)

                          FF01572457 FB02825199 FF00653393 FB02846074
Actinobaculum massiliense 0          0          0          0.01894
Aerococcus christensenii  0          0          0          0.00000
Alloscardovia omnicolens  0          0          0          0.41648
Anaerococcus hydrogenalis 0          0          0          0.00000
Anaerococcus lactolyticus 0          0          0          0.00000
Anaerococcus prevotii     0          0          0          0.09146
                          FF00619375 FF00531869 FF03815895 FF06039864
Actinobaculum massiliense 0.00000    0.00000    0          0
Aerococcus christensenii  0.00000    0.06042    0          0
Alloscardovia omnicolens  0.00000    0.00000    0          0
Anaerococcus hydrogenalis 0.00000    0.00656    0          0
Anaerococcus lactolyticus 0.01752    0.00000    0          0
Anaerococcus prevotii     0.00000    0.00000    0          0
                          FF00652166 not_sequenced_010SweMaMi_tra16_FF00530583
Actinobaculum massiliense 0.00000    0
Aerococcus christensenii  0.00000    0
Alloscardovia omnicolens  0.00238    0
Anaerococcus hydrogenalis 0.00000    0
Anaerococcus lactolyticus 0.02028    0
Anaerococcus prevotii     0.00000    0
                          ⋯ FF02014701 FF02014180 FF02014994 FF05044768
Actinobaculum massiliense ⋯ 0          0.01675    0.00000    0
Aerococcus christensenii  ⋯ 0          0.00000    0.98823    0
Alloscardovia omnicolens  ⋯ 0          0.15420    0.00000    0
Anaerococcus hydrogenalis ⋯ 0          0.00000    0.00000    0
Anaerococcus lactolyticus ⋯ 0          0.00000    0.00000    0
Anaerococcus prevotii     ⋯ 0          0.00000    0.00000    0
                          FF02015306 FF03815206 FF02014712 FF05044788 neg_seq
Actinobaculum massiliense 0          0.00000    0.00000    0          0
Aerococcus christensenii  0          0.49743    0.00000    0          0
Alloscardovia omnicolens  0          0.00000    0.00000    0          0
Anaerococcus hydrogenalis 0          0.00000    0.00000    0          0
Anaerococcus lactolyticus 0          0.00000    0.00000    0          0
Anaerococcus prevotii     0          0.00000    0.00484    0          0
                          zymomock_seq
Actinobaculum massiliense 0
Aerococcus christensenii  0
Alloscardovia omnicolens  0
Anaerococcus hydrogenalis 0
Anaerococcus lactolyticus 0
Anaerococcus prevotii     0

[1]   64 6037

In [34]:
colSums(filt_taxa)
#which(colSums(filt_taxa) > 98)

                                           FF01572457
                                             99.97415
                                           FB02825199
                                            100.00001
                                           FF00653393
                                             58.03806
                                           FB02846074
                                             98.07328
                                           FF00619375
                                             98.79101
                                           FF00531869
                                             99.80528
                                           FF03815895
                                             99.99712
                                           FF06039864
                                             99.48992
                                           FF00652166
                                             99.47115
            not_sequenced_010SweMaMi_tra16_FF00530583
                                              0.00000
                                           FF00941092
                                             99.59164
                                           FF00657963
                                             99.74427
                                           FF02013805
                                            100.00001
                                           FB03582940
                                            100.00001
                                           FF00619946
                                            100.00000
                                           FF00652980
                                             99.88956
                                           FF00652175
                                            100.00001
                                           FF00620188
                                             86.43285
                                           FF00620287
                                            100.00000
                                           FF00620181
                                             99.72980
                                           FF00530066
                                            100.00000
                                           FF01571920
                                             99.34074
                                           FF01570835
                                             99.81638
                                           FF03937632
                                             99.97714
                                           FF00531221
                                             99.87989
                                           FF01570372
                                             98.65028
                                           FF00652106
                                             99.76558
                                           FF00940839
                                             99.92199
                                           FF00652256
                                             99.73181
                                           FF02740640
                                             99.98684
                                           FF00653421
                                             99.91198
                                           FF00657463
                                             99.99972
                                           FF02015801
                                            100.00000
                                           FF00620189
                                             99.84744
                                           FB02825209
                                             99.99999
                                           FF04023597
                                             99.98157
                                           FB03582963
                                             99.66693
                                           FF00620031
                                             99.90903
                                           FF00653003
                                             98.71088
                                           FF02015163
                                            100.00000
                                           FF00940827
                                             99.99346
                                           FF00530255
                                             99.40912
                                           FF01572410
                                             99.30060
                                           FF00652240
                                             98.33791
                                           FF00652234
                                             55.17737
                                           FF00620196
                                             99.74375
                                           FF00940854
                                             99.93793
                                           FF05043895
                                             99.52349
                                           FF01571549
                                             99.99999
                                           FF00652207
                                            100.00001
                                           FF00620269
                                             93.53488
                                           FF00530249
                                            100.00000
                                           FF02739464
                                            100.00000
                                           FF02557391
                                             97.77564
                                           FB02846079
                                             95.89789
                                           FF02014428
                                             96.43004
                                           FF03815890
                                             91.97573
                                           FF00657311
                                             86.84944
                                           FF02557308
                                            100.00000
                                           FF01570284
                                             99.72587
                                           FF00531731
                                             99.95654
                                           FF01571457
                                             99.99968
                                           FF00657492
                                             99.99883
                                           FF00531073
                                             95.22808
                                           FF04024705
                                             99.84709
                                           FF00620299
                                             88.86577
            not_sequenced_010SweMaMi_tra41_FF00657579
                                            100.00000
            not_sequenced_010SweMaMi_tra46_FF02557387
                                            100.00000
                                           FF03815891
                                             98.24089
                                           FF00657949
                                            100.00000
                                           FF00940857
                                            100.00000
                                           FF01571283
                                             99.99999
                                           FF00653389
                                             99.99776
                                           FF03815360
                                            100.00000
                                           FF00651884
                                             98.18990
                                           FF06040480
                                             99.90667
                                           FF03815297
                                             99.98788
                                           FB03582939
                                             99.87557
                                           FF00619369
                                             99.99999
                                           FF02740655
                                             99.99966
                                           FF00653544
                                            100.00000
                                           FB02825181
                                            100.00000
                                           FF02015862
                                            100.00000
                                           FF06040493
                                             98.12317
                                           FF01572557
                                            100.00000
                                           FF02015764
                                             87.71554
                                           FB03582933
                                             99.65844
                                           FF02014319
                                             99.95868
                                           FF00531735
                                             99.86657
                                           FF06039204
                                             99.84065
                                           FF00652206
                                             99.99999
                                           FF05042910
                                             99.68299
                                           FF00620055
                                             99.99448
                                           FF00619964
                                             77.42542
                                           FB02826905
                                             99.95505
                                           FF00651964
                                             99.99456
                                           FF00653390
                                            100.00000
                                           FF00620290
                                             99.78864
                                           FF01571924
                                             99.99999
                                           FF00940908
                                             96.95853
                                           FF00653373
                                             99.63266
                                           FF05043985
                                             99.74188
                                           FF00657453
                                             99.28231
                                           FF00620302
                                              0.79250
                                           FF00657928
                                             99.99999
            not_sequenced_010SweMaMi_tra46_FF02557389
                                            100.00000
                                           FF00657547
                                            100.00000
                                           FF03815917
                                             98.25265
                                           FF03815751
                                             99.69363
                                           FB02825411
                                             99.99335
                                           FF04023675
                                             99.81211
                                           FF00619876
                                            100.00000
                                           FF05043811
                                             83.56274
                                           FF00652250
                                            100.00000
                                           FF05043808
                                             99.50068
                                           FF00619883
                                             99.92399
                                           FF00531217
                                            100.00001
            not_sequenced_010SweMaMi_tra40_FF00531135
                                              0.00000
                                           FF01571556
                                            100.00001
                                           FF00620194
                                             99.55601
                                           FF05042914
                                             99.98044
                                           FF06039246
                                             99.99999
                                           FF00530069
                                            100.00000
                                           FF02557846
                                            100.00000
                                           FF00657322
                                            100.00000
                                           FF00653388
                                             99.42393
                                           FF02014790
                                             99.89146
                                           FF03815369
                                             82.93147
                                           FB02846071
                                             99.74261
                                           FF00531464
                                             90.96183
                                           FF02556147
                                            100.00000
                                           FF03815350
                                             99.98938
                                           FF01571928
                                             13.83742
                                           FB02846884
                                            100.00000
                                           FB02826883
                                             99.82197
                                           FF00530113
                                            100.00000
                                           FF05044785
                                              0.01873
                                           FF00530215
                                            100.00000
                                           FF06039868
                                             99.34596
                                           FF00620285
                                             31.80092
                                           FF00653542
                                             99.99960
                                           FB02826918
                                             98.66828
                                           FF01570379
                                             94.39307
                                           FF01572487
                                             99.69859
                                           FF00530554
                                             99.32995
                                           FF00531145
                                             99.99999
                                           FF00652205
                                             94.25113
                                           FF01572445
                                             99.99586
            not_sequenced_010SweMaMi_tra46_FF02557383
                                            100.00000
                                           FF02739450
                                             97.84447
                                           FF01571290
                                             99.72510
                                           FF01572121
                                             97.19761
                                           FF00529960
                                            100.00000
                                           FF02014830
                                             99.27637
                                           FB02846877
                                             99.31915
                                           FF00651959
                                            100.00000
                                           FF02015778
                                             99.96489
                                           FF05024953
                                            100.00000
                                           FB02825192
                                            100.00001
                                           FF00653522
                                            100.00000
                                           FF01571335
                                             99.93633
                                           FF00651912
                                             99.77834
                                           FF00530111
                                             99.99999
                                           FB02825208
                                            100.00001
                                           FF00619950
                                             99.67440
                                           FB02825185
                                            100.00001
                                           FF06039962
                                            100.00000
                                           FF00620268
                                             99.43062
                                           FF02739452
                                             99.93317
                                           FF00940878
                                             98.14072
                                           FF03815228
                                             99.98656
                                           FF03815353
                                            100.00001
                                           FF00531134
                                             99.89133
                                           FF03815873
                                             89.69927
                                           FF05043972
                                            100.00000
                                           FF05043973
                                             99.99064
                                           FF00653452
                                             99.88370
                                           FF01571282
                                             99.30134
                                           FF00657481
                                             99.70070
                                           FF01570356
                                             98.25990
                                           FF00529967
                                            100.00000
                                           FF00653440
                                             99.86711
                                           FF00653269
                                             99.90522
                                           FF05043956
                                            100.00000
                                           FF03815380
                                             99.86667

# Remove all samples where colSums less than 80

In [35]:
#((colSums(filt_taxa) > 80)) 
col_names_to_drop <- names(filt_taxa)[colSums(filt_taxa) < 80]
length(col_names_to_drop)
head(col_names_to_drop)

[1] 454

[1] "FF00653393"
[2] "not_sequenced_010SweMaMi_tra16_FF00530583"
[3] "FF00652234"
[4] "FF00619964"
[5] "FF00620302"
[6] "not_sequenced_010SweMaMi_tra40_FF00531135"

In [36]:
sum(filt_taxa$FF00653393)
sum(filt_taxa$not_sequenced_010SweMaMi_tra16_FF00530583)
sum(filt_taxa$FF00652234)

[1] 58.03806

[1] 0

[1] 55.17737

In [37]:
colsum_filt_taxa <- filt_taxa |> 
    select(!all_of(col_names_to_drop))
length(colsum_filt_taxa)
dim(colsum_filt_taxa)

[1] 5583

[1]   64 5583

# Add other_taxa row to make all columns same constant value

In [38]:
new_row <- c()
tot <- colSums(colsum_filt_taxa)
for(i in tot){
    if(i < 100){
        new_row <- c(new_row, 100 - i)
    } else if (i >= 100){
        new_row <- c(new_row, 0)
    }
}
head(tot)
head(new_row)

FF01572457 FB02825199 FB02846074 FF00619375 FF00531869 FF03815895
  99.97415  100.00001   98.07328   98.79101   99.80528   99.99712

[1] 0.02585 0.00000 1.92672 1.20899 0.19472 0.00288

In [39]:
# add this vector as row to the taxa table
new_row <- setNames(new_row, names(colsum_filt_taxa))
#new_row
new_row2 <- as.data.frame(t(new_row))
#new_row2
rownames(new_row2) <- "Other_taxa"
best_filt_new <- rbind(colsum_filt_taxa ,new_row2) 
#colSums(best_filt_new )
#now the colSums == 100

filt_new_arrange <- as.data.frame(best_filt_new)
head(filt_new_arrange)
dim(filt_new_arrange)

                          FF01572457 FB02825199 FB02846074 FF00619375
Actinobaculum massiliense 0          0          0.01894    0.00000
Aerococcus christensenii  0          0          0.00000    0.00000
Alloscardovia omnicolens  0          0          0.41648    0.00000
Anaerococcus hydrogenalis 0          0          0.00000    0.00000
Anaerococcus lactolyticus 0          0          0.00000    0.01752
Anaerococcus prevotii     0          0          0.09146    0.00000
                          FF00531869 FF03815895 FF06039864 FF00652166
Actinobaculum massiliense 0.00000    0          0          0.00000
Aerococcus christensenii  0.06042    0          0          0.00000
Alloscardovia omnicolens  0.00000    0          0          0.00238
Anaerococcus hydrogenalis 0.00656    0          0          0.00000
Anaerococcus lactolyticus 0.00000    0          0          0.02028
Anaerococcus prevotii     0.00000    0          0          0.00000
                          FF00941092 FF00657963 ⋯ FF03816802 FF02014707
Actinobaculum massiliense 0          0          ⋯ 0          0
Aerococcus christensenii  0          0          ⋯ 0          0
Alloscardovia omnicolens  0          0          ⋯ 0          0
Anaerococcus hydrogenalis 0          0          ⋯ 0          0
Anaerococcus lactolyticus 0          0          ⋯ 0          0
Anaerococcus prevotii     0          0          ⋯ 0          0
                          FF01571909 FF02014701 FF02014994 FF05044768
Actinobaculum massiliense 0          0          0.00000    0
Aerococcus christensenii  0          0          0.98823    0
Alloscardovia omnicolens  0          0          0.00000    0
Anaerococcus hydrogenalis 0          0          0.00000    0
Anaerococcus lactolyticus 0          0          0.00000    0
Anaerococcus prevotii     0          0          0.00000    0
                          FF02015306 FF03815206 FF02014712 FF05044788
Actinobaculum massiliense 0          0.00000    0.00000    0
Aerococcus christensenii  0          0.49743    0.00000    0
Alloscardovia omnicolens  0          0.00000    0.00000    0
Anaerococcus hydrogenalis 0          0.00000    0.00000    0
Anaerococcus lactolyticus 0          0.00000    0.00000    0
Anaerococcus prevotii     0          0.00000    0.00484    0

[1]   65 5583

In [40]:
tail(filt_new_arrange)
dim(filt_new_arrange)

                                   FF01572457 FB02825199 FB02846074 FF00619375
Ureaplasma parvum                  0.00000    0          2.51981    0.01556
Varibaculum cambriense             0.00000    0          0.00000    0.00000
Varibaculum massiliense            0.00000    0          0.12809    0.00000
Veillonellaceae bacterium_DNF00626 0.00000    0          0.00000    0.00357
Winkia neuii                       0.00000    0          0.51561    0.00000
Other_taxa                         0.02585    0          1.92672    1.20899
                                   FF00531869 FF03815895 FF06039864 FF00652166
Ureaplasma parvum                  0.31970    0.07113    0.00000    0.23839
Varibaculum cambriense             0.00000    0.00000    0.01856    0.00000
Varibaculum massiliense            0.00000    0.00000    0.00000    0.00000
Veillonellaceae bacterium_DNF00626 0.00380    0.00000    0.00000    0.02703
Winkia neuii                       0.00405    0.00000    0.00000    0.00654
Other_taxa                         0.19472    0.00288    0.51008    0.52885
                                   FF00941092 FF00657963 ⋯ FF03816802
Ureaplasma parvum                  0.00000    0.13400    ⋯ 5.377300e-01
Varibaculum cambriense             0.00000    0.00000    ⋯ 0.000000e+00
Varibaculum massiliense            0.00000    0.00000    ⋯ 0.000000e+00
Veillonellaceae bacterium_DNF00626 0.01982    0.00000    ⋯ 0.000000e+00
Winkia neuii                       0.00000    0.10695    ⋯ 0.000000e+00
Other_taxa                         0.40836    0.25573    ⋯ 1.421085e-14
                                   FF02014707 FF01571909 FF02014701 FF02014994
Ureaplasma parvum                  0          0.00000    0          0.00000
Varibaculum cambriense             0          0.00000    0          0.00000
Varibaculum massiliense            0          0.00000    0          0.00000
Veillonellaceae bacterium_DNF00626 0          0.00000    0          0.17191
Winkia neuii                       0          0.00000    0          0.00000
Other_taxa                         0          0.01371    0          0.45639
                                   FF05044768 FF02015306 FF03815206 FF02014712
Ureaplasma parvum                  0          0.00000    0.00000    0.00000
Varibaculum cambriense             0          0.00000    0.00000    0.00000
Varibaculum massiliense            0          0.00000    0.00000    0.00000
Veillonellaceae bacterium_DNF00626 0          0.00000    0.44607    0.00000
Winkia neuii                       0          0.00000    0.00000    0.00000
Other_taxa                         0          1.09491    1.96160    0.27025
                                   FF05044788
Ureaplasma parvum                  0.04530
Varibaculum cambriense             0.00000
Varibaculum massiliense            0.00000
Veillonellaceae bacterium_DNF00626 0.00000
Winkia neuii                       0.01039
Other_taxa                         0.01331

[1]   65 5583

In [41]:
barcodes_vaginal <- colnames(filt_new_arrange)
head(barcodes_vaginal)
length(barcodes_vaginal)

[1] "FF01572457" "FB02825199" "FB02846074" "FF00619375" "FF00531869"
[6] "FF03815895"

[1] 5583

# Filter based on reads, if reads are less than 100k drop the barcode

In [42]:
read_count <- read.table("/ceph/projects/010_SweMaMi/anusha.antony/Anu_SweMaMi/dnbseq_sample_202309180813.csv", sep = ",", header = TRUE)
dim(read_count)
head (read_count)

[1] 10808    20

  sample_sheet_id sample_id  project_id  extraction_plate_id pcr_well
1 575             FF00657323 010_SweMaMi Extraction37        B4
2 575             FF00653549 010_SweMaMi Extraction37        A6
3 575             FF00653546 010_SweMaMi Extraction37        B1
4 575             FF00653545 010_SweMaMi Extraction37        H2
5 575             FF00653539 010_SweMaMi Extraction37        H5
6 575             FF00653396 010_SweMaMi Extraction37        G3
  adapter_id adapter_id_reverse sequencer_id   flowcell_id lane_id duplication
1 66         NA                 R1100600190018 E100033300  1       0.0277994
2 81         NA                 R1100600190018 E100033300  1       0.0272472
3  2         NA                 R1100600190018 E100033300  1       0.0327817
4 48         NA                 R1100600190018 E100033300  1       0.0309015
5 80         NA                 R1100600190018 E100033300  1       0.0251646
6 63         NA                 R1100600190018 E100033300  1       0.0255734
  reads_post_qc reads_post_hr host_proportion dna_concentration fragment_size
1 59793178      10801415      81.94            8.6105           475
2 60560303       3534319      94.16           41.3450           476
3 60258541       5754625      90.45           16.4310           440
4 60266650       1082499      98.20           30.7000           455
5 60330309       4017428      93.34           17.5810           482
6 57288608       5651955      90.13           13.0810           444
  library_concentration extraction_id library_failed not_sequenced
1 37.628
2 53.112
3 34.767
4 44.449
5 44.453
6 28.766

In [43]:
barcodes_in_reads <- read_count |>
    filter(sample_id %in% barcodes_vaginal)
dim(barcodes_in_reads)
length(unique(barcodes_in_reads$sample_id))

[1] 5738   20

[1] 5332

In [44]:
# Keep only barcodes where the reads are qual to or more than 100k
read_filtered_barcodes <- barcodes_in_reads |> filter(reads_post_hr >= 100000) |> pull(sample_id)
head(read_filtered_barcodes)
length(read_filtered_barcodes)

[1] "FF00657323" "FF00653549" "FF00653546" "FF00653545" "FF00653539"
[6] "FF00653396"

[1] 5056

# Filtering on Nulliparity ------------------------------------------------------------------------------------------

# Also prepare a taxa table containing only samples from Nulliparous participants

In [45]:
grep("kit", names(fp), value = TRUE)

 [1] "kit1.faecal_sample.barcode"
 [2] "kit2.faecal_sample.barcode"
 [3] "kit3.faecal_sample.barcode"
 [4] "kit3.infant_faecal_sample.barcode"
 [5] "kit3.infant_faecal_sample_2.barcode"
 [6] "kit3.salival_sample.barcode"
 [7] "kit1.salival_sample.barcode"
 [8] "kit1.vaginal_sample.barcode"
 [9] "kit1.faecal_sample.datetime_taken"
[10] "kit1.salival_sample.datetime_taken"
[11] "kit1.vaginal_sample.datetime_taken"
[12] "kit2.salival_sample.barcode"
[13] "kit2.vaginal_sample.barcode"
[14] "kit2.faecal_sample.datetime_taken"
[15] "kit2.salival_sample.datetime_taken"
[16] "kit2.vaginal_sample.datetime_taken"
[17] "kit3.vaginal_sample.barcode"
[18] "kit3.faecal_sample.datetime_taken"
[19] "kit3.infant_faecal_sample.datetime_taken"
[20] "kit3.infant_faecal_sample_2.datetime_taken"
[21] "kit3.salival_sample.datetime_taken"
[22] "kit3.vaginal_sample.datetime_taken"

In [46]:
barcodes_fp_kit1 <- fp |> 
    filter(!(is.na(kit1.vaginal_sample.barcode ))) |>
    pull(kit1.vaginal_sample.barcode)
length(barcodes_fp_kit1)

[1] 59

In [47]:
barcodes_sp_kit1 <- sp |> 
    filter(!(is.na(kit1.vaginal_sample.barcode ))) |>
    pull(kit1.vaginal_sample.barcode)
length(barcodes_sp_kit1)

[1] 58

In [48]:
setdiff(barcodes_fp_kit1, barcodes_sp_kit1)

 [1] "FF00530163" "FF02015546" "FF02014263" "FF02739091" "FF00653544"
 [6] "Ff00657518" "FF00653507" "FF00653546" "FF00653525" "FF00531719"
[11] "FF00530586" "FF02557868" "FB02825409" "FF00657534" "FF02015010"
[16] "FF03817636" "FF00530528" "FF01571976" "FF02740674" "FF02014805"
[21] "FF00531139" "FF00651927" "FF00652411" "FF02015815" "FF00619940"
[26] "FF02014833" "FF00657923" "FF00657544" "FF00619356" "FF03817626"
[31] "FF00653065" "FF00620268" "FF00653167" "FF02556135" "FB02846091"
[36] "FF02556105" "FF02015296" "FF00651910" "FF03815366" "FF00653014"
[41] "FF02015432" "FF02014716" "FF01570828" "FF00653071" "FF00941094"
[46] "FF00652106" "FF02015011" "FF00657476" "FF02014181" "FF00657582"
[51] "FF00531215" "FF03818430" "FF00530208" "FF05025294" "FF00657563"
[56] "FF00657546" "FF02015345" "FF00652988" "FF00530064"

In [49]:
intersect(barcodes_fp_kit1, barcodes_sp_kit1)

character(0)

In [50]:
barcodes_fp_kit2 <- fp |> 
    filter(!(is.na(kit2.vaginal_sample.barcode ))) |>
    pull(kit2.vaginal_sample.barcode)
length(barcodes_fp_kit2)

barcodes_sp_kit2 <- sp |> 
    filter(!(is.na(kit2.vaginal_sample.barcode ))) |>
    pull(kit2.vaginal_sample.barcode)
length(barcodes_sp_kit2)

[1] 41

[1] 58

In [51]:
intersect(barcodes_fp_kit1, barcodes_fp_kit2)

character(0)

In [52]:
intersect(barcodes_fp_kit2, barcodes_sp_kit2)

character(0)

In [53]:
barcodes_to_keep <- c(barcodes_fp_kit1, barcodes_fp_kit2, barcodes_sp_kit1, barcodes_sp_kit2)
length(barcodes_to_keep)

[1] 216

In [54]:
length(unique(barcodes_to_keep))

[1] 216

# Now from the filtered taxa make a new vector with only nulliparous barcodes

In [55]:
nulliparous_taxa_barcodes <- read_filtered_barcodes[read_filtered_barcodes %in% barcodes_to_keep]
head(nulliparous_taxa_barcodes)

length(nulliparous_taxa_barcodes)

[1] "FF00653546" "FF00653544" "FB02825409" "FF03817116" "FF01566745"
[6] "FF02556135"

[1] 178

In [58]:
# Keep only columns whos names are in the barcodes list
reads_filtered_taxa <- filt_new_arrange |> select(all_of(nulliparous_taxa_barcodes))
head(reads_filtered_taxa)
dim(reads_filtered_taxa)

                          FF00653546 FF00653544 FB02825409 FF03817116
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.37028    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00697    0          0.00000    0
Anaerococcus lactolyticus 0.01879    0          0.00000    0
Anaerococcus prevotii     0.00000    0          0.00000    0
                          FF01566745 FF02556135 FF03818430 FF01571976
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00000    0          0.00000    0
Anaerococcus lactolyticus 0.00000    0          0.00013    0
Anaerococcus prevotii     0.01267    0          0.00000    0
                          FF06040450 FF06039085 ⋯ FF05044395 FF04760422
Actinobaculum massiliense 0          0.00000    ⋯ 0          0.00000
Aerococcus christensenii  0          0.00000    ⋯ 0          0.00000
Alloscardovia omnicolens  0          0.00000    ⋯ 0          0.00197
Anaerococcus hydrogenalis 0          0.00000    ⋯ 0          0.00000
Anaerococcus lactolyticus 0          0.00035    ⋯ 0          0.00000
Anaerococcus prevotii     0          0.00000    ⋯ 0          0.00000
                          FF00531801 FF08440403 FF08440398 FF08440427
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          1.74307    0
Anaerococcus hydrogenalis 0.00000    0          0.00420    0
Anaerococcus lactolyticus 0.00062    0          0.02457    0
Anaerococcus prevotii     0.00000    0          0.00989    0
                          FF03818480 FF08440674 FF08440393 FF06039070
Actinobaculum massiliense 0.38593    0.00000    0.00000    0.00000
Aerococcus christensenii  0.00000    0.00000    0.23952    0.00000
Alloscardovia omnicolens  0.00000    0.00509    0.00000    0.71791
Anaerococcus hydrogenalis 0.00319    0.00000    0.00000    0.00000
Anaerococcus lactolyticus 0.00000    0.00166    0.00000    0.00000
Anaerococcus prevotii     0.00000    0.00000    0.00000    0.00000

[1]  65 175

# Write to file------------------------------------------------------------------------------------------------------------------------------------

# Save all valid barcodes to file as lines

In [113]:
writeLines(read_filtered_barcodes, con = paste0("/ceph/projects/010_SweMaMi/bm.nowak/data/",  Sys.Date(), "_reads_filtered_barcodes_vaginal", ".txt" ), sep = "\n")

In [195]:
writeLines(nulliparous_taxa_barcodes, con = paste0("/ceph/projects/010_SweMaMi/bm.nowak/data/",  Sys.Date(), "_valid_barcodes_vaginal_nuliparous", ".txt" ), sep = "\n")

In [69]:
write.table(reads_filtered_taxa, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/", Sys.Date(), 
                                                       "_vaginal_taxa_filtered", ".tsv"), sep = "\t")

# Divide taxa into TP1 and TP2 -----------------------------------------------------------------------------