#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: vag_tp1_filtering_data_diffrential
# Date: 2025.12.12
# Programmer: Barbara Nowak
# Purpose: Vagina, Filter metadata and taxa table for diffrential abundance and prevalence analysis, TP1
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [172]:
library(tidyverse)
library(dplyr)

# Load Files ----------------------------------------------------------------------------------------------------------

In [173]:
# Read taxa data
taxa_tab <- read.table("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/2025-11-11_vaginal_taxa_filtered.tsv", header = TRUE, sep ="\t", check.names = FALSE, quote='"') 
dim(taxa_tab)
head(taxa_tab)

[1]  65 175

                          FF00653546 FF00653544 FB02825409 FF03817116
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.37028    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00697    0          0.00000    0
Anaerococcus lactolyticus 0.01879    0          0.00000    0
Anaerococcus prevotii     0.00000    0          0.00000    0
                          FF01566745 FF02556135 FF03818430 FF01571976
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00000    0          0.00000    0
Anaerococcus lactolyticus 0.00000    0          0.00013    0
Anaerococcus prevotii     0.01267    0          0.00000    0
                          FF06040450 FF06039085 ⋯ FF05044395 FF04760422
Actinobaculum massiliense 0          0.00000    ⋯ 0          0.00000
Aerococcus christensenii  0          0.00000    ⋯ 0          0.00000
Alloscardovia omnicolens  0          0.00000    ⋯ 0          0.00197
Anaerococcus hydrogenalis 0          0.00000    ⋯ 0          0.00000
Anaerococcus lactolyticus 0          0.00035    ⋯ 0          0.00000
Anaerococcus prevotii     0          0.00000    ⋯ 0          0.00000
                          FF00531801 FF08440403 FF08440398 FF08440427
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          1.74307    0
Anaerococcus hydrogenalis 0.00000    0          0.00420    0
Anaerococcus lactolyticus 0.00062    0          0.02457    0
Anaerococcus prevotii     0.00000    0          0.00989    0
                          FF03818480 FF08440674 FF08440393 FF06039070
Actinobaculum massiliense 0.38593    0.00000    0.00000    0.00000
Aerococcus christensenii  0.00000    0.00000    0.23952    0.00000
Alloscardovia omnicolens  0.00000    0.00509    0.00000    0.71791
Anaerococcus hydrogenalis 0.00319    0.00000    0.00000    0.00000
Anaerococcus lactolyticus 0.00000    0.00166    0.00000    0.00000
Anaerococcus prevotii     0.00000    0.00000    0.00000    0.00000

In [174]:
# Read metadata
combined_meta_tp1 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/2025-11-11_combined_tp1_filt_nulliparous.csv", header = TRUE, row.names = 1)
head(combined_meta_tp1)
dim(combined_meta_tp1)

     Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
5367 S194e21b     NA         0        0         0
5301 S1f862a6     NA         0        0         0
5258 S1f95844     NA         0        0         0
5275 S2b86cc0     NA         0        0         0
5243 S39fe1d7     NA         0        0         0
5383 S7e4a963     NA         0        0         0
     Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked Age_groups ⋯
5367 2018-11-16 P159f9c8        0                   36          4          ⋯
5301 2018-03-07 P1f862a6        0                   32          3          ⋯
5258 2018-04-10 P1f95844        0                   30          3          ⋯
5275 2019-05-29 P3cac7b0        0                   31          3          ⋯
5243 2018-06-23 P3db7da6        0                   29          2          ⋯
5383 2018-02-18 P424fd61        0                   37          4          ⋯
     missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
5367 NA                 NA   NA       NA                     41
5301 NA                 NA   NA       NA                     31
5258 NA                 NA   NA       NA                     40
5275 NA                 NA   NA       NA                     39
5243 NA                 NA   NA       NA                     41
5383 NA                 NA   NA       NA                     38
     deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
5367 Spontaneous          NA          NA    0
5301 Spontaneous          very_w28_31  1    0
5258 Spontaneous          NA          NA    0
5275 Spontaneous          NA          NA    0
5243 Spontaneous          NA          NA    0
5383 Induction            NA          NA    0
     Group
5367 First pregnancy
5301 First pregnancy
5258 First pregnancy
5275 First pregnancy
5243 First pregnancy
5383 First pregnancy

[1]  52 566

# Sort taxa table ---------------------------------------------------------------------------------------

In [175]:
head(taxa_tab)

                          FF00653546 FF00653544 FB02825409 FF03817116
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.37028    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00697    0          0.00000    0
Anaerococcus lactolyticus 0.01879    0          0.00000    0
Anaerococcus prevotii     0.00000    0          0.00000    0
                          FF01566745 FF02556135 FF03818430 FF01571976
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          0.00000    0
Anaerococcus hydrogenalis 0.00000    0          0.00000    0
Anaerococcus lactolyticus 0.00000    0          0.00013    0
Anaerococcus prevotii     0.01267    0          0.00000    0
                          FF06040450 FF06039085 ⋯ FF05044395 FF04760422
Actinobaculum massiliense 0          0.00000    ⋯ 0          0.00000
Aerococcus christensenii  0          0.00000    ⋯ 0          0.00000
Alloscardovia omnicolens  0          0.00000    ⋯ 0          0.00197
Anaerococcus hydrogenalis 0          0.00000    ⋯ 0          0.00000
Anaerococcus lactolyticus 0          0.00035    ⋯ 0          0.00000
Anaerococcus prevotii     0          0.00000    ⋯ 0          0.00000
                          FF00531801 FF08440403 FF08440398 FF08440427
Actinobaculum massiliense 0.00000    0          0.00000    0
Aerococcus christensenii  0.00000    0          0.00000    0
Alloscardovia omnicolens  0.00000    0          1.74307    0
Anaerococcus hydrogenalis 0.00000    0          0.00420    0
Anaerococcus lactolyticus 0.00062    0          0.02457    0
Anaerococcus prevotii     0.00000    0          0.00989    0
                          FF03818480 FF08440674 FF08440393 FF06039070
Actinobaculum massiliense 0.38593    0.00000    0.00000    0.00000
Aerococcus christensenii  0.00000    0.00000    0.23952    0.00000
Alloscardovia omnicolens  0.00000    0.00509    0.00000    0.71791
Anaerococcus hydrogenalis 0.00319    0.00000    0.00000    0.00000
Anaerococcus lactolyticus 0.00000    0.00166    0.00000    0.00000
Anaerococcus prevotii     0.00000    0.00000    0.00000    0.00000

In [176]:
# Flipping the table 
taxa_flipped <- taxa_tab |> t() |>
    as.data.frame() |>
    rownames_to_column("sample_id")

taxa_flipped |> head()

  sample_id  Actinobaculum massiliense Aerococcus christensenii
1 FF00653546 0                         0.00000
2 FF00653544 0                         0.00000
3 FB02825409 0                         0.37028
4 FF03817116 0                         0.00000
5 FF01566745 0                         0.00000
6 FF02556135 0                         0.00000
  Alloscardovia omnicolens Anaerococcus hydrogenalis Anaerococcus lactolyticus
1 0                        0.00697                   0.01879
2 0                        0.00000                   0.00000
3 0                        0.00000                   0.00000
4 0                        0.00000                   0.00000
5 0                        0.00000                   0.00000
6 0                        0.00000                   0.00000
  Anaerococcus prevotii Anaerococcus sp_Marseille_P3915 Anaerococcus tetradius
1 0.00000               0.00623                         0.00000
2 0.00000               0.00000                         0.00000
3 0.00000               0.00000                         0.00477
4 0.00000               0.00000                         0.00000
5 0.01267               0.00000                         0.00000
6 0.00000               0.00000                         0.00000
  Anaerococcus vaginalis ⋯ Staphylococcus epidermidis Streptococcus anginosus
1 0                      ⋯ 0                          0
2 0                      ⋯ 0                          0
3 0                      ⋯ 0                          0
4 0                      ⋯ 0                          0
5 0                      ⋯ 0                          0
6 0                      ⋯ 0                          0
  Streptococcus SGB3665 Tissierellia bacterium_KA00581 Ureaplasma parvum
1 0                     0.00000                        0.00000
2 0                     0.00000                        0.05158
3 0                     0.25771                        0.00970
4 0                     0.00000                        0.00000
5 0                     0.00000                        0.00000
6 0                     0.00000                        0.00000
  Varibaculum cambriense Varibaculum massiliense
1 0.00805                0
2 0.00000                0
3 0.00000                0
4 0.00000                0
5 0.00000                0
6 0.00000                0
  Veillonellaceae bacterium_DNF00626 Winkia neuii Other_taxa
1 0.02838                            0            0.09977
2 0.00000                            0            0.00000
3 0.90706                            0            0.80965
4 0.00000                            0            0.00544
5 0.00000                            0            0.00000
6 0.00000                            0            0.00000

In [177]:
# Extract sample id, personal num, groups

In [178]:
grep("kit1", names(combined_meta_tp1), value = TRUE)

[1] "kit1.faecal_sample.barcode"         "kit1.salival_sample.barcode"
[3] "kit1.vaginal_sample.barcode"        "kit1.faecal_sample.datetime_taken"
[5] "kit1.salival_sample.datetime_taken" "kit1.vaginal_sample.datetime_taken"

In [192]:
variables_df <- combined_meta_tp1 |> select(Group, Studienummer, Q1_Personnummer, 
                                            kit1.vaginal_sample.barcode, BMI_prior) 
head(variables_df)

     Group            Studienummer Q1_Personnummer kit1.vaginal_sample.barcode
5367 First pregnancy  S194e21b     P159f9c8        FF02014263
5301 First pregnancy  S1f862a6     P1f862a6        FF00653507
5258 First pregnancy  S1f95844     P1f95844        FF00653546
5275 First pregnancy  S2b86cc0     P3cac7b0        FF02557868
5243 First pregnancy  S39fe1d7     P3db7da6        FB02825409
5383 First pregnancy  S7e4a963     P424fd61        FF00657534
     BMI_prior
5367 21
5301 25
5258 22
5275 21
5243 21
5383 24

In [193]:
meta_BMI_update <- variables_df %>%
 mutate(
  BMI_group_prior = case_when(
   BMI_prior < 18.5 ~ "Underweight",
   BMI_prior >= 18.5 & BMI_prior <= 24.9 ~ "Normalweight",
   BMI_prior >= 25 & BMI_prior <= 29.9 ~ "Overweight",
   BMI_prior >= 30 ~ "Obese",
   TRUE ~ NA_character_  
 ))

head(meta_BMI_update$BMI_group_prior)
head(meta_BMI_update )

[1] "Normalweight" "Overweight"   "Normalweight" "Normalweight" "Normalweight"
[6] "Normalweight"

     Group            Studienummer Q1_Personnummer kit1.vaginal_sample.barcode
5367 First pregnancy  S194e21b     P159f9c8        FF02014263
5301 First pregnancy  S1f862a6     P1f862a6        FF00653507
5258 First pregnancy  S1f95844     P1f95844        FF00653546
5275 First pregnancy  S2b86cc0     P3cac7b0        FF02557868
5243 First pregnancy  S39fe1d7     P3db7da6        FB02825409
5383 First pregnancy  S7e4a963     P424fd61        FF00657534
     BMI_prior BMI_group_prior
5367 21        Normalweight
5301 25        Overweight
5258 22        Normalweight
5275 21        Normalweight
5243 21        Normalweight
5383 24        Normalweight

In [195]:
# sort df so same paricipants grouped together
variables_df_sorted <- meta_BMI_update |>  sort_by(meta_BMI_update$Q1_Personnummer)
head(variables_df_sorted)

     Group            Studienummer Q1_Personnummer kit1.vaginal_sample.barcode
5367 First pregnancy  S194e21b     P159f9c8        FF02014263
5391 Second pregnancy S159f9c8     P159f9c8        FF06039085
5301 First pregnancy  S1f862a6     P1f862a6        FF00653507
5305 Second pregnancy Sa79a719     P1f862a6        FF00530247
5258 First pregnancy  S1f95844     P1f95844        FF00653546
5309 Second pregnancy S0e78496     P1f95844        FF06580399
     BMI_prior BMI_group_prior
5367 21        Normalweight
5391 25        Overweight
5301 25        Overweight
5305 25        Overweight
5258 22        Normalweight
5309 21        Normalweight

In [164]:
# Order taxa table accoring to metadata

#create a column with studienummer + sample number + pregnancy 
variables_df_sorted <- variables_df_sorted |> mutate(sample = paste0(kit1.vaginal_sample.barcode, "_", "S", dense_rank(Q1_Personnummer), "_",
                                                                     ifelse(Group == "First pregnancy ", "P1", "P2")))
head(variables_df_sorted)

In [196]:
# Remove rownames
variables_df_sorted <- variables_df_sorted |> rownames_to_column ("old") |> 
    select(- old, -BMI_prior) |> 
    column_to_rownames(var = "kit1.vaginal_sample.barcode") |>
    rownames_to_column("sample_id")
head(variables_df_sorted)

  sample_id  Group            Studienummer Q1_Personnummer BMI_group_prior
1 FF02014263 First pregnancy  S194e21b     P159f9c8        Normalweight
2 FF06039085 Second pregnancy S159f9c8     P159f9c8        Overweight
3 FF00653507 First pregnancy  S1f862a6     P1f862a6        Overweight
4 FF00530247 Second pregnancy Sa79a719     P1f862a6        Overweight
5 FF00653546 First pregnancy  S1f95844     P1f95844        Normalweight
6 FF06580399 Second pregnancy S0e78496     P1f95844        Normalweight

In [197]:
# Now sort the taxa table according to the above metadata 
taxa_flipped_sorted <- taxa_flipped[match(variables_df_sorted$sample_id, taxa_flipped$sample_id ),]
taxa_flipped_sorted |> head()

   sample_id  Actinobaculum massiliense Aerococcus christensenii
31 FF02014263 0                         0.00000
10 FF06039085 0                         0.00000
86 FF00653507 0                         1.96578
83 FF00530247 0                         1.85412
1  FF00653546 0                         0.00000
56 FF06580399 0                         0.00000
   Alloscardovia omnicolens Anaerococcus hydrogenalis Anaerococcus lactolyticus
31 0.00000                  0.00000                   0.00000
10 0.00000                  0.00000                   0.00035
86 0.00000                  0.00000                   0.00000
83 0.00000                  0.00000                   0.00000
1  0.00000                  0.00697                   0.01879
56 0.04067                  0.00000                   0.12813
   Anaerococcus prevotii Anaerococcus sp_Marseille_P3915 Anaerococcus tetradius
31 0                     0.00000                         0.00000
10 0                     0.00000                         0.00000
86 0                     0.00000                         0.08090
83 0                     0.00000                         0.00000
1  0                     0.00623                         0.00000
56 0                     0.13056                         2.32269
   Anaerococcus vaginalis ⋯ Staphylococcus epidermidis Streptococcus anginosus
31 0                      ⋯ 0.00000                    0.00000
10 0                      ⋯ 0.00798                    0.00000
86 0                      ⋯ 0.00000                    0.00000
83 0                      ⋯ 0.00000                    0.00000
1  0                      ⋯ 0.00000                    0.00000
56 0                      ⋯ 0.00000                    0.46751
   Streptococcus SGB3665 Tissierellia bacterium_KA00581 Ureaplasma parvum
31 0                     0                              0.00000
10 0                     0                              0.00000
86 0                     0                              0.00000
83 0                     0                              0.00000
1  0                     0                              0.00000
56 0                     0                              0.08773
   Varibaculum cambriense Varibaculum massiliense
31 0.00000                0
10 0.00000                0
86 0.00000                0
83 0.00000                0
1  0.00805                0
56 0.00000                0
   Veillonellaceae bacterium_DNF00626 Winkia neuii Other_taxa
31 0.00000                            0            0.00000
10 0.00000                            0            0.01244
86 0.17824                            0            0.12387
83 0.16967                            0            0.05787
1  0.02838                            0            0.09977
56 0.05025                            0            0.64062

In [198]:
# Remove rownames
taxa_flipped_sorted <- taxa_flipped_sorted |> rownames_to_column ("old") |> 
    select(- old) 
head(taxa_flipped_sorted)

  sample_id  Actinobaculum massiliense Aerococcus christensenii
1 FF02014263 0                         0.00000
2 FF06039085 0                         0.00000
3 FF00653507 0                         1.96578
4 FF00530247 0                         1.85412
5 FF00653546 0                         0.00000
6 FF06580399 0                         0.00000
  Alloscardovia omnicolens Anaerococcus hydrogenalis Anaerococcus lactolyticus
1 0.00000                  0.00000                   0.00000
2 0.00000                  0.00000                   0.00035
3 0.00000                  0.00000                   0.00000
4 0.00000                  0.00000                   0.00000
5 0.00000                  0.00697                   0.01879
6 0.04067                  0.00000                   0.12813
  Anaerococcus prevotii Anaerococcus sp_Marseille_P3915 Anaerococcus tetradius
1 0                     0.00000                         0.00000
2 0                     0.00000                         0.00000
3 0                     0.00000                         0.08090
4 0                     0.00000                         0.00000
5 0                     0.00623                         0.00000
6 0                     0.13056                         2.32269
  Anaerococcus vaginalis ⋯ Staphylococcus epidermidis Streptococcus anginosus
1 0                      ⋯ 0.00000                    0.00000
2 0                      ⋯ 0.00798                    0.00000
3 0                      ⋯ 0.00000                    0.00000
4 0                      ⋯ 0.00000                    0.00000
5 0                      ⋯ 0.00000                    0.00000
6 0                      ⋯ 0.00000                    0.46751
  Streptococcus SGB3665 Tissierellia bacterium_KA00581 Ureaplasma parvum
1 0                     0                              0.00000
2 0                     0                              0.00000
3 0                     0                              0.00000
4 0                     0                              0.00000
5 0                     0                              0.00000
6 0                     0                              0.08773
  Varibaculum cambriense Varibaculum massiliense
1 0.00000                0
2 0.00000                0
3 0.00000                0
4 0.00000                0
5 0.00805                0
6 0.00000                0
  Veillonellaceae bacterium_DNF00626 Winkia neuii Other_taxa
1 0.00000                            0            0.00000
2 0.00000                            0            0.01244
3 0.17824                            0            0.12387
4 0.16967                            0            0.05787
5 0.02838                            0            0.09977
6 0.05025                            0            0.64062

# Write to file --------------------------------------------------------------------------------

In [168]:
#Export as .tsv
#write.table(taxa_flipped_sorted, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/diffrential_abundance/", Sys.Date(),
 #                                          "_vag_tp1_ordered_taxa", ".tsv"), sep = "\t", row.names = FALSE)

In [200]:
# Write to file, name with no space between, without barcodes
write.csv(variables_df_sorted, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/diffrential_abundance/", 
                                       Sys.Date(), "_vag_tp1_ordered_metadata", ".csv"), row.names = FALSE)