#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: vag_check_descriptive_statistics_nulliparous_tp2
# Date: 2025.12.06
# Programmer: Barbara Nowak
# Purpose: Vaginal, To find out the characteristics of nulliparous tp2 women
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

── Attaching core tidyverse packages ─────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ───────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
# Read file
fp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/2025-11-11_fp_tp2_filt.csv", header = TRUE)
head(fp_tp2)
dim(fp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5258 S1f95844     NA         0        0         0
3 5275 S2b86cc0     NA         0        0         0
4 5243 S39fe1d7     NA         0        0         0
5 5383 S7e4a963     NA         0        0         0
6 5239 S5fa4a39     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2018-04-10 P1f95844        0                   30          ⋯ 0
3 2019-05-29 P3cac7b0        0                   31          ⋯ 0
4 2018-06-23 P3db7da6        0                   29          ⋯ 0
5 2018-02-18 P424fd61        0                   37          ⋯ 0
6 2018-08-30 P4de45e7        0                   29          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    1

[1]  16 566

In [3]:
sp_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/2025-11-11_sp_tp2_filt.csv", header = TRUE)
head(sp_tp2)
dim(sp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5309 S0e78496     NA         0        0         0
3 5311 S3cac7b0     NA         0        0         0
4 5252 S3db7da6     NA         0        0         1
5 5415 S424fd61     NA         0        0         0
6 5272 S4de45e7     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2020-12-17 P1f95844        0                   33          ⋯  0
3 2020-10-20 P3cac7b0        0                   33          ⋯  0
4 2019-09-24 P3db7da6        0                   30          ⋯  0
5 2020-11-03 P424fd61        0                   40          ⋯ 31
6 2020-11-05 P4de45e7        0                   31          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  16 566

In [4]:
combined_tp2 <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/2025-11-11_combined_fp_sp_tp2.csv", header = TRUE)
head(combined_tp2)
dim(combined_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5258 S1f95844     NA         0        0         0
3 5275 S2b86cc0     NA         0        0         0
4 5243 S39fe1d7     NA         0        0         0
5 5383 S7e4a963     NA         0        0         0
6 5239 S5fa4a39     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-11-16 P159f9c8        0                   36          ⋯
2 2018-04-10 P1f95844        0                   30          ⋯
3 2019-05-29 P3cac7b0        0                   31          ⋯
4 2018-06-23 P3db7da6        0                   29          ⋯
5 2018-02-18 P424fd61        0                   37          ⋯
6 2018-08-30 P4de45e7        0                   29          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    1
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

[1]  32 567

# BMI prior ---------------------------------------------------------------------------------

In [5]:
BMI_summary_stat <- combined_tp2 |>
  group_by(Group)|> 
  summarise(
    mean_bmi = mean(BMI_prior, na.rm = TRUE),
    sd_bmi = sd(BMI_prior, na.rm = TRUE),
    min_bmi = min(BMI_prior, na.rm = TRUE),
    max_bmi = max(BMI_prior, na.rm = TRUE)
  )
print(BMI_summary_stat)

# A tibble: 2 × 5
  Group              mean_bmi sd_bmi min_bmi max_bmi
  <chr>                 <dbl>  <dbl>   <int>   <int>
1 "First pregnancy "     22.8   3.21      16      29
2 "Second pregnancy"     23.8   3.43      17      30

# Age ---------------------------------------------------------------------------------

In [6]:
Age_summary_stats <- combined_tp2|>
  group_by(Group) |>
  summarise(
    mean_age = mean(age_checked, na.rm = TRUE),
    sd_age = sd(age_checked, na.rm = TRUE),
    min_age = min(age_checked, na.rm = TRUE),
    max_age = max(age_checked, na.rm = TRUE)
  )
print(Age_summary_stats)

# A tibble: 2 × 5
  Group              mean_age sd_age min_age max_age
  <chr>                 <dbl>  <dbl>   <int>   <int>
1 "First pregnancy "     29.6   3.24      25      37
2 "Second pregnancy"     31.8   3.39      27      40

# BMI categories ---------------------------------------------------------------------------------

In [7]:
# BMI_groups
grep("BMI", names(combined_tp2), value = TRUE)
combined_tp2$BMI_3_groups
# check type of data
class(combined_tp2$BMI_now_3_groups)

[1] "BMI_prior"        "BMI_3_groups"     "BMI_now_3_groups"

 [1] "18.5-25 Normal weight" "18.5-25 Normal weight" "18.5-25 Normal weight"
 [4] "18.5-25 Normal weight" "18.5-25 Normal weight" "> 25 Overweight"
 [7] "18.5-25 Normal weight" "18.5-25 Normal weight" "< 18.5 Underweight"
[10] "> 25 Overweight"       "18.5-25 Normal weight" "18.5-25 Normal weight"
[13] "18.5-25 Normal weight" "> 25 Overweight"       "18.5-25 Normal weight"
[16] "18.5-25 Normal weight" "Missing"               "18.5-25 Normal weight"
[19] "18.5-25 Normal weight" "18.5-25 Normal weight" "18.5-25 Normal weight"
[22] "> 25 Overweight"       "18.5-25 Normal weight" "18.5-25 Normal weight"
[25] "< 18.5 Underweight"    "> 25 Overweight"       "18.5-25 Normal weight"
[28] "> 25 Overweight"       "> 25 Overweight"       "> 25 Overweight"
[31] "18.5-25 Normal weight" "18.5-25 Normal weight"

[1] "character"

In [8]:
# Count total in both groups
total_counts_bmi <- table(combined_tp2$Group)
print(total_counts_bmi)

First pregnancy  Second pregnancy
              16               16

In [9]:
# Calculate the count and percentage for each BMI_3_groups within each group
BMI_3_groups_summary <- combined_tp2 |>
  group_by(Group, BMI_3_groups) |>         
  summarise(
    count = n(),
    
    .groups = 'drop'  # This argument drops the grouping after summarising                    
  ) |>
  group_by(Group) |> # Regroup by 'group' to calculate percentage
  mutate(
    percentage = (count / sum(count)) * 100  
  )
print(BMI_3_groups_summary)

# A tibble: 7 × 4
# Groups:   Group [2]
  Group              BMI_3_groups          count percentage
  <chr>              <chr>                 <int>      <dbl>
1 "First pregnancy " 18.5-25 Normal weight    12      75
2 "First pregnancy " < 18.5 Underweight        1       6.25
3 "First pregnancy " > 25 Overweight           3      18.8
4 "Second pregnancy" 18.5-25 Normal weight     9      56.2
5 "Second pregnancy" < 18.5 Underweight        1       6.25
6 "Second pregnancy" > 25 Overweight           5      31.2
7 "Second pregnancy" Missing                   1       6.25

# Gestational diabetes==========================================================

In [10]:
grep("diabetes", names(combined_tp2), value = TRUE)
table(combined_tp2$Q2_X13.1.Pregproblem_gestational_diabetes)

[1] "Q1_X73.1_Pregnancy_problems_gestational_diabetes"
[2] "Q1_prior_diabetes_medication"
[3] "Q1_during_diabetes_medication"
[4] "Q2_X13.1.Pregproblem_gestational_diabetes"
[5] "Q2_diabetes_medication"
[6] "Q3_X41_Pregproblem_gestational_diabetes"
[7] "Q3_diabetes_medication"

     Nej Vet inte
       5        1

In [11]:
# Check variable type
class(combined_tp2$Q2_X13.1.Pregproblem_gestational_diabetes)

[1] "character"

In [12]:
# Transform into factor
combined_tp2$Q2_X13.1.Pregproblem_gestational_diabetes <- as.factor(combined_tp2$Q2_X13.1.Pregproblem_gestational_diabetes)
class(combined_tp2$Q2_X13.1.Pregproblem_gestational_diabetes)

[1] "factor"

In [13]:
summary_diabetes <-  combined_tp2 |>
  group_by(Group, Q2_X13.1.Pregproblem_gestational_diabetes) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count / sum(count)) * 100
  )
print(summary_diabetes)

# A tibble: 5 × 4
# Groups:   Group [2]
  Group              Q2_X13.1.Pregproblem_gestational_diabetes count percentage
  <chr>              <fct>                                     <int>      <dbl>
1 "First pregnancy " Nej                                           3      18.8
2 "First pregnancy " Vet inte                                      1       6.25
3 "First pregnancy " NA                                           12      75
4 "Second pregnancy" Nej                                           2      12.5
5 "Second pregnancy" NA                                           14      87.5

# Depression====================================================================

In [14]:
grep("depression", names(combined_tp2), value= TRUE)
grep("Depression", names(combined_tp2), value= TRUE)

[1] "Q1_X73.7_Pregnancy_problems_depression"
[2] "Q2_X13.7.Pregproblem_depression"
[3] "Q3_X41_Pregproblem_depression"

[1] "Depression_score_sum_Q1" "Depression_score_sum_Q2"
[3] "Depression_score_sum_Q3"

In [15]:
# Check variable type 
class(combined_tp2$Depression_score_sum_Q2)

[1] "integer"

In [16]:
# Convert to categories
depression_category <- ifelse(combined_tp2$Depression_score_sum_Q2 >= 0 & combined_tp2$Depression_score_sum_Q2 < 13,  "no depression", 
                              ifelse(combined_tp2$Depression_score_sum_Q2 >= 13 & combined_tp2$Depression_score_sum_Q2 <= 30, "depression", NA))
depression_category
sum(is.na(depression_category))

 [1] "no depression" NA              "no depression" "no depression"
 [5] "no depression" "no depression" "no depression" "no depression"
 [9] "no depression" "depression"    "no depression" NA
[13] "no depression" "no depression" NA              "no depression"
[17] "no depression" "no depression" "no depression" "depression"
[21] "no depression" "no depression" "no depression" "no depression"
[25] "no depression" "no depression" "no depression" NA
[29] "no depression" "depression"    "depression"    "no depression"

[1] 4

In [17]:
# Create new column with categories for depression
combined_tp2$Q2_Depression_category <- depression_category
table(combined_tp2$Q2_Depression_category)

   depression no depression
            4            24

In [50]:
summary_depression <- combined_tp2 |>
  group_by(Group, Q2_Depression_category) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count / sum(count)) * 100
  )
print(summary_depression)

# A tibble: 6 × 4
# Groups:   Group [2]
  Group              Q2_Depression_category count percentage
  <chr>              <chr>                  <int>      <dbl>
1 "First pregnancy " depression                 1       6.25
2 "First pregnancy " no depression             12      75
3 "First pregnancy " NA                         3      18.8
4 "Second pregnancy" depression                 3      18.8
5 "Second pregnancy" no depression             12      75
6 "Second pregnancy" NA                         1       6.25

## Excess weight

In [52]:
grep("excess",names(combined_tp2), value = TRUE )
class(combined_tp2$excess_weight)
table(combined_tp2$excess_weight)

combined_tp2$excess_weight <- as.factor(combined_tp2$excess_weight)
total_counts_excess_weight <- table(combined_tp2$Group)

[1] "excess_weight"

[1] "character"

 No Yes
 17  14

In [53]:
# Generate a table
summary_excess_weight <- combined_tp2 |>
  group_by(Group, excess_weight) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count / sum(count)) * 100
  )
print(summary_excess_weight)

# A tibble: 5 × 4
# Groups:   Group [2]
  Group              excess_weight count percentage
  <chr>              <fct>         <int>      <dbl>
1 "First pregnancy " No               10      62.5
2 "First pregnancy " Yes               5      31.2
3 "First pregnancy " NA                1       6.25
4 "Second pregnancy" No                7      43.8
5 "Second pregnancy" Yes               9      56.2

# Stress========================================================================

In [19]:
grep("stress", names(combined_tp2), value = TRUE)
table(combined_tp2$stress_sum_score_Q2)

[1] "stress_sum_score_Q1" "high_stress_Q1"      "stress_sum_score_Q2"
[4] "stress_sum_score_Q3"

 0  1  2  3  4  5  6  7  8  9 11 12
 1  2  3  3  4  6  6  2  1  2  1  1

In [20]:
# There was no high stress column for Q2
# Convert stress score to categories
high_stress_Q2 <- ifelse(combined_tp2$stress_sum_score_Q2 >= 7, 1, ifelse(combined_tp2$stress_sum_score_Q2 < 7 , 0, NA))
table(high_stress_Q2)
length(combined_tp2$stress_sum_score_Q2)

high_stress_Q2
 0  1
25  7

[1] 32

In [21]:
# Create new column with yes/no for high stress
combined_tp2$high_stress_Q2 <- high_stress_Q2
table(combined_tp2$high_stress_Q2)

 0  1
25  7

In [22]:
summary_stress <-  combined_tp2 |>
  group_by(Group, high_stress_Q2) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count / sum(count)) * 100
  )
print(summary_stress)

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              high_stress_Q2 count percentage
  <chr>                       <dbl> <int>      <dbl>
1 "First pregnancy "              0    13       81.2
2 "First pregnancy "              1     3       18.8
3 "Second pregnancy"              0    12       75
4 "Second pregnancy"              1     4       25

In [23]:
# Check for NA (Just to make sure)
combined_tp2 |> filter(is.na(stress_sum_score_Q2)) |> pull(Q1_Personnummer)

character(0)

# Smoking=======================================================================

In [24]:
grep("smok", names(combined_tp2), value = TRUE)
grep("Smok", names(combined_tp2), value = TRUE)

combined_tp2$Q2_X25_Smoking_snus_now

[1] "Q1_X55_Year_stopped_smoking"       "Q1_X57_Which_other_smoking_habits"
[3] "smoking"

[1] "Q1_Smoking_checked"
[2] "Q2_X25_Smoking_snus_now"
[3] "Q3_X35_Smoking_snus_end_of_pregnancy"

 [1] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej"
[13] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej"
[25] "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej" "Nej"

In [25]:
# Convert to categories 
smoking_category <- ifelse(combined_tp2$Q2_X25_Smoking_snus_now == "Nej", 0, 
                           ifelse(combined_tp2$Q2_X25_Smoking_snus_now == "Ja", 1, NA))
table(smoking_category)

smoking_category
 0
32

In [26]:
# Check for NA
sum(is.na(smoking_category))

[1] 0

In [27]:
combined_tp2$smoking_category_Q2 <- smoking_category
table(combined_tp2$smoking_category_Q2)

 0
32

In [28]:
summary_smoking <-  combined_tp2 |>
  group_by(Group, smoking_category_Q2) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count / sum(count)) * 100
  )
print(summary_smoking)

# A tibble: 2 × 4
# Groups:   Group [2]
  Group              smoking_category_Q2 count percentage
  <chr>                            <dbl> <int>      <dbl>
1 "First pregnancy "                   0    16        100
2 "Second pregnancy"                   0    16        100

# Alcohol=======================================================================

In [29]:
grep("alcohol", names(combined_tp2), value = TRUE)
grep("Alcohol", names(combined_tp2), value = TRUE)

[1] "Q2_X28_How_often_alcohol_since_pregnancy"
[2] "Q2_X29_How_many_alcohol_drinks_daily_when_drinking"
[3] "Q3_X38_How_often_alcohol_end_of_pregnancy"
[4] "Q3_X39_How_many_alcohol_drinks_daily_when_drinking"

[1] "Q1_X62_Alcohol_3_months_before_pregnancy"
[2] "Q1_X64_Alcohol_during_pregnancy"
[3] "Q1_X62_Alcohol_3_months_before_pregnancy_cat"
[4] "Q1_X64_Alcohol_during_pregnancy_cat"

In [30]:
combined_tp2$Q2_X28_How_often_alcohol_since_pregnancy

 [1] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
 [9] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[17] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"
[25] "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig" "Aldrig"

In [31]:
# Convert to categories (no other than "Aldrig" and NA)??? 
alcohol_category <- ifelse(combined_tp2$Q2_X28_How_often_alcohol_since_pregnancy == "Aldrig", 0, NA)
table(alcohol_category)

alcohol_category
 0
32

In [32]:
# Check for NA
sum(is.na(alcohol_category))

[1] 0

In [33]:
combined_tp2$alcohol_category_Q2 <- alcohol_category
table(combined_tp2$alcohol_category_Q2)

 0
32

In [34]:
# Check for NA again
sum(is.na(combined_tp2$alcohol_category_Q2))

[1] 0

In [35]:
summary_alcohol <- combined_tp2 |>
  group_by(Group, alcohol_category_Q2) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/ sum(count))
  )
print(summary_alcohol)

# A tibble: 2 × 4
# Groups:   Group [2]
  Group              alcohol_category_Q2 count percentage
  <chr>                            <dbl> <int>      <dbl>
1 "First pregnancy "                   0    16          1
2 "Second pregnancy"                   0    16          1

# Antibiotic====================================================================

In [36]:
grep("antibiotic", names(combined_tp2), value = TRUE)
grep("Antibiotic", names(combined_tp2), value = TRUE)

[1] "Q1_X32_Adult_acne_yes_antibiotic_treatment"
[2] "Q2_X7.Pregnancy_week_antibiotics"
[3] "Q3_X18_antibiotics_during_delivery"
[4] "Q3_X23_Child_antibiotics_during_after_delivery"
[5] "Q3_X24_Why_child_antibiotics"
[6] "Q3_X29_Pregnancy_week_antibiotics"

[1] "Q1_X43.Antibiotics_last_3_months"
[2] "Q1_X46_Antibiotics_during_this_pregnancy"
[3] "Q1_X47_Antibiotics_which_pregnancy_week"
[4] "Q2_X6.Antibiotics_during_pregnancy"
[5] "Q3_X28_Antibiotics_last_month_of_pregnancy"
[6] "Q3_X30_Antibiotics_comments"

In [37]:
combined_tp2$Q2_X6.Antibiotics_during_pregnancy
class(combined_tp2$Q2_X6.Antibiotics_during_pregnancy)

 [1] 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0

[1] "integer"

In [38]:
# Convert to factor
combined_tp2$Q2_X6.Antibiotics_during_pregnancy <- as.factor(combined_tp2$Q2_X6.Antibiotics_during_pregnancy)
class(combined_tp2$Q2_X6.Antibiotics_during_pregnancy)

[1] "factor"

In [39]:
sum(is.na(combined_tp2$Q2_X6.Antibiotics_during_pregnancy))

[1] 0

In [40]:
summary_antibiotics <- combined_tp2 |>
  group_by(Group, Q2_X6.Antibiotics_during_pregnancy) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/ sum(count)) * 100
  )
print(summary_antibiotics)

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              Q2_X6.Antibiotics_during_pregnancy count percentage
  <chr>              <fct>                              <int>      <dbl>
1 "First pregnancy " 0                                     15      93.8
2 "First pregnancy " 1                                      1       6.25
3 "Second pregnancy" 0                                     15      93.8
4 "Second pregnancy" 1                                      1       6.25

# Diet score====================================================================

In [41]:
grep("diet", names(combined_tp2), value = TRUE)
grep("Diet", names(combined_tp2), value = TRUE)

 [1] "Q1_X88_Vegetarian_diet" "Q1_X89_Vegan_diet"      "Q1_dietscore"
 [4] "Q1_healthydiet"         "Q2_X36_vegetarian_diet" "Q2_X37_Vegan_diet"
 [7] "Q2_dietscore"           "Q2_healthydiet"         "Q3_X48_Vegetarian_diet"
[10] "Q3_X49_Vegan_diet"      "Q3_dietscore"           "Q3_healthydiet"

character(0)

In [42]:
combined_tp2$Q2_dietscore
combined_tp2$Q2_healthydiet 
combined_tp2$Q2_dailyfiber

 [1] 0 1 3 2 2 4 0 1 3 2 2 3 3 1 1 1 2 1 3 1 2 4 0 1 4 2 1 4 4 1 1 1

 [1] 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 0 1 1 1

 [1] 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1

In [43]:
# combined$Q2_healthydiet --> yes if health score less than 3
summary_diet <- combined_tp2 |>
  group_by(Group, Q2_healthydiet) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/sum(count)) * 100
  )
print(summary_diet)

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              Q2_healthydiet count percentage
  <chr>                       <int> <int>      <dbl>
1 "First pregnancy "              0     5       31.2
2 "First pregnancy "              1    11       68.8
3 "Second pregnancy"              0     5       31.2
4 "Second pregnancy"              1    11       68.8

# Daily fiber-------------------------------------------------------------------

In [44]:
combined_tp2$Q2_dailyfiber
summary_fiber <-  combined_tp2 |>
  group_by(Group, Q2_dailyfiber) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/sum(count)) * 100
  )
print(summary_fiber)

 [1] 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              Q2_dailyfiber count percentage
  <chr>                      <int> <int>      <dbl>
1 "First pregnancy "             0     4       25
2 "First pregnancy "             1    12       75
3 "Second pregnancy"             0     2       12.5
4 "Second pregnancy"             1    14       87.5

# Preeclampsia============================================================================

In [45]:
grep("preeclampsia", names(combined_tp2), value = TRUE)
grep("Preeclampsia", names(combined_tp2), value = TRUE)

[1] "Q1_X73.5_Pregnancy_problems_preeclampsia"
[2] "Q2_X13.5.Pregproblem_preeclampsia"
[3] "preeclampsia_epi_analysis"

character(0)

In [46]:
summary_preeclampsia <- combined_tp2 |>
  group_by(Group, Q2_X13.5.Pregproblem_preeclampsia) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/ sum(count)) * 100
  )
print(summary_preeclampsia)

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              Q2_X13.5.Pregproblem_preeclampsia count percentage
  <chr>              <chr>                             <int>      <dbl>
1 "First pregnancy " Nej                                   4       25
2 "First pregnancy " NA                                   12       75
3 "Second pregnancy" Nej                                   2       12.5
4 "Second pregnancy" NA                                   14       87.5

# Hypertension====================================================================================

In [47]:
grep("pressure", names(combined_tp2), value = TRUE)

 [1] "Q1_X66.2_prior_treatment_high_bloodpressure"
 [2] "Q1_X73.4_Pregnancy_problems_high_bloodpressure"
 [3] "Q1_X75_prior_bloodpressure_medication"
 [4] "Q1_X77_during_bloodpressure_medication"
 [5] "Q1_prior_bloodpressure"
 [6] "Q1_during_bloodpressure"
 [7] "Q2_X13.4.Pregproblem_high_bloodpressure"
 [8] "Q2_X15_during_bloodpressure_medication"
 [9] "Q2_bloodpressure"
[10] "Q3_X42_during_bloodpressure_medication"
[11] "Q3_bloodpressure"

In [48]:
summary_bp <- combined_tp2 |>
  group_by(Group, Q2_X13.4.Pregproblem_high_bloodpressure) |>
  summarise(
    count = n(),
    
    .groups = 'drop'
  ) |>
  group_by(Group) |>
  mutate(
    percentage = (count/ sum(count)) * 100
  )
print(summary_bp)

# A tibble: 4 × 4
# Groups:   Group [2]
  Group              Q2_X13.4.Pregproblem_high_bloodpressure count percentage
  <chr>              <chr>                                   <int>      <dbl>
1 "First pregnancy " Nej                                         4       25
2 "First pregnancy " NA                                         12       75
3 "Second pregnancy" Nej                                         2       12.5
4 "Second pregnancy" NA                                         14       87.5

In [49]:
combined_tp2$Q2_bloodpressure
combined_tp2$Q2_bloodpressure <- as.factor(combined_tp2$Q2_bloodpressure)
class(combined_tp2$Q2_bloodpressure)

 [1] 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1

[1] "factor"