#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: vagina_drop_na_kit2
# Date: 2025.11.11
# Programmer: Barbara Nowak
# Purpose: Vaginal, drop participants with missing values in kit2 & invalid samples (missing barcodes)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [1]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [5]:
# Read in filtered data 
 fp_tp2 <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/2025-11-10_fp_tp1_filt_nulliparous.csv", header = TRUE)
 head(fp_tp2)
 dim(fp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5301 S1f862a6     NA         0        0         0
3 5258 S1f95844     NA         0        0         0
4 5275 S2b86cc0     NA         0        0         0
5 5243 S39fe1d7     NA         0        0         0
6 5383 S7e4a963     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2018-03-07 P1f862a6        0                   32          ⋯ 0
3 2018-04-10 P1f95844        0                   30          ⋯ 0
4 2019-05-29 P3cac7b0        0                   31          ⋯ 0
5 2018-06-23 P3db7da6        0                   29          ⋯ 0
6 2018-02-18 P424fd61        0                   37          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     31
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          very_w28_31  1    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0

[1]  26 566

In [6]:
sp_tp2 <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/2025-11-10_sp_tp1_filt_nulliparous.csv", header = TRUE)
 head(sp_tp2)
 dim(sp_tp2)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5305 Sa79a719     NA         0        0         1
3 5309 S0e78496     NA         0        0         0
4 5311 S3cac7b0     NA         0        0         0
5 5252 S3db7da6     NA         0        0         1
6 5415 S424fd61     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2019-01-17 P1f862a6        0                   32          ⋯  0
3 2020-12-17 P1f95844        0                   33          ⋯  0
4 2020-10-20 P3cac7b0        0                   33          ⋯  0
5 2019-09-24 P3db7da6        0                   30          ⋯  0
6 2020-11-03 P424fd61        0                   40          ⋯ 31
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  26 566

In [7]:
# Read valid sample list
sample_id <- readLines("/ceph/projects/010_SweMaMi/bm.nowak/data/2025-11-06_valid_barcodes_vaginal_nuliparous.txt")
length(sample_id)

[1] 178

In [ ]:
# Find fp women where birth date of child is missing & keep only participants where birthdate exists- ALREADY DONE
# Find women where primipara = TRUE for fp and keep them in fp and sp - ALREADY DONE

In [8]:
# Make sure all fp are primiparous
fp_pn_check <- fp_tp2 |> 
  filter(fp_tp1$Primipara == 1) |>
  pull(Q1_Personnummer)
fp_pn_check
length(fp_pn_check)

 [1] "P159f9c8" "P1f862a6" "P1f95844" "P3cac7b0" "P3db7da6" "P424fd61"
 [7] "P42f2c08" "P4de45e7" "P50f102c" "P5b98b6c" "P62ea0b2" "P719b21e"
[13] "P735d77f" "P7ece52e" "P92b4604" "P97574f9" "P9cdfd5a" "Pa8f3b51"
[19] "Pbe04f9f" "Pbe289c8" "Pc44e366" "Pc77a35c" "Pca94a0f" "Pdab1897"
[25] "Pe706703" "Pf573f67"

[1] 26

In [9]:
# Doubble check that all sp are not primiparous
pn_check <- sp_tp2 |> 
  filter(sp_tp1$Primipara == 1) |>
  pull(Q1_Personnummer)
pn_check
length(pn_check)

character(0)

[1] 0

# ==============================================================================

In [10]:
grep("kit", names(fp_tp2), value = TRUE)

 [1] "kit1.faecal_sample.barcode"
 [2] "kit2.faecal_sample.barcode"
 [3] "kit3.faecal_sample.barcode"
 [4] "kit3.infant_faecal_sample.barcode"
 [5] "kit3.infant_faecal_sample_2.barcode"
 [6] "kit3.salival_sample.barcode"
 [7] "kit1.salival_sample.barcode"
 [8] "kit1.vaginal_sample.barcode"
 [9] "kit1.faecal_sample.datetime_taken"
[10] "kit1.salival_sample.datetime_taken"
[11] "kit1.vaginal_sample.datetime_taken"
[12] "kit2.salival_sample.barcode"
[13] "kit2.vaginal_sample.barcode"
[14] "kit2.faecal_sample.datetime_taken"
[15] "kit2.salival_sample.datetime_taken"
[16] "kit2.vaginal_sample.datetime_taken"
[17] "kit3.vaginal_sample.barcode"
[18] "kit3.faecal_sample.datetime_taken"
[19] "kit3.infant_faecal_sample.datetime_taken"
[20] "kit3.infant_faecal_sample_2.datetime_taken"
[21] "kit3.salival_sample.datetime_taken"
[22] "kit3.vaginal_sample.datetime_taken"

In [19]:
# Find participants where kit2 is missing
fp_pn_kit2_missing <- fp_tp2 |>
  filter(is.na(kit2.vaginal_sample.barcode)) |>
  pull(Q1_Personnummer)
fp_pn_kit2_missing

[1] "Pf573f67"

In [20]:
sp_pn_kit2_missing <-  sp_tp2 |>
  filter(is.na(kit2.vaginal_sample.barcode)) |>
  pull(Q1_Personnummer)
sp_pn_kit2_missing

character(0)

In [21]:
# doubble check 
fp_tp1$kit2.vaginal_sample.barcode
sp_tp1$kit2.vaginal_sample.barcode

 [1] "FF00531801" "FB02845714" "FF02014735" "FF03816858" "FF02015861"
 [6] "FF00657251" "FF03816190" "FF02015423" "FF02013773" "FF00657220"
[11] "FF00531275" "FF02014450" "FF00530161" "FF02740077" "FF00531186"
[16] "FF02557245" "FF02014344" "FF00653280" "FF00620158" "FF00619973"
[21] "FF00531053" "FB02825218" "FF00531062" "FF02740612" "FF00652209"
[26] NA

 [1] "FF06580149" "FF02557890" "FF08440398" "FF06032916" "FF01572330"
 [6] "FF08440702" "FF04760422" "FF04761496" "FF06039625" "FF06039851"
[11] "FF06743126" "FF06032176" "FF01570606" "FF08440357" "FF05044402"
[16] "FF04761515" "FF06743139" "FF06040362" "FF06033029" "FF08440262"
[21] "FF06580134" "FF08440427" "FF06033016" "FF05024823" "FF03815867"
[26] "FF01570524"

In [22]:
# combine both sets of participants to drop (just good practice here) 
combined_missing_kit2 <- c(fp_pn_kit2_missing, sp_pn_kit2_missing)
length(combined_missing_kit2)

[1] 1

# -------------------------------------------------------------------------------

# Drop all participants with missing tp2 faecal sample (kit2)
# If missing in either fp or sp, BOTH ARE DROPPED

In [23]:
# Keep only participants with valid tp2 faecal samples
fp_tp2_filt <- fp_tp2 |>
  filter(!(Q1_Personnummer %in% combined_missing_kit2))
head(fp_tp2_filt)
dim(fp_tp2_filt)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5301 S1f862a6     NA         0        0         0
3 5258 S1f95844     NA         0        0         0
4 5275 S2b86cc0     NA         0        0         0
5 5243 S39fe1d7     NA         0        0         0
6 5383 S7e4a963     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2018-03-07 P1f862a6        0                   32          ⋯ 0
3 2018-04-10 P1f95844        0                   30          ⋯ 0
4 2019-05-29 P3cac7b0        0                   31          ⋯ 0
5 2018-06-23 P3db7da6        0                   29          ⋯ 0
6 2018-02-18 P424fd61        0                   37          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     31
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          very_w28_31  1    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0

[1]  25 566

In [24]:
sp_tp2_filt <- sp_tp2 |>
  filter(!(Q1_Personnummer %in% combined_missing_kit2))
head(sp_tp2_filt)
dim(sp_tp2_filt)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5305 Sa79a719     NA         0        0         1
3 5309 S0e78496     NA         0        0         0
4 5311 S3cac7b0     NA         0        0         0
5 5252 S3db7da6     NA         0        0         1
6 5415 S424fd61     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2019-01-17 P1f862a6        0                   32          ⋯  0
3 2020-12-17 P1f95844        0                   33          ⋯  0
4 2020-10-20 P3cac7b0        0                   33          ⋯  0
5 2019-09-24 P3db7da6        0                   30          ⋯  0
6 2020-11-03 P424fd61        0                   40          ⋯ 31
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  25 566

In [25]:
# Find barcodes that are missing from valid sample list
missing_fp_tp2_samples <- setdiff(fp_tp2_filt$kit2.vaginal_sample.barcode, sample_id)
length(missing_fp_tp2_samples)

[1] 4

In [26]:
missing_sp_tp2_samples <- setdiff(sp_tp2_filt$kit2.vaginal_sample.barcode, sample_id)
length(missing_sp_tp2_samples)

[1] 5

In [27]:
# This part is mostly good practice since no more samples were missing
# Combine all missing samples (good practice)
all_missing_samples <-c(missing_fp_tp2_samples, missing_sp_tp2_samples)
all_missing_samples

[1] "FB02845714" "FF03816190" "FF00530161" "FF00531186" "FF06039625"
[6] "FF06040362" "FF06033029" "FF06580134" "FF03815867"

In [28]:
# Get the personal numbers
fp_pn_to_drop <- fp_tp2_filt |>
  filter(kit2.vaginal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(fp_pn_to_drop)

[1] 4

In [30]:
sp_pn_to_drop <- sp_tp2_filt |>
  filter(kit2.vaginal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(sp_pn_to_drop)

[1] 5

In [31]:
# Combine all to drop
combined_pn_to_drop <- c(fp_pn_to_drop, sp_pn_to_drop)
length(combined_pn_to_drop)

[1] 9

In [32]:
# Keep only participants with valid sample
fp_tp2_filtered_nulliparous <- fp_tp2_filt |>
  filter(!(Q1_Personnummer %in% combined_pn_to_drop)) 
head(fp_tp2_filtered_nulliparous)
dim(fp_tp2_filtered_nulliparous)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5258 S1f95844     NA         0        0         0
3 5275 S2b86cc0     NA         0        0         0
4 5243 S39fe1d7     NA         0        0         0
5 5383 S7e4a963     NA         0        0         0
6 5239 S5fa4a39     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2018-04-10 P1f95844        0                   30          ⋯ 0
3 2019-05-29 P3cac7b0        0                   31          ⋯ 0
4 2018-06-23 P3db7da6        0                   29          ⋯ 0
5 2018-02-18 P424fd61        0                   37          ⋯ 0
6 2018-08-30 P4de45e7        0                   29          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    1

[1]  16 566

In [33]:
sp_tp2_filtered_nulliparous <- sp_tp2_filt |>
  filter(!(Q1_Personnummer %in% combined_pn_to_drop))
head(sp_tp2_filtered_nulliparous)
dim(sp_tp2_filtered_nulliparous)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5309 S0e78496     NA         0        0         0
3 5311 S3cac7b0     NA         0        0         0
4 5252 S3db7da6     NA         0        0         1
5 5415 S424fd61     NA         0        0         0
6 5272 S4de45e7     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2020-12-17 P1f95844        0                   33          ⋯  0
3 2020-10-20 P3cac7b0        0                   33          ⋯  0
4 2019-09-24 P3db7da6        0                   30          ⋯  0
5 2020-11-03 P424fd61        0                   40          ⋯ 31
6 2020-11-05 P4de45e7        0                   31          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

[1]  16 566

In [34]:
# Contain only participants with valid, non-missing faecal sample barcodes for kit2 (AND kit1)
# Final check: Make sure both fp and sp have the same participants with intersect
 length(intersect(fp_tp2_filtered_nulliparous$Q1_Personnummer, sp_tp2_filtered_nulliparous$Q1_Personnummer))

[1] 16

# ===============================================================================

In [36]:
# Write to file
write.table(fp_tp2_filtered_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/", Sys.Date(), "_fp_tp2_filt", ".csv"), sep = ",", row.names = FALSE)
write.table(sp_tp2_filtered_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/", Sys.Date(), "_sp_tp2_filt", ".csv"), sep = ",", row.names = FALSE)

In [37]:
# Write file with combined fp and sp 
fp_tp2_filtered_nulliparous$Group <- "First pregnancy "
sp_tp2_filtered_nulliparous$Group <- "Second pregnancy"

In [38]:
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_tp2_filtered_nulliparous, sp_tp2_filtered_nulliparous)
head(combined_fp_sp)
dim(combined_fp_sp)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5258 S1f95844     NA         0        0         0
3 5275 S2b86cc0     NA         0        0         0
4 5243 S39fe1d7     NA         0        0         0
5 5383 S7e4a963     NA         0        0         0
6 5239 S5fa4a39     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-11-16 P159f9c8        0                   36          ⋯
2 2018-04-10 P1f95844        0                   30          ⋯
3 2019-05-29 P3cac7b0        0                   31          ⋯
4 2018-06-23 P3db7da6        0                   29          ⋯
5 2018-02-18 P424fd61        0                   37          ⋯
6 2018-08-30 P4de45e7        0                   29          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     40
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     38
6 NA                 NA   NA       NA                     39
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Induction            NA          NA    1
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

[1]  32 567

In [45]:
# Write combined, filtered data to file
write.tablele(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp2_nulliparous/", Sys.Date(), "_combined_fp_sp_tp2", ".csv"), sep = ",", row.names = FALSE)

In [ ]:
 # Test written file
#test <- read.csv("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/tp2_nulliparous/2025-09-01_combined_fp_sp_tp2.csv", header = TRUE)
#head(test)
#dim(test)