#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# File name: vagina_drop_na_kit1
# Date: 2025.11.06
# Programmer: Barbara Nowak
# Purpose: Vaginal, drop participants with missing values in kit1 & invalid samples (missing barcodes), and select only nulliparous during FP
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [2]:
library(tidyverse)
library(dplyr)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Reading files~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [3]:
# Read cleaned first and second pregnancy
fp <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_fp_.csv", header = TRUE)
dim(fp)
head(fp)

[1]  59 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

In [4]:
sp <-  read.csv("/ceph/projects/010_SweMaMi/bm.nowak/unfiltered_divided_data/2025-07-29_kit_sp_.csv", header = TRUE)
dim(sp)
head(sp)

[1]  59 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

In [5]:
sample_id <- readLines("/ceph/projects/010_SweMaMi/bm.nowak/data/2025-11-06_valid_barcodes_vaginal_nuliparous.txt")
length(sample_id)

[1] 178

In [6]:
grep("kit", names(fp), value = TRUE)

 [1] "kit1.faecal_sample.barcode"
 [2] "kit2.faecal_sample.barcode"
 [3] "kit3.faecal_sample.barcode"
 [4] "kit3.infant_faecal_sample.barcode"
 [5] "kit3.infant_faecal_sample_2.barcode"
 [6] "kit3.salival_sample.barcode"
 [7] "kit1.salival_sample.barcode"
 [8] "kit1.vaginal_sample.barcode"
 [9] "kit1.faecal_sample.datetime_taken"
[10] "kit1.salival_sample.datetime_taken"
[11] "kit1.vaginal_sample.datetime_taken"
[12] "kit2.salival_sample.barcode"
[13] "kit2.vaginal_sample.barcode"
[14] "kit2.faecal_sample.datetime_taken"
[15] "kit2.salival_sample.datetime_taken"
[16] "kit2.vaginal_sample.datetime_taken"
[17] "kit3.vaginal_sample.barcode"
[18] "kit3.faecal_sample.datetime_taken"
[19] "kit3.infant_faecal_sample.datetime_taken"
[20] "kit3.infant_faecal_sample_2.datetime_taken"
[21] "kit3.salival_sample.datetime_taken"
[22] "kit3.vaginal_sample.datetime_taken"

In [7]:
# Find participants in fp where vaginal barcode is missing
pn_fp_tp1 <- fp |>
  filter(is.na(kit1.vaginal_sample.barcode)) |>
  pull(Q1_Personnummer)
pn_fp_tp1

character(0)

In [8]:
# Find participants in sp where vaginal barcode is missing
pn_sp_tp1 <- sp |>
  filter(is.na(kit2.vaginal_sample.barcode)) |>
  pull(Q1_Personnummer)
pn_sp_tp1

[1] "Pc9a3575"

In [9]:
# Combine both sets of participants to drop
drop_tp1_pn <- c(pn_fp_tp1, pn_sp_tp1)
drop_tp1_pn
length(drop_tp1_pn)

[1] "Pc9a3575"

[1] 1

# ===============================================================================

# Remove participants with missing TP1 vaginal samples
# Q1_Personnummer is used to track individuals.
# If the barcode is missing in either fp or sp, both entries are dropped.

In [10]:
# Keep only participants with valid TP1 faecal samples
fp_tp1 <- fp |>
  filter(!(Q1_Personnummer %in% drop_tp1_pn))
head(fp_tp1)
dim(fp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5265 Scf5931f     NA         0        0         0
2 5254 S14e664f     NA         0        0         1
3 5367 S194e21b     NA         0        0         0
4 5297 S1a267fa     NA         0        0         0
5 5300 S30bce16     NA         0        0         0
6 5208 Sa8397fa     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-12-13 P060d440        0                   30          ⋯ NA
2 2018-09-10 P14e664f        0                   30          ⋯  0
3 2018-11-16 P159f9c8        0                   36          ⋯  0
4 2019-05-23 P1a267fa        0                   32          ⋯  0
5 2018-04-18 P1d75300        0                   32          ⋯ NA
6 2018-03-14 P1ef420d        0                   27          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA    1       MISSED ABORTION        NA
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     41
4 NA                 NA   NA       NA                     38
5 NA                 NA   NA       NA                     NA
6 NA                 NA   NA       NA                     28
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 NA                   NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 NA                   NA          NA    0
6 Spontaneous          very_w28_31  1    0

[1]  58 566

In [11]:
sp_tp1 <- sp |> 
  filter(!(Q1_Personnummer %in% drop_tp1_pn))
head(sp_tp1)
dim(sp_tp1)

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5253 S060d440     NA         0        0         1
2 5290 Sefe71fe     NA         0        0         1
3 5391 S159f9c8     NA         0        0         0
4 5332 Sb124b17     NA         0        0         2
5 5322 S1d75300     NA         0        0         0
6 5247 S1ef420d     NA         0        0         1
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2019-06-03 P060d440        0                   30          ⋯  0
2 2020-08-17 P14e664f        0                   32          ⋯  0
3 2021-01-28 P159f9c8        0                   38          ⋯  0
4 2021-01-06 P1a267fa        0                   34          ⋯  0
5 2019-05-14 P1d75300        0                   33          ⋯ NA
6 2020-09-17 P1ef420d        0                   30          ⋯  0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     38
2 NA                 NA   NA       NA                     39
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     41
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     40
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Unlaboured c-section NA          NA    0
2 Spontaneous          NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Induction            NA          NA    0
6 Spontaneous          NA          NA    0

[1]  58 566

In [12]:
# Find barcodes in fp that are missing from the valid sample list
missing_fp_tp1_samples <- setdiff(fp_tp1$kit1.vaginal_sample.barcode, sample_id)

In [13]:
# Same for sp
missing_sp_tp1_samples <- setdiff(sp_tp1$kit1.vaginal_sample.barcode, sample_id)

In [14]:
# Combine all missing sample barcodes
all_missing_samples <-  c(missing_fp_tp1_samples, missing_sp_tp1_samples)
length(all_missing_samples)

[1] 20

# Some barcodes might be present, but not part of the filtered list of valid samples

In [15]:
# Get person num for those missing samples from fp and sp
pn_fp_to_drop <- fp_tp1 |>
  filter(kit1.vaginal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(pn_fp_to_drop)

[1] 10

In [16]:
pn_sp_to_drop <-  sp_tp1 |>
  filter(kit1.vaginal_sample.barcode %in% all_missing_samples) |>
  pull(Q1_Personnummer)
length(pn_sp_to_drop)

[1] 10

In [17]:
# Combine all personal num to drop
pn_drop_all <- c(pn_fp_to_drop, pn_sp_to_drop)
pn_drop_all
length(pn_drop_all)

 [1] "P1ef420d" "P3399626" "P3c0f6ee" "P43d1efc" "P6d2ebc4" "Pbbb08bd"
 [7] "Pc10d0b0" "Pcd2c0d1" "Ped8773b" "Pff3c644" "P1a267fa" "P4a05456"
[13] "P7b2ccf8" "Pa8747ea" "Pb752955" "Pc10d0b0" "Pc75b32a" "Pe3450d3"
[19] "Ped8773b" "Pff3c644"

[1] 20

In [18]:
# Ensure we only retain those whose samples are both present and valid
# Final cleaned dataset after filtering out bad samples
fp_tp1_filt <- fp_tp1 |>
  filter(!(Q1_Personnummer %in% pn_drop_all))
dim(fp_tp1_filt)

[1]  41 566

In [19]:
sp_tp1_filt <- sp_tp1 |>
  filter(!(Q1_Personnummer %in% pn_drop_all))
dim(sp_tp1_filt)

[1]  41 566

In [20]:
# These contain only participants with valid, non-missing faecal sample barcodes also found in sample_id.
# Final check: Make sure both fp and sp have the same participants
# intersect() confirms the alignment.
length(intersect(fp_tp1_filt$Q1_Personnummer, sp_tp1_filt$Q1_Personnummer))

[1] 41

In [77]:
# make sure all in FP are nulliparous and all SP are NOT nulliparous
fp_primipara_check <- fp_tp1_filt |> 
    filter(fp_tp1_filt$Primipara == 1) |>
    pull(Q1_Personnummer)
length(fp_primipara_check) #REMEMBER to remove those pn that are NOT NULLIPAROUS here!!

[1] 31

In [23]:
sp_primipara_check <- sp_tp1_filt |> 
    filter(sp_tp1_filt$Primipara == 1) |>
    pull(Q1_Personnummer)

In [80]:
# Extract non primiparous pn in FP
non_primipara <- fp_tp1_filt |> 
    filter(!(fp_tp1_filt$Primipara == 1)) |>
    pull(Q1_Personnummer)
length(non_primipara)

[1] 10

In [33]:
int_primipara <- intersect(fp_primipara_check, sp_primipara_check)
int_primipara

[1] "P46f36c7" "Pab443f9" "Pbdbd455" "Pc3a5016" "Pd3b97e6"

In [76]:
# check dates of intersecting primipara personal#
fp_tp1_filt |> filter(fp_tp1_filt$Q1_Personnummer %in% int_primipara) |> 
    pull(Q1_Datum, missfall.IUFD_comments ) 

sp_tp1_filt |> filter(sp_tp1_filt$Q1_Personnummer %in% int_primipara) |> 
    pull(Q1_Datum, Q3_X7_Birthdate)

                                  MISSFALL Dock födde jag min flicka den 4/3, v22+3. Hon dog precis innan hon kom ut.
                                                                                                         "2019-12-04"
                                                                                                                 <NA>
                                                                                                         "2019-06-07"
MISSFALL jag hade missfallet den 5 januari med hjälp av cytotek eftersom vi hade fått besked att inga hjärtslag fanns
                                                                                                         "2019-12-18"
           MISSFALL Fick konstaterat missfall 8/6 (v11). Embryot var ca 3mm långt så missfallet skedde långt tidigare
                                                                                                         "2020-06-02"
                                                                                                                 <NA>
                                                                                                         "2019-09-10"

  2021-08-24   2021-02-02   2021-03-28   2021-06-28   2021-02-15
"2021-01-12" "2020-07-24" "2020-08-25" "2020-12-27" "2020-08-18"

In [74]:
grep("date", names(fp_tp1_filt), value = TRUE)

[1] "Birthweight_checked" "excess_weight"

In [78]:
fp_tp1_filt |> filter(fp_tp1_filt$Q1_Personnummer %in% int_primipara) |> 
    pull(Q1_Datum, Q1_Personnummer ) 

sp_tp1_filt |> filter(sp_tp1_filt$Q1_Personnummer %in% int_primipara) |> 
    pull(Q1_Datum, Q1_Personnummer)

    P46f36c7     Pab443f9     Pbdbd455     Pc3a5016     Pd3b97e6
"2019-12-04" "2019-06-07" "2019-12-18" "2020-06-02" "2019-09-10"

    P46f36c7     Pab443f9     Pbdbd455     Pc3a5016     Pd3b97e6
"2021-01-12" "2020-07-24" "2020-08-25" "2020-12-27" "2020-08-18"

# We decided to remove the 5 participants above who were marked as primiparous twice
# Ragad did the same in her data

In [82]:
# Combine non primiparous personal# and the 5 participants to drop:
non_primipara_pn_to_drop <- c(non_primipara, int_primipara)
length(non_primipara_pn_to_drop)

[1] 15

In [87]:
fp_tp1_nulliparous <- fp_tp1_filt |> 
    filter(!(fp_tp1_filt$Q1_Personnummer %in% non_primipara_pn_to_drop))
dim(fp_tp1_nulliparous)
head(fp_tp1_nulliparous)

[1]  26 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5301 S1f862a6     NA         0        0         0
3 5258 S1f95844     NA         0        0         0
4 5275 S2b86cc0     NA         0        0         0
5 5243 S39fe1d7     NA         0        0         0
6 5383 S7e4a963     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2018-11-16 P159f9c8        0                   36          ⋯ 0
2 2018-03-07 P1f862a6        0                   32          ⋯ 0
3 2018-04-10 P1f95844        0                   30          ⋯ 0
4 2019-05-29 P3cac7b0        0                   31          ⋯ 0
5 2018-06-23 P3db7da6        0                   29          ⋯ 0
6 2018-02-18 P424fd61        0                   37          ⋯ 0
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     31
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          very_w28_31  1    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0

In [88]:
sp_tp1_nulliparous <- sp_tp1_filt |> 
    filter(!(sp_tp1_filt$Q1_Personnummer %in% non_primipara_pn_to_drop))
dim(sp_tp1_nulliparous)
head(sp_tp1_nulliparous)

[1]  26 566

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5391 S159f9c8     NA         0        0         0
2 5305 Sa79a719     NA         0        0         1
3 5309 S0e78496     NA         0        0         0
4 5311 S3cac7b0     NA         0        0         0
5 5252 S3db7da6     NA         0        0         1
6 5415 S424fd61     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯ diffdays
1 2021-01-28 P159f9c8        0                   38          ⋯  0
2 2019-01-17 P1f862a6        0                   32          ⋯  0
3 2020-12-17 P1f95844        0                   33          ⋯  0
4 2020-10-20 P3cac7b0        0                   33          ⋯  0
5 2019-09-24 P3db7da6        0                   30          ⋯  0
6 2020-11-03 P424fd61        0                   40          ⋯ 31
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     40
2 NA                 NA   NA       NA                     41
3 NA                 NA   NA       NA                     39
4 NA                 NA   NA       NA                     40
5 NA                 NA   NA       NA                     39
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Induction            NA          NA    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Spontaneous          NA          NA    0

In [91]:
sp_tp1_nulliparous |> 
    filter(sp_tp1_nulliparous$Primipara == 0) |>
    pull(Q1_Personnummer) |> 
    length()

[1] 26

In [96]:
fp_tp1_nulliparous$kit1.vaginal_sample.barcode

 [1] "FF02014263" "FF00653507" "FF00653546" "FF02557868" "FB02825409"
 [6] "FF00657534" "FF03817636" "FF02014805" "FF00651927" "FF00652411"
[11] "FF02015815" "FF02014833" "FF00657923" "FF00619356" "FF00653065"
[16] "FF00620268" "FF00653167" "FB02846091" "FF00653014" "FF02015432"
[21] "FF00653071" "FF00652106" "FF02014181" "FF00530208" "FF00657563"
[26] "FF02015345"

In [93]:
# Write to file
write.table(fp_tp1_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/", Sys.Date(), "_fp_tp1_filt_nulliparous", ".csv"), sep = ",", row.names = FALSE)
write.table(sp_tp1_nulliparous, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/", Sys.Date(), "_sp_tp1_filt_nulliparous", ".csv"), sep = ",", row.names = FALSE)

In [100]:
# Write file with combined fp and sp 
fp_tp1_nulliparous$Group <- "First pregnancy "
sp_tp1_nulliparous$Group <- "Second pregnancy"
#fp_tp1_nulliparous$Group

 [1] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [5] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
 [9] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[13] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[17] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[21] "First pregnancy " "First pregnancy " "First pregnancy " "First pregnancy "
[25] "First pregnancy " "First pregnancy "

In [101]:
# Merge the two df vertically:
combined_fp_sp <- rbind(fp_tp1_nulliparous, sp_tp1_nulliparous)
dim(combined_fp_sp)
head(combined_fp_sp)

[1]  52 567

  X    Studienummer Correct_PN Prev_RPL Prev_IUFD Prev_miscarriage_numb
1 5367 S194e21b     NA         0        0         0
2 5301 S1f862a6     NA         0        0         0
3 5258 S1f95844     NA         0        0         0
4 5275 S2b86cc0     NA         0        0         0
5 5243 S39fe1d7     NA         0        0         0
6 5383 S7e4a963     NA         0        0         0
  Q1_Datum   Q1_Personnummer Avbruten_graviditet age_checked ⋯
1 2018-11-16 P159f9c8        0                   36          ⋯
2 2018-03-07 P1f862a6        0                   32          ⋯
3 2018-04-10 P1f95844        0                   30          ⋯
4 2019-05-29 P3cac7b0        0                   31          ⋯
5 2018-06-23 P3db7da6        0                   29          ⋯
6 2018-02-18 P424fd61        0                   37          ⋯
  missfall.IUFD_week IUFD missfall missfall.IUFD_comments Gest_w_combined
1 NA                 NA   NA       NA                     41
2 NA                 NA   NA       NA                     31
3 NA                 NA   NA       NA                     40
4 NA                 NA   NA       NA                     39
5 NA                 NA   NA       NA                     41
6 NA                 NA   NA       NA                     38
  deliv_start_combined Type_of_PTB s_PTB preeclampsia_epi_analysis
1 Spontaneous          NA          NA    0
2 Spontaneous          very_w28_31  1    0
3 Spontaneous          NA          NA    0
4 Spontaneous          NA          NA    0
5 Spontaneous          NA          NA    0
6 Induction            NA          NA    0
  Group
1 First pregnancy
2 First pregnancy
3 First pregnancy
4 First pregnancy
5 First pregnancy
6 First pregnancy

In [102]:
write.table(combined_fp_sp, file = paste0("/ceph/projects/010_SweMaMi/bm.nowak/filtered_data/vaginal/tp1_nulliparous/", 
                                          Sys.Date(), "_combined_tp1_filt_nulliparous", ".csv"), sep = ",", row.names = FALSE)